C:/Users/Md. Istiaq Mahbub/Desktop/IMU/MPU6050_MotionDriver/DeviceSupport/src/board-st_discovery.c File Reference
#include `stm32f4xx.h`
#include `stm32f4xx_usart.h`
#include `stm32f4xx_rcc.h`
#include `stm32f4xx_pwr.h`
#include `i2c.h`
#include `uart.h`
#include `gpio.h`
#include `board-st_discovery.h`
Macros
#define TICK_FREQ (1000u)
Functions
void board_init ()
void mdelay (unsigned long nTime)
int get_tick_count (unsigned long *count)
void TimingDelay_Decrement (void)
void TimeStamp_Increment (void)
void SysTick_Handler (void)
Variables
volatile uint32_t g_ul_ms_ticks =0
static volatile uint32_t TimingDelay =0
unsigned long idle_time =0
uint32_t SystemCoreClock
Macro Definition Documentation
TICK_FREQ
#define TICK_FREQ (1000u)
Definition at line 10 of file board-st_discovery.c.
Function Documentation
board_init()
void board_init ()
Definition at line 17 of file board-st_discovery.c.
References DISABLE, ENABLE, GPIO_Config(), I2cMaster_Init(), PWR_BackupAccessCmd(), RCC_APB1PeriphClockCmd(), RCC_BackupResetCmd(), Set_I2C_Retry(), SystemCoreClockUpdate(), and USART_Config().
Referenced by main().
{
    //SystemInit();
    SystemCoreClockUpdate(); // Update the system clock variable (might not
       have been set before)
                                                           // With this call, the core clock gets set to
       56MHz
    
    if (SysTick_Config (SystemCoreClock / TICK_FREQ)) { // Setup SysTick Timer for 1 msec interrupts
        while (1); // Handle Error
    }
    
    Set_I2C_Retry(5);
  
    /* Enable PWR APB1 Clock */
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_PWR, ENABLE);
    /* Allow access to Backup */
    PWR_BackupAccessCmd(ENABLE);
    /* Reset RTC Domain */
    RCC_BackupResetCmd(ENABLE);
    RCC_BackupResetCmd(DISABLE);
 
    //Configure Interrupts
    GPIO_Config();
    // Configure I2C
    I2cMaster_Init();
    // Configure UART
    USART_Config();
}
get_tick_count()
int get_tick_count (unsigned long * count)
Definition at line 55 of file board-st_discovery.c.
References g_ul_ms_ticks.
Referenced by main(), and read_from_mpl().
{
        count[0] = g_ul_ms_ticks;
    return 0;
}
mdelay()
void mdelay (unsigned long nTime)
Definition at line 49 of file board-st_discovery.c.
References TimingDelay.
Referenced by Sensors_I2C_ReadRegister(), and Sensors_I2C_WriteRegister().
{
    TimingDelay = nTime;
    while(TimingDelay != 0);
}
SysTick_Handler()
void SysTick_Handler (void)
Definition at line 72 of file board-st_discovery.c.
References TimeStamp_Increment(), and TimingDelay_Decrement().
{
    TimingDelay_Decrement();
    TimeStamp_Increment();
}
TimeStamp_Increment()
void TimeStamp_Increment (void)
Definition at line 67 of file board-st_discovery.c.
References g_ul_ms_ticks.
Referenced by SysTick_Handler().
{
    g_ul_ms_ticks++;
}
TimingDelay_Decrement()
void TimingDelay_Decrement (void)
Definition at line 61 of file board-st_discovery.c.
References TimingDelay.
Referenced by SysTick_Handler().
{
    if (TimingDelay != 0x00)
        TimingDelay--;
}
Variable Documentation
g_ul_ms_ticks
volatile uint32_t g_ul_ms_ticks =0
Definition at line 12 of file board-st_discovery.c.
Referenced by get_tick_count(), and TimeStamp_Increment().
idle_time
unsigned long idle_time =0
Definition at line 14 of file board-st_discovery.c.
TimingDelay
volatile uint32_t TimingDelay =0 [static]
Definition at line 13 of file board-st_discovery.c.
Referenced by mdelay(), and TimingDelay_Decrement().