C:/Users/Md. Istiaq Mahbub/Desktop/IMU/MPU6050_MotionDriver/DeviceSupport/src/board-st_discovery.h File Reference
Functions
void board_init ()
int get_tick_count (unsigned long *count)
void mdelay (unsigned long nTime)
void SysTick_Handler (void)
Function Documentation
board_init()
void board_init ()
Definition at line 17 of file board-st_discovery.c.
References DISABLE, ENABLE, GPIO_Config(), I2cMaster_Init(), PWR_BackupAccessCmd(), RCC_APB1PeriphClockCmd(), RCC_BackupResetCmd(), Set_I2C_Retry(), SystemCoreClockUpdate(), and USART_Config().
Referenced by main().
{
    //SystemInit();
    SystemCoreClockUpdate(); // Update the system clock variable (might not
       have been set before)
                                                           // With this call, the core clock gets set to
       56MHz
    
    if (SysTick_Config (SystemCoreClock / TICK_FREQ)) { // Setup SysTick Timer for 1 msec interrupts
        while (1); // Handle Error
    }
    
    Set_I2C_Retry(5);
  
    /* Enable PWR APB1 Clock */
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_PWR, ENABLE);
    /* Allow access to Backup */
    PWR_BackupAccessCmd(ENABLE);
    /* Reset RTC Domain */
    RCC_BackupResetCmd(ENABLE);
    RCC_BackupResetCmd(DISABLE);
 
    //Configure Interrupts
    GPIO_Config();
    // Configure I2C
    I2cMaster_Init();
    // Configure UART
    USART_Config();
}
get_tick_count()
int get_tick_count (unsigned long * count)
Definition at line 55 of file board-st_discovery.c.
References g_ul_ms_ticks.
Referenced by main(), and read_from_mpl().
{
        count[0] = g_ul_ms_ticks;
    return 0;
}
mdelay()
void mdelay (unsigned long nTime)
Definition at line 49 of file board-st_discovery.c.
References TimingDelay.
Referenced by Sensors_I2C_ReadRegister(), and Sensors_I2C_WriteRegister().
{
    TimingDelay = nTime;
    while(TimingDelay != 0);
}
SysTick_Handler()
void SysTick_Handler (void)
Definition at line 72 of file board-st_discovery.c.
{
    TimingDelay_Decrement();
    TimeStamp_Increment();
}