C:/Users/Md. Istiaq Mahbub/Desktop/IMU/MPU6050_MotionDriver/Peripheral/src/gpio.c File Reference
#include `stm32f4xx.h`
#include `stm32f4xx_gpio.h`
#include `misc.h`
#include `stm32f4xx_exti.h`
#include `stm32f4xx_rcc.h`
#include `stm32f4xx_syscfg.h`
#include `GPIO.h`
Macros
#define INVEN_INT_PIN GPIO_Pin_1
#define INVEN_INT_GPIO_PORT GPIOB
#define INVEN_INT_GPIO_CLK RCC_AHB1Periph_GPIOB
#define INVEN_INT_EXTI_PORT EXTI_PortSourceGPIOB
#define INVEN_INT_EXTI_PIN EXTI_PinSource1
#define INVEN_INT_EXTI_LINE EXTI_Line1
#define INVEN_INT_EXTI_IRQ EXTI1_IRQn
Functions
void GPIO_Config (void)
void EnableInvInterrupt (void)
void DisableInvInterrupt (void)
void InvIntHandler (void)
Macro Definition Documentation
INVEN_INT_EXTI_IRQ
#define INVEN_INT_EXTI_IRQ EXTI1_IRQn
Definition at line 24 of file gpio.c.
INVEN_INT_EXTI_LINE
#define INVEN_INT_EXTI_LINE EXTI_Line1
Definition at line 23 of file gpio.c.
INVEN_INT_EXTI_PIN
#define INVEN_INT_EXTI_PIN EXTI_PinSource1
Definition at line 22 of file gpio.c.
INVEN_INT_EXTI_PORT
#define INVEN_INT_EXTI_PORT EXTI_PortSourceGPIOB
Definition at line 21 of file gpio.c.
INVEN_INT_GPIO_CLK
#define INVEN_INT_GPIO_CLK RCC_AHB1Periph_GPIOB
Definition at line 20 of file gpio.c.
INVEN_INT_GPIO_PORT
#define INVEN_INT_GPIO_PORT GPIOB
Definition at line 19 of file gpio.c.
INVEN_INT_PIN
#define INVEN_INT_PIN GPIO_Pin_1
Definition at line 18 of file gpio.c.
Function Documentation
DisableInvInterrupt()
void DisableInvInterrupt (void)
Definition at line 81 of file gpio.c.
References DISABLE, EXTI_ClearITPendingBit(), EXTI_Init(), EXTI_InitTypeDef::EXTI_Line, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_InitTypeDef::EXTI_Mode, EXTI_Mode_Interrupt, EXTI_InitTypeDef::EXTI_Trigger, and EXTI_Trigger_Rising.
{
  EXTI_InitTypeDef EXTI_InitStructure;
    /* Configure EXTI Line1 */
  EXTI_InitStructure.EXTI_Line = INVEN_INT_EXTI_LINE;
  EXTI_InitStructure.EXTI_Mode = EXTI_Mode_Interrupt;
  EXTI_InitStructure.EXTI_Trigger = EXTI_Trigger_Rising;
  EXTI_InitStructure.EXTI_LineCmd = DISABLE;
  EXTI_Init(&EXTI_InitStructure);
  EXTI_ClearITPendingBit(INVEN_INT_EXTI_LINE);
}
EnableInvInterrupt()
void EnableInvInterrupt (void)
Definition at line 71 of file gpio.c.
References ENABLE, EXTI_Init(), EXTI_InitTypeDef::EXTI_Line, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_InitTypeDef::EXTI_Mode, EXTI_Mode_Interrupt, EXTI_InitTypeDef::EXTI_Trigger, and EXTI_Trigger_Rising.
Referenced by GPIO_Config().
{
  EXTI_InitTypeDef EXTI_InitStructure;
  /* Configure EXTI Line1 */
  EXTI_InitStructure.EXTI_Line = INVEN_INT_EXTI_LINE;
  EXTI_InitStructure.EXTI_Mode = EXTI_Mode_Interrupt;
  EXTI_InitStructure.EXTI_Trigger = EXTI_Trigger_Rising;
  EXTI_InitStructure.EXTI_LineCmd = ENABLE;
  EXTI_Init(&EXTI_InitStructure);
}
GPIO_Config()
void GPIO_Config (void)
Definition at line 30 of file gpio.c.
References ENABLE, EnableInvInterrupt(), EXTI_Init(), EXTI_InitTypeDef::EXTI_Line, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_InitTypeDef::EXTI_Mode, EXTI_Mode_Interrupt, EXTI_InitTypeDef::EXTI_Trigger, EXTI_Trigger_Rising, GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_IN, GPIO_InitTypeDef::GPIO_Pin, GPIO_InitTypeDef::GPIO_PuPd, GPIO_PuPd_NOPULL, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_100MHz, NVIC_Init(), NVIC_InitTypeDef::NVIC_IRQChannel, NVIC_InitTypeDef::NVIC_IRQChannelCmd, NVIC_InitTypeDef::NVIC_IRQChannelPreemptionPriority, NVIC_InitTypeDef::NVIC_IRQChannelSubPriority, RCC_AHB1PeriphClockCmd(), RCC_APB2PeriphClockCmd(), and SYSCFG_EXTILineConfig().
Referenced by board_init().
{
  GPIO_InitTypeDef GPIO_InitStructure;
  NVIC_InitTypeDef NVIC_InitStructure;
  EXTI_InitTypeDef EXTI_InitStructure;
// GPIO_DeInit(GPIOA);
// GPIO_DeInit(GPIOC);
  
  /* Enable GPIOB clock */
  RCC_AHB1PeriphClockCmd(INVEN_INT_GPIO_CLK, ENABLE);
  /* Enable SYSCFG clock */
  RCC_APB2PeriphClockCmd(RCC_APB2Periph_SYSCFG, ENABLE);
  
  /* Configure invensense sensor interrupt pin as input floating */
  GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;
  GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
  GPIO_InitStructure.GPIO_Speed = GPIO_Speed_100MHz;
  GPIO_InitStructure.GPIO_Pin = INVEN_INT_PIN;
  GPIO_Init(INVEN_INT_GPIO_PORT, &GPIO_InitStructure); //GPIOA
  /* Connect EXTI Line to inv sensor interrupt pin */
  SYSCFG_EXTILineConfig(INVEN_INT_EXTI_PORT, INVEN_INT_EXTI_PIN);
  /* Configure EXTI Line1 */
  EXTI_InitStructure.EXTI_Line = INVEN_INT_EXTI_LINE;
  EXTI_InitStructure.EXTI_Mode = EXTI_Mode_Interrupt;
  EXTI_InitStructure.EXTI_Trigger = EXTI_Trigger_Rising;
  EXTI_InitStructure.EXTI_LineCmd = ENABLE;
  EXTI_Init(&EXTI_InitStructure);
  /* Enable and set EXTI Line Interrupt to the highest priority */
  NVIC_InitStructure.NVIC_IRQChannel = INVEN_INT_EXTI_IRQ;
  NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0x00;
  NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0x00;
  NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
  NVIC_Init(&NVIC_InitStructure);
  EnableInvInterrupt();
}
InvIntHandler()
void InvIntHandler (void)
Definition at line 93 of file gpio.c.
References EXTI_ClearITPendingBit().
{
  /* Clear the EXTI line 1 pending bit */
   EXTI_ClearITPendingBit(INVEN_INT_EXTI_LINE);
}