C:/Users/Md. Istiaq Mahbub/Desktop/IMU/MPU6050_MotionDriver/Peripheral/src/gpio.h File Reference
Macros
#define ENABLE_INV_INTERRUPTS EnableInvInterrupt()
#define DISABLE_INV_INTERRUPTS DisableInvInterrupt()
Functions
void GPIO_Config (void)
void EnableInvInterrupt (void)
void DisableInvInterrupt (void)
Macro Definition Documentation
DISABLE_INV_INTERRUPTS
#define DISABLE_INV_INTERRUPTS DisableInvInterrupt()
Definition at line 12 of file gpio.h.
ENABLE_INV_INTERRUPTS
#define ENABLE_INV_INTERRUPTS EnableInvInterrupt()
Definition at line 11 of file gpio.h.
Function Documentation
DisableInvInterrupt()
void DisableInvInterrupt (void)
Definition at line 81 of file gpio.c.
References DISABLE, EXTI_ClearITPendingBit(), EXTI_Init(), EXTI_InitTypeDef::EXTI_Line, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_InitTypeDef::EXTI_Mode, EXTI_Mode_Interrupt, EXTI_InitTypeDef::EXTI_Trigger, and EXTI_Trigger_Rising.
{
  EXTI_InitTypeDef EXTI_InitStructure;
    /* Configure EXTI Line1 */
  EXTI_InitStructure.EXTI_Line = INVEN_INT_EXTI_LINE;
  EXTI_InitStructure.EXTI_Mode = EXTI_Mode_Interrupt;
  EXTI_InitStructure.EXTI_Trigger = EXTI_Trigger_Rising;
  EXTI_InitStructure.EXTI_LineCmd = DISABLE;
  EXTI_Init(&EXTI_InitStructure);
  EXTI_ClearITPendingBit(INVEN_INT_EXTI_LINE);
}
EnableInvInterrupt()
void EnableInvInterrupt (void)
Definition at line 71 of file gpio.c.
References ENABLE, EXTI_Init(), EXTI_InitTypeDef::EXTI_Line, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_InitTypeDef::EXTI_Mode, EXTI_Mode_Interrupt, EXTI_InitTypeDef::EXTI_Trigger, and EXTI_Trigger_Rising.
Referenced by GPIO_Config().
{
  EXTI_InitTypeDef EXTI_InitStructure;
  /* Configure EXTI Line1 */
  EXTI_InitStructure.EXTI_Line = INVEN_INT_EXTI_LINE;
  EXTI_InitStructure.EXTI_Mode = EXTI_Mode_Interrupt;
  EXTI_InitStructure.EXTI_Trigger = EXTI_Trigger_Rising;
  EXTI_InitStructure.EXTI_LineCmd = ENABLE;
  EXTI_Init(&EXTI_InitStructure);
}
GPIO_Config()
void GPIO_Config (void)
Definition at line 30 of file gpio.c.
References ENABLE, EnableInvInterrupt(), EXTI_Init(), EXTI_InitTypeDef::EXTI_Line, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_InitTypeDef::EXTI_Mode, EXTI_Mode_Interrupt, EXTI_InitTypeDef::EXTI_Trigger, EXTI_Trigger_Rising, GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_IN, GPIO_InitTypeDef::GPIO_Pin, GPIO_InitTypeDef::GPIO_PuPd, GPIO_PuPd_NOPULL, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_100MHz, NVIC_Init(), NVIC_InitTypeDef::NVIC_IRQChannel, NVIC_InitTypeDef::NVIC_IRQChannelCmd, NVIC_InitTypeDef::NVIC_IRQChannelPreemptionPriority, NVIC_InitTypeDef::NVIC_IRQChannelSubPriority, RCC_AHB1PeriphClockCmd(), RCC_APB2PeriphClockCmd(), and SYSCFG_EXTILineConfig().
Referenced by board_init().
{
  GPIO_InitTypeDef GPIO_InitStructure;
  NVIC_InitTypeDef NVIC_InitStructure;
  EXTI_InitTypeDef EXTI_InitStructure;
// GPIO_DeInit(GPIOA);
// GPIO_DeInit(GPIOC);
  
  /* Enable GPIOB clock */
  RCC_AHB1PeriphClockCmd(INVEN_INT_GPIO_CLK, ENABLE);
  /* Enable SYSCFG clock */
  RCC_APB2PeriphClockCmd(RCC_APB2Periph_SYSCFG, ENABLE);
  
  /* Configure invensense sensor interrupt pin as input floating */
  GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;
  GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
  GPIO_InitStructure.GPIO_Speed = GPIO_Speed_100MHz;
  GPIO_InitStructure.GPIO_Pin = INVEN_INT_PIN;
  GPIO_Init(INVEN_INT_GPIO_PORT, &GPIO_InitStructure); //GPIOA
  /* Connect EXTI Line to inv sensor interrupt pin */
  SYSCFG_EXTILineConfig(INVEN_INT_EXTI_PORT, INVEN_INT_EXTI_PIN);
  /* Configure EXTI Line1 */
  EXTI_InitStructure.EXTI_Line = INVEN_INT_EXTI_LINE;
  EXTI_InitStructure.EXTI_Mode = EXTI_Mode_Interrupt;
  EXTI_InitStructure.EXTI_Trigger = EXTI_Trigger_Rising;
  EXTI_InitStructure.EXTI_LineCmd = ENABLE;
  EXTI_Init(&EXTI_InitStructure);
  /* Enable and set EXTI Line Interrupt to the highest priority */
  NVIC_InitStructure.NVIC_IRQChannel = INVEN_INT_EXTI_IRQ;
  NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0x00;
  NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0x00;
  NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
  NVIC_Init(&NVIC_InitStructure);
  EnableInvInterrupt();
}