Initialization and Configuration functions
Initialization and Configuration functions.
Functions
void CRYP_DeInit (void)
Deinitializes the CRYP peripheral registers to their default reset values.
void CRYP_Init (CRYP_InitTypeDef *CRYP_InitStruct)
Initializes the CRYP peripheral according to the specified parameters in the CRYP_InitStruct.
void CRYP_StructInit (CRYP_InitTypeDef *CRYP_InitStruct)
Fills each CRYP_InitStruct member with its default value.
void CRYP_KeyInit (CRYP_KeyInitTypeDef *CRYP_KeyInitStruct)
Initializes the CRYP Keys according to the specified parameters in the CRYP_KeyInitStruct.
void CRYP_KeyStructInit (CRYP_KeyInitTypeDef *CRYP_KeyInitStruct)
Fills each CRYP_KeyInitStruct member with its default value.
void CRYP_IVInit (CRYP_IVInitTypeDef *CRYP_IVInitStruct)
Initializes the CRYP Initialization Vectors(IV) according to the specified parameters in the CRYP_IVInitStruct.
void CRYP_IVStructInit (CRYP_IVInitTypeDef *CRYP_IVInitStruct)
Fills each CRYP_IVInitStruct member with its default value.
void CRYP_FIFOFlush (void)
Flushes the IN and OUT FIFOs (that is read and write pointers of the FIFOs are reset)
void CRYP_Cmd (FunctionalState NewState)
Enables or disables the CRYP peripheral.
Detailed Description
Initialization and Configuration functions.
 ===============================================================================
                      Initialization and Configuration functions
 ===============================================================================  
  This section provides functions allowing to 
   - Initialize the cryptographic Processor using CRYP_Init() function 
      -  Encrypt or Decrypt 
      -  mode : TDES-ECB, TDES-CBC, 
                DES-ECB, DES-CBC, 
                AES-ECB, AES-CBC, AES-CTR, AES-Key 
      - DataType :  32-bit data, 16-bit data, bit data or bit-string
      - Key Size (only in AES modes)
   - Configure the Encrypt or Decrypt Key using CRYP_KeyInit() function 
   - Configure the Initialization Vectors(IV) for CBC and CTR modes using 
     CRYP_IVInit() function.  
   - Flushes the IN and OUT FIFOs : using CRYP_FIFOFlush() function.                         
   - Enable or disable the CRYP Processor using CRYP_Cmd() function 
Function Documentation
CRYP_Cmd()
void CRYP_Cmd (FunctionalState NewState)
Enables or disables the CRYP peripheral.
Parameters
NewState new state of the CRYP peripheral. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 370 of file stm32f4xx_cryp.c.
References DISABLE.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the Cryptographic processor */
    CRYP->CR |= CRYP_CR_CRYPEN;
  }
  else
  {
    /* Disable the Cryptographic processor */
    CRYP->CR &= ~CRYP_CR_CRYPEN;
  }
}
CRYP_DeInit()
void CRYP_DeInit (void)
Deinitializes the CRYP peripheral registers to their default reset values.
Parameters
None
Return values
None
Definition at line 215 of file stm32f4xx_cryp.c.
References DISABLE, ENABLE, and RCC_AHB2PeriphResetCmd().
{
  /* Enable CRYP reset state */
  RCC_AHB2PeriphResetCmd(RCC_AHB2Periph_CRYP, ENABLE);
  /* Release CRYP from reset state */
  RCC_AHB2PeriphResetCmd(RCC_AHB2Periph_CRYP, DISABLE);
}
CRYP_FIFOFlush()
void CRYP_FIFOFlush (void)
Flushes the IN and OUT FIFOs (that is read and write pointers of the FIFOs are reset)
Note
The FIFOs must be flushed only when BUSY flag is reset.
Parameters
None
Return values
None
Definition at line 358 of file stm32f4xx_cryp.c.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().
{
  /* Reset the read and write pointers of the FIFOs */
  CRYP->CR |= CRYP_CR_FFLUSH;
}
CRYP_Init()
void CRYP_Init (CRYP_InitTypeDef * CRYP_InitStruct)
Initializes the CRYP peripheral according to the specified parameters in the CRYP_InitStruct.
Parameters
CRYP_InitStruct pointer to a CRYP_InitTypeDef structure that contains the configuration information for the CRYP peripheral.
Return values
None
Definition at line 231 of file stm32f4xx_cryp.c.
References CRYP_InitTypeDef::CRYP_AlgoMode.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().
{
  /* Check the parameters */
  assert_param(IS_CRYP_ALGOMODE(CRYP_InitStruct->CRYP_AlgoMode));
  assert_param(IS_CRYP_DATATYPE(CRYP_InitStruct->CRYP_DataType));
  assert_param(IS_CRYP_ALGODIR(CRYP_InitStruct->CRYP_AlgoDir));
  /* Select Algorithm mode*/
  CRYP->CR &= ~CRYP_CR_ALGOMODE;
  CRYP->CR |= CRYP_InitStruct->CRYP_AlgoMode;
  /* Select dataType */
  CRYP->CR &= ~CRYP_CR_DATATYPE;
  CRYP->CR |= CRYP_InitStruct->CRYP_DataType;
  /* select Key size (used only with AES algorithm) */
  if ((CRYP_InitStruct->CRYP_AlgoMode == CRYP_AlgoMode_AES_ECB) ||
      (CRYP_InitStruct->CRYP_AlgoMode == CRYP_AlgoMode_AES_CBC) ||
      (CRYP_InitStruct->CRYP_AlgoMode == CRYP_AlgoMode_AES_CTR) ||
      (CRYP_InitStruct->CRYP_AlgoMode == CRYP_AlgoMode_AES_Key))
  {
    assert_param(IS_CRYP_KEYSIZE(CRYP_InitStruct->CRYP_KeySize));
    CRYP->CR &= ~CRYP_CR_KEYSIZE;
    CRYP->CR |= CRYP_InitStruct->CRYP_KeySize; /* Key size and value must be
                                                  configured once the key has
                                                  been prepared */
  }
  /* Select data Direction */
  CRYP->CR &= ~CRYP_CR_ALGODIR;
  CRYP->CR |= CRYP_InitStruct->CRYP_AlgoDir;
}
CRYP_IVInit()
void CRYP_IVInit (CRYP_IVInitTypeDef * CRYP_IVInitStruct)
Initializes the CRYP Initialization Vectors(IV) according to the specified parameters in the CRYP_IVInitStruct.
Parameters
CRYP_IVInitStruct pointer to a CRYP_IVInitTypeDef structure that contains the configuration information for the CRYP Initialization Vectors(IV).
Return values
None
Definition at line 329 of file stm32f4xx_cryp.c.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_DES_CBC(), and CRYP_TDES_CBC().
{
  CRYP->IV0LR = CRYP_IVInitStruct->CRYP_IV0Left;
  CRYP->IV0RR = CRYP_IVInitStruct->CRYP_IV0Right;
  CRYP->IV1LR = CRYP_IVInitStruct->CRYP_IV1Left;
  CRYP->IV1RR = CRYP_IVInitStruct->CRYP_IV1Right;
}
CRYP_IVStructInit()
void CRYP_IVStructInit (CRYP_IVInitTypeDef * CRYP_IVInitStruct)
Fills each CRYP_IVInitStruct member with its default value.
Parameters
CRYP_IVInitStruct pointer to a CRYP_IVInitTypeDef Initialization Vectors(IV) structure which will be initialized.
Return values
None
Definition at line 343 of file stm32f4xx_cryp.c.
References CRYP_IVInitTypeDef::CRYP_IV0Left, CRYP_IVInitTypeDef::CRYP_IV0Right, CRYP_IVInitTypeDef::CRYP_IV1Left, and CRYP_IVInitTypeDef::CRYP_IV1Right.
{
  CRYP_IVInitStruct->CRYP_IV0Left = 0;
  CRYP_IVInitStruct->CRYP_IV0Right = 0;
  CRYP_IVInitStruct->CRYP_IV1Left = 0;
  CRYP_IVInitStruct->CRYP_IV1Right = 0;
}
CRYP_KeyInit()
void CRYP_KeyInit (CRYP_KeyInitTypeDef * CRYP_KeyInitStruct)
Initializes the CRYP Keys according to the specified parameters in the CRYP_KeyInitStruct.
Parameters
CRYP_KeyInitStruct pointer to a CRYP_KeyInitTypeDef structure that contains the configuration information for the CRYP Keys.
Return values
None
Definition at line 292 of file stm32f4xx_cryp.c.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().
{
  /* Key Initialisation */
  CRYP->K0LR = CRYP_KeyInitStruct->CRYP_Key0Left;
  CRYP->K0RR = CRYP_KeyInitStruct->CRYP_Key0Right;
  CRYP->K1LR = CRYP_KeyInitStruct->CRYP_Key1Left;
  CRYP->K1RR = CRYP_KeyInitStruct->CRYP_Key1Right;
  CRYP->K2LR = CRYP_KeyInitStruct->CRYP_Key2Left;
  CRYP->K2RR = CRYP_KeyInitStruct->CRYP_Key2Right;
  CRYP->K3LR = CRYP_KeyInitStruct->CRYP_Key3Left;
  CRYP->K3RR = CRYP_KeyInitStruct->CRYP_Key3Right;
}
CRYP_KeyStructInit()
void CRYP_KeyStructInit (CRYP_KeyInitTypeDef * CRYP_KeyInitStruct)
Fills each CRYP_KeyInitStruct member with its default value.
Parameters
CRYP_KeyInitStruct pointer to a CRYP_KeyInitTypeDef structure which will be initialized.
Return values
None
Definition at line 311 of file stm32f4xx_cryp.c.
References CRYP_KeyInitTypeDef::CRYP_Key0Left, CRYP_KeyInitTypeDef::CRYP_Key0Right, CRYP_KeyInitTypeDef::CRYP_Key1Left, CRYP_KeyInitTypeDef::CRYP_Key1Right, CRYP_KeyInitTypeDef::CRYP_Key2Left, CRYP_KeyInitTypeDef::CRYP_Key2Right, CRYP_KeyInitTypeDef::CRYP_Key3Left, and CRYP_KeyInitTypeDef::CRYP_Key3Right.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().
{
  CRYP_KeyInitStruct->CRYP_Key0Left = 0;
  CRYP_KeyInitStruct->CRYP_Key0Right = 0;
  CRYP_KeyInitStruct->CRYP_Key1Left = 0;
  CRYP_KeyInitStruct->CRYP_Key1Right = 0;
  CRYP_KeyInitStruct->CRYP_Key2Left = 0;
  CRYP_KeyInitStruct->CRYP_Key2Right = 0;
  CRYP_KeyInitStruct->CRYP_Key3Left = 0;
  CRYP_KeyInitStruct->CRYP_Key3Right = 0;
}
CRYP_StructInit()
void CRYP_StructInit (CRYP_InitTypeDef * CRYP_InitStruct)
Fills each CRYP_InitStruct member with its default value.
Parameters
CRYP_InitStruct pointer to a CRYP_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 270 of file stm32f4xx_cryp.c.
References CRYP_InitTypeDef::CRYP_AlgoDir, CRYP_InitTypeDef::CRYP_AlgoMode, CRYP_InitTypeDef::CRYP_DataType, and CRYP_InitTypeDef::CRYP_KeySize.
{
  /* Initialize the CRYP_AlgoDir member */
  CRYP_InitStruct->CRYP_AlgoDir = CRYP_AlgoDir_Encrypt;
  /* initialize the CRYP_AlgoMode member */
  CRYP_InitStruct->CRYP_AlgoMode = CRYP_AlgoMode_TDES_ECB;
  /* initialize the CRYP_DataType member */
  CRYP_InitStruct->CRYP_DataType = CRYP_DataType_32b;
  
  /* Initialize the CRYP_KeySize member */
  CRYP_InitStruct->CRYP_KeySize = CRYP_KeySize_128b;
}