Initialization and Configuration functions
Initialization and Configuration functions.
Functions
void USART_DeInit (USART_TypeDef * USARTx)
Deinitializes the USARTx peripheral registers to their default reset values.
void USART_Init (USART_TypeDef * USARTx, USART_InitTypeDef *USART_InitStruct)
Initializes the USARTx peripheral according to the specified parameters in the USART_InitStruct .
void USART_StructInit (USART_InitTypeDef *USART_InitStruct)
Fills each USART_InitStruct member with its default value.
void USART_ClockInit (USART_TypeDef * USARTx, USART_ClockInitTypeDef *USART_ClockInitStruct)
Initializes the USARTx peripheral Clock according to the specified parameters in the USART_ClockInitStruct .
void USART_ClockStructInit (USART_ClockInitTypeDef *USART_ClockInitStruct)
Fills each USART_ClockInitStruct member with its default value.
void USART_Cmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the specified USART peripheral.
void USART_SetPrescaler (USART_TypeDef * USARTx, uint8_t USART_Prescaler)
Sets the system clock prescaler.
void USART_OverSampling8Cmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's 8x oversampling mode.
void USART_OneBitMethodCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's one bit sampling method.
Detailed Description
Initialization and Configuration functions.
 ===============================================================================
                  Initialization and Configuration functions
 ===============================================================================  

  This subsection provides a set of functions allowing to initialize the USART 
  in asynchronous and in synchronous modes.
   - For the asynchronous mode only these parameters can be configured: 
        - Baud Rate
        - Word Length 
        - Stop Bit
        - Parity: If the parity is enabled, then the MSB bit of the data written
          in the data register is transmitted but is changed by the parity bit.
          Depending on the frame length defined by the M bit (8-bits or 9-bits),
          the possible USART frame formats are as listed in the following table:
   +-------------------------------------------------------------+     
   |   M bit |  PCE bit  |            USART frame                |
   |---------------------|---------------------------------------|             
   |    0    |    0      |    | SB | 8 bit data | STB |          |
   |---------|-----------|---------------------------------------|  
   |    0    |    1      |    | SB | 7 bit data | PB | STB |     |
   |---------|-----------|---------------------------------------|  
   |    1    |    0      |    | SB | 9 bit data | STB |          |
   |---------|-----------|---------------------------------------|  
   |    1    |    1      |    | SB | 8 bit data | PB | STB |     |
   +-------------------------------------------------------------+            
        - Hardware flow control
        - Receiver/transmitter modes

  The USART_Init() function follows the USART  asynchronous configuration procedure
  (details for the procedure are available in reference manual (RM0090)).

  - For the synchronous mode in addition to the asynchronous mode parameters these 
    parameters should be also configured:
        - USART Clock Enabled
        - USART polarity
        - USART phase
        - USART LastBit
  
  These parameters can be configured using the USART_ClockInit() function.
Function Documentation
USART_ClockInit()
void USART_ClockInit (USART_TypeDef * USARTx, USART_ClockInitTypeDef * USART_ClockInitStruct)
Initializes the USARTx peripheral Clock according to the specified parameters in the USART_ClockInitStruct .
Parameters
USARTx where x can be 1, 2, 3 or 6 to select the USART peripheral.
USART_ClockInitStruct pointer to a USART_ClockInitTypeDef structure that contains the configuration information for the specified USART peripheral.
Note
The Smart Card and Synchronous modes are not available for UART4 and UART5.
Return values
None
Definition at line 360 of file stm32f4xx_usart.c.
References USART_ClockInitTypeDef::USART_Clock, USART_ClockInitTypeDef::USART_CPHA, USART_ClockInitTypeDef::USART_CPOL, and USART_ClockInitTypeDef::USART_LastBit.
{
  uint32_t tmpreg = 0x00;
  /* Check the parameters */
  assert_param(IS_USART_1236_PERIPH(USARTx));
  assert_param(IS_USART_CLOCK(USART_ClockInitStruct->USART_Clock));
  assert_param(IS_USART_CPOL(USART_ClockInitStruct->USART_CPOL));
  assert_param(IS_USART_CPHA(USART_ClockInitStruct->USART_CPHA));
  assert_param(IS_USART_LASTBIT(USART_ClockInitStruct->USART_LastBit));
  
/*---------------------------- USART CR2 Configuration -----------------------*/
  tmpreg = USARTx->CR2;
  /* Clear CLKEN, CPOL, CPHA and LBCL bits */
  tmpreg &= (uint32_t)~((uint32_t)CR2_CLOCK_CLEAR_MASK);
  /* Configure the USART Clock, CPOL, CPHA and LastBit ------------*/
  /* Set CLKEN bit according to USART_Clock value */
  /* Set CPOL bit according to USART_CPOL value */
  /* Set CPHA bit according to USART_CPHA value */
  /* Set LBCL bit according to USART_LastBit value */
  tmpreg |= (uint32_t)USART_ClockInitStruct->USART_Clock | USART_ClockInitStruct->
      USART_CPOL |
                 USART_ClockInitStruct->USART_CPHA | USART_ClockInitStruct->
      USART_LastBit;
  /* Write to USART CR2 */
  USARTx->CR2 = (uint16_t)tmpreg;
}
USART_ClockStructInit()
void USART_ClockStructInit (USART_ClockInitTypeDef * USART_ClockInitStruct)
Fills each USART_ClockInitStruct member with its default value.
Parameters
USART_ClockInitStruct pointer to a USART_ClockInitTypeDef structure which will be initialized.
Return values
None
Definition at line 391 of file stm32f4xx_usart.c.
References USART_ClockInitTypeDef::USART_Clock, USART_ClockInitTypeDef::USART_CPHA, USART_ClockInitTypeDef::USART_CPOL, and USART_ClockInitTypeDef::USART_LastBit.
{
  /* USART_ClockInitStruct members default value */
  USART_ClockInitStruct->USART_Clock = USART_Clock_Disable;
  USART_ClockInitStruct->USART_CPOL = USART_CPOL_Low;
  USART_ClockInitStruct->USART_CPHA = USART_CPHA_1Edge;
  USART_ClockInitStruct->USART_LastBit = USART_LastBit_Disable;
}
USART_Cmd()
void USART_Cmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the specified USART peripheral.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
NewState new state of the USARTx peripheral. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 408 of file stm32f4xx_usart.c.
References DISABLE.
Referenced by USART_Config().
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the selected USART by setting the UE bit in the CR1 register */
    USARTx->CR1 |= USART_CR1_UE;
  }
  else
  {
    /* Disable the selected USART by clearing the UE bit in the CR1 register */
    USARTx->CR1 &= (uint16_t)~((uint16_t)USART_CR1_UE);
  }
}
USART_DeInit()
void USART_DeInit (USART_TypeDef * USARTx)
Deinitializes the USARTx peripheral registers to their default reset values.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
Return values
None
Definition at line 178 of file stm32f4xx_usart.c.
References DISABLE, ENABLE, RCC_APB1PeriphResetCmd(), and RCC_APB2PeriphResetCmd().
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  if (USARTx == USART1)
  {
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_USART1, ENABLE);
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_USART1, DISABLE);
  }
  else if (USARTx == USART2)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_USART2, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_USART2, DISABLE);
  }
  else if (USARTx == USART3)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_USART3, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_USART3, DISABLE);
  }
  else if (USARTx == UART4)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_UART4, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_UART4, DISABLE);
  }
  else if (USARTx == UART5)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_UART5, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_UART5, DISABLE);
  }
  else
  {
    if (USARTx == USART6)
    {
      RCC_APB2PeriphResetCmd(RCC_APB2Periph_USART6, ENABLE);
      RCC_APB2PeriphResetCmd(RCC_APB2Periph_USART6, DISABLE);
    }
  }
}
USART_Init()
void USART_Init (USART_TypeDef * USARTx, USART_InitTypeDef * USART_InitStruct)
Initializes the USARTx peripheral according to the specified parameters in the USART_InitStruct .
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_InitStruct pointer to a USART_InitTypeDef structure that contains the configuration information for the specified USART peripheral.
Return values
None
Definition at line 227 of file stm32f4xx_usart.c.
References RCC_ClocksTypeDef::PCLK1_Frequency, RCC_ClocksTypeDef::PCLK2_Frequency, RCC_GetClocksFreq(), USART_InitTypeDef::USART_HardwareFlowControl, USART_InitTypeDef::USART_Mode, USART_InitTypeDef::USART_Parity, USART_InitTypeDef::USART_StopBits, and USART_InitTypeDef::USART_WordLength.
Referenced by USART_Config().
{
  uint32_t tmpreg = 0x00, apbclock = 0x00;
  uint32_t integerdivider = 0x00;
  uint32_t fractionaldivider = 0x00;
  RCC_ClocksTypeDef RCC_ClocksStatus;
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_BAUDRATE(USART_InitStruct->USART_BaudRate));
  assert_param(IS_USART_WORD_LENGTH(USART_InitStruct->USART_WordLength));
  assert_param(IS_USART_STOPBITS(USART_InitStruct->USART_StopBits));
  assert_param(IS_USART_PARITY(USART_InitStruct->USART_Parity));
  assert_param(IS_USART_MODE(USART_InitStruct->USART_Mode));
  assert_param(IS_USART_HARDWARE_FLOW_CONTROL(USART_InitStruct->
      USART_HardwareFlowControl));
  /* The hardware flow control is available only for USART1, USART2, USART3 and USART6 */
  if (USART_InitStruct->USART_HardwareFlowControl !=
      USART_HardwareFlowControl_None)
  {
    assert_param(IS_USART_1236_PERIPH(USARTx));
  }
/*---------------------------- USART CR2 Configuration -----------------------*/
  tmpreg = USARTx->CR2;
  /* Clear STOP[13:12] bits */
  tmpreg &= (uint32_t)~((uint32_t)USART_CR2_STOP);
  /* Configure the USART Stop Bits, Clock, CPOL, CPHA and LastBit :
      Set STOP[13:12] bits according to USART_StopBits value */
  tmpreg |= (uint32_t)USART_InitStruct->USART_StopBits;
  
  /* Write to USART CR2 */
  USARTx->CR2 = (uint16_t)tmpreg;
/*---------------------------- USART CR1 Configuration -----------------------*/
  tmpreg = USARTx->CR1;
  /* Clear M, PCE, PS, TE and RE bits */
  tmpreg &= (uint32_t)~((uint32_t)CR1_CLEAR_MASK);
  /* Configure the USART Word Length, Parity and mode:
     Set the M bits according to USART_WordLength value
     Set PCE and PS bits according to USART_Parity value
     Set TE and RE bits according to USART_Mode value */
  tmpreg |= (uint32_t)USART_InitStruct->USART_WordLength | USART_InitStruct->
      USART_Parity |
            USART_InitStruct->USART_Mode;
  /* Write to USART CR1 */
  USARTx->CR1 = (uint16_t)tmpreg;
/*---------------------------- USART CR3 Configuration -----------------------*/
  tmpreg = USARTx->CR3;
  /* Clear CTSE and RTSE bits */
  tmpreg &= (uint32_t)~((uint32_t)CR3_CLEAR_MASK);
  /* Configure the USART HFC :
      Set CTSE and RTSE bits according to USART_HardwareFlowControl value */
  tmpreg |= USART_InitStruct->USART_HardwareFlowControl;
  /* Write to USART CR3 */
  USARTx->CR3 = (uint16_t)tmpreg;
/*---------------------------- USART BRR Configuration -----------------------*/
  /* Configure the USART Baud Rate */
  RCC_GetClocksFreq(&RCC_ClocksStatus);
  if ((USARTx == USART1) || (USARTx == USART6))
  {
    apbclock = RCC_ClocksStatus.PCLK2_Frequency;
  }
  else
  {
    apbclock = RCC_ClocksStatus.PCLK1_Frequency;
  }
  
  /* Determine the integer part */
  if ((USARTx->CR1 & USART_CR1_OVER8) != 0)
  {
    /* Integer part computing in case Oversampling mode is 8 Samples */
    integerdivider = ((25 * apbclock) / (2 * (USART_InitStruct->USART_BaudRate)));
  }
  else /* if ((USARTx->CR1 & USART_CR1_OVER8) == 0) */
  {
    /* Integer part computing in case Oversampling mode is 16 Samples */
    integerdivider = ((25 * apbclock) / (4 * (USART_InitStruct->USART_BaudRate)));
  }
  tmpreg = (integerdivider / 100) << 4;
  /* Determine the fractional part */
  fractionaldivider = integerdivider - (100 * (tmpreg >> 4));
  /* Implement the fractional part in the register */
  if ((USARTx->CR1 & USART_CR1_OVER8) != 0)
  {
    tmpreg |= ((((fractionaldivider * 8) + 50) / 100)) & ((uint8_t)0x07);
  }
  else /* if ((USARTx->CR1 & USART_CR1_OVER8) == 0) */
  {
    tmpreg |= ((((fractionaldivider * 16) + 50) / 100)) & ((uint8_t)0x0F);
  }
  
  /* Write to USART BRR register */
  USARTx->BRR = (uint16_t)tmpreg;
}
USART_OneBitMethodCmd()
void USART_OneBitMethodCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's one bit sampling method.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
NewState new state of the USART one bit sampling method. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 481 of file stm32f4xx_usart.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the one bit method by setting the ONEBITE bit in the CR3 register */
    USARTx->CR3 |= USART_CR3_ONEBIT;
  }
  else
  {
    /* Disable the one bit method by clearing the ONEBITE bit in the CR3 register */
    USARTx->CR3 &= (uint16_t)~((uint16_t)USART_CR3_ONEBIT);
  }
}
USART_OverSampling8Cmd()
void USART_OverSampling8Cmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's 8x oversampling mode.
Note
This function has to be called before calling USART_Init() function in order to have correct baudrate Divider value.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
NewState new state of the USART 8x oversampling mode. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 455 of file stm32f4xx_usart.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the 8x Oversampling mode by setting the OVER8 bit in the CR1 register */
    USARTx->CR1 |= USART_CR1_OVER8;
  }
  else
  {
    /* Disable the 8x Oversampling mode by clearing the OVER8 bit in the CR1 register */
    USARTx->CR1 &= (uint16_t)~((uint16_t)USART_CR1_OVER8);
  }
}
USART_SetPrescaler()
void USART_SetPrescaler (USART_TypeDef * USARTx, uint8_t USART_Prescaler)
Sets the system clock prescaler.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_Prescaler specifies the prescaler clock.
Note
The function is used for IrDA mode with UART4 and UART5.
Return values
None
Definition at line 434 of file stm32f4xx_usart.c.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  
  /* Clear the USART prescaler */
  USARTx->GTPR &= USART_GTPR_GT;
  /* Set the USART prescaler */
  USARTx->GTPR |= USART_Prescaler;
}
USART_StructInit()
void USART_StructInit (USART_InitTypeDef * USART_InitStruct)
Fills each USART_InitStruct member with its default value.
Parameters
USART_InitStruct pointer to a USART_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 340 of file stm32f4xx_usart.c.
References USART_InitTypeDef::USART_BaudRate, USART_InitTypeDef::USART_HardwareFlowControl, USART_InitTypeDef::USART_Mode, USART_InitTypeDef::USART_Parity, USART_InitTypeDef::USART_StopBits, and USART_InitTypeDef::USART_WordLength.
{
  /* USART_InitStruct members default value */
  USART_InitStruct->USART_BaudRate = 9600;
  USART_InitStruct->USART_WordLength = USART_WordLength_8b;
  USART_InitStruct->USART_StopBits = USART_StopBits_1;
  USART_InitStruct->USART_Parity = USART_Parity_No ;
  USART_InitStruct->USART_Mode = USART_Mode_Rx | USART_Mode_Tx;
  USART_InitStruct->USART_HardwareFlowControl = USART_HardwareFlowControl_None;
}