TIM_Private_Functions
Modules
 Advanced-control timers (TIM1 and TIM8) specific features
Advanced-control timers (TIM1 and TIM8) specific features.
 Clocks management functions
Clocks management functions.
 Input Capture management functions
Input Capture management functions.
 Interrupts DMA and flags management functions
Interrupts, DMA and flags management functions.
 Output Compare management functions
Output Compare management functions.
 Specific interface management functions
Specific interface management functions.
 Specific remapping management function
Specific remapping management function.
 Synchronization management functions
Synchronization management functions.
 TimeBase management functions
TimeBase management functions.
Functions
static void TI1_Config (TIM_TypeDef *TIMx, uint16_t TIM_ICPolarity, uint16_t TIM_ICSelection, uint16_t TIM_ICFilter)
Configure the TI1 as Input.
static void TI2_Config (TIM_TypeDef *TIMx, uint16_t TIM_ICPolarity, uint16_t TIM_ICSelection, uint16_t TIM_ICFilter)
Configure the TI2 as Input.
static void TI3_Config (TIM_TypeDef *TIMx, uint16_t TIM_ICPolarity, uint16_t TIM_ICSelection, uint16_t TIM_ICFilter)
Configure the TI3 as Input.
static void TI4_Config (TIM_TypeDef *TIMx, uint16_t TIM_ICPolarity, uint16_t TIM_ICSelection, uint16_t TIM_ICFilter)
Configure the TI4 as Input.
Detailed Description
Function Documentation
TI1_Config()
static void TI1_Config (TIM_TypeDef * TIMx, uint16_t TIM_ICPolarity, uint16_t TIM_ICSelection, uint16_t TIM_ICFilter) [static]
Configure the TI1 as Input.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13 or 14 to select the TIM peripheral.
TIM_ICPolarity : The Input Polarity. This parameter can be one of the following values:
TIM_ICPolarity_Rising
TIM_ICPolarity_Falling
TIM_ICPolarity_BothEdge
TIM_ICSelection specifies the input to be used. This parameter can be one of the following values:
TIM_ICSelection_DirectTI: TIM Input 1 is selected to be connected to IC1.
TIM_ICSelection_IndirectTI: TIM Input 1 is selected to be connected to IC2.
TIM_ICSelection_TRC: TIM Input 1 is selected to be connected to TRC.
TIM_ICFilter Specifies the Input Capture Filter. This parameter must be a value between 0x00 and 0x0F.
Return values
None
Definition at line 3191 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit(), TIM_PWMIConfig(), and TIM_TIxExternalClockConfig().
{
  uint16_t tmpccmr1 = 0, tmpccer = 0;
  /* Disable the Channel 1: Reset the CC1E Bit */
  TIMx->CCER &= (uint16_t)~TIM_CCER_CC1E;
  tmpccmr1 = TIMx->CCMR1;
  tmpccer = TIMx->CCER;
  /* Select the Input and set the filter */
  tmpccmr1 &= ((uint16_t)~TIM_CCMR1_CC1S) & ((uint16_t)~TIM_CCMR1_IC1F);
  tmpccmr1 |= (uint16_t)(TIM_ICSelection | (uint16_t)(TIM_ICFilter << (uint16_t)4));
  /* Select the Polarity and set the CC1E Bit */
  tmpccer &= (uint16_t)~(TIM_CCER_CC1P | TIM_CCER_CC1NP);
  tmpccer |= (uint16_t)(TIM_ICPolarity | (uint16_t)TIM_CCER_CC1E);
  /* Write to TIMx CCMR1 and CCER registers */
  TIMx->CCMR1 = tmpccmr1;
  TIMx->CCER = tmpccer;
}
TI2_Config()
static void TI2_Config (TIM_TypeDef * TIMx, uint16_t TIM_ICPolarity, uint16_t TIM_ICSelection, uint16_t TIM_ICFilter) [static]
Configure the TI2 as Input.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_ICPolarity : The Input Polarity. This parameter can be one of the following values:
TIM_ICPolarity_Rising
TIM_ICPolarity_Falling
TIM_ICPolarity_BothEdge
TIM_ICSelection specifies the input to be used. This parameter can be one of the following values:
TIM_ICSelection_DirectTI: TIM Input 2 is selected to be connected to IC2.
TIM_ICSelection_IndirectTI: TIM Input 2 is selected to be connected to IC1.
TIM_ICSelection_TRC: TIM Input 2 is selected to be connected to TRC.
TIM_ICFilter Specifies the Input Capture Filter. This parameter must be a value between 0x00 and 0x0F.
Return values
None
Definition at line 3232 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit(), TIM_PWMIConfig(), and TIM_TIxExternalClockConfig().
{
  uint16_t tmpccmr1 = 0, tmpccer = 0, tmp = 0;
  /* Disable the Channel 2: Reset the CC2E Bit */
  TIMx->CCER &= (uint16_t)~TIM_CCER_CC2E;
  tmpccmr1 = TIMx->CCMR1;
  tmpccer = TIMx->CCER;
  tmp = (uint16_t)(TIM_ICPolarity << 4);
  /* Select the Input and set the filter */
  tmpccmr1 &= ((uint16_t)~TIM_CCMR1_CC2S) & ((uint16_t)~TIM_CCMR1_IC2F);
  tmpccmr1 |= (uint16_t)(TIM_ICFilter << 12);
  tmpccmr1 |= (uint16_t)(TIM_ICSelection << 8);
  /* Select the Polarity and set the CC2E Bit */
  tmpccer &= (uint16_t)~(TIM_CCER_CC2P | TIM_CCER_CC2NP);
  tmpccer |= (uint16_t)(tmp | (uint16_t)TIM_CCER_CC2E);
  /* Write to TIMx CCMR1 and CCER registers */
  TIMx->CCMR1 = tmpccmr1 ;
  TIMx->CCER = tmpccer;
}
TI3_Config()
static void TI3_Config (TIM_TypeDef * TIMx, uint16_t TIM_ICPolarity, uint16_t TIM_ICSelection, uint16_t TIM_ICFilter) [static]
Configure the TI3 as Input.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ICPolarity : The Input Polarity. This parameter can be one of the following values:
TIM_ICPolarity_Rising
TIM_ICPolarity_Falling
TIM_ICPolarity_BothEdge
TIM_ICSelection specifies the input to be used. This parameter can be one of the following values:
TIM_ICSelection_DirectTI: TIM Input 3 is selected to be connected to IC3.
TIM_ICSelection_IndirectTI: TIM Input 3 is selected to be connected to IC4.
TIM_ICSelection_TRC: TIM Input 3 is selected to be connected to TRC.
TIM_ICFilter Specifies the Input Capture Filter. This parameter must be a value between 0x00 and 0x0F.
Return values
None
Definition at line 3274 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit().
{
  uint16_t tmpccmr2 = 0, tmpccer = 0, tmp = 0;
  /* Disable the Channel 3: Reset the CC3E Bit */
  TIMx->CCER &= (uint16_t)~TIM_CCER_CC3E;
  tmpccmr2 = TIMx->CCMR2;
  tmpccer = TIMx->CCER;
  tmp = (uint16_t)(TIM_ICPolarity << 8);
  /* Select the Input and set the filter */
  tmpccmr2 &= ((uint16_t)~TIM_CCMR1_CC1S) & ((uint16_t)~TIM_CCMR2_IC3F);
  tmpccmr2 |= (uint16_t)(TIM_ICSelection | (uint16_t)(TIM_ICFilter << (uint16_t)4));
  /* Select the Polarity and set the CC3E Bit */
  tmpccer &= (uint16_t)~(TIM_CCER_CC3P | TIM_CCER_CC3NP);
  tmpccer |= (uint16_t)(tmp | (uint16_t)TIM_CCER_CC3E);
  /* Write to TIMx CCMR2 and CCER registers */
  TIMx->CCMR2 = tmpccmr2;
  TIMx->CCER = tmpccer;
}
TI4_Config()
static void TI4_Config (TIM_TypeDef * TIMx, uint16_t TIM_ICPolarity, uint16_t TIM_ICSelection, uint16_t TIM_ICFilter) [static]
Configure the TI4 as Input.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ICPolarity : The Input Polarity. This parameter can be one of the following values:
TIM_ICPolarity_Rising
TIM_ICPolarity_Falling
TIM_ICPolarity_BothEdge
TIM_ICSelection specifies the input to be used. This parameter can be one of the following values:
TIM_ICSelection_DirectTI: TIM Input 4 is selected to be connected to IC4.
TIM_ICSelection_IndirectTI: TIM Input 4 is selected to be connected to IC3.
TIM_ICSelection_TRC: TIM Input 4 is selected to be connected to TRC.
TIM_ICFilter Specifies the Input Capture Filter. This parameter must be a value between 0x00 and 0x0F.
Return values
None
Definition at line 3315 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit().
{
  uint16_t tmpccmr2 = 0, tmpccer = 0, tmp = 0;
  /* Disable the Channel 4: Reset the CC4E Bit */
  TIMx->CCER &= (uint16_t)~TIM_CCER_CC4E;
  tmpccmr2 = TIMx->CCMR2;
  tmpccer = TIMx->CCER;
  tmp = (uint16_t)(TIM_ICPolarity << 12);
  /* Select the Input and set the filter */
  tmpccmr2 &= ((uint16_t)~TIM_CCMR1_CC2S) & ((uint16_t)~TIM_CCMR1_IC2F);
  tmpccmr2 |= (uint16_t)(TIM_ICSelection << 8);
  tmpccmr2 |= (uint16_t)(TIM_ICFilter << 12);
  /* Select the Polarity and set the CC4E Bit */
  tmpccer &= (uint16_t)~(TIM_CCER_CC4P | TIM_CCER_CC4NP);
  tmpccer |= (uint16_t)(tmp | (uint16_t)TIM_CCER_CC4E);
  /* Write to TIMx CCMR2 and CCER registers */
  TIMx->CCMR2 = tmpccmr2;
  TIMx->CCER = tmpccer ;
}