Input Capture management functions
Input Capture management functions.
Functions
void TIM_ICInit (TIM_TypeDef *TIMx, TIM_ICInitTypeDef *TIM_ICInitStruct)
Initializes the TIM peripheral according to the specified parameters in the TIM_ICInitStruct.
void TIM_ICStructInit (TIM_ICInitTypeDef *TIM_ICInitStruct)
Fills each TIM_ICInitStruct member with its default value.
void TIM_PWMIConfig (TIM_TypeDef *TIMx, TIM_ICInitTypeDef *TIM_ICInitStruct)
Configures the TIM peripheral according to the specified parameters in the TIM_ICInitStruct to measure an external PWM signal.
uint32_t TIM_GetCapture1 (TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 1 value.
uint32_t TIM_GetCapture2 (TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 2 value.
uint32_t TIM_GetCapture3 (TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 3 value.
uint32_t TIM_GetCapture4 (TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 4 value.
void TIM_SetIC1Prescaler (TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 1 prescaler.
void TIM_SetIC2Prescaler (TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 2 prescaler.
void TIM_SetIC3Prescaler (TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 3 prescaler.
void TIM_SetIC4Prescaler (TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 4 prescaler.
Detailed Description
Input Capture management functions.
 ===============================================================================
                      Input Capture management functions
 ===============================================================================  
   
       ===================================================================      
              TIM Driver: how to use it in Input Capture Mode
       =================================================================== 
       To use the Timer in Input Capture mode, the following steps are mandatory:
       
       1. Enable TIM clock using RCC_APBxPeriphClockCmd(RCC_APBxPeriph_TIMx, ENABLE) function
       
       2. Configure the TIM pins by configuring the corresponding GPIO pins
       
       2. Configure the Time base unit as described in the first part of this driver,
          if needed, else the Timer will run with the default configuration:
          - Autoreload value = 0xFFFF
          - Prescaler value = 0x0000
          - Counter mode = Up counting
          - Clock Division = TIM_CKD_DIV1
          
       3. Fill the TIM_ICInitStruct with the desired parameters including:
          - TIM Channel: TIM_Channel
          - TIM Input Capture polarity: TIM_ICPolarity
          - TIM Input Capture selection: TIM_ICSelection
          - TIM Input Capture Prescaler: TIM_ICPrescaler
          - TIM Input CApture filter value: TIM_ICFilter
       
       4. Call TIM_ICInit(TIMx, &TIM_ICInitStruct) to configure the desired channel with the 
          corresponding configuration and to measure only frequency or duty cycle of the input signal,
          or,
          Call TIM_PWMIConfig(TIMx, &TIM_ICInitStruct) to configure the desired channels with the 
          corresponding configuration and to measure the frequency and the duty cycle of the input signal
          
       5. Enable the NVIC or the DMA to read the measured frequency. 
          
       6. Enable the corresponding interrupt (or DMA request) to read the Captured value,
          using the function TIM_ITConfig(TIMx, TIM_IT_CCx) (or TIM_DMA_Cmd(TIMx, TIM_DMA_CCx)) 
       
       7. Call the TIM_Cmd(ENABLE) function to enable the TIM counter.
       
       8. Use TIM_GetCapturex(TIMx); to read the captured value.
       
       Note1: All other functions can be used separately to modify, if needed,
              a specific feature of the Timer. 
Function Documentation
TIM_GetCapture1()
uint32_t TIM_GetCapture1 (TIM_TypeDef * TIMx)
Gets the TIMx Input Capture 1 value.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
Return values
Capture Compare 1 Register value.
Definition at line 2022 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  /* Get the Capture 1 Register value */
  return TIMx->CCR1;
}
TIM_GetCapture2()
uint32_t TIM_GetCapture2 (TIM_TypeDef * TIMx)
Gets the TIMx Input Capture 2 value.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
Return values
Capture Compare 2 Register value.
Definition at line 2037 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  /* Get the Capture 2 Register value */
  return TIMx->CCR2;
}
TIM_GetCapture3()
uint32_t TIM_GetCapture3 (TIM_TypeDef * TIMx)
Gets the TIMx Input Capture 3 value.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
Return values
Capture Compare 3 Register value.
Definition at line 2051 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  /* Get the Capture 3 Register value */
  return TIMx->CCR3;
}
TIM_GetCapture4()
uint32_t TIM_GetCapture4 (TIM_TypeDef * TIMx)
Gets the TIMx Input Capture 4 value.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
Return values
Capture Compare 4 Register value.
Definition at line 2065 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  /* Get the Capture 4 Register value */
  return TIMx->CCR4;
}
TIM_ICInit()
void TIM_ICInit (TIM_TypeDef * TIMx, TIM_ICInitTypeDef * TIM_ICInitStruct)
Initializes the TIM peripheral according to the specified parameters in the TIM_ICInitStruct.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_ICInitStruct pointer to a TIM_ICInitTypeDef structure that contains the configuration information for the specified TIM peripheral.
Return values
None
Definition at line 1890 of file stm32f4xx_tim.c.
References TI1_Config(), TI2_Config(), TI3_Config(), TI4_Config(), TIM_ICInitTypeDef::TIM_Channel, TIM_ICInitTypeDef::TIM_ICFilter, TIM_ICInitTypeDef::TIM_ICPolarity, TIM_ICInitTypeDef::TIM_ICPrescaler, TIM_ICInitTypeDef::TIM_ICSelection, TIM_SetIC1Prescaler(), TIM_SetIC2Prescaler(), TIM_SetIC3Prescaler(), and TIM_SetIC4Prescaler().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_IC_POLARITY(TIM_ICInitStruct->TIM_ICPolarity));
  assert_param(IS_TIM_IC_SELECTION(TIM_ICInitStruct->TIM_ICSelection));
  assert_param(IS_TIM_IC_PRESCALER(TIM_ICInitStruct->TIM_ICPrescaler));
  assert_param(IS_TIM_IC_FILTER(TIM_ICInitStruct->TIM_ICFilter));
  
  if (TIM_ICInitStruct->TIM_Channel == TIM_Channel_1)
  {
    /* TI1 Configuration */
    TI1_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity,
               TIM_ICInitStruct->TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC1Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
  else if (TIM_ICInitStruct->TIM_Channel == TIM_Channel_2)
  {
    /* TI2 Configuration */
    assert_param(IS_TIM_LIST2_PERIPH(TIMx));
    TI2_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity,
               TIM_ICInitStruct->TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC2Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
  else if (TIM_ICInitStruct->TIM_Channel == TIM_Channel_3)
  {
    /* TI3 Configuration */
    assert_param(IS_TIM_LIST3_PERIPH(TIMx));
    TI3_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity,
               TIM_ICInitStruct->TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC3Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
  else
  {
    /* TI4 Configuration */
    assert_param(IS_TIM_LIST3_PERIPH(TIMx));
    TI4_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity,
               TIM_ICInitStruct->TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC4Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
}
TIM_ICStructInit()
void TIM_ICStructInit (TIM_ICInitTypeDef * TIM_ICInitStruct)
Fills each TIM_ICInitStruct member with its default value.
Parameters
TIM_ICInitStruct pointer to a TIM_ICInitTypeDef structure which will be initialized.
Return values
None
Definition at line 1946 of file stm32f4xx_tim.c.
References TIM_ICInitTypeDef::TIM_Channel, TIM_ICInitTypeDef::TIM_ICFilter, TIM_ICInitTypeDef::TIM_ICPolarity, TIM_ICInitTypeDef::TIM_ICPrescaler, and TIM_ICInitTypeDef::TIM_ICSelection.
{
  /* Set the default configuration */
  TIM_ICInitStruct->TIM_Channel = TIM_Channel_1;
  TIM_ICInitStruct->TIM_ICPolarity = TIM_ICPolarity_Rising;
  TIM_ICInitStruct->TIM_ICSelection = TIM_ICSelection_DirectTI;
  TIM_ICInitStruct->TIM_ICPrescaler = TIM_ICPSC_DIV1;
  TIM_ICInitStruct->TIM_ICFilter = 0x00;
}
TIM_PWMIConfig()
void TIM_PWMIConfig (TIM_TypeDef * TIMx, TIM_ICInitTypeDef * TIM_ICInitStruct)
Configures the TIM peripheral according to the specified parameters in the TIM_ICInitStruct to measure an external PWM signal.
Parameters
TIMx where x can be 1, 2, 3, 4, 5,8, 9 or 12 to select the TIM peripheral.
TIM_ICInitStruct pointer to a TIM_ICInitTypeDef structure that contains the configuration information for the specified TIM peripheral.
Return values
None
Definition at line 1965 of file stm32f4xx_tim.c.
References TI1_Config(), TI2_Config(), TIM_ICInitTypeDef::TIM_Channel, TIM_ICInitTypeDef::TIM_ICFilter, TIM_ICInitTypeDef::TIM_ICPolarity, TIM_ICInitTypeDef::TIM_ICPrescaler, TIM_ICInitTypeDef::TIM_ICSelection, TIM_SetIC1Prescaler(), and TIM_SetIC2Prescaler().
{
  uint16_t icoppositepolarity = TIM_ICPolarity_Rising;
  uint16_t icoppositeselection = TIM_ICSelection_DirectTI;
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  /* Select the Opposite Input Polarity */
  if (TIM_ICInitStruct->TIM_ICPolarity == TIM_ICPolarity_Rising)
  {
    icoppositepolarity = TIM_ICPolarity_Falling;
  }
  else
  {
    icoppositepolarity = TIM_ICPolarity_Rising;
  }
  /* Select the Opposite Input */
  if (TIM_ICInitStruct->TIM_ICSelection == TIM_ICSelection_DirectTI)
  {
    icoppositeselection = TIM_ICSelection_IndirectTI;
  }
  else
  {
    icoppositeselection = TIM_ICSelection_DirectTI;
  }
  if (TIM_ICInitStruct->TIM_Channel == TIM_Channel_1)
  {
    /* TI1 Configuration */
    TI1_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity, TIM_ICInitStruct->
      TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC1Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
    /* TI2 Configuration */
    TI2_Config(TIMx, icoppositepolarity, icoppositeselection, TIM_ICInitStruct->
      TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC2Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
  else
  {
    /* TI2 Configuration */
    TI2_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity, TIM_ICInitStruct->
      TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC2Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
    /* TI1 Configuration */
    TI1_Config(TIMx, icoppositepolarity, icoppositeselection, TIM_ICInitStruct->
      TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC1Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
}
TIM_SetIC1Prescaler()
void TIM_SetIC1Prescaler (TIM_TypeDef * TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 1 prescaler.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_ICPSC specifies the Input Capture1 prescaler new value. This parameter can be one of the following values:
TIM_ICPSC_DIV1: no prescaler
TIM_ICPSC_DIV2: capture is done once every 2 events
TIM_ICPSC_DIV4: capture is done once every 4 events
TIM_ICPSC_DIV8: capture is done once every 8 events
Return values
None
Definition at line 2085 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit(), and TIM_PWMIConfig().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_IC_PRESCALER(TIM_ICPSC));
  /* Reset the IC1PSC Bits */
  TIMx->CCMR1 &= (uint16_t)~TIM_CCMR1_IC1PSC;
  /* Set the IC1PSC value */
  TIMx->CCMR1 |= TIM_ICPSC;
}
TIM_SetIC2Prescaler()
void TIM_SetIC2Prescaler (TIM_TypeDef * TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 2 prescaler.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_ICPSC specifies the Input Capture2 prescaler new value. This parameter can be one of the following values:
TIM_ICPSC_DIV1: no prescaler
TIM_ICPSC_DIV2: capture is done once every 2 events
TIM_ICPSC_DIV4: capture is done once every 4 events
TIM_ICPSC_DIV8: capture is done once every 8 events
Return values
None
Definition at line 2110 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit(), and TIM_PWMIConfig().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_IC_PRESCALER(TIM_ICPSC));
  /* Reset the IC2PSC Bits */
  TIMx->CCMR1 &= (uint16_t)~TIM_CCMR1_IC2PSC;
  /* Set the IC2PSC value */
  TIMx->CCMR1 |= (uint16_t)(TIM_ICPSC << 8);
}
TIM_SetIC3Prescaler()
void TIM_SetIC3Prescaler (TIM_TypeDef * TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 3 prescaler.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ICPSC specifies the Input Capture3 prescaler new value. This parameter can be one of the following values:
TIM_ICPSC_DIV1: no prescaler
TIM_ICPSC_DIV2: capture is done once every 2 events
TIM_ICPSC_DIV4: capture is done once every 4 events
TIM_ICPSC_DIV8: capture is done once every 8 events
Return values
None
Definition at line 2134 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_IC_PRESCALER(TIM_ICPSC));
  /* Reset the IC3PSC Bits */
  TIMx->CCMR2 &= (uint16_t)~TIM_CCMR2_IC3PSC;
  /* Set the IC3PSC value */
  TIMx->CCMR2 |= TIM_ICPSC;
}
TIM_SetIC4Prescaler()
void TIM_SetIC4Prescaler (TIM_TypeDef * TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 4 prescaler.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ICPSC specifies the Input Capture4 prescaler new value. This parameter can be one of the following values:
TIM_ICPSC_DIV1: no prescaler
TIM_ICPSC_DIV2: capture is done once every 2 events
TIM_ICPSC_DIV4: capture is done once every 4 events
TIM_ICPSC_DIV8: capture is done once every 8 events
Return values
None
Definition at line 2158 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_IC_PRESCALER(TIM_ICPSC));
  /* Reset the IC4PSC Bits */
  TIMx->CCMR2 &= (uint16_t)~TIM_CCMR2_IC4PSC;
  /* Set the IC4PSC value */
  TIMx->CCMR2 |= (uint16_t)(TIM_ICPSC << 8);
}