TIM
TIM driver modules.
Modules
 TIM_Exported_constants
 TIM_Private_Functions
Classes
struct TIM_TimeBaseInitTypeDef
TIM Time Base Init structure definition.
struct TIM_OCInitTypeDef
TIM Output Compare Init structure definition.
struct TIM_ICInitTypeDef
TIM Input Capture Init structure definition.
struct TIM_BDTRInitTypeDef
BDTR structure definition.
Macros
#define SMCR_ETR_MASK ((uint16_t)0x00FF)
#define CCMR_OFFSET ((uint16_t)0x0018)
#define CCER_CCE_SET ((uint16_t)0x0001)
#define CCER_CCNE_SET ((uint16_t)0x0004)
#define CCMR_OC13M_MASK ((uint16_t)0xFF8F)
#define CCMR_OC24M_MASK ((uint16_t)0x8FFF)
Functions
void TIM_DeInit (TIM_TypeDef *TIMx)
Deinitializes the TIMx peripheral registers to their default reset values.
void TIM_TimeBaseInit (TIM_TypeDef *TIMx, TIM_TimeBaseInitTypeDef *TIM_TimeBaseInitStruct)
Initializes the TIMx Time Base Unit peripheral according to the specified parameters in the TIM_TimeBaseInitStruct.
void TIM_TimeBaseStructInit (TIM_TimeBaseInitTypeDef *TIM_TimeBaseInitStruct)
Fills each TIM_TimeBaseInitStruct member with its default value.
void TIM_PrescalerConfig (TIM_TypeDef *TIMx, uint16_t Prescaler, uint16_t TIM_PSCReloadMode)
Configures the TIMx Prescaler.
void TIM_CounterModeConfig (TIM_TypeDef *TIMx, uint16_t TIM_CounterMode)
Specifies the TIMx Counter Mode to be used.
void TIM_SetCounter (TIM_TypeDef *TIMx, uint32_t Counter)
Sets the TIMx Counter Register value.
void TIM_SetAutoreload (TIM_TypeDef *TIMx, uint32_t Autoreload)
Sets the TIMx Autoreload Register value.
uint32_t TIM_GetCounter (TIM_TypeDef *TIMx)
Gets the TIMx Counter value.
uint16_t TIM_GetPrescaler (TIM_TypeDef *TIMx)
Gets the TIMx Prescaler value.
void TIM_UpdateDisableConfig (TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or Disables the TIMx Update event.
void TIM_UpdateRequestConfig (TIM_TypeDef *TIMx, uint16_t TIM_UpdateSource)
Configures the TIMx Update Request Interrupt source.
void TIM_ARRPreloadConfig (TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or disables TIMx peripheral Preload register on ARR.
void TIM_SelectOnePulseMode (TIM_TypeDef *TIMx, uint16_t TIM_OPMode)
Selects the TIMx's One Pulse Mode.
void TIM_SetClockDivision (TIM_TypeDef *TIMx, uint16_t TIM_CKD)
Sets the TIMx Clock Division value.
void TIM_Cmd (TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or disables the specified TIM peripheral.
void TIM_OC1Init (TIM_TypeDef *TIMx, TIM_OCInitTypeDef *TIM_OCInitStruct)
Initializes the TIMx Channel1 according to the specified parameters in the TIM_OCInitStruct.
void TIM_OC2Init (TIM_TypeDef *TIMx, TIM_OCInitTypeDef *TIM_OCInitStruct)
Initializes the TIMx Channel2 according to the specified parameters in the TIM_OCInitStruct.
void TIM_OC3Init (TIM_TypeDef *TIMx, TIM_OCInitTypeDef *TIM_OCInitStruct)
Initializes the TIMx Channel3 according to the specified parameters in the TIM_OCInitStruct.
void TIM_OC4Init (TIM_TypeDef *TIMx, TIM_OCInitTypeDef *TIM_OCInitStruct)
Initializes the TIMx Channel4 according to the specified parameters in the TIM_OCInitStruct.
void TIM_OCStructInit (TIM_OCInitTypeDef *TIM_OCInitStruct)
Fills each TIM_OCInitStruct member with its default value.
void TIM_SelectOCxM (TIM_TypeDef *TIMx, uint16_t TIM_Channel, uint16_t TIM_OCMode)
Selects the TIM Output Compare Mode.
void TIM_SetCompare1 (TIM_TypeDef *TIMx, uint32_t Compare1)
Sets the TIMx Capture Compare1 Register value.
void TIM_SetCompare2 (TIM_TypeDef *TIMx, uint32_t Compare2)
Sets the TIMx Capture Compare2 Register value.
void TIM_SetCompare3 (TIM_TypeDef *TIMx, uint32_t Compare3)
Sets the TIMx Capture Compare3 Register value.
void TIM_SetCompare4 (TIM_TypeDef *TIMx, uint32_t Compare4)
Sets the TIMx Capture Compare4 Register value.
void TIM_ForcedOC1Config (TIM_TypeDef *TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 1 waveform to active or inactive level.
void TIM_ForcedOC2Config (TIM_TypeDef *TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 2 waveform to active or inactive level.
void TIM_ForcedOC3Config (TIM_TypeDef *TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 3 waveform to active or inactive level.
void TIM_ForcedOC4Config (TIM_TypeDef *TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 4 waveform to active or inactive level.
void TIM_OC1PreloadConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR1.
void TIM_OC2PreloadConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR2.
void TIM_OC3PreloadConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR3.
void TIM_OC4PreloadConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR4.
void TIM_OC1FastConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 1 Fast feature.
void TIM_OC2FastConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 2 Fast feature.
void TIM_OC3FastConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 3 Fast feature.
void TIM_OC4FastConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 4 Fast feature.
void TIM_ClearOC1Ref (TIM_TypeDef *TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF1 signal on an external event.
void TIM_ClearOC2Ref (TIM_TypeDef *TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF2 signal on an external event.
void TIM_ClearOC3Ref (TIM_TypeDef *TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF3 signal on an external event.
void TIM_ClearOC4Ref (TIM_TypeDef *TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF4 signal on an external event.
void TIM_OC1PolarityConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 1 polarity.
void TIM_OC1NPolarityConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCNPolarity)
Configures the TIMx Channel 1N polarity.
void TIM_OC2PolarityConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 2 polarity.
void TIM_OC2NPolarityConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCNPolarity)
Configures the TIMx Channel 2N polarity.
void TIM_OC3PolarityConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 3 polarity.
void TIM_OC3NPolarityConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCNPolarity)
Configures the TIMx Channel 3N polarity.
void TIM_OC4PolarityConfig (TIM_TypeDef *TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 4 polarity.
void TIM_CCxCmd (TIM_TypeDef *TIMx, uint16_t TIM_Channel, uint16_t TIM_CCx)
Enables or disables the TIM Capture Compare Channel x.
void TIM_CCxNCmd (TIM_TypeDef *TIMx, uint16_t TIM_Channel, uint16_t TIM_CCxN)
Enables or disables the TIM Capture Compare Channel xN.
void TIM_ICInit (TIM_TypeDef *TIMx, TIM_ICInitTypeDef *TIM_ICInitStruct)
Initializes the TIM peripheral according to the specified parameters in the TIM_ICInitStruct.
void TIM_ICStructInit (TIM_ICInitTypeDef *TIM_ICInitStruct)
Fills each TIM_ICInitStruct member with its default value.
void TIM_PWMIConfig (TIM_TypeDef *TIMx, TIM_ICInitTypeDef *TIM_ICInitStruct)
Configures the TIM peripheral according to the specified parameters in the TIM_ICInitStruct to measure an external PWM signal.
uint32_t TIM_GetCapture1 (TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 1 value.
uint32_t TIM_GetCapture2 (TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 2 value.
uint32_t TIM_GetCapture3 (TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 3 value.
uint32_t TIM_GetCapture4 (TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 4 value.
void TIM_SetIC1Prescaler (TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 1 prescaler.
void TIM_SetIC2Prescaler (TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 2 prescaler.
void TIM_SetIC3Prescaler (TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 3 prescaler.
void TIM_SetIC4Prescaler (TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 4 prescaler.
void TIM_BDTRConfig (TIM_TypeDef *TIMx, TIM_BDTRInitTypeDef *TIM_BDTRInitStruct)
Configures the Break feature, dead time, Lock level, OSSI/OSSR State and the AOE(automatic output enable).
void TIM_BDTRStructInit (TIM_BDTRInitTypeDef *TIM_BDTRInitStruct)
Fills each TIM_BDTRInitStruct member with its default value.
void TIM_CtrlPWMOutputs (TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or disables the TIM peripheral Main Outputs.
void TIM_SelectCOM (TIM_TypeDef *TIMx, FunctionalState NewState)
Selects the TIM peripheral Commutation event.
void TIM_CCPreloadControl (TIM_TypeDef *TIMx, FunctionalState NewState)
Sets or Resets the TIM peripheral Capture Compare Preload Control bit.
void TIM_ITConfig (TIM_TypeDef *TIMx, uint16_t TIM_IT, FunctionalState NewState)
Enables or disables the specified TIM interrupts.
void TIM_GenerateEvent (TIM_TypeDef *TIMx, uint16_t TIM_EventSource)
Configures the TIMx event to be generate by software.
 FlagStatus TIM_GetFlagStatus (TIM_TypeDef *TIMx, uint16_t TIM_FLAG)
Checks whether the specified TIM flag is set or not.
void TIM_ClearFlag (TIM_TypeDef *TIMx, uint16_t TIM_FLAG)
Clears the TIMx's pending flags.
 ITStatus TIM_GetITStatus (TIM_TypeDef *TIMx, uint16_t TIM_IT)
Checks whether the TIM interrupt has occurred or not.
void TIM_ClearITPendingBit (TIM_TypeDef *TIMx, uint16_t TIM_IT)
Clears the TIMx's interrupt pending bits.
void TIM_DMAConfig (TIM_TypeDef *TIMx, uint16_t TIM_DMABase, uint16_t TIM_DMABurstLength)
Configures the TIMx's DMA interface.
void TIM_DMACmd (TIM_TypeDef *TIMx, uint16_t TIM_DMASource, FunctionalState NewState)
Enables or disables the TIMx's DMA Requests.
void TIM_SelectCCDMA (TIM_TypeDef *TIMx, FunctionalState NewState)
Selects the TIMx peripheral Capture Compare DMA source.
void TIM_InternalClockConfig (TIM_TypeDef *TIMx)
Configures the TIMx internal Clock.
void TIM_ITRxExternalClockConfig (TIM_TypeDef *TIMx, uint16_t TIM_InputTriggerSource)
Configures the TIMx Internal Trigger as External Clock.
void TIM_TIxExternalClockConfig (TIM_TypeDef *TIMx, uint16_t TIM_TIxExternalCLKSource, uint16_t TIM_ICPolarity, uint16_t ICFilter)
Configures the TIMx Trigger as External Clock.
void TIM_ETRClockMode1Config (TIM_TypeDef *TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the External clock Mode1.
void TIM_ETRClockMode2Config (TIM_TypeDef *TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the External clock Mode2.
void TIM_SelectInputTrigger (TIM_TypeDef *TIMx, uint16_t TIM_InputTriggerSource)
Selects the Input Trigger source.
void TIM_SelectOutputTrigger (TIM_TypeDef *TIMx, uint16_t TIM_TRGOSource)
Selects the TIMx Trigger Output Mode.
void TIM_SelectSlaveMode (TIM_TypeDef *TIMx, uint16_t TIM_SlaveMode)
Selects the TIMx Slave Mode.
void TIM_SelectMasterSlaveMode (TIM_TypeDef *TIMx, uint16_t TIM_MasterSlaveMode)
Sets or Resets the TIMx Master/Slave Mode.
void TIM_ETRConfig (TIM_TypeDef *TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the TIMx External Trigger (ETR).
void TIM_EncoderInterfaceConfig (TIM_TypeDef *TIMx, uint16_t TIM_EncoderMode, uint16_t TIM_IC1Polarity, uint16_t TIM_IC2Polarity)
Configures the TIMx Encoder Interface.
void TIM_SelectHallSensor (TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or disables the TIMx's Hall sensor interface.
void TIM_RemapConfig (TIM_TypeDef *TIMx, uint16_t TIM_Remap)
Configures the TIM2, TIM5 and TIM11 Remapping input capabilities.
Detailed Description
TIM driver modules.
Macro Definition Documentation
CCER_CCE_SET
#define CCER_CCE_SET ((uint16_t)0x0001)
Definition at line 132 of file stm32f4xx_tim.c.
CCER_CCNE_SET
#define CCER_CCNE_SET ((uint16_t)0x0004)
Definition at line 133 of file stm32f4xx_tim.c.
CCMR_OC13M_MASK
#define CCMR_OC13M_MASK ((uint16_t)0xFF8F)
Definition at line 134 of file stm32f4xx_tim.c.
CCMR_OC24M_MASK
#define CCMR_OC24M_MASK ((uint16_t)0x8FFF)
Definition at line 135 of file stm32f4xx_tim.c.
CCMR_OFFSET
#define CCMR_OFFSET ((uint16_t)0x0018)
Definition at line 131 of file stm32f4xx_tim.c.
SMCR_ETR_MASK
#define SMCR_ETR_MASK ((uint16_t)0x00FF)
Definition at line 130 of file stm32f4xx_tim.c.
Function Documentation
TIM_ARRPreloadConfig()
void TIM_ARRPreloadConfig (TIM_TypeDef * TIMx, FunctionalState NewState)
Enables or disables TIMx peripheral Preload register on ARR.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
NewState new state of the TIMx peripheral Preload register This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 516 of file stm32f4xx_tim.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Set the ARR Preload Bit */
    TIMx->CR1 |= TIM_CR1_ARPE;
  }
  else
  {
    /* Reset the ARR Preload Bit */
    TIMx->CR1 &= (uint16_t)~TIM_CR1_ARPE;
  }
}
TIM_BDTRConfig()
void TIM_BDTRConfig (TIM_TypeDef * TIMx, TIM_BDTRInitTypeDef * TIM_BDTRInitStruct)
Configures the Break feature, dead time, Lock level, OSSI/OSSR State and the AOE(automatic output enable).
Parameters
TIMx where x can be 1 or 8 to select the TIM
TIM_BDTRInitStruct pointer to a TIM_BDTRInitTypeDef structure that contains the BDTR Register configuration information for the TIM peripheral.
Return values
None
Definition at line 2211 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST4_PERIPH(TIMx));
  assert_param(IS_TIM_OSSR_STATE(TIM_BDTRInitStruct->TIM_OSSRState));
  assert_param(IS_TIM_OSSI_STATE(TIM_BDTRInitStruct->TIM_OSSIState));
  assert_param(IS_TIM_LOCK_LEVEL(TIM_BDTRInitStruct->TIM_LOCKLevel));
  assert_param(IS_TIM_BREAK_STATE(TIM_BDTRInitStruct->TIM_Break));
  assert_param(IS_TIM_BREAK_POLARITY(TIM_BDTRInitStruct->TIM_BreakPolarity));
  assert_param(IS_TIM_AUTOMATIC_OUTPUT_STATE(TIM_BDTRInitStruct->
      TIM_AutomaticOutput));
  /* Set the Lock level, the Break enable Bit and the Polarity, the OSSR State,
     the OSSI State, the dead time value and the Automatic Output Enable Bit */
  TIMx->BDTR = (uint32_t)TIM_BDTRInitStruct->TIM_OSSRState | TIM_BDTRInitStruct->
      TIM_OSSIState |
             TIM_BDTRInitStruct->TIM_LOCKLevel | TIM_BDTRInitStruct->
      TIM_DeadTime |
             TIM_BDTRInitStruct->TIM_Break | TIM_BDTRInitStruct->
      TIM_BreakPolarity |
             TIM_BDTRInitStruct->TIM_AutomaticOutput;
}
TIM_BDTRStructInit()
void TIM_BDTRStructInit (TIM_BDTRInitTypeDef * TIM_BDTRInitStruct)
Fills each TIM_BDTRInitStruct member with its default value.
Parameters
TIM_BDTRInitStruct pointer to a TIM_BDTRInitTypeDef structure which will be initialized.
Return values
None
Definition at line 2236 of file stm32f4xx_tim.c.
References TIM_BDTRInitTypeDef::TIM_AutomaticOutput, TIM_BDTRInitTypeDef::TIM_Break, TIM_BDTRInitTypeDef::TIM_BreakPolarity, TIM_BDTRInitTypeDef::TIM_DeadTime, TIM_BDTRInitTypeDef::TIM_LOCKLevel, TIM_BDTRInitTypeDef::TIM_OSSIState, and TIM_BDTRInitTypeDef::TIM_OSSRState.
{
  /* Set the default configuration */
  TIM_BDTRInitStruct->TIM_OSSRState = TIM_OSSRState_Disable;
  TIM_BDTRInitStruct->TIM_OSSIState = TIM_OSSIState_Disable;
  TIM_BDTRInitStruct->TIM_LOCKLevel = TIM_LOCKLevel_OFF;
  TIM_BDTRInitStruct->TIM_DeadTime = 0x00;
  TIM_BDTRInitStruct->TIM_Break = TIM_Break_Disable;
  TIM_BDTRInitStruct->TIM_BreakPolarity = TIM_BreakPolarity_Low;
  TIM_BDTRInitStruct->TIM_AutomaticOutput = TIM_AutomaticOutput_Disable;
}
TIM_CCPreloadControl()
void TIM_CCPreloadControl (TIM_TypeDef * TIMx, FunctionalState NewState)
Sets or Resets the TIM peripheral Capture Compare Preload Control bit.
Parameters
TIMx where x can be 1 or 8 to select the TIMx peripheral
NewState new state of the Capture Compare Preload Control bit This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 2305 of file stm32f4xx_tim.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST4_PERIPH(TIMx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Set the CCPC Bit */
    TIMx->CR2 |= TIM_CR2_CCPC;
  }
  else
  {
    /* Reset the CCPC Bit */
    TIMx->CR2 &= (uint16_t)~TIM_CR2_CCPC;
  }
}
TIM_CCxCmd()
void TIM_CCxCmd (TIM_TypeDef * TIMx, uint16_t TIM_Channel, uint16_t TIM_CCx)
Enables or disables the TIM Capture Compare Channel x.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_Channel specifies the TIM Channel This parameter can be one of the following values:
TIM_Channel_1: TIM Channel 1
TIM_Channel_2: TIM Channel 2
TIM_Channel_3: TIM Channel 3
TIM_Channel_4: TIM Channel 4
TIM_CCx specifies the TIM Channel CCxE bit new state. This parameter can be: TIM_CCx_Enable or TIM_CCx_Disable.
Return values
None
Definition at line 1778 of file stm32f4xx_tim.c.
{
  uint16_t tmp = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_CHANNEL(TIM_Channel));
  assert_param(IS_TIM_CCX(TIM_CCx));
  tmp = CCER_CCE_SET << TIM_Channel;
  /* Reset the CCxE Bit */
  TIMx->CCER &= (uint16_t)~ tmp;
  /* Set or reset the CCxE Bit */
  TIMx->CCER |= (uint16_t)(TIM_CCx << TIM_Channel);
}
TIM_CCxNCmd()
void TIM_CCxNCmd (TIM_TypeDef * TIMx, uint16_t TIM_Channel, uint16_t TIM_CCxN)
Enables or disables the TIM Capture Compare Channel xN.
Parameters
TIMx where x can be 1 or 8 to select the TIM peripheral.
TIM_Channel specifies the TIM Channel This parameter can be one of the following values:
TIM_Channel_1: TIM Channel 1
TIM_Channel_2: TIM Channel 2
TIM_Channel_3: TIM Channel 3
TIM_CCxN specifies the TIM Channel CCxNE bit new state. This parameter can be: TIM_CCxN_Enable or TIM_CCxN_Disable.
Return values
None
Definition at line 1808 of file stm32f4xx_tim.c.
{
  uint16_t tmp = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST4_PERIPH(TIMx));
  assert_param(IS_TIM_COMPLEMENTARY_CHANNEL(TIM_Channel));
  assert_param(IS_TIM_CCXN(TIM_CCxN));
  tmp = CCER_CCNE_SET << TIM_Channel;
  /* Reset the CCxNE Bit */
  TIMx->CCER &= (uint16_t) ~tmp;
  /* Set or reset the CCxNE Bit */
  TIMx->CCER |= (uint16_t)(TIM_CCxN << TIM_Channel);
}
TIM_ClearFlag()
void TIM_ClearFlag (TIM_TypeDef * TIMx, uint16_t TIM_FLAG)
Clears the TIMx's pending flags.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
TIM_FLAG specifies the flag bit to clear. This parameter can be any combination of the following values:
TIM_FLAG_Update: TIM update Flag
TIM_FLAG_CC1: TIM Capture Compare 1 Flag
TIM_FLAG_CC2: TIM Capture Compare 2 Flag
TIM_FLAG_CC3: TIM Capture Compare 3 Flag
TIM_FLAG_CC4: TIM Capture Compare 4 Flag
TIM_FLAG_COM: TIM Commutation Flag
TIM_FLAG_Trigger: TIM Trigger Flag
TIM_FLAG_Break: TIM Break Flag
TIM_FLAG_CC1OF: TIM Capture Compare 1 over capture Flag
TIM_FLAG_CC2OF: TIM Capture Compare 2 over capture Flag
TIM_FLAG_CC3OF: TIM Capture Compare 3 over capture Flag
TIM_FLAG_CC4OF: TIM Capture Compare 4 over capture Flag
Note
TIM6 and TIM7 can have only one update flag.
TIM_FLAG_COM and TIM_FLAG_Break are used only with TIM1 and TIM8.
Return values
None
Definition at line 2475 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
   
  /* Clear the flags */
  TIMx->SR = (uint16_t)~TIM_FLAG;
}
TIM_ClearITPendingBit()
void TIM_ClearITPendingBit (TIM_TypeDef * TIMx, uint16_t TIM_IT)
Clears the TIMx's interrupt pending bits.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
TIM_IT specifies the pending bit to clear. This parameter can be any combination of the following values:
TIM_IT_Update: TIM1 update Interrupt source
TIM_IT_CC1: TIM Capture Compare 1 Interrupt source
TIM_IT_CC2: TIM Capture Compare 2 Interrupt source
TIM_IT_CC3: TIM Capture Compare 3 Interrupt source
TIM_IT_CC4: TIM Capture Compare 4 Interrupt source
TIM_IT_COM: TIM Commutation Interrupt source
TIM_IT_Trigger: TIM Trigger Interrupt source
TIM_IT_Break: TIM Break Interrupt source
Note
TIM6 and TIM7 can generate only an update interrupt.
TIM_IT_COM and TIM_IT_Break are used only with TIM1 and TIM8.
Return values
None
Definition at line 2544 of file stm32f4xx_tim.c.
Referenced by TIM4_IRQHandler().
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  /* Clear the IT pending Bit */
  TIMx->SR = (uint16_t)~TIM_IT;
}
TIM_ClearOC1Ref()
void TIM_ClearOC1Ref (TIM_TypeDef * TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF1 signal on an external event.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_OCClear new state of the Output Compare Clear Enable Bit. This parameter can be one of the following values:
TIM_OCClear_Enable: TIM Output clear enable
TIM_OCClear_Disable: TIM Output clear disable
Return values
None
Definition at line 1468 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr1 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_OCCLEAR_STATE(TIM_OCClear));
  tmpccmr1 = TIMx->CCMR1;
  /* Reset the OC1CE Bit */
  tmpccmr1 &= (uint16_t)~TIM_CCMR1_OC1CE;
  /* Enable or Disable the Output Compare Clear Bit */
  tmpccmr1 |= TIM_OCClear;
  /* Write to TIMx CCMR1 register */
  TIMx->CCMR1 = tmpccmr1;
}
TIM_ClearOC2Ref()
void TIM_ClearOC2Ref (TIM_TypeDef * TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF2 signal on an external event.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_OCClear new state of the Output Compare Clear Enable Bit. This parameter can be one of the following values:
TIM_OCClear_Enable: TIM Output clear enable
TIM_OCClear_Disable: TIM Output clear disable
Return values
None
Definition at line 1498 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr1 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_OCCLEAR_STATE(TIM_OCClear));
  tmpccmr1 = TIMx->CCMR1;
  /* Reset the OC2CE Bit */
  tmpccmr1 &= (uint16_t)~TIM_CCMR1_OC2CE;
  /* Enable or Disable the Output Compare Clear Bit */
  tmpccmr1 |= (uint16_t)(TIM_OCClear << 8);
  /* Write to TIMx CCMR1 register */
  TIMx->CCMR1 = tmpccmr1;
}
TIM_ClearOC3Ref()
void TIM_ClearOC3Ref (TIM_TypeDef * TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF3 signal on an external event.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_OCClear new state of the Output Compare Clear Enable Bit. This parameter can be one of the following values:
TIM_OCClear_Enable: TIM Output clear enable
TIM_OCClear_Disable: TIM Output clear disable
Return values
None
Definition at line 1527 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr2 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_OCCLEAR_STATE(TIM_OCClear));
  tmpccmr2 = TIMx->CCMR2;
  /* Reset the OC3CE Bit */
  tmpccmr2 &= (uint16_t)~TIM_CCMR2_OC3CE;
  /* Enable or Disable the Output Compare Clear Bit */
  tmpccmr2 |= TIM_OCClear;
  /* Write to TIMx CCMR2 register */
  TIMx->CCMR2 = tmpccmr2;
}
TIM_ClearOC4Ref()
void TIM_ClearOC4Ref (TIM_TypeDef * TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF4 signal on an external event.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_OCClear new state of the Output Compare Clear Enable Bit. This parameter can be one of the following values:
TIM_OCClear_Enable: TIM Output clear enable
TIM_OCClear_Disable: TIM Output clear disable
Return values
None
Definition at line 1556 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr2 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_OCCLEAR_STATE(TIM_OCClear));
  tmpccmr2 = TIMx->CCMR2;
  /* Reset the OC4CE Bit */
  tmpccmr2 &= (uint16_t)~TIM_CCMR2_OC4CE;
  /* Enable or Disable the Output Compare Clear Bit */
  tmpccmr2 |= (uint16_t)(TIM_OCClear << 8);
  /* Write to TIMx CCMR2 register */
  TIMx->CCMR2 = tmpccmr2;
}
TIM_Cmd()
void TIM_Cmd (TIM_TypeDef * TIMx, FunctionalState NewState)
Enables or disables the specified TIM peripheral.
Parameters
TIMx where x can be 1 to 14 to select the TIMx peripheral.
NewState new state of the TIMx peripheral. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 586 of file stm32f4xx_tim.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the TIM Counter */
    TIMx->CR1 |= TIM_CR1_CEN;
  }
  else
  {
    /* Disable the TIM Counter */
    TIMx->CR1 &= (uint16_t)~TIM_CR1_CEN;
  }
}
TIM_CounterModeConfig()
void TIM_CounterModeConfig (TIM_TypeDef * TIMx, uint16_t TIM_CounterMode)
Specifies the TIMx Counter Mode to be used.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_CounterMode specifies the Counter Mode to be used This parameter can be one of the following values:
TIM_CounterMode_Up: TIM Up Counting Mode
TIM_CounterMode_Down: TIM Down Counting Mode
TIM_CounterMode_CenterAligned1: TIM Center Aligned Mode1
TIM_CounterMode_CenterAligned2: TIM Center Aligned Mode2
TIM_CounterMode_CenterAligned3: TIM Center Aligned Mode3
Return values
None
Definition at line 377 of file stm32f4xx_tim.c.
{
  uint16_t tmpcr1 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_COUNTER_MODE(TIM_CounterMode));
  tmpcr1 = TIMx->CR1;
  /* Reset the CMS and DIR Bits */
  tmpcr1 &= (uint16_t)~(TIM_CR1_DIR | TIM_CR1_CMS);
  /* Set the Counter Mode */
  tmpcr1 |= TIM_CounterMode;
  /* Write to TIMx CR1 register */
  TIMx->CR1 = tmpcr1;
}
TIM_CtrlPWMOutputs()
void TIM_CtrlPWMOutputs (TIM_TypeDef * TIMx, FunctionalState NewState)
Enables or disables the TIM peripheral Main Outputs.
Parameters
TIMx where x can be 1 or 8 to select the TIMx peripheral.
NewState new state of the TIM peripheral Main Outputs. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 2255 of file stm32f4xx_tim.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST4_PERIPH(TIMx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the TIM Main Output */
    TIMx->BDTR |= TIM_BDTR_MOE;
  }
  else
  {
    /* Disable the TIM Main Output */
    TIMx->BDTR &= (uint16_t)~TIM_BDTR_MOE;
  }
}
TIM_DeInit()
void TIM_DeInit (TIM_TypeDef * TIMx)
Deinitializes the TIMx peripheral registers to their default reset values.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Return values
None
Definition at line 194 of file stm32f4xx_tim.c.
References DISABLE, ENABLE, RCC_APB1PeriphResetCmd(), and RCC_APB2PeriphResetCmd().
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
 
  if (TIMx == TIM1)
  {
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_TIM1, ENABLE);
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_TIM1, DISABLE);
  }
  else if (TIMx == TIM2)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM2, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM2, DISABLE);
  }
  else if (TIMx == TIM3)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM3, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM3, DISABLE);
  }
  else if (TIMx == TIM4)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM4, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM4, DISABLE);
  }
  else if (TIMx == TIM5)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM5, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM5, DISABLE);
  }
  else if (TIMx == TIM6)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM6, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM6, DISABLE);
  }
  else if (TIMx == TIM7)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM7, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM7, DISABLE);
  }
  else if (TIMx == TIM8)
  {
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_TIM8, ENABLE);
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_TIM8, DISABLE);
  }
  else if (TIMx == TIM9)
  {
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_TIM9, ENABLE);
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_TIM9, DISABLE);
   }
  else if (TIMx == TIM10)
  {
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_TIM10, ENABLE);
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_TIM10, DISABLE);
  }
  else if (TIMx == TIM11)
  {
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_TIM11, ENABLE);
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_TIM11, DISABLE);
  }
  else if (TIMx == TIM12)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM12, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM12, DISABLE);
  }
  else if (TIMx == TIM13)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM13, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM13, DISABLE);
  }
  else
  {
    if (TIMx == TIM14)
    {
      RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM14, ENABLE);
      RCC_APB1PeriphResetCmd(RCC_APB1Periph_TIM14, DISABLE);
    }
  }
}
TIM_DMACmd()
void TIM_DMACmd (TIM_TypeDef * TIMx, uint16_t TIM_DMASource, FunctionalState NewState)
Enables or disables the TIMx's DMA Requests.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 6, 7 or 8 to select the TIM peripheral.
TIM_DMASource specifies the DMA Request sources. This parameter can be any combination of the following values:
TIM_DMA_Update: TIM update Interrupt source
TIM_DMA_CC1: TIM Capture Compare 1 DMA source
TIM_DMA_CC2: TIM Capture Compare 2 DMA source
TIM_DMA_CC3: TIM Capture Compare 3 DMA source
TIM_DMA_CC4: TIM Capture Compare 4 DMA source
TIM_DMA_COM: TIM Commutation DMA source
TIM_DMA_Trigger: TIM Trigger DMA source
NewState new state of the DMA Request sources. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 2608 of file stm32f4xx_tim.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST5_PERIPH(TIMx));
  assert_param(IS_TIM_DMA_SOURCE(TIM_DMASource));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the DMA sources */
    TIMx->DIER |= TIM_DMASource;
  }
  else
  {
    /* Disable the DMA sources */
    TIMx->DIER &= (uint16_t)~TIM_DMASource;
  }
}
TIM_DMAConfig()
void TIM_DMAConfig (TIM_TypeDef * TIMx, uint16_t TIM_DMABase, uint16_t TIM_DMABurstLength)
Configures the TIMx's DMA interface.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_DMABase DMA Base address. This parameter can be one of the following values:
TIM_DMABase_CR1
TIM_DMABase_CR2
TIM_DMABase_SMCR
TIM_DMABase_DIER
TIM1_DMABase_SR
TIM_DMABase_EGR
TIM_DMABase_CCMR1
TIM_DMABase_CCMR2
TIM_DMABase_CCER
TIM_DMABase_CNT
TIM_DMABase_PSC
TIM_DMABase_ARR
TIM_DMABase_RCR
TIM_DMABase_CCR1
TIM_DMABase_CCR2
TIM_DMABase_CCR3
TIM_DMABase_CCR4
TIM_DMABase_BDTR
TIM_DMABase_DCR
TIM_DMABurstLength DMA Burst length. This parameter can be one value between: TIM_DMABurstLength_1Transfer and TIM_DMABurstLength_18Transfers.
Return values
None
Definition at line 2581 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_DMA_BASE(TIM_DMABase));
  assert_param(IS_TIM_DMA_LENGTH(TIM_DMABurstLength));
  /* Set the DMA Base and the DMA Burst Length */
  TIMx->DCR = TIM_DMABase | TIM_DMABurstLength;
}
TIM_EncoderInterfaceConfig()
void TIM_EncoderInterfaceConfig (TIM_TypeDef * TIMx, uint16_t TIM_EncoderMode, uint16_t TIM_IC1Polarity, uint16_t TIM_IC2Polarity)
Configures the TIMx Encoder Interface.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_EncoderMode specifies the TIMx Encoder Mode. This parameter can be one of the following values:
TIM_EncoderMode_TI1: Counter counts on TI1FP1 edge depending on TI2FP2 level.
TIM_EncoderMode_TI2: Counter counts on TI2FP2 edge depending on TI1FP1 level.
TIM_EncoderMode_TI12: Counter counts on both TI1FP1 and TI2FP2 edges depending on the level of the other input.
TIM_IC1Polarity specifies the IC1 Polarity This parameter can be one of the following values:
TIM_ICPolarity_Falling: IC Falling edge.
TIM_ICPolarity_Rising: IC Rising edge.
TIM_IC2Polarity specifies the IC2 Polarity This parameter can be one of the following values:
TIM_ICPolarity_Falling: IC Falling edge.
TIM_ICPolarity_Rising: IC Rising edge.
Return values
None
Definition at line 3057 of file stm32f4xx_tim.c.
{
  uint16_t tmpsmcr = 0;
  uint16_t tmpccmr1 = 0;
  uint16_t tmpccer = 0;
    
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_ENCODER_MODE(TIM_EncoderMode));
  assert_param(IS_TIM_IC_POLARITY(TIM_IC1Polarity));
  assert_param(IS_TIM_IC_POLARITY(TIM_IC2Polarity));
  /* Get the TIMx SMCR register value */
  tmpsmcr = TIMx->SMCR;
  /* Get the TIMx CCMR1 register value */
  tmpccmr1 = TIMx->CCMR1;
  /* Get the TIMx CCER register value */
  tmpccer = TIMx->CCER;
  /* Set the encoder Mode */
  tmpsmcr &= (uint16_t)~TIM_SMCR_SMS;
  tmpsmcr |= TIM_EncoderMode;
  /* Select the Capture Compare 1 and the Capture Compare 2 as input */
  tmpccmr1 &= ((uint16_t)~TIM_CCMR1_CC1S) & ((uint16_t)~TIM_CCMR1_CC2S);
  tmpccmr1 |= TIM_CCMR1_CC1S_0 | TIM_CCMR1_CC2S_0;
  /* Set the TI1 and the TI2 Polarities */
  tmpccer &= ((uint16_t)~TIM_CCER_CC1P) & ((uint16_t)~TIM_CCER_CC2P);
  tmpccer |= (uint16_t)(TIM_IC1Polarity | (uint16_t)(TIM_IC2Polarity << (uint16_t)4));
  /* Write to TIMx SMCR */
  TIMx->SMCR = tmpsmcr;
  /* Write to TIMx CCMR1 */
  TIMx->CCMR1 = tmpccmr1;
  /* Write to TIMx CCER */
  TIMx->CCER = tmpccer;
}
TIM_ETRClockMode1Config()
void TIM_ETRClockMode1Config (TIM_TypeDef * TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the External clock Mode1.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ExtTRGPrescaler The external Trigger Prescaler. This parameter can be one of the following values:
TIM_ExtTRGPSC_OFF: ETRP Prescaler OFF.
TIM_ExtTRGPSC_DIV2: ETRP frequency divided by 2.
TIM_ExtTRGPSC_DIV4: ETRP frequency divided by 4.
TIM_ExtTRGPSC_DIV8: ETRP frequency divided by 8.
TIM_ExtTRGPolarity The external Trigger Polarity. This parameter can be one of the following values:
TIM_ExtTRGPolarity_Inverted: active low or falling edge active.
TIM_ExtTRGPolarity_NonInverted: active high or rising edge active.
ExtTRGFilter External Trigger Filter. This parameter must be a value between 0x00 and 0x0F
Return values
None
Definition at line 2764 of file stm32f4xx_tim.c.
References TIM_ETRConfig().
{
  uint16_t tmpsmcr = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_EXT_PRESCALER(TIM_ExtTRGPrescaler));
  assert_param(IS_TIM_EXT_POLARITY(TIM_ExtTRGPolarity));
  assert_param(IS_TIM_EXT_FILTER(ExtTRGFilter));
  /* Configure the ETR Clock source */
  TIM_ETRConfig(TIMx, TIM_ExtTRGPrescaler, TIM_ExtTRGPolarity, ExtTRGFilter);
  
  /* Get the TIMx SMCR register value */
  tmpsmcr = TIMx->SMCR;
  /* Reset the SMS Bits */
  tmpsmcr &= (uint16_t)~TIM_SMCR_SMS;
  /* Select the External clock mode1 */
  tmpsmcr |= TIM_SlaveMode_External1;
  /* Select the Trigger selection : ETRF */
  tmpsmcr &= (uint16_t)~TIM_SMCR_TS;
  tmpsmcr |= TIM_TS_ETRF;
  /* Write to TIMx SMCR */
  TIMx->SMCR = tmpsmcr;
}
TIM_ETRClockMode2Config()
void TIM_ETRClockMode2Config (TIM_TypeDef * TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the External clock Mode2.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ExtTRGPrescaler The external Trigger Prescaler. This parameter can be one of the following values:
TIM_ExtTRGPSC_OFF: ETRP Prescaler OFF.
TIM_ExtTRGPSC_DIV2: ETRP frequency divided by 2.
TIM_ExtTRGPSC_DIV4: ETRP frequency divided by 4.
TIM_ExtTRGPSC_DIV8: ETRP frequency divided by 8.
TIM_ExtTRGPolarity The external Trigger Polarity. This parameter can be one of the following values:
TIM_ExtTRGPolarity_Inverted: active low or falling edge active.
TIM_ExtTRGPolarity_NonInverted: active high or rising edge active.
ExtTRGFilter External Trigger Filter. This parameter must be a value between 0x00 and 0x0F
Return values
None
Definition at line 2811 of file stm32f4xx_tim.c.
References TIM_ETRConfig().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_EXT_PRESCALER(TIM_ExtTRGPrescaler));
  assert_param(IS_TIM_EXT_POLARITY(TIM_ExtTRGPolarity));
  assert_param(IS_TIM_EXT_FILTER(ExtTRGFilter));
  /* Configure the ETR Clock source */
  TIM_ETRConfig(TIMx, TIM_ExtTRGPrescaler, TIM_ExtTRGPolarity, ExtTRGFilter);
  /* Enable the External clock mode2 */
  TIMx->SMCR |= TIM_SMCR_ECE;
}
TIM_ETRConfig()
void TIM_ETRConfig (TIM_TypeDef * TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the TIMx External Trigger (ETR).
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ExtTRGPrescaler The external Trigger Prescaler. This parameter can be one of the following values:
TIM_ExtTRGPSC_OFF: ETRP Prescaler OFF.
TIM_ExtTRGPSC_DIV2: ETRP frequency divided by 2.
TIM_ExtTRGPSC_DIV4: ETRP frequency divided by 4.
TIM_ExtTRGPSC_DIV8: ETRP frequency divided by 8.
TIM_ExtTRGPolarity The external Trigger Polarity. This parameter can be one of the following values:
TIM_ExtTRGPolarity_Inverted: active low or falling edge active.
TIM_ExtTRGPolarity_NonInverted: active high or rising edge active.
ExtTRGFilter External Trigger Filter. This parameter must be a value between 0x00 and 0x0F
Return values
None
Definition at line 2999 of file stm32f4xx_tim.c.
Referenced by TIM_ETRClockMode1Config(), and TIM_ETRClockMode2Config().
{
  uint16_t tmpsmcr = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_EXT_PRESCALER(TIM_ExtTRGPrescaler));
  assert_param(IS_TIM_EXT_POLARITY(TIM_ExtTRGPolarity));
  assert_param(IS_TIM_EXT_FILTER(ExtTRGFilter));
  tmpsmcr = TIMx->SMCR;
  /* Reset the ETR Bits */
  tmpsmcr &= SMCR_ETR_MASK;
  /* Set the Prescaler, the Filter value and the Polarity */
  tmpsmcr |= (uint16_t)(TIM_ExtTRGPrescaler | (uint16_t)(TIM_ExtTRGPolarity | (uint16_t)(ExtTRGFilter << (
      uint16_t)8)));
  /* Write to TIMx SMCR */
  TIMx->SMCR = tmpsmcr;
}
TIM_ForcedOC1Config()
void TIM_ForcedOC1Config (TIM_TypeDef * TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 1 waveform to active or inactive level.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_ForcedAction specifies the forced Action to be set to the output waveform. This parameter can be one of the following values:
TIM_ForcedAction_Active: Force active level on OC1REF
TIM_ForcedAction_InActive: Force inactive level on OC1REF.
Return values
None
Definition at line 1116 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr1 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_FORCED_ACTION(TIM_ForcedAction));
  tmpccmr1 = TIMx->CCMR1;
  /* Reset the OC1M Bits */
  tmpccmr1 &= (uint16_t)~TIM_CCMR1_OC1M;
  /* Configure The Forced output Mode */
  tmpccmr1 |= TIM_ForcedAction;
  /* Write to TIMx CCMR1 register */
  TIMx->CCMR1 = tmpccmr1;
}
TIM_ForcedOC2Config()
void TIM_ForcedOC2Config (TIM_TypeDef * TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 2 waveform to active or inactive level.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_ForcedAction specifies the forced Action to be set to the output waveform. This parameter can be one of the following values:
TIM_ForcedAction_Active: Force active level on OC2REF
TIM_ForcedAction_InActive: Force inactive level on OC2REF.
Return values
None
Definition at line 1145 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr1 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_FORCED_ACTION(TIM_ForcedAction));
  tmpccmr1 = TIMx->CCMR1;
  /* Reset the OC2M Bits */
  tmpccmr1 &= (uint16_t)~TIM_CCMR1_OC2M;
  /* Configure The Forced output Mode */
  tmpccmr1 |= (uint16_t)(TIM_ForcedAction << 8);
  /* Write to TIMx CCMR1 register */
  TIMx->CCMR1 = tmpccmr1;
}
TIM_ForcedOC3Config()
void TIM_ForcedOC3Config (TIM_TypeDef * TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 3 waveform to active or inactive level.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ForcedAction specifies the forced Action to be set to the output waveform. This parameter can be one of the following values:
TIM_ForcedAction_Active: Force active level on OC3REF
TIM_ForcedAction_InActive: Force inactive level on OC3REF.
Return values
None
Definition at line 1173 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr2 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_FORCED_ACTION(TIM_ForcedAction));
  tmpccmr2 = TIMx->CCMR2;
  /* Reset the OC1M Bits */
  tmpccmr2 &= (uint16_t)~TIM_CCMR2_OC3M;
  /* Configure The Forced output Mode */
  tmpccmr2 |= TIM_ForcedAction;
  /* Write to TIMx CCMR2 register */
  TIMx->CCMR2 = tmpccmr2;
}
TIM_ForcedOC4Config()
void TIM_ForcedOC4Config (TIM_TypeDef * TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 4 waveform to active or inactive level.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ForcedAction specifies the forced Action to be set to the output waveform. This parameter can be one of the following values:
TIM_ForcedAction_Active: Force active level on OC4REF
TIM_ForcedAction_InActive: Force inactive level on OC4REF.
Return values
None
Definition at line 1202 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr2 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_FORCED_ACTION(TIM_ForcedAction));
  tmpccmr2 = TIMx->CCMR2;
  /* Reset the OC2M Bits */
  tmpccmr2 &= (uint16_t)~TIM_CCMR2_OC4M;
  /* Configure The Forced output Mode */
  tmpccmr2 |= (uint16_t)(TIM_ForcedAction << 8);
  /* Write to TIMx CCMR2 register */
  TIMx->CCMR2 = tmpccmr2;
}
TIM_GenerateEvent()
void TIM_GenerateEvent (TIM_TypeDef * TIMx, uint16_t TIM_EventSource)
Configures the TIMx event to be generate by software.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
TIM_EventSource specifies the event source. This parameter can be one or more of the following values:
TIM_EventSource_Update: Timer update Event source
TIM_EventSource_CC1: Timer Capture Compare 1 Event source
TIM_EventSource_CC2: Timer Capture Compare 2 Event source
TIM_EventSource_CC3: Timer Capture Compare 3 Event source
TIM_EventSource_CC4: Timer Capture Compare 4 Event source
TIM_EventSource_COM: Timer COM event source
TIM_EventSource_Trigger: Timer Trigger Event source
TIM_EventSource_Break: Timer Break event source
Note
TIM6 and TIM7 can only generate an update event.
TIM_EventSource_COM and TIM_EventSource_Break are used only with TIM1 and TIM8.
Return values
None
Definition at line 2400 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  assert_param(IS_TIM_EVENT_SOURCE(TIM_EventSource));
 
  /* Set the event sources */
  TIMx->EGR = TIM_EventSource;
}
TIM_GetCapture1()
uint32_t TIM_GetCapture1 (TIM_TypeDef * TIMx)
Gets the TIMx Input Capture 1 value.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
Return values
Capture Compare 1 Register value.
Definition at line 2022 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  /* Get the Capture 1 Register value */
  return TIMx->CCR1;
}
TIM_GetCapture2()
uint32_t TIM_GetCapture2 (TIM_TypeDef * TIMx)
Gets the TIMx Input Capture 2 value.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
Return values
Capture Compare 2 Register value.
Definition at line 2037 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  /* Get the Capture 2 Register value */
  return TIMx->CCR2;
}
TIM_GetCapture3()
uint32_t TIM_GetCapture3 (TIM_TypeDef * TIMx)
Gets the TIMx Input Capture 3 value.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
Return values
Capture Compare 3 Register value.
Definition at line 2051 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  /* Get the Capture 3 Register value */
  return TIMx->CCR3;
}
TIM_GetCapture4()
uint32_t TIM_GetCapture4 (TIM_TypeDef * TIMx)
Gets the TIMx Input Capture 4 value.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
Return values
Capture Compare 4 Register value.
Definition at line 2065 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  /* Get the Capture 4 Register value */
  return TIMx->CCR4;
}
TIM_GetCounter()
uint32_t TIM_GetCounter (TIM_TypeDef * TIMx)
Gets the TIMx Counter value.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Return values
Counter Register value
Definition at line 432 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  /* Get the Counter Register value */
  return TIMx->CNT;
}
TIM_GetFlagStatus()
 FlagStatus TIM_GetFlagStatus (TIM_TypeDef * TIMx, uint16_t TIM_FLAG)
Checks whether the specified TIM flag is set or not.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
TIM_FLAG specifies the flag to check. This parameter can be one of the following values:
TIM_FLAG_Update: TIM update Flag
TIM_FLAG_CC1: TIM Capture Compare 1 Flag
TIM_FLAG_CC2: TIM Capture Compare 2 Flag
TIM_FLAG_CC3: TIM Capture Compare 3 Flag
TIM_FLAG_CC4: TIM Capture Compare 4 Flag
TIM_FLAG_COM: TIM Commutation Flag
TIM_FLAG_Trigger: TIM Trigger Flag
TIM_FLAG_Break: TIM Break Flag
TIM_FLAG_CC1OF: TIM Capture Compare 1 over capture Flag
TIM_FLAG_CC2OF: TIM Capture Compare 2 over capture Flag
TIM_FLAG_CC3OF: TIM Capture Compare 3 over capture Flag
TIM_FLAG_CC4OF: TIM Capture Compare 4 over capture Flag
Note
TIM6 and TIM7 can have only one update flag.
TIM_FLAG_COM and TIM_FLAG_Break are used only with TIM1 and TIM8.
Return values
The new state of TIM_FLAG (SET or RESET).
Definition at line 2433 of file stm32f4xx_tim.c.
References RESET.
{
  ITStatus bitstatus = RESET;
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  assert_param(IS_TIM_GET_FLAG(TIM_FLAG));
  
  if ((TIMx->SR & TIM_FLAG) != (uint16_t)RESET)
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  return bitstatus;
}
TIM_GetITStatus()
 ITStatus TIM_GetITStatus (TIM_TypeDef * TIMx, uint16_t TIM_IT)
Checks whether the TIM interrupt has occurred or not.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
TIM_IT specifies the TIM interrupt source to check. This parameter can be one of the following values:
TIM_IT_Update: TIM update Interrupt source
TIM_IT_CC1: TIM Capture Compare 1 Interrupt source
TIM_IT_CC2: TIM Capture Compare 2 Interrupt source
TIM_IT_CC3: TIM Capture Compare 3 Interrupt source
TIM_IT_CC4: TIM Capture Compare 4 Interrupt source
TIM_IT_COM: TIM Commutation Interrupt source
TIM_IT_Trigger: TIM Trigger Interrupt source
TIM_IT_Break: TIM Break Interrupt source
Note
TIM6 and TIM7 can generate only an update interrupt.
TIM_IT_COM and TIM_IT_Break are used only with TIM1 and TIM8.
Return values
The new state of the TIM_IT(SET or RESET).
Definition at line 2503 of file stm32f4xx_tim.c.
References RESET, and SET.
{
  ITStatus bitstatus = RESET;
  uint16_t itstatus = 0x0, itenable = 0x0;
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  assert_param(IS_TIM_GET_IT(TIM_IT));
   
  itstatus = TIMx->SR & TIM_IT;
  
  itenable = TIMx->DIER & TIM_IT;
  if ((itstatus != (uint16_t)RESET) && (itenable != (uint16_t)RESET))
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  return bitstatus;
}
TIM_GetPrescaler()
uint16_t TIM_GetPrescaler (TIM_TypeDef * TIMx)
Gets the TIMx Prescaler value.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Return values
Prescaler Register value.
Definition at line 446 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  /* Get the Prescaler Register value */
  return TIMx->PSC;
}
TIM_ICInit()
void TIM_ICInit (TIM_TypeDef * TIMx, TIM_ICInitTypeDef * TIM_ICInitStruct)
Initializes the TIM peripheral according to the specified parameters in the TIM_ICInitStruct.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_ICInitStruct pointer to a TIM_ICInitTypeDef structure that contains the configuration information for the specified TIM peripheral.
Return values
None
Definition at line 1890 of file stm32f4xx_tim.c.
References TI1_Config(), TI2_Config(), TI3_Config(), TI4_Config(), TIM_ICInitTypeDef::TIM_Channel, TIM_ICInitTypeDef::TIM_ICFilter, TIM_ICInitTypeDef::TIM_ICPolarity, TIM_ICInitTypeDef::TIM_ICPrescaler, TIM_ICInitTypeDef::TIM_ICSelection, TIM_SetIC1Prescaler(), TIM_SetIC2Prescaler(), TIM_SetIC3Prescaler(), and TIM_SetIC4Prescaler().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_IC_POLARITY(TIM_ICInitStruct->TIM_ICPolarity));
  assert_param(IS_TIM_IC_SELECTION(TIM_ICInitStruct->TIM_ICSelection));
  assert_param(IS_TIM_IC_PRESCALER(TIM_ICInitStruct->TIM_ICPrescaler));
  assert_param(IS_TIM_IC_FILTER(TIM_ICInitStruct->TIM_ICFilter));
  
  if (TIM_ICInitStruct->TIM_Channel == TIM_Channel_1)
  {
    /* TI1 Configuration */
    TI1_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity,
               TIM_ICInitStruct->TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC1Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
  else if (TIM_ICInitStruct->TIM_Channel == TIM_Channel_2)
  {
    /* TI2 Configuration */
    assert_param(IS_TIM_LIST2_PERIPH(TIMx));
    TI2_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity,
               TIM_ICInitStruct->TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC2Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
  else if (TIM_ICInitStruct->TIM_Channel == TIM_Channel_3)
  {
    /* TI3 Configuration */
    assert_param(IS_TIM_LIST3_PERIPH(TIMx));
    TI3_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity,
               TIM_ICInitStruct->TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC3Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
  else
  {
    /* TI4 Configuration */
    assert_param(IS_TIM_LIST3_PERIPH(TIMx));
    TI4_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity,
               TIM_ICInitStruct->TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC4Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
}
TIM_ICStructInit()
void TIM_ICStructInit (TIM_ICInitTypeDef * TIM_ICInitStruct)
Fills each TIM_ICInitStruct member with its default value.
Parameters
TIM_ICInitStruct pointer to a TIM_ICInitTypeDef structure which will be initialized.
Return values
None
Definition at line 1946 of file stm32f4xx_tim.c.
References TIM_ICInitTypeDef::TIM_Channel, TIM_ICInitTypeDef::TIM_ICFilter, TIM_ICInitTypeDef::TIM_ICPolarity, TIM_ICInitTypeDef::TIM_ICPrescaler, and TIM_ICInitTypeDef::TIM_ICSelection.
{
  /* Set the default configuration */
  TIM_ICInitStruct->TIM_Channel = TIM_Channel_1;
  TIM_ICInitStruct->TIM_ICPolarity = TIM_ICPolarity_Rising;
  TIM_ICInitStruct->TIM_ICSelection = TIM_ICSelection_DirectTI;
  TIM_ICInitStruct->TIM_ICPrescaler = TIM_ICPSC_DIV1;
  TIM_ICInitStruct->TIM_ICFilter = 0x00;
}
TIM_InternalClockConfig()
void TIM_InternalClockConfig (TIM_TypeDef * TIMx)
Configures the TIMx internal Clock.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
Return values
None
Definition at line 2673 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  /* Disable slave mode to clock the prescaler directly with the internal clock */
  TIMx->SMCR &= (uint16_t)~TIM_SMCR_SMS;
}
TIM_ITConfig()
void TIM_ITConfig (TIM_TypeDef * TIMx, uint16_t TIM_IT, FunctionalState NewState)
Enables or disables the specified TIM interrupts.
Parameters
TIMx where x can be 1 to 14 to select the TIMx peripheral.
TIM_IT specifies the TIM interrupts sources to be enabled or disabled. This parameter can be any combination of the following values:
TIM_IT_Update: TIM update Interrupt source
TIM_IT_CC1: TIM Capture Compare 1 Interrupt source
TIM_IT_CC2: TIM Capture Compare 2 Interrupt source
TIM_IT_CC3: TIM Capture Compare 3 Interrupt source
TIM_IT_CC4: TIM Capture Compare 4 Interrupt source
TIM_IT_COM: TIM Commutation Interrupt source
TIM_IT_Trigger: TIM Trigger Interrupt source
TIM_IT_Break: TIM Break Interrupt source
Note
For TIM6 and TIM7 only the parameter TIM_IT_Update can be used
For TIM9 and TIM12 only one of the following parameters can be used: TIM_IT_Update, TIM_IT_CC1, TIM_IT_CC2 or TIM_IT_Trigger.
For TIM10, TIM11, TIM13 and TIM14 only one of the following parameters can be used: TIM_IT_Update or TIM_IT_CC1
TIM_IT_COM and TIM_IT_Break can be used only with TIM1 and TIM8
Parameters
NewState new state of the TIM interrupts. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 2362 of file stm32f4xx_tim.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  assert_param(IS_TIM_IT(TIM_IT));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the Interrupt sources */
    TIMx->DIER |= TIM_IT;
  }
  else
  {
    /* Disable the Interrupt sources */
    TIMx->DIER &= (uint16_t)~TIM_IT;
  }
}
TIM_ITRxExternalClockConfig()
void TIM_ITRxExternalClockConfig (TIM_TypeDef * TIMx, uint16_t TIM_InputTriggerSource)
Configures the TIMx Internal Trigger as External Clock.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_InputTriggerSource Trigger source. This parameter can be one of the following values:
TIM_TS_ITR0: Internal Trigger 0
TIM_TS_ITR1: Internal Trigger 1
TIM_TS_ITR2: Internal Trigger 2
TIM_TS_ITR3: Internal Trigger 3
Return values
None
Definition at line 2694 of file stm32f4xx_tim.c.
References TIM_SelectInputTrigger().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_INTERNAL_TRIGGER_SELECTION(TIM_InputTriggerSource));
  /* Select the Internal Trigger */
  TIM_SelectInputTrigger(TIMx, TIM_InputTriggerSource);
  /* Select the External clock mode1 */
  TIMx->SMCR |= TIM_SlaveMode_External1;
}
TIM_OC1FastConfig()
void TIM_OC1FastConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 1 Fast feature.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_OCFast new state of the Output Compare Fast Enable Bit. This parameter can be one of the following values:
TIM_OCFast_Enable: TIM output compare fast enable
TIM_OCFast_Disable: TIM output compare fast disable
Return values
None
Definition at line 1347 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr1 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_OCFAST_STATE(TIM_OCFast));
  /* Get the TIMx CCMR1 register value */
  tmpccmr1 = TIMx->CCMR1;
  /* Reset the OC1FE Bit */
  tmpccmr1 &= (uint16_t)~TIM_CCMR1_OC1FE;
  /* Enable or Disable the Output Compare Fast Bit */
  tmpccmr1 |= TIM_OCFast;
  /* Write to TIMx CCMR1 */
  TIMx->CCMR1 = tmpccmr1;
}
TIM_OC1Init()
void TIM_OC1Init (TIM_TypeDef * TIMx, TIM_OCInitTypeDef * TIM_OCInitStruct)
Initializes the TIMx Channel1 according to the specified parameters in the TIM_OCInitStruct.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_OCInitStruct pointer to a TIM_OCInitTypeDef structure that contains the configuration information for the specified TIM peripheral.
Return values
None
Definition at line 665 of file stm32f4xx_tim.c.
References TIM_OCInitTypeDef::TIM_OCIdleState, TIM_OCInitTypeDef::TIM_OCMode, TIM_OCInitTypeDef::TIM_OCNIdleState, TIM_OCInitTypeDef::TIM_OCNPolarity, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_OCInitTypeDef::TIM_OutputNState, and TIM_OCInitTypeDef::TIM_OutputState.
{
  uint16_t tmpccmrx = 0, tmpccer = 0, tmpcr2 = 0;
   
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_OC_MODE(TIM_OCInitStruct->TIM_OCMode));
  assert_param(IS_TIM_OUTPUT_STATE(TIM_OCInitStruct->TIM_OutputState));
  assert_param(IS_TIM_OC_POLARITY(TIM_OCInitStruct->TIM_OCPolarity));
  /* Disable the Channel 1: Reset the CC1E Bit */
  TIMx->CCER &= (uint16_t)~TIM_CCER_CC1E;
  
  /* Get the TIMx CCER register value */
  tmpccer = TIMx->CCER;
  /* Get the TIMx CR2 register value */
  tmpcr2 = TIMx->CR2;
  
  /* Get the TIMx CCMR1 register value */
  tmpccmrx = TIMx->CCMR1;
    
  /* Reset the Output Compare Mode Bits */
  tmpccmrx &= (uint16_t)~TIM_CCMR1_OC1M;
  tmpccmrx &= (uint16_t)~TIM_CCMR1_CC1S;
  /* Select the Output Compare Mode */
  tmpccmrx |= TIM_OCInitStruct->TIM_OCMode;
  
  /* Reset the Output Polarity level */
  tmpccer &= (uint16_t)~TIM_CCER_CC1P;
  /* Set the Output Compare Polarity */
  tmpccer |= TIM_OCInitStruct->TIM_OCPolarity;
  
  /* Set the Output State */
  tmpccer |= TIM_OCInitStruct->TIM_OutputState;
    
  if((TIMx == TIM1) || (TIMx == TIM8))
  {
    assert_param(IS_TIM_OUTPUTN_STATE(TIM_OCInitStruct->TIM_OutputNState));
    assert_param(IS_TIM_OCN_POLARITY(TIM_OCInitStruct->TIM_OCNPolarity));
    assert_param(IS_TIM_OCNIDLE_STATE(TIM_OCInitStruct->TIM_OCNIdleState));
    assert_param(IS_TIM_OCIDLE_STATE(TIM_OCInitStruct->TIM_OCIdleState));
    
    /* Reset the Output N Polarity level */
    tmpccer &= (uint16_t)~TIM_CCER_CC1NP;
    /* Set the Output N Polarity */
    tmpccer |= TIM_OCInitStruct->TIM_OCNPolarity;
    /* Reset the Output N State */
    tmpccer &= (uint16_t)~TIM_CCER_CC1NE;
    
    /* Set the Output N State */
    tmpccer |= TIM_OCInitStruct->TIM_OutputNState;
    /* Reset the Output Compare and Output Compare N IDLE State */
    tmpcr2 &= (uint16_t)~TIM_CR2_OIS1;
    tmpcr2 &= (uint16_t)~TIM_CR2_OIS1N;
    /* Set the Output Idle state */
    tmpcr2 |= TIM_OCInitStruct->TIM_OCIdleState;
    /* Set the Output N Idle state */
    tmpcr2 |= TIM_OCInitStruct->TIM_OCNIdleState;
  }
  /* Write to TIMx CR2 */
  TIMx->CR2 = tmpcr2;
  
  /* Write to TIMx CCMR1 */
  TIMx->CCMR1 = tmpccmrx;
  
  /* Set the Capture Compare Register value */
  TIMx->CCR1 = TIM_OCInitStruct->TIM_Pulse;
  
  /* Write to TIMx CCER */
  TIMx->CCER = tmpccer;
}
TIM_OC1NPolarityConfig()
void TIM_OC1NPolarityConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCNPolarity)
Configures the TIMx Channel 1N polarity.
Parameters
TIMx where x can be 1 or 8 to select the TIM peripheral.
TIM_OCNPolarity specifies the OC1N Polarity This parameter can be one of the following values:
TIM_OCNPolarity_High: Output Compare active high
TIM_OCNPolarity_Low: Output Compare active low
Return values
None
Definition at line 1612 of file stm32f4xx_tim.c.
{
  uint16_t tmpccer = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST4_PERIPH(TIMx));
  assert_param(IS_TIM_OCN_POLARITY(TIM_OCNPolarity));
   
  tmpccer = TIMx->CCER;
  /* Set or Reset the CC1NP Bit */
  tmpccer &= (uint16_t)~TIM_CCER_CC1NP;
  tmpccer |= TIM_OCNPolarity;
  /* Write to TIMx CCER register */
  TIMx->CCER = tmpccer;
}
TIM_OC1PolarityConfig()
void TIM_OC1PolarityConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 1 polarity.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_OCPolarity specifies the OC1 Polarity This parameter can be one of the following values:
TIM_OCPolarity_High: Output Compare active high
TIM_OCPolarity_Low: Output Compare active low
Return values
None
Definition at line 1585 of file stm32f4xx_tim.c.
{
  uint16_t tmpccer = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_OC_POLARITY(TIM_OCPolarity));
  tmpccer = TIMx->CCER;
  /* Set or Reset the CC1P Bit */
  tmpccer &= (uint16_t)(~TIM_CCER_CC1P);
  tmpccer |= TIM_OCPolarity;
  /* Write to TIMx CCER register */
  TIMx->CCER = tmpccer;
}
TIM_OC1PreloadConfig()
void TIM_OC1PreloadConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR1.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_OCPreload new state of the TIMx peripheral Preload register This parameter can be one of the following values:
TIM_OCPreload_Enable
TIM_OCPreload_Disable
Return values
None
Definition at line 1230 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr1 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_OCPRELOAD_STATE(TIM_OCPreload));
  tmpccmr1 = TIMx->CCMR1;
  /* Reset the OC1PE Bit */
  tmpccmr1 &= (uint16_t)(~TIM_CCMR1_OC1PE);
  /* Enable or Disable the Output Compare Preload feature */
  tmpccmr1 |= TIM_OCPreload;
  /* Write to TIMx CCMR1 register */
  TIMx->CCMR1 = tmpccmr1;
}
TIM_OC2FastConfig()
void TIM_OC2FastConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 2 Fast feature.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_OCFast new state of the Output Compare Fast Enable Bit. This parameter can be one of the following values:
TIM_OCFast_Enable: TIM output compare fast enable
TIM_OCFast_Disable: TIM output compare fast disable
Return values
None
Definition at line 1378 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr1 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_OCFAST_STATE(TIM_OCFast));
  /* Get the TIMx CCMR1 register value */
  tmpccmr1 = TIMx->CCMR1;
  /* Reset the OC2FE Bit */
  tmpccmr1 &= (uint16_t)(~TIM_CCMR1_OC2FE);
  /* Enable or Disable the Output Compare Fast Bit */
  tmpccmr1 |= (uint16_t)(TIM_OCFast << 8);
  /* Write to TIMx CCMR1 */
  TIMx->CCMR1 = tmpccmr1;
}
TIM_OC2Init()
void TIM_OC2Init (TIM_TypeDef * TIMx, TIM_OCInitTypeDef * TIM_OCInitStruct)
Initializes the TIMx Channel2 according to the specified parameters in the TIM_OCInitStruct.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_OCInitStruct pointer to a TIM_OCInitTypeDef structure that contains the configuration information for the specified TIM peripheral.
Return values
None
Definition at line 746 of file stm32f4xx_tim.c.
References TIM_OCInitTypeDef::TIM_OCIdleState, TIM_OCInitTypeDef::TIM_OCMode, TIM_OCInitTypeDef::TIM_OCNIdleState, TIM_OCInitTypeDef::TIM_OCNPolarity, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_OCInitTypeDef::TIM_OutputNState, and TIM_OCInitTypeDef::TIM_OutputState.
{
  uint16_t tmpccmrx = 0, tmpccer = 0, tmpcr2 = 0;
   
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_OC_MODE(TIM_OCInitStruct->TIM_OCMode));
  assert_param(IS_TIM_OUTPUT_STATE(TIM_OCInitStruct->TIM_OutputState));
  assert_param(IS_TIM_OC_POLARITY(TIM_OCInitStruct->TIM_OCPolarity));
  /* Disable the Channel 2: Reset the CC2E Bit */
  TIMx->CCER &= (uint16_t)~TIM_CCER_CC2E;
  
  /* Get the TIMx CCER register value */
  tmpccer = TIMx->CCER;
  /* Get the TIMx CR2 register value */
  tmpcr2 = TIMx->CR2;
  
  /* Get the TIMx CCMR1 register value */
  tmpccmrx = TIMx->CCMR1;
    
  /* Reset the Output Compare mode and Capture/Compare selection Bits */
  tmpccmrx &= (uint16_t)~TIM_CCMR1_OC2M;
  tmpccmrx &= (uint16_t)~TIM_CCMR1_CC2S;
  
  /* Select the Output Compare Mode */
  tmpccmrx |= (uint16_t)(TIM_OCInitStruct->TIM_OCMode << 8);
  
  /* Reset the Output Polarity level */
  tmpccer &= (uint16_t)~TIM_CCER_CC2P;
  /* Set the Output Compare Polarity */
  tmpccer |= (uint16_t)(TIM_OCInitStruct->TIM_OCPolarity << 4);
  
  /* Set the Output State */
  tmpccer |= (uint16_t)(TIM_OCInitStruct->TIM_OutputState << 4);
    
  if((TIMx == TIM1) || (TIMx == TIM8))
  {
    assert_param(IS_TIM_OUTPUTN_STATE(TIM_OCInitStruct->TIM_OutputNState));
    assert_param(IS_TIM_OCN_POLARITY(TIM_OCInitStruct->TIM_OCNPolarity));
    assert_param(IS_TIM_OCNIDLE_STATE(TIM_OCInitStruct->TIM_OCNIdleState));
    assert_param(IS_TIM_OCIDLE_STATE(TIM_OCInitStruct->TIM_OCIdleState));
    
    /* Reset the Output N Polarity level */
    tmpccer &= (uint16_t)~TIM_CCER_CC2NP;
    /* Set the Output N Polarity */
    tmpccer |= (uint16_t)(TIM_OCInitStruct->TIM_OCNPolarity << 4);
    /* Reset the Output N State */
    tmpccer &= (uint16_t)~TIM_CCER_CC2NE;
    
    /* Set the Output N State */
    tmpccer |= (uint16_t)(TIM_OCInitStruct->TIM_OutputNState << 4);
    /* Reset the Output Compare and Output Compare N IDLE State */
    tmpcr2 &= (uint16_t)~TIM_CR2_OIS2;
    tmpcr2 &= (uint16_t)~TIM_CR2_OIS2N;
    /* Set the Output Idle state */
    tmpcr2 |= (uint16_t)(TIM_OCInitStruct->TIM_OCIdleState << 2);
    /* Set the Output N Idle state */
    tmpcr2 |= (uint16_t)(TIM_OCInitStruct->TIM_OCNIdleState << 2);
  }
  /* Write to TIMx CR2 */
  TIMx->CR2 = tmpcr2;
  
  /* Write to TIMx CCMR1 */
  TIMx->CCMR1 = tmpccmrx;
  
  /* Set the Capture Compare Register value */
  TIMx->CCR2 = TIM_OCInitStruct->TIM_Pulse;
  
  /* Write to TIMx CCER */
  TIMx->CCER = tmpccer;
}
TIM_OC2NPolarityConfig()
void TIM_OC2NPolarityConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCNPolarity)
Configures the TIMx Channel 2N polarity.
Parameters
TIMx where x can be 1 or 8 to select the TIM peripheral.
TIM_OCNPolarity specifies the OC2N Polarity This parameter can be one of the following values:
TIM_OCNPolarity_High: Output Compare active high
TIM_OCNPolarity_Low: Output Compare active low
Return values
None
Definition at line 1666 of file stm32f4xx_tim.c.
{
  uint16_t tmpccer = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST4_PERIPH(TIMx));
  assert_param(IS_TIM_OCN_POLARITY(TIM_OCNPolarity));
  
  tmpccer = TIMx->CCER;
  /* Set or Reset the CC2NP Bit */
  tmpccer &= (uint16_t)~TIM_CCER_CC2NP;
  tmpccer |= (uint16_t)(TIM_OCNPolarity << 4);
  /* Write to TIMx CCER register */
  TIMx->CCER = tmpccer;
}
TIM_OC2PolarityConfig()
void TIM_OC2PolarityConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 2 polarity.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_OCPolarity specifies the OC2 Polarity This parameter can be one of the following values:
TIM_OCPolarity_High: Output Compare active high
TIM_OCPolarity_Low: Output Compare active low
Return values
None
Definition at line 1639 of file stm32f4xx_tim.c.
{
  uint16_t tmpccer = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_OC_POLARITY(TIM_OCPolarity));
  tmpccer = TIMx->CCER;
  /* Set or Reset the CC2P Bit */
  tmpccer &= (uint16_t)(~TIM_CCER_CC2P);
  tmpccer |= (uint16_t)(TIM_OCPolarity << 4);
  /* Write to TIMx CCER register */
  TIMx->CCER = tmpccer;
}
TIM_OC2PreloadConfig()
void TIM_OC2PreloadConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR2.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_OCPreload new state of the TIMx peripheral Preload register This parameter can be one of the following values:
TIM_OCPreload_Enable
TIM_OCPreload_Disable
Return values
None
Definition at line 1260 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr1 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_OCPRELOAD_STATE(TIM_OCPreload));
  tmpccmr1 = TIMx->CCMR1;
  /* Reset the OC2PE Bit */
  tmpccmr1 &= (uint16_t)(~TIM_CCMR1_OC2PE);
  /* Enable or Disable the Output Compare Preload feature */
  tmpccmr1 |= (uint16_t)(TIM_OCPreload << 8);
  /* Write to TIMx CCMR1 register */
  TIMx->CCMR1 = tmpccmr1;
}
TIM_OC3FastConfig()
void TIM_OC3FastConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 3 Fast feature.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_OCFast new state of the Output Compare Fast Enable Bit. This parameter can be one of the following values:
TIM_OCFast_Enable: TIM output compare fast enable
TIM_OCFast_Disable: TIM output compare fast disable
Return values
None
Definition at line 1408 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr2 = 0;
  
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_OCFAST_STATE(TIM_OCFast));
  /* Get the TIMx CCMR2 register value */
  tmpccmr2 = TIMx->CCMR2;
  /* Reset the OC3FE Bit */
  tmpccmr2 &= (uint16_t)~TIM_CCMR2_OC3FE;
  /* Enable or Disable the Output Compare Fast Bit */
  tmpccmr2 |= TIM_OCFast;
  /* Write to TIMx CCMR2 */
  TIMx->CCMR2 = tmpccmr2;
}
TIM_OC3Init()
void TIM_OC3Init (TIM_TypeDef * TIMx, TIM_OCInitTypeDef * TIM_OCInitStruct)
Initializes the TIMx Channel3 according to the specified parameters in the TIM_OCInitStruct.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_OCInitStruct pointer to a TIM_OCInitTypeDef structure that contains the configuration information for the specified TIM peripheral.
Return values
None
Definition at line 827 of file stm32f4xx_tim.c.
References TIM_OCInitTypeDef::TIM_OCIdleState, TIM_OCInitTypeDef::TIM_OCMode, TIM_OCInitTypeDef::TIM_OCNIdleState, TIM_OCInitTypeDef::TIM_OCNPolarity, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_OCInitTypeDef::TIM_OutputNState, and TIM_OCInitTypeDef::TIM_OutputState.
{
  uint16_t tmpccmrx = 0, tmpccer = 0, tmpcr2 = 0;
   
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_OC_MODE(TIM_OCInitStruct->TIM_OCMode));
  assert_param(IS_TIM_OUTPUT_STATE(TIM_OCInitStruct->TIM_OutputState));
  assert_param(IS_TIM_OC_POLARITY(TIM_OCInitStruct->TIM_OCPolarity));
  /* Disable the Channel 3: Reset the CC2E Bit */
  TIMx->CCER &= (uint16_t)~TIM_CCER_CC3E;
  
  /* Get the TIMx CCER register value */
  tmpccer = TIMx->CCER;
  /* Get the TIMx CR2 register value */
  tmpcr2 = TIMx->CR2;
  
  /* Get the TIMx CCMR2 register value */
  tmpccmrx = TIMx->CCMR2;
    
  /* Reset the Output Compare mode and Capture/Compare selection Bits */
  tmpccmrx &= (uint16_t)~TIM_CCMR2_OC3M;
  tmpccmrx &= (uint16_t)~TIM_CCMR2_CC3S;
  /* Select the Output Compare Mode */
  tmpccmrx |= TIM_OCInitStruct->TIM_OCMode;
  
  /* Reset the Output Polarity level */
  tmpccer &= (uint16_t)~TIM_CCER_CC3P;
  /* Set the Output Compare Polarity */
  tmpccer |= (uint16_t)(TIM_OCInitStruct->TIM_OCPolarity << 8);
  
  /* Set the Output State */
  tmpccer |= (uint16_t)(TIM_OCInitStruct->TIM_OutputState << 8);
    
  if((TIMx == TIM1) || (TIMx == TIM8))
  {
    assert_param(IS_TIM_OUTPUTN_STATE(TIM_OCInitStruct->TIM_OutputNState));
    assert_param(IS_TIM_OCN_POLARITY(TIM_OCInitStruct->TIM_OCNPolarity));
    assert_param(IS_TIM_OCNIDLE_STATE(TIM_OCInitStruct->TIM_OCNIdleState));
    assert_param(IS_TIM_OCIDLE_STATE(TIM_OCInitStruct->TIM_OCIdleState));
    
    /* Reset the Output N Polarity level */
    tmpccer &= (uint16_t)~TIM_CCER_CC3NP;
    /* Set the Output N Polarity */
    tmpccer |= (uint16_t)(TIM_OCInitStruct->TIM_OCNPolarity << 8);
    /* Reset the Output N State */
    tmpccer &= (uint16_t)~TIM_CCER_CC3NE;
    
    /* Set the Output N State */
    tmpccer |= (uint16_t)(TIM_OCInitStruct->TIM_OutputNState << 8);
    /* Reset the Output Compare and Output Compare N IDLE State */
    tmpcr2 &= (uint16_t)~TIM_CR2_OIS3;
    tmpcr2 &= (uint16_t)~TIM_CR2_OIS3N;
    /* Set the Output Idle state */
    tmpcr2 |= (uint16_t)(TIM_OCInitStruct->TIM_OCIdleState << 4);
    /* Set the Output N Idle state */
    tmpcr2 |= (uint16_t)(TIM_OCInitStruct->TIM_OCNIdleState << 4);
  }
  /* Write to TIMx CR2 */
  TIMx->CR2 = tmpcr2;
  
  /* Write to TIMx CCMR2 */
  TIMx->CCMR2 = tmpccmrx;
  
  /* Set the Capture Compare Register value */
  TIMx->CCR3 = TIM_OCInitStruct->TIM_Pulse;
  
  /* Write to TIMx CCER */
  TIMx->CCER = tmpccer;
}
TIM_OC3NPolarityConfig()
void TIM_OC3NPolarityConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCNPolarity)
Configures the TIMx Channel 3N polarity.
Parameters
TIMx where x can be 1 or 8 to select the TIM peripheral.
TIM_OCNPolarity specifies the OC3N Polarity This parameter can be one of the following values:
TIM_OCNPolarity_High: Output Compare active high
TIM_OCNPolarity_Low: Output Compare active low
Return values
None
Definition at line 1720 of file stm32f4xx_tim.c.
{
  uint16_t tmpccer = 0;
 
  /* Check the parameters */
  assert_param(IS_TIM_LIST4_PERIPH(TIMx));
  assert_param(IS_TIM_OCN_POLARITY(TIM_OCNPolarity));
    
  tmpccer = TIMx->CCER;
  /* Set or Reset the CC3NP Bit */
  tmpccer &= (uint16_t)~TIM_CCER_CC3NP;
  tmpccer |= (uint16_t)(TIM_OCNPolarity << 8);
  /* Write to TIMx CCER register */
  TIMx->CCER = tmpccer;
}
TIM_OC3PolarityConfig()
void TIM_OC3PolarityConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 3 polarity.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_OCPolarity specifies the OC3 Polarity This parameter can be one of the following values:
TIM_OCPolarity_High: Output Compare active high
TIM_OCPolarity_Low: Output Compare active low
Return values
None
Definition at line 1693 of file stm32f4xx_tim.c.
{
  uint16_t tmpccer = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_OC_POLARITY(TIM_OCPolarity));
  tmpccer = TIMx->CCER;
  /* Set or Reset the CC3P Bit */
  tmpccer &= (uint16_t)~TIM_CCER_CC3P;
  tmpccer |= (uint16_t)(TIM_OCPolarity << 8);
  /* Write to TIMx CCER register */
  TIMx->CCER = tmpccer;
}
TIM_OC3PreloadConfig()
void TIM_OC3PreloadConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR3.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_OCPreload new state of the TIMx peripheral Preload register This parameter can be one of the following values:
TIM_OCPreload_Enable
TIM_OCPreload_Disable
Return values
None
Definition at line 1289 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr2 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_OCPRELOAD_STATE(TIM_OCPreload));
  tmpccmr2 = TIMx->CCMR2;
  /* Reset the OC3PE Bit */
  tmpccmr2 &= (uint16_t)(~TIM_CCMR2_OC3PE);
  /* Enable or Disable the Output Compare Preload feature */
  tmpccmr2 |= TIM_OCPreload;
  /* Write to TIMx CCMR2 register */
  TIMx->CCMR2 = tmpccmr2;
}
TIM_OC4FastConfig()
void TIM_OC4FastConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 4 Fast feature.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_OCFast new state of the Output Compare Fast Enable Bit. This parameter can be one of the following values:
TIM_OCFast_Enable: TIM output compare fast enable
TIM_OCFast_Disable: TIM output compare fast disable
Return values
None
Definition at line 1438 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr2 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_OCFAST_STATE(TIM_OCFast));
  /* Get the TIMx CCMR2 register value */
  tmpccmr2 = TIMx->CCMR2;
  /* Reset the OC4FE Bit */
  tmpccmr2 &= (uint16_t)(~TIM_CCMR2_OC4FE);
  /* Enable or Disable the Output Compare Fast Bit */
  tmpccmr2 |= (uint16_t)(TIM_OCFast << 8);
  /* Write to TIMx CCMR2 */
  TIMx->CCMR2 = tmpccmr2;
}
TIM_OC4Init()
void TIM_OC4Init (TIM_TypeDef * TIMx, TIM_OCInitTypeDef * TIM_OCInitStruct)
Initializes the TIMx Channel4 according to the specified parameters in the TIM_OCInitStruct.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_OCInitStruct pointer to a TIM_OCInitTypeDef structure that contains the configuration information for the specified TIM peripheral.
Return values
None
Definition at line 907 of file stm32f4xx_tim.c.
References TIM_OCInitTypeDef::TIM_OCIdleState, TIM_OCInitTypeDef::TIM_OCMode, TIM_OCInitTypeDef::TIM_OCPolarity, and TIM_OCInitTypeDef::TIM_OutputState.
{
  uint16_t tmpccmrx = 0, tmpccer = 0, tmpcr2 = 0;
   
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_OC_MODE(TIM_OCInitStruct->TIM_OCMode));
  assert_param(IS_TIM_OUTPUT_STATE(TIM_OCInitStruct->TIM_OutputState));
  assert_param(IS_TIM_OC_POLARITY(TIM_OCInitStruct->TIM_OCPolarity));
  /* Disable the Channel 4: Reset the CC4E Bit */
  TIMx->CCER &= (uint16_t)~TIM_CCER_CC4E;
  
  /* Get the TIMx CCER register value */
  tmpccer = TIMx->CCER;
  /* Get the TIMx CR2 register value */
  tmpcr2 = TIMx->CR2;
  
  /* Get the TIMx CCMR2 register value */
  tmpccmrx = TIMx->CCMR2;
    
  /* Reset the Output Compare mode and Capture/Compare selection Bits */
  tmpccmrx &= (uint16_t)~TIM_CCMR2_OC4M;
  tmpccmrx &= (uint16_t)~TIM_CCMR2_CC4S;
  
  /* Select the Output Compare Mode */
  tmpccmrx |= (uint16_t)(TIM_OCInitStruct->TIM_OCMode << 8);
  
  /* Reset the Output Polarity level */
  tmpccer &= (uint16_t)~TIM_CCER_CC4P;
  /* Set the Output Compare Polarity */
  tmpccer |= (uint16_t)(TIM_OCInitStruct->TIM_OCPolarity << 12);
  
  /* Set the Output State */
  tmpccer |= (uint16_t)(TIM_OCInitStruct->TIM_OutputState << 12);
  
  if((TIMx == TIM1) || (TIMx == TIM8))
  {
    assert_param(IS_TIM_OCIDLE_STATE(TIM_OCInitStruct->TIM_OCIdleState));
    /* Reset the Output Compare IDLE State */
    tmpcr2 &=(uint16_t) ~TIM_CR2_OIS4;
    /* Set the Output Idle state */
    tmpcr2 |= (uint16_t)(TIM_OCInitStruct->TIM_OCIdleState << 6);
  }
  /* Write to TIMx CR2 */
  TIMx->CR2 = tmpcr2;
  
  /* Write to TIMx CCMR2 */
  TIMx->CCMR2 = tmpccmrx;
    
  /* Set the Capture Compare Register value */
  TIMx->CCR4 = TIM_OCInitStruct->TIM_Pulse;
  
  /* Write to TIMx CCER */
  TIMx->CCER = tmpccer;
}
TIM_OC4PolarityConfig()
void TIM_OC4PolarityConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 4 polarity.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_OCPolarity specifies the OC4 Polarity This parameter can be one of the following values:
TIM_OCPolarity_High: Output Compare active high
TIM_OCPolarity_Low: Output Compare active low
Return values
None
Definition at line 1747 of file stm32f4xx_tim.c.
{
  uint16_t tmpccer = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_OC_POLARITY(TIM_OCPolarity));
  tmpccer = TIMx->CCER;
  /* Set or Reset the CC4P Bit */
  tmpccer &= (uint16_t)~TIM_CCER_CC4P;
  tmpccer |= (uint16_t)(TIM_OCPolarity << 12);
  /* Write to TIMx CCER register */
  TIMx->CCER = tmpccer;
}
TIM_OC4PreloadConfig()
void TIM_OC4PreloadConfig (TIM_TypeDef * TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR4.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_OCPreload new state of the TIMx peripheral Preload register This parameter can be one of the following values:
TIM_OCPreload_Enable
TIM_OCPreload_Disable
Return values
None
Definition at line 1318 of file stm32f4xx_tim.c.
{
  uint16_t tmpccmr2 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_OCPRELOAD_STATE(TIM_OCPreload));
  tmpccmr2 = TIMx->CCMR2;
  /* Reset the OC4PE Bit */
  tmpccmr2 &= (uint16_t)(~TIM_CCMR2_OC4PE);
  /* Enable or Disable the Output Compare Preload feature */
  tmpccmr2 |= (uint16_t)(TIM_OCPreload << 8);
  /* Write to TIMx CCMR2 register */
  TIMx->CCMR2 = tmpccmr2;
}
TIM_OCStructInit()
void TIM_OCStructInit (TIM_OCInitTypeDef * TIM_OCInitStruct)
Fills each TIM_OCInitStruct member with its default value.
Parameters
TIM_OCInitStruct pointer to a TIM_OCInitTypeDef structure which will be initialized.
Return values
None
Definition at line 970 of file stm32f4xx_tim.c.
References TIM_OCInitTypeDef::TIM_OCIdleState, TIM_OCInitTypeDef::TIM_OCMode, TIM_OCInitTypeDef::TIM_OCNIdleState, TIM_OCInitTypeDef::TIM_OCNPolarity, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_OCInitTypeDef::TIM_OutputNState, TIM_OCInitTypeDef::TIM_OutputState, and TIM_OCInitTypeDef::TIM_Pulse.
{
  /* Set the default configuration */
  TIM_OCInitStruct->TIM_OCMode = TIM_OCMode_Timing;
  TIM_OCInitStruct->TIM_OutputState = TIM_OutputState_Disable;
  TIM_OCInitStruct->TIM_OutputNState = TIM_OutputNState_Disable;
  TIM_OCInitStruct->TIM_Pulse = 0x00000000;
  TIM_OCInitStruct->TIM_OCPolarity = TIM_OCPolarity_High;
  TIM_OCInitStruct->TIM_OCNPolarity = TIM_OCPolarity_High;
  TIM_OCInitStruct->TIM_OCIdleState = TIM_OCIdleState_Reset;
  TIM_OCInitStruct->TIM_OCNIdleState = TIM_OCNIdleState_Reset;
}
TIM_PrescalerConfig()
void TIM_PrescalerConfig (TIM_TypeDef * TIMx, uint16_t Prescaler, uint16_t TIM_PSCReloadMode)
Configures the TIMx Prescaler.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Prescaler specifies the Prescaler Register value
TIM_PSCReloadMode specifies the TIM Prescaler Reload mode This parameter can be one of the following values:
TIM_PSCReloadMode_Update: The Prescaler is loaded at the update event.
TIM_PSCReloadMode_Immediate: The Prescaler is loaded immediatly.
Return values
None
Definition at line 354 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  assert_param(IS_TIM_PRESCALER_RELOAD(TIM_PSCReloadMode));
  /* Set the Prescaler value */
  TIMx->PSC = Prescaler;
  /* Set or reset the UG Bit */
  TIMx->EGR = TIM_PSCReloadMode;
}
TIM_PWMIConfig()
void TIM_PWMIConfig (TIM_TypeDef * TIMx, TIM_ICInitTypeDef * TIM_ICInitStruct)
Configures the TIM peripheral according to the specified parameters in the TIM_ICInitStruct to measure an external PWM signal.
Parameters
TIMx where x can be 1, 2, 3, 4, 5,8, 9 or 12 to select the TIM peripheral.
TIM_ICInitStruct pointer to a TIM_ICInitTypeDef structure that contains the configuration information for the specified TIM peripheral.
Return values
None
Definition at line 1965 of file stm32f4xx_tim.c.
References TI1_Config(), TI2_Config(), TIM_ICInitTypeDef::TIM_Channel, TIM_ICInitTypeDef::TIM_ICFilter, TIM_ICInitTypeDef::TIM_ICPolarity, TIM_ICInitTypeDef::TIM_ICPrescaler, TIM_ICInitTypeDef::TIM_ICSelection, TIM_SetIC1Prescaler(), and TIM_SetIC2Prescaler().
{
  uint16_t icoppositepolarity = TIM_ICPolarity_Rising;
  uint16_t icoppositeselection = TIM_ICSelection_DirectTI;
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  /* Select the Opposite Input Polarity */
  if (TIM_ICInitStruct->TIM_ICPolarity == TIM_ICPolarity_Rising)
  {
    icoppositepolarity = TIM_ICPolarity_Falling;
  }
  else
  {
    icoppositepolarity = TIM_ICPolarity_Rising;
  }
  /* Select the Opposite Input */
  if (TIM_ICInitStruct->TIM_ICSelection == TIM_ICSelection_DirectTI)
  {
    icoppositeselection = TIM_ICSelection_IndirectTI;
  }
  else
  {
    icoppositeselection = TIM_ICSelection_DirectTI;
  }
  if (TIM_ICInitStruct->TIM_Channel == TIM_Channel_1)
  {
    /* TI1 Configuration */
    TI1_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity, TIM_ICInitStruct->
      TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC1Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
    /* TI2 Configuration */
    TI2_Config(TIMx, icoppositepolarity, icoppositeselection, TIM_ICInitStruct->
      TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC2Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
  else
  {
    /* TI2 Configuration */
    TI2_Config(TIMx, TIM_ICInitStruct->TIM_ICPolarity, TIM_ICInitStruct->
      TIM_ICSelection,
               TIM_ICInitStruct->TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC2Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
    /* TI1 Configuration */
    TI1_Config(TIMx, icoppositepolarity, icoppositeselection, TIM_ICInitStruct->
      TIM_ICFilter);
    /* Set the Input Capture Prescaler value */
    TIM_SetIC1Prescaler(TIMx, TIM_ICInitStruct->TIM_ICPrescaler);
  }
}
TIM_RemapConfig()
void TIM_RemapConfig (TIM_TypeDef * TIMx, uint16_t TIM_Remap)
Configures the TIM2, TIM5 and TIM11 Remapping input capabilities.
Parameters
TIMx where x can be 2, 5 or 11 to select the TIM peripheral.
TIM_Remap specifies the TIM input remapping source. This parameter can be one of the following values:
TIM2_TIM8_TRGO: TIM2 ITR1 input is connected to TIM8 Trigger output(default)
TIM2_ETH_PTP: TIM2 ITR1 input is connected to ETH PTP trogger output.
TIM2_USBFS_SOF: TIM2 ITR1 input is connected to USB FS SOF.
TIM2_USBHS_SOF: TIM2 ITR1 input is connected to USB HS SOF.
TIM5_GPIO: TIM5 CH4 input is connected to dedicated Timer pin(default)
TIM5_LSI: TIM5 CH4 input is connected to LSI clock.
TIM5_LSE: TIM5 CH4 input is connected to LSE clock.
TIM5_RTC: TIM5 CH4 input is connected to RTC Output event.
TIM11_GPIO: TIM11 CH4 input is connected to dedicated Timer pin(default)
TIM11_HSE: TIM11 CH4 input is connected to HSE_RTC clock (HSE divided by a programmable prescaler)
Return values
None
Definition at line 3160 of file stm32f4xx_tim.c.
{
 /* Check the parameters */
  assert_param(IS_TIM_LIST6_PERIPH(TIMx));
  assert_param(IS_TIM_REMAP(TIM_Remap));
  /* Set the Timer remapping configuration */
  TIMx->OR = TIM_Remap;
}
TIM_SelectCCDMA()
void TIM_SelectCCDMA (TIM_TypeDef * TIMx, FunctionalState NewState)
Selects the TIMx peripheral Capture Compare DMA source.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
NewState new state of the Capture Compare DMA source This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 2634 of file stm32f4xx_tim.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Set the CCDS Bit */
    TIMx->CR2 |= TIM_CR2_CCDS;
  }
  else
  {
    /* Reset the CCDS Bit */
    TIMx->CR2 &= (uint16_t)~TIM_CR2_CCDS;
  }
}
TIM_SelectCOM()
void TIM_SelectCOM (TIM_TypeDef * TIMx, FunctionalState NewState)
Selects the TIM peripheral Commutation event.
Parameters
TIMx where x can be 1 or 8 to select the TIMx peripheral
NewState new state of the Commutation event. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 2280 of file stm32f4xx_tim.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST4_PERIPH(TIMx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Set the COM Bit */
    TIMx->CR2 |= TIM_CR2_CCUS;
  }
  else
  {
    /* Reset the COM Bit */
    TIMx->CR2 &= (uint16_t)~TIM_CR2_CCUS;
  }
}
TIM_SelectHallSensor()
void TIM_SelectHallSensor (TIM_TypeDef * TIMx, FunctionalState NewState)
Enables or disables the TIMx's Hall sensor interface.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
NewState new state of the TIMx Hall sensor interface. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 3109 of file stm32f4xx_tim.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Set the TI1S Bit */
    TIMx->CR2 |= TIM_CR2_TI1S;
  }
  else
  {
    /* Reset the TI1S Bit */
    TIMx->CR2 &= (uint16_t)~TIM_CR2_TI1S;
  }
}
TIM_SelectInputTrigger()
void TIM_SelectInputTrigger (TIM_TypeDef * TIMx, uint16_t TIM_InputTriggerSource)
Selects the Input Trigger source.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13 or 14 to select the TIM peripheral.
TIM_InputTriggerSource The Input Trigger source. This parameter can be one of the following values:
TIM_TS_ITR0: Internal Trigger 0
TIM_TS_ITR1: Internal Trigger 1
TIM_TS_ITR2: Internal Trigger 2
TIM_TS_ITR3: Internal Trigger 3
TIM_TS_TI1F_ED: TI1 Edge Detector
TIM_TS_TI1FP1: Filtered Timer Input 1
TIM_TS_TI2FP2: Filtered Timer Input 2
TIM_TS_ETRF: External Trigger input
Return values
None
Definition at line 2879 of file stm32f4xx_tim.c.
Referenced by TIM_ITRxExternalClockConfig(), and TIM_TIxExternalClockConfig().
{
  uint16_t tmpsmcr = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_TRIGGER_SELECTION(TIM_InputTriggerSource));
  /* Get the TIMx SMCR register value */
  tmpsmcr = TIMx->SMCR;
  /* Reset the TS Bits */
  tmpsmcr &= (uint16_t)~TIM_SMCR_TS;
  /* Set the Input Trigger source */
  tmpsmcr |= TIM_InputTriggerSource;
  /* Write to TIMx SMCR */
  TIMx->SMCR = tmpsmcr;
}
TIM_SelectMasterSlaveMode()
void TIM_SelectMasterSlaveMode (TIM_TypeDef * TIMx, uint16_t TIM_MasterSlaveMode)
Sets or Resets the TIMx Master/Slave Mode.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_MasterSlaveMode specifies the Timer Master Slave Mode. This parameter can be one of the following values:
TIM_MasterSlaveMode_Enable: synchronization between the current timer and its slaves (through TRGO)
TIM_MasterSlaveMode_Disable: No action
Return values
None
Definition at line 2969 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_MSM_STATE(TIM_MasterSlaveMode));
  /* Reset the MSM Bit */
  TIMx->SMCR &= (uint16_t)~TIM_SMCR_MSM;
  
  /* Set or Reset the MSM Bit */
  TIMx->SMCR |= TIM_MasterSlaveMode;
}
TIM_SelectOCxM()
void TIM_SelectOCxM (TIM_TypeDef * TIMx, uint16_t TIM_Channel, uint16_t TIM_OCMode)
Selects the TIM Output Compare Mode.
Note
This function disables the selected channel before changing the Output Compare Mode. If needed, user has to enable this channel using TIM_CCxCmd() and TIM_CCxNCmd() functions.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_Channel specifies the TIM Channel This parameter can be one of the following values:
TIM_Channel_1: TIM Channel 1
TIM_Channel_2: TIM Channel 2
TIM_Channel_3: TIM Channel 3
TIM_Channel_4: TIM Channel 4
TIM_OCMode specifies the TIM Output Compare Mode. This parameter can be one of the following values:
TIM_OCMode_Timing
TIM_OCMode_Active
TIM_OCMode_Toggle
TIM_OCMode_PWM1
TIM_OCMode_PWM2
TIM_ForcedAction_Active
TIM_ForcedAction_InActive
Return values
None
Definition at line 1006 of file stm32f4xx_tim.c.
{
  uint32_t tmp = 0;
  uint16_t tmp1 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_CHANNEL(TIM_Channel));
  assert_param(IS_TIM_OCM(TIM_OCMode));
  tmp = (uint32_t) TIMx;
  tmp += CCMR_OFFSET;
  tmp1 = CCER_CCE_SET << (uint16_t)TIM_Channel;
  /* Disable the Channel: Reset the CCxE Bit */
  TIMx->CCER &= (uint16_t) ~tmp1;
  if((TIM_Channel == TIM_Channel_1) ||(TIM_Channel == TIM_Channel_3))
  {
    tmp += (TIM_Channel>>1);
    /* Reset the OCxM bits in the CCMRx register */
    *(__IO uint32_t *) tmp &= CCMR_OC13M_MASK;
   
    /* Configure the OCxM bits in the CCMRx register */
    *(__IO uint32_t *) tmp |= TIM_OCMode;
  }
  else
  {
    tmp += (uint16_t)(TIM_Channel - (uint16_t)4)>> (uint16_t)1;
    /* Reset the OCxM bits in the CCMRx register */
    *(__IO uint32_t *) tmp &= CCMR_OC24M_MASK;
    
    /* Configure the OCxM bits in the CCMRx register */
    *(__IO uint32_t *) tmp |= (uint16_t)(TIM_OCMode << 8);
  }
}
TIM_SelectOnePulseMode()
void TIM_SelectOnePulseMode (TIM_TypeDef * TIMx, uint16_t TIM_OPMode)
Selects the TIMx's One Pulse Mode.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
TIM_OPMode specifies the OPM Mode to be used. This parameter can be one of the following values:
TIM_OPMode_Single
TIM_OPMode_Repetitive
Return values
None
Definition at line 543 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  assert_param(IS_TIM_OPM_MODE(TIM_OPMode));
  /* Reset the OPM Bit */
  TIMx->CR1 &= (uint16_t)~TIM_CR1_OPM;
  /* Configure the OPM Mode */
  TIMx->CR1 |= TIM_OPMode;
}
TIM_SelectOutputTrigger()
void TIM_SelectOutputTrigger (TIM_TypeDef * TIMx, uint16_t TIM_TRGOSource)
Selects the TIMx Trigger Output Mode.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 6, 7 or 8 to select the TIM peripheral.
TIM_TRGOSource specifies the Trigger Output source. This parameter can be one of the following values:
For all TIMx
TIM_TRGOSource_Reset: The UG bit in the TIM_EGR register is used as the trigger output(TRGO)
TIM_TRGOSource_Enable: The Counter Enable CEN is used as the trigger output(TRGO)
TIM_TRGOSource_Update: The update event is selected as the trigger output(TRGO)
For all TIMx except TIM6 and TIM7
TIM_TRGOSource_OC1: The trigger output sends a positive pulse when the CC1IF flag is to be set, as soon as a capture or compare match occurs(TRGO)
TIM_TRGOSource_OC1Ref: OC1REF signal is used as the trigger output(TRGO)
TIM_TRGOSource_OC2Ref: OC2REF signal is used as the trigger output(TRGO)
TIM_TRGOSource_OC3Ref: OC3REF signal is used as the trigger output(TRGO)
TIM_TRGOSource_OC4Ref: OC4REF signal is used as the trigger output(TRGO)
Return values
None
Definition at line 2922 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST5_PERIPH(TIMx));
  assert_param(IS_TIM_TRGO_SOURCE(TIM_TRGOSource));
  /* Reset the MMS Bits */
  TIMx->CR2 &= (uint16_t)~TIM_CR2_MMS;
  /* Select the TRGO source */
  TIMx->CR2 |= TIM_TRGOSource;
}
TIM_SelectSlaveMode()
void TIM_SelectSlaveMode (TIM_TypeDef * TIMx, uint16_t TIM_SlaveMode)
Selects the TIMx Slave Mode.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_SlaveMode specifies the Timer Slave Mode. This parameter can be one of the following values:
TIM_SlaveMode_Reset: Rising edge of the selected trigger signal(TRGI) reinitialize the counter and triggers an update of the registers
TIM_SlaveMode_Gated: The counter clock is enabled when the trigger signal (TRGI) is high
TIM_SlaveMode_Trigger: The counter starts at a rising edge of the trigger TRGI
TIM_SlaveMode_External1: Rising edges of the selected trigger (TRGI) clock the counter
Return values
None
Definition at line 2946 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_SLAVE_MODE(TIM_SlaveMode));
  /* Reset the SMS Bits */
  TIMx->SMCR &= (uint16_t)~TIM_SMCR_SMS;
  /* Select the Slave Mode */
  TIMx->SMCR |= TIM_SlaveMode;
}
TIM_SetAutoreload()
void TIM_SetAutoreload (TIM_TypeDef * TIMx, uint32_t Autoreload)
Sets the TIMx Autoreload Register value.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Autoreload specifies the Autoreload register new value.
Return values
None
Definition at line 418 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  
  /* Set the Autoreload Register value */
  TIMx->ARR = Autoreload;
}
TIM_SetClockDivision()
void TIM_SetClockDivision (TIM_TypeDef * TIMx, uint16_t TIM_CKD)
Sets the TIMx Clock Division value.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_CKD specifies the clock division value. This parameter can be one of the following value:
TIM_CKD_DIV1: TDTS = Tck_tim
TIM_CKD_DIV2: TDTS = 2*Tck_tim
TIM_CKD_DIV4: TDTS = 4*Tck_tim
Return values
None
Definition at line 566 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_CKD_DIV(TIM_CKD));
  /* Reset the CKD Bits */
  TIMx->CR1 &= (uint16_t)(~TIM_CR1_CKD);
  /* Set the CKD value */
  TIMx->CR1 |= TIM_CKD;
}
TIM_SetCompare1()
void TIM_SetCompare1 (TIM_TypeDef * TIMx, uint32_t Compare1)
Sets the TIMx Capture Compare1 Register value.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
Compare1 specifies the Capture Compare1 register new value.
Return values
None
Definition at line 1052 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  /* Set the Capture Compare1 Register value */
  TIMx->CCR1 = Compare1;
}
TIM_SetCompare2()
void TIM_SetCompare2 (TIM_TypeDef * TIMx, uint32_t Compare2)
Sets the TIMx Capture Compare2 Register value.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
Compare2 specifies the Capture Compare2 register new value.
Return values
None
Definition at line 1068 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  /* Set the Capture Compare2 Register value */
  TIMx->CCR2 = Compare2;
}
TIM_SetCompare3()
void TIM_SetCompare3 (TIM_TypeDef * TIMx, uint32_t Compare3)
Sets the TIMx Capture Compare3 Register value.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
Compare3 specifies the Capture Compare3 register new value.
Return values
None
Definition at line 1083 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  /* Set the Capture Compare3 Register value */
  TIMx->CCR3 = Compare3;
}
TIM_SetCompare4()
void TIM_SetCompare4 (TIM_TypeDef * TIMx, uint32_t Compare4)
Sets the TIMx Capture Compare4 Register value.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
Compare4 specifies the Capture Compare4 register new value.
Return values
None
Definition at line 1098 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  /* Set the Capture Compare4 Register value */
  TIMx->CCR4 = Compare4;
}
TIM_SetCounter()
void TIM_SetCounter (TIM_TypeDef * TIMx, uint32_t Counter)
Sets the TIMx Counter Register value.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
Counter specifies the Counter register new value.
Return values
None
Definition at line 403 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
   assert_param(IS_TIM_ALL_PERIPH(TIMx));
  /* Set the Counter Register value */
  TIMx->CNT = Counter;
}
TIM_SetIC1Prescaler()
void TIM_SetIC1Prescaler (TIM_TypeDef * TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 1 prescaler.
Parameters
TIMx where x can be 1 to 14 except 6 and 7, to select the TIM peripheral.
TIM_ICPSC specifies the Input Capture1 prescaler new value. This parameter can be one of the following values:
TIM_ICPSC_DIV1: no prescaler
TIM_ICPSC_DIV2: capture is done once every 2 events
TIM_ICPSC_DIV4: capture is done once every 4 events
TIM_ICPSC_DIV8: capture is done once every 8 events
Return values
None
Definition at line 2085 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit(), and TIM_PWMIConfig().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_IC_PRESCALER(TIM_ICPSC));
  /* Reset the IC1PSC Bits */
  TIMx->CCMR1 &= (uint16_t)~TIM_CCMR1_IC1PSC;
  /* Set the IC1PSC value */
  TIMx->CCMR1 |= TIM_ICPSC;
}
TIM_SetIC2Prescaler()
void TIM_SetIC2Prescaler (TIM_TypeDef * TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 2 prescaler.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_ICPSC specifies the Input Capture2 prescaler new value. This parameter can be one of the following values:
TIM_ICPSC_DIV1: no prescaler
TIM_ICPSC_DIV2: capture is done once every 2 events
TIM_ICPSC_DIV4: capture is done once every 4 events
TIM_ICPSC_DIV8: capture is done once every 8 events
Return values
None
Definition at line 2110 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit(), and TIM_PWMIConfig().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_IC_PRESCALER(TIM_ICPSC));
  /* Reset the IC2PSC Bits */
  TIMx->CCMR1 &= (uint16_t)~TIM_CCMR1_IC2PSC;
  /* Set the IC2PSC value */
  TIMx->CCMR1 |= (uint16_t)(TIM_ICPSC << 8);
}
TIM_SetIC3Prescaler()
void TIM_SetIC3Prescaler (TIM_TypeDef * TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 3 prescaler.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ICPSC specifies the Input Capture3 prescaler new value. This parameter can be one of the following values:
TIM_ICPSC_DIV1: no prescaler
TIM_ICPSC_DIV2: capture is done once every 2 events
TIM_ICPSC_DIV4: capture is done once every 4 events
TIM_ICPSC_DIV8: capture is done once every 8 events
Return values
None
Definition at line 2134 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_IC_PRESCALER(TIM_ICPSC));
  /* Reset the IC3PSC Bits */
  TIMx->CCMR2 &= (uint16_t)~TIM_CCMR2_IC3PSC;
  /* Set the IC3PSC value */
  TIMx->CCMR2 |= TIM_ICPSC;
}
TIM_SetIC4Prescaler()
void TIM_SetIC4Prescaler (TIM_TypeDef * TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 4 prescaler.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ICPSC specifies the Input Capture4 prescaler new value. This parameter can be one of the following values:
TIM_ICPSC_DIV1: no prescaler
TIM_ICPSC_DIV2: capture is done once every 2 events
TIM_ICPSC_DIV4: capture is done once every 4 events
TIM_ICPSC_DIV8: capture is done once every 8 events
Return values
None
Definition at line 2158 of file stm32f4xx_tim.c.
Referenced by TIM_ICInit().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_IC_PRESCALER(TIM_ICPSC));
  /* Reset the IC4PSC Bits */
  TIMx->CCMR2 &= (uint16_t)~TIM_CCMR2_IC4PSC;
  /* Set the IC4PSC value */
  TIMx->CCMR2 |= (uint16_t)(TIM_ICPSC << 8);
}
TIM_TimeBaseInit()
void TIM_TimeBaseInit (TIM_TypeDef * TIMx, TIM_TimeBaseInitTypeDef * TIM_TimeBaseInitStruct)
Initializes the TIMx Time Base Unit peripheral according to the specified parameters in the TIM_TimeBaseInitStruct.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
TIM_TimeBaseInitStruct pointer to a TIM_TimeBaseInitTypeDef structure that contains the configuration information for the specified TIM peripheral.
Return values
None
Definition at line 282 of file stm32f4xx_tim.c.
References TIM_TimeBaseInitTypeDef::TIM_ClockDivision, and TIM_TimeBaseInitTypeDef::TIM_CounterMode.
{
  uint16_t tmpcr1 = 0;
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  assert_param(IS_TIM_COUNTER_MODE(TIM_TimeBaseInitStruct->TIM_CounterMode));
  assert_param(IS_TIM_CKD_DIV(TIM_TimeBaseInitStruct->TIM_ClockDivision));
  tmpcr1 = TIMx->CR1;
  if((TIMx == TIM1) || (TIMx == TIM8)||
     (TIMx == TIM2) || (TIMx == TIM3)||
     (TIMx == TIM4) || (TIMx == TIM5))
  {
    /* Select the Counter Mode */
    tmpcr1 &= (uint16_t)(~(TIM_CR1_DIR | TIM_CR1_CMS));
    tmpcr1 |= (uint32_t)TIM_TimeBaseInitStruct->TIM_CounterMode;
  }
 
  if((TIMx != TIM6) && (TIMx != TIM7))
  {
    /* Set the clock division */
    tmpcr1 &= (uint16_t)(~TIM_CR1_CKD);
    tmpcr1 |= (uint32_t)TIM_TimeBaseInitStruct->TIM_ClockDivision;
  }
  TIMx->CR1 = tmpcr1;
  /* Set the Autoreload value */
  TIMx->ARR = TIM_TimeBaseInitStruct->TIM_Period ;
 
  /* Set the Prescaler value */
  TIMx->PSC = TIM_TimeBaseInitStruct->TIM_Prescaler;
    
  if ((TIMx == TIM1) || (TIMx == TIM8))
  {
    /* Set the Repetition Counter value */
    TIMx->RCR = TIM_TimeBaseInitStruct->TIM_RepetitionCounter;
  }
  /* Generate an update event to reload the Prescaler
     and the repetition counter(only for TIM1 and TIM8) value immediatly */
  TIMx->EGR = TIM_PSCReloadMode_Immediate;
}
TIM_TimeBaseStructInit()
void TIM_TimeBaseStructInit (TIM_TimeBaseInitTypeDef * TIM_TimeBaseInitStruct)
Fills each TIM_TimeBaseInitStruct member with its default value.
Parameters
TIM_TimeBaseInitStruct : pointer to a TIM_TimeBaseInitTypeDef structure which will be initialized.
Return values
None
Definition at line 334 of file stm32f4xx_tim.c.
References TIM_TimeBaseInitTypeDef::TIM_ClockDivision, TIM_TimeBaseInitTypeDef::TIM_CounterMode, TIM_TimeBaseInitTypeDef::TIM_Period, TIM_TimeBaseInitTypeDef::TIM_Prescaler, and TIM_TimeBaseInitTypeDef::TIM_RepetitionCounter.
{
  /* Set the default configuration */
  TIM_TimeBaseInitStruct->TIM_Period = 0xFFFFFFFF;
  TIM_TimeBaseInitStruct->TIM_Prescaler = 0x0000;
  TIM_TimeBaseInitStruct->TIM_ClockDivision = TIM_CKD_DIV1;
  TIM_TimeBaseInitStruct->TIM_CounterMode = TIM_CounterMode_Up;
  TIM_TimeBaseInitStruct->TIM_RepetitionCounter = 0x0000;
}
TIM_TIxExternalClockConfig()
void TIM_TIxExternalClockConfig (TIM_TypeDef * TIMx, uint16_t TIM_TIxExternalCLKSource, uint16_t TIM_ICPolarity, uint16_t ICFilter)
Configures the TIMx Trigger as External Clock.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13 or 14 to select the TIM peripheral.
TIM_TIxExternalCLKSource Trigger source. This parameter can be one of the following values:
TIM_TIxExternalCLK1Source_TI1ED: TI1 Edge Detector
TIM_TIxExternalCLK1Source_TI1: Filtered Timer Input 1
TIM_TIxExternalCLK1Source_TI2: Filtered Timer Input 2
TIM_ICPolarity specifies the TIx Polarity. This parameter can be one of the following values:
TIM_ICPolarity_Rising
TIM_ICPolarity_Falling
ICFilter specifies the filter value. This parameter must be a value between 0x0 and 0xF.
Return values
None
Definition at line 2724 of file stm32f4xx_tim.c.
References TI1_Config(), TI2_Config(), and TIM_SelectInputTrigger().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_IC_POLARITY(TIM_ICPolarity));
  assert_param(IS_TIM_IC_FILTER(ICFilter));
  /* Configure the Timer Input Clock Source */
  if (TIM_TIxExternalCLKSource == TIM_TIxExternalCLK1Source_TI2)
  {
    TI2_Config(TIMx, TIM_ICPolarity, TIM_ICSelection_DirectTI, ICFilter);
  }
  else
  {
    TI1_Config(TIMx, TIM_ICPolarity, TIM_ICSelection_DirectTI, ICFilter);
  }
  /* Select the Trigger source */
  TIM_SelectInputTrigger(TIMx, TIM_TIxExternalCLKSource);
  /* Select the External clock mode1 */
  TIMx->SMCR |= TIM_SlaveMode_External1;
}
TIM_UpdateDisableConfig()
void TIM_UpdateDisableConfig (TIM_TypeDef * TIMx, FunctionalState NewState)
Enables or Disables the TIMx Update event.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
NewState new state of the TIMx UDIS bit This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 462 of file stm32f4xx_tim.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Set the Update Disable Bit */
    TIMx->CR1 |= TIM_CR1_UDIS;
  }
  else
  {
    /* Reset the Update Disable Bit */
    TIMx->CR1 &= (uint16_t)~TIM_CR1_UDIS;
  }
}
TIM_UpdateRequestConfig()
void TIM_UpdateRequestConfig (TIM_TypeDef * TIMx, uint16_t TIM_UpdateSource)
Configures the TIMx Update Request Interrupt source.
Parameters
TIMx where x can be 1 to 14 to select the TIM peripheral.
TIM_UpdateSource specifies the Update source. This parameter can be one of the following values:
TIM_UpdateSource_Global: Source of update is the counter overflow/underflow or the setting of UG bit, or an update generation through the slave mode controller.
TIM_UpdateSource_Regular: Source of update is counter overflow/underflow.
Return values
None
Definition at line 491 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_ALL_PERIPH(TIMx));
  assert_param(IS_TIM_UPDATE_SOURCE(TIM_UpdateSource));
  if (TIM_UpdateSource != TIM_UpdateSource_Global)
  {
    /* Set the URS Bit */
    TIMx->CR1 |= TIM_CR1_URS;
  }
  else
  {
    /* Reset the URS Bit */
    TIMx->CR1 &= (uint16_t)~TIM_CR1_URS;
  }
}