RTC
RTC driver modules.
Modules
 RTC_Exported_Constants
 RTC_Private_Functions
Classes
struct RTC_InitTypeDef
RTC Init structures definition.
struct RTC_TimeTypeDef
RTC Time structure definition.
struct RTC_DateTypeDef
RTC Date structure definition.
struct RTC_AlarmTypeDef
RTC Alarm structure definition.
Macros
#define RTC_TR_RESERVED_MASK ((uint32_t)0x007F7F7F)
#define RTC_DR_RESERVED_MASK ((uint32_t)0x00FFFF3F)
#define RTC_INIT_MASK ((uint32_t)0xFFFFFFFF)
#define RTC_RSF_MASK ((uint32_t)0xFFFFFF5F)
#define RTC_FLAGS_MASK
#define INITMODE_TIMEOUT ((uint32_t) 0x00010000)
#define SYNCHRO_TIMEOUT ((uint32_t) 0x00020000)
#define RECALPF_TIMEOUT ((uint32_t) 0x00020000)
#define SHPF_TIMEOUT ((uint32_t) 0x00001000)
Functions
 ErrorStatus RTC_DeInit (void)
Deinitializes the RTC registers to their default reset values.
 ErrorStatus RTC_Init (RTC_InitTypeDef *RTC_InitStruct)
Initializes the RTC registers according to the specified parameters in RTC_InitStruct.
void RTC_StructInit (RTC_InitTypeDef *RTC_InitStruct)
Fills each RTC_InitStruct member with its default value.
void RTC_WriteProtectionCmd (FunctionalState NewState)
Enables or disables the RTC registers write protection.
 ErrorStatus RTC_EnterInitMode (void)
Enters the RTC Initialization mode.
void RTC_ExitInitMode (void)
Exits the RTC Initialization mode.
 ErrorStatus RTC_WaitForSynchro (void)
Waits until the RTC Time and Date registers (RTC_TR and RTC_DR) are synchronized with RTC APB clock.
 ErrorStatus RTC_RefClockCmd (FunctionalState NewState)
Enables or disables the RTC reference clock detection.
void RTC_BypassShadowCmd (FunctionalState NewState)
Enables or Disables the Bypass Shadow feature.
 ErrorStatus RTC_SetTime (uint32_t RTC_Format, RTC_TimeTypeDef *RTC_TimeStruct)
Set the RTC current time.
void RTC_TimeStructInit (RTC_TimeTypeDef *RTC_TimeStruct)
Fills each RTC_TimeStruct member with its default value (Time = 00h:00min:00sec).
void RTC_GetTime (uint32_t RTC_Format, RTC_TimeTypeDef *RTC_TimeStruct)
Get the RTC current Time.
uint32_t RTC_GetSubSecond (void)
Gets the RTC current Calendar Subseconds value.
 ErrorStatus RTC_SetDate (uint32_t RTC_Format, RTC_DateTypeDef *RTC_DateStruct)
Set the RTC current date.
void RTC_DateStructInit (RTC_DateTypeDef *RTC_DateStruct)
Fills each RTC_DateStruct member with its default value (Monday, January 01 xx00).
void RTC_GetDate (uint32_t RTC_Format, RTC_DateTypeDef *RTC_DateStruct)
Get the RTC current date.
void RTC_SetAlarm (uint32_t RTC_Format, uint32_t RTC_Alarm, RTC_AlarmTypeDef *RTC_AlarmStruct)
Set the specified RTC Alarm.
void RTC_AlarmStructInit (RTC_AlarmTypeDef *RTC_AlarmStruct)
Fills each RTC_AlarmStruct member with its default value (Time = 00h:00mn:00sec / Date = 1st day of the month/Mask = all fields are masked).
void RTC_GetAlarm (uint32_t RTC_Format, uint32_t RTC_Alarm, RTC_AlarmTypeDef *RTC_AlarmStruct)
Get the RTC Alarm value and masks.
 ErrorStatus RTC_AlarmCmd (uint32_t RTC_Alarm, FunctionalState NewState)
Enables or disables the specified RTC Alarm.
void RTC_AlarmSubSecondConfig (uint32_t RTC_Alarm, uint32_t RTC_AlarmSubSecondValue, uint32_t RTC_AlarmSubSecondMask)
Configure the RTC AlarmA/B Subseconds value and mask.*.
uint32_t RTC_GetAlarmSubSecond (uint32_t RTC_Alarm)
Gets the RTC Alarm Subseconds value.
void RTC_WakeUpClockConfig (uint32_t RTC_WakeUpClock)
Configures the RTC Wakeup clock source.
void RTC_SetWakeUpCounter (uint32_t RTC_WakeUpCounter)
Configures the RTC Wakeup counter.
uint32_t RTC_GetWakeUpCounter (void)
Returns the RTC WakeUp timer counter value.
 ErrorStatus RTC_WakeUpCmd (FunctionalState NewState)
Enables or Disables the RTC WakeUp timer.
void RTC_DayLightSavingConfig (uint32_t RTC_DayLightSaving, uint32_t RTC_StoreOperation)
Adds or substract one hour from the current time.
uint32_t RTC_GetStoreOperation (void)
Returns the RTC Day Light Saving stored operation.
void RTC_OutputConfig (uint32_t RTC_Output, uint32_t RTC_OutputPolarity)
Configures the RTC output source (AFO_ALARM).
 ErrorStatus RTC_CoarseCalibConfig (uint32_t RTC_CalibSign, uint32_t Value)
Configures the Coarse calibration parameters.
 ErrorStatus RTC_CoarseCalibCmd (FunctionalState NewState)
Enables or disables the Coarse calibration process.
void RTC_CalibOutputCmd (FunctionalState NewState)
Enables or disables the RTC clock to be output through the relative pin.
void RTC_CalibOutputConfig (uint32_t RTC_CalibOutput)
Configure the Calibration Pinout (RTC_CALIB) Selection (1Hz or 512Hz).
 ErrorStatus RTC_SmoothCalibConfig (uint32_t RTC_SmoothCalibPeriod, uint32_t RTC_SmoothCalibPlusPulses, uint32_t RTC_SmouthCalibMinusPulsesValue)
Configures the Smooth Calibration Settings.
void RTC_TimeStampCmd (uint32_t RTC_TimeStampEdge, FunctionalState NewState)
Enables or Disables the RTC TimeStamp functionality with the specified time stamp pin stimulating edge.
void RTC_GetTimeStamp (uint32_t RTC_Format, RTC_TimeTypeDef *RTC_StampTimeStruct, RTC_DateTypeDef *RTC_StampDateStruct)
Get the RTC TimeStamp value and masks.
uint32_t RTC_GetTimeStampSubSecond (void)
Get the RTC timestamp Subseconds value.
void RTC_TamperTriggerConfig (uint32_t RTC_Tamper, uint32_t RTC_TamperTrigger)
Configures the select Tamper pin edge.
void RTC_TamperCmd (uint32_t RTC_Tamper, FunctionalState NewState)
Enables or Disables the Tamper detection.
void RTC_TamperFilterConfig (uint32_t RTC_TamperFilter)
Configures the Tampers Filter.
void RTC_TamperSamplingFreqConfig (uint32_t RTC_TamperSamplingFreq)
Configures the Tampers Sampling Frequency.
void RTC_TamperPinsPrechargeDuration (uint32_t RTC_TamperPrechargeDuration)
Configures the Tampers Pins input Precharge Duration.
void RTC_TimeStampOnTamperDetectionCmd (FunctionalState NewState)
Enables or Disables the TimeStamp on Tamper Detection Event.
void RTC_TamperPullUpCmd (FunctionalState NewState)
Enables or Disables the Precharge of Tamper pin.
void RTC_WriteBackupRegister (uint32_t RTC_BKP_DR, uint32_t Data)
Writes a data in a specified RTC Backup data register.
uint32_t RTC_ReadBackupRegister (uint32_t RTC_BKP_DR)
Reads data from the specified RTC Backup data Register.
void RTC_TamperPinSelection (uint32_t RTC_TamperPin)
Selects the RTC Tamper Pin.
void RTC_TimeStampPinSelection (uint32_t RTC_TimeStampPin)
Selects the RTC TimeStamp Pin.
void RTC_OutputTypeConfig (uint32_t RTC_OutputType)
Configures the RTC Output Pin mode.
 ErrorStatus RTC_SynchroShiftConfig (uint32_t RTC_ShiftAdd1S, uint32_t RTC_ShiftSubFS)
Configures the Synchronization Shift Control Settings.
void RTC_ITConfig (uint32_t RTC_IT, FunctionalState NewState)
Enables or disables the specified RTC interrupts.
 FlagStatus RTC_GetFlagStatus (uint32_t RTC_FLAG)
Checks whether the specified RTC flag is set or not.
void RTC_ClearFlag (uint32_t RTC_FLAG)
Clears the RTC's pending flags.
 ITStatus RTC_GetITStatus (uint32_t RTC_IT)
Checks whether the specified RTC interrupt has occurred or not.
void RTC_ClearITPendingBit (uint32_t RTC_IT)
Clears the RTC's interrupt pending bits.
Detailed Description
RTC driver modules.
Macro Definition Documentation
INITMODE_TIMEOUT
#define INITMODE_TIMEOUT ((uint32_t) 0x00010000)
Definition at line 302 of file stm32f4xx_rtc.c.
RECALPF_TIMEOUT
#define RECALPF_TIMEOUT ((uint32_t) 0x00020000)
Definition at line 304 of file stm32f4xx_rtc.c.
RTC_DR_RESERVED_MASK
#define RTC_DR_RESERVED_MASK ((uint32_t)0x00FFFF3F)
Definition at line 294 of file stm32f4xx_rtc.c.
RTC_FLAGS_MASK
#define RTC_FLAGS_MASK
Value:
((uint32_t)(RTC_FLAG_TSOVF | RTC_FLAG_TSF | RTC_FLAG_WUTF | \
                                            RTC_FLAG_ALRBF | RTC_FLAG_ALRAF |
      RTC_FLAG_INITF | \
                                            RTC_FLAG_RSF | RTC_FLAG_INITS |
      RTC_FLAG_WUTWF | \
                                            RTC_FLAG_ALRBWF | RTC_FLAG_ALRAWF |
      RTC_FLAG_TAMP1F))
Definition at line 297 of file stm32f4xx_rtc.c.
RTC_INIT_MASK
#define RTC_INIT_MASK ((uint32_t)0xFFFFFFFF)
Definition at line 295 of file stm32f4xx_rtc.c.
RTC_RSF_MASK
#define RTC_RSF_MASK ((uint32_t)0xFFFFFF5F)
Definition at line 296 of file stm32f4xx_rtc.c.
RTC_TR_RESERVED_MASK
#define RTC_TR_RESERVED_MASK ((uint32_t)0x007F7F7F)
Definition at line 293 of file stm32f4xx_rtc.c.
SHPF_TIMEOUT
#define SHPF_TIMEOUT ((uint32_t) 0x00001000)
Definition at line 305 of file stm32f4xx_rtc.c.
SYNCHRO_TIMEOUT
#define SYNCHRO_TIMEOUT ((uint32_t) 0x00020000)
Definition at line 303 of file stm32f4xx_rtc.c.
Function Documentation
RTC_AlarmCmd()
 ErrorStatus RTC_AlarmCmd (uint32_t RTC_Alarm, FunctionalState NewState)
Enables or disables the specified RTC Alarm.
Parameters
RTC_Alarm specifies the alarm to be configured. This parameter can be any combination of the following values:
RTC_Alarm_A: to select Alarm A
RTC_Alarm_B: to select Alarm B
NewState new state of the specified alarm. This parameter can be: ENABLE or DISABLE.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC Alarm is enabled/disabled
ERROR: RTC Alarm is not enabled/disabled
Definition at line 1283 of file stm32f4xx_rtc.c.
References DISABLE, ERROR, and SUCCESS.
{
  __IO uint32_t alarmcounter = 0x00;
  uint32_t alarmstatus = 0x00;
  ErrorStatus status = ERROR;
    
  /* Check the parameters */
  assert_param(IS_RTC_CMD_ALARM(RTC_Alarm));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Configure the Alarm state */
  if (NewState != DISABLE)
  {
    RTC->CR |= (uint32_t)RTC_Alarm;
    status = SUCCESS;
  }
  else
  {
    /* Disable the Alarm in RTC_CR register */
    RTC->CR &= (uint32_t)~RTC_Alarm;
   
    /* Wait till RTC ALRxWF flag is set and if Time out is reached exit */
    do
    {
      alarmstatus = RTC->ISR & (RTC_Alarm >> 8);
      alarmcounter++;
    } while((alarmcounter != INITMODE_TIMEOUT) && (alarmstatus == 0x00));
    
    if ((RTC->ISR & (RTC_Alarm >> 8)) == RESET)
    {
      status = ERROR;
    }
    else
    {
      status = SUCCESS;
    }
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_AlarmStructInit()
void RTC_AlarmStructInit (RTC_AlarmTypeDef * RTC_AlarmStruct)
Fills each RTC_AlarmStruct member with its default value (Time = 00h:00mn:00sec / Date = 1st day of the month/Mask = all fields are masked).
Parameters
RTC_AlarmStruct pointer to a RTC_AlarmTypeDef structure which will be initialized.
Return values
None
Definition at line 1199 of file stm32f4xx_rtc.c.
References RTC_AlarmTypeDef::RTC_AlarmDateWeekDay, RTC_AlarmTypeDef::RTC_AlarmDateWeekDaySel, RTC_AlarmTypeDef::RTC_AlarmMask, RTC_AlarmTypeDef::RTC_AlarmTime, RTC_TimeTypeDef::RTC_H12, RTC_TimeTypeDef::RTC_Hours, RTC_TimeTypeDef::RTC_Minutes, and RTC_TimeTypeDef::RTC_Seconds.
{
  /* Alarm Time Settings : Time = 00h:00mn:00sec */
  RTC_AlarmStruct->RTC_AlarmTime.RTC_H12 = RTC_H12_AM;
  RTC_AlarmStruct->RTC_AlarmTime.RTC_Hours = 0;
  RTC_AlarmStruct->RTC_AlarmTime.RTC_Minutes = 0;
  RTC_AlarmStruct->RTC_AlarmTime.RTC_Seconds = 0;
  /* Alarm Date Settings : Date = 1st day of the month */
  RTC_AlarmStruct->RTC_AlarmDateWeekDaySel = RTC_AlarmDateWeekDaySel_Date;
  RTC_AlarmStruct->RTC_AlarmDateWeekDay = 1;
  /* Alarm Masks Settings : Mask = all fields are not masked */
  RTC_AlarmStruct->RTC_AlarmMask = RTC_AlarmMask_None;
}
RTC_AlarmSubSecondConfig()
void RTC_AlarmSubSecondConfig (uint32_t RTC_Alarm, uint32_t RTC_AlarmSubSecondValue, uint32_t RTC_AlarmSubSecondMask)
Configure the RTC AlarmA/B Subseconds value and mask.*.
Note
This function is performed only when the Alarm is disabled.
Parameters
RTC_Alarm specifies the alarm to be configured. This parameter can be one of the following values:
RTC_Alarm_A: to select Alarm A
RTC_Alarm_B: to select Alarm B
RTC_AlarmSubSecondValue specifies the Subseconds value. This parameter can be a value from 0 to 0x00007FFF.
RTC_AlarmSubSecondMask specifies the Subseconds Mask. This parameter can be any combination of the following values:
RTC_AlarmSubSecondMask_All : All Alarm SS fields are masked. There is no comparison on sub seconds for Alarm.
RTC_AlarmSubSecondMask_SS14_1 : SS[14:1] are don't care in Alarm comparison. Only SS[0] is compared
RTC_AlarmSubSecondMask_SS14_2 : SS[14:2] are don't care in Alarm comparison. Only SS[1:0] are compared
RTC_AlarmSubSecondMask_SS14_3 : SS[14:3] are don't care in Alarm comparison. Only SS[2:0] are compared
RTC_AlarmSubSecondMask_SS14_4 : SS[14:4] are don't care in Alarm comparison. Only SS[3:0] are compared
RTC_AlarmSubSecondMask_SS14_5 : SS[14:5] are don't care in Alarm comparison. Only SS[4:0] are compared
RTC_AlarmSubSecondMask_SS14_6 : SS[14:6] are don't care in Alarm comparison. Only SS[5:0] are compared
RTC_AlarmSubSecondMask_SS14_7 : SS[14:7] are don't care in Alarm comparison. Only SS[6:0] are compared
RTC_AlarmSubSecondMask_SS14_8 : SS[14:8] are don't care in Alarm comparison. Only SS[7:0] are compared
RTC_AlarmSubSecondMask_SS14_9 : SS[14:9] are don't care in Alarm comparison. Only SS[8:0] are compared
RTC_AlarmSubSecondMask_SS14_10: SS[14:10] are don't care in Alarm comparison. Only SS[9:0] are compared
RTC_AlarmSubSecondMask_SS14_11: SS[14:11] are don't care in Alarm comparison. Only SS[10:0] are compared
RTC_AlarmSubSecondMask_SS14_12: SS[14:12] are don't care in Alarm comparison. Only SS[11:0] are compared
RTC_AlarmSubSecondMask_SS14_13: SS[14:13] are don't care in Alarm comparison. Only SS[12:0] are compared
RTC_AlarmSubSecondMask_SS14 : SS[14] is don't care in Alarm comparison. Only SS[13:0] are compared
RTC_AlarmSubSecondMask_None : SS[14:0] are compared and must match to activate alarm
Return values
None
Definition at line 1377 of file stm32f4xx_rtc.c.
{
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_RTC_ALARM(RTC_Alarm));
  assert_param(IS_RTC_ALARM_SUB_SECOND_VALUE(RTC_AlarmSubSecondValue));
  assert_param(IS_RTC_ALARM_SUB_SECOND_MASK(RTC_AlarmSubSecondMask));
  
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  /* Configure the Alarm A or Alarm B SubSecond registers */
  tmpreg = (uint32_t) (uint32_t)(RTC_AlarmSubSecondValue) | (uint32_t)(RTC_AlarmSubSecondMask);
  
  if (RTC_Alarm == RTC_Alarm_A)
  {
    /* Configure the AlarmA SubSecond register */
    RTC->ALRMASSR = tmpreg;
  }
  else
  {
    /* Configure the Alarm B SubSecond register */
    RTC->ALRMBSSR = tmpreg;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_BypassShadowCmd()
void RTC_BypassShadowCmd (FunctionalState NewState)
Enables or Disables the Bypass Shadow feature.
Note
When the Bypass Shadow is enabled the calendar value are taken directly from the Calendar counter.
Parameters
NewState new state of the Bypass Shadow feature. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 698 of file stm32f4xx_rtc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  if (NewState != DISABLE)
  {
    /* Set the BYPSHAD bit */
    RTC->CR |= (uint8_t)RTC_CR_BYPSHAD;
  }
  else
  {
    /* Reset the BYPSHAD bit */
    RTC->CR &= (uint8_t)~RTC_CR_BYPSHAD;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_CalibOutputCmd()
void RTC_CalibOutputCmd (FunctionalState NewState)
Enables or disables the RTC clock to be output through the relative pin.
Parameters
NewState new state of the digital calibration Output. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1811 of file stm32f4xx_rtc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  if (NewState != DISABLE)
  {
    /* Enable the RTC clock output */
    RTC->CR |= (uint32_t)RTC_CR_COE;
  }
  else
  {
    /* Disable the RTC clock output */
    RTC->CR &= (uint32_t)~RTC_CR_COE;
  }
  
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_CalibOutputConfig()
void RTC_CalibOutputConfig (uint32_t RTC_CalibOutput)
Configure the Calibration Pinout (RTC_CALIB) Selection (1Hz or 512Hz).
Parameters
RTC_CalibOutput : Select the Calibration output Selection . This parameter can be one of the following values:
RTC_CalibOutput_512Hz: A signal has a regular waveform at 512Hz.
RTC_CalibOutput_1Hz : A signal has a regular waveform at 1Hz.
Return values
None
Definition at line 1843 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_CALIB_OUTPUT(RTC_CalibOutput));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  /*clear flags before config*/
  RTC->CR &= (uint32_t)~(RTC_CR_COSEL);
  /* Configure the RTC_CR register */
  RTC->CR |= (uint32_t)RTC_CalibOutput;
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_ClearFlag()
void RTC_ClearFlag (uint32_t RTC_FLAG)
Clears the RTC's pending flags.
Parameters
RTC_FLAG specifies the RTC flag to clear. This parameter can be any combination of the following values:
RTC_FLAG_TAMP1F: Tamper 1 event flag
RTC_FLAG_TSOVF: Time Stamp Overflow flag
RTC_FLAG_TSF: Time Stamp event flag
RTC_FLAG_WUTF: WakeUp Timer flag
RTC_FLAG_ALRBF: Alarm B flag
RTC_FLAG_ALRAF: Alarm A flag
RTC_FLAG_RSF: Registers Synchronized flag
Return values
None
Definition at line 2612 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_CLEAR_FLAG(RTC_FLAG));
  /* Clear the Flags in the RTC_ISR register */
  RTC->ISR = (uint32_t)((uint32_t)(~((RTC_FLAG | RTC_ISR_INIT)& 0x0000FFFF) | (uint32_t)(
      RTC->ISR & RTC_ISR_INIT)));
}
RTC_ClearITPendingBit()
void RTC_ClearITPendingBit (uint32_t RTC_IT)
Clears the RTC's interrupt pending bits.
Parameters
RTC_IT specifies the RTC interrupt pending bit to clear. This parameter can be any combination of the following values:
RTC_IT_TS: Time Stamp interrupt
RTC_IT_WUT: WakeUp Timer interrupt
RTC_IT_ALRB: Alarm B interrupt
RTC_IT_ALRA: Alarm A interrupt
RTC_IT_TAMP1: Tamper 1 event interrupt
Return values
None
Definition at line 2672 of file stm32f4xx_rtc.c.
{
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_RTC_CLEAR_IT(RTC_IT));
  /* Get the RTC_ISR Interrupt pending bits mask */
  tmpreg = (uint32_t)(RTC_IT >> 4);
  /* Clear the interrupt pending bits in the RTC_ISR register */
  RTC->ISR = (uint32_t)((uint32_t)(~((tmpreg | RTC_ISR_INIT)& 0x0000FFFF) | (uint32_t)(
      RTC->ISR & RTC_ISR_INIT)));
}
RTC_CoarseCalibCmd()
 ErrorStatus RTC_CoarseCalibCmd (FunctionalState NewState)
Enables or disables the Coarse calibration process.
Parameters
NewState new state of the Coarse calibration. This parameter can be: ENABLE or DISABLE.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC Coarse calibration are enabled/disabled
ERROR: RTC Coarse calibration are not enabled/disabled
Definition at line 1765 of file stm32f4xx_rtc.c.
References DISABLE, ERROR, RTC_EnterInitMode(), RTC_ExitInitMode(), and SUCCESS.
{
  ErrorStatus status = ERROR;
  
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    if (NewState != DISABLE)
    {
      /* Enable the Coarse Calibration */
      RTC->CR |= (uint32_t)RTC_CR_DCE;
    }
    else
    {
      /* Disable the Coarse Calibration */
      RTC->CR &= (uint32_t)~RTC_CR_DCE;
    }
    /* Exit Initialization mode */
    RTC_ExitInitMode();
    
    status = SUCCESS;
  }
  
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_CoarseCalibConfig()
 ErrorStatus RTC_CoarseCalibConfig (uint32_t RTC_CalibSign, uint32_t Value)
Configures the Coarse calibration parameters.
Parameters
RTC_CalibSign specifies the sign of the coarse calibration value. This parameter can be one of the following values:
RTC_CalibSign_Positive: The value sign is positive
RTC_CalibSign_Negative: The value sign is negative
Value value of coarse calibration expressed in ppm (coded on 5 bits).
Note
This Calibration value should be between 0 and 63 when using negative sign with a 2-ppm step.
This Calibration value should be between 0 and 126 when using positive sign with a 4-ppm step.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC Coarse calibration are initialized
ERROR: RTC Coarse calibration are not initialized
Definition at line 1724 of file stm32f4xx_rtc.c.
References ERROR, RTC_EnterInitMode(), RTC_ExitInitMode(), and SUCCESS.
{
  ErrorStatus status = ERROR;
   
  /* Check the parameters */
  assert_param(IS_RTC_CALIB_SIGN(RTC_CalibSign));
  assert_param(IS_RTC_CALIB_VALUE(Value));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    /* Set the coarse calibration value */
    RTC->CALIBR = (uint32_t)(RTC_CalibSign | Value);
    /* Exit Initialization mode */
    RTC_ExitInitMode();
    
    status = SUCCESS;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_DateStructInit()
void RTC_DateStructInit (RTC_DateTypeDef * RTC_DateStruct)
Fills each RTC_DateStruct member with its default value (Monday, January 01 xx00).
Parameters
RTC_DateStruct pointer to a RTC_DateTypeDef structure which will be initialized.
Return values
None
Definition at line 1009 of file stm32f4xx_rtc.c.
References RTC_DateTypeDef::RTC_Date, RTC_DateTypeDef::RTC_Month, RTC_DateTypeDef::RTC_WeekDay, and RTC_DateTypeDef::RTC_Year.
{
  /* Monday, January 01 xx00 */
  RTC_DateStruct->RTC_WeekDay = RTC_Weekday_Monday;
  RTC_DateStruct->RTC_Date = 1;
  RTC_DateStruct->RTC_Month = RTC_Month_January;
  RTC_DateStruct->RTC_Year = 0;
}
RTC_DayLightSavingConfig()
void RTC_DayLightSavingConfig (uint32_t RTC_DayLightSaving, uint32_t RTC_StoreOperation)
Adds or substract one hour from the current time.
Parameters
RTC_DayLightSaveOperation the value of hour adjustment. This parameter can be one of the following values:
RTC_DayLightSaving_SUB1H: Substract one hour (winter time)
RTC_DayLightSaving_ADD1H: Add one hour (summer time)
RTC_StoreOperation Specifies the value to be written in the BCK bit in CR register to store the operation. This parameter can be one of the following values:
RTC_StoreOperation_Reset: BCK Bit Reset
RTC_StoreOperation_Set: BCK Bit Set
Return values
None
Definition at line 1604 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_DAYLIGHT_SAVING(RTC_DayLightSaving));
  assert_param(IS_RTC_STORE_OPERATION(RTC_StoreOperation));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Clear the bits to be configured */
  RTC->CR &= (uint32_t)~(RTC_CR_BCK);
  /* Configure the RTC_CR register */
  RTC->CR |= (uint32_t)(RTC_DayLightSaving | RTC_StoreOperation);
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_DeInit()
 ErrorStatus RTC_DeInit (void)
Deinitializes the RTC registers to their default reset values.
Note
This function doesn't reset the RTC Clock source and RTC Backup Data registers.
Parameters
None
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC registers are deinitialized
ERROR: RTC registers are not deinitialized
Definition at line 367 of file stm32f4xx_rtc.c.
References ERROR, and RTC_EnterInitMode().
{
  __IO uint32_t wutcounter = 0x00;
  uint32_t wutwfstatus = 0x00;
  ErrorStatus status = ERROR;
  
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    /* Reset TR, DR and CR registers */
    RTC->TR = (uint32_t)0x00000000;
    RTC->DR = (uint32_t)0x00002101;
    /* Reset All CR bits except CR[2:0] */
    RTC->CR &= (uint32_t)0x00000007;
  
    /* Wait till RTC WUTWF flag is set and if Time out is reached exit */
    do
    {
      wutwfstatus = RTC->ISR & RTC_ISR_WUTWF;
      wutcounter++;
    } while((wutcounter != INITMODE_TIMEOUT) && (wutwfstatus == 0x00));
    
    if ((RTC->ISR & RTC_ISR_WUTWF) == RESET)
    {
      status = ERROR;
    }
    else
    {
      /* Reset all RTC CR register bits */
      RTC->CR &= (uint32_t)0x00000000;
      RTC->WUTR = (uint32_t)0x0000FFFF;
      RTC->PRER = (uint32_t)0x007F00FF;
      RTC->CALIBR = (uint32_t)0x00000000;
      RTC->ALRMAR = (uint32_t)0x00000000;
      RTC->ALRMBR = (uint32_t)0x00000000;
      
      /* Reset ISR register and exit initialization mode */
      RTC->ISR = (uint32_t)0x00000000;
      
      /* Reset Tamper and alternate functions configuration register */
      RTC->TAFCR = 0x00000000;
  
      if(RTC_WaitForSynchro() == ERROR)
      {
        status = ERROR;
      }
      else
      {
        status = SUCCESS;
      }
    }
  }
  
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_EnterInitMode()
 ErrorStatus RTC_EnterInitMode (void)
Enters the RTC Initialization mode.
Note
The RTC Initialization mode is write protected, use the RTC_WriteProtectionCmd(DISABLE) before calling this function.
Parameters
None
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC is in Init mode
ERROR: RTC is not in Init mode
Definition at line 540 of file stm32f4xx_rtc.c.
References ERROR.
Referenced by RTC_CoarseCalibCmd(), RTC_CoarseCalibConfig(), RTC_DeInit(), RTC_Init(), RTC_RefClockCmd(), RTC_SetDate(), and RTC_SetTime().
{
  __IO uint32_t initcounter = 0x00;
  ErrorStatus status = ERROR;
  uint32_t initstatus = 0x00;
     
  /* Check if the Initialization mode is set */
  if ((RTC->ISR & RTC_ISR_INITF) == (uint32_t)RESET)
  {
    /* Set the Initialization mode */
    RTC->ISR = (uint32_t)RTC_INIT_MASK;
    
    /* Wait till RTC is in INIT state and if Time out is reached exit */
    do
    {
      initstatus = RTC->ISR & RTC_ISR_INITF;
      initcounter++;
    } while((initcounter != INITMODE_TIMEOUT) && (initstatus == 0x00));
    
    if ((RTC->ISR & RTC_ISR_INITF) != RESET)
    {
      status = SUCCESS;
    }
    else
    {
      status = ERROR;
    }
  }
  else
  {
    status = SUCCESS;
  }
    
  return (status);
}
RTC_ExitInitMode()
void RTC_ExitInitMode (void)
Exits the RTC Initialization mode.
Note
When the initialization sequence is complete, the calendar restarts counting after 4 RTCCLK cycles.
The RTC Initialization mode is write protected, use the RTC_WriteProtectionCmd(DISABLE) before calling this function.
Parameters
None
Return values
None
Definition at line 585 of file stm32f4xx_rtc.c.
Referenced by RTC_CoarseCalibCmd(), RTC_CoarseCalibConfig(), RTC_Init(), RTC_RefClockCmd(), RTC_SetDate(), and RTC_SetTime().
{
  /* Exit Initialization mode */
  RTC->ISR &= (uint32_t)~RTC_ISR_INIT;
}
RTC_GetAlarm()
void RTC_GetAlarm (uint32_t RTC_Format, uint32_t RTC_Alarm, RTC_AlarmTypeDef * RTC_AlarmStruct)
Get the RTC Alarm value and masks.
Parameters
RTC_Format specifies the format of the output parameters. This parameter can be one of the following values:
RTC_Format_BIN: Binary data format
RTC_Format_BCD: BCD data format
RTC_Alarm specifies the alarm to be read. This parameter can be one of the following values:
RTC_Alarm_A: to select Alarm A
RTC_Alarm_B: to select Alarm B
RTC_AlarmStruct pointer to a RTC_AlarmTypeDef structure that will contains the output alarm configuration values.
Return values
None
Definition at line 1229 of file stm32f4xx_rtc.c.
References RTC_AlarmTypeDef::RTC_AlarmDateWeekDay, RTC_AlarmTypeDef::RTC_AlarmDateWeekDaySel, RTC_AlarmTypeDef::RTC_AlarmMask, RTC_AlarmTypeDef::RTC_AlarmTime, RTC_Bcd2ToByte(), RTC_TimeTypeDef::RTC_H12, RTC_TimeTypeDef::RTC_Hours, RTC_TimeTypeDef::RTC_Minutes, and RTC_TimeTypeDef::RTC_Seconds.
{
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_RTC_FORMAT(RTC_Format));
  assert_param(IS_RTC_ALARM(RTC_Alarm));
  /* Get the RTC_ALRMxR register */
  if (RTC_Alarm == RTC_Alarm_A)
  {
    tmpreg = (uint32_t)(RTC->ALRMAR);
  }
  else
  {
    tmpreg = (uint32_t)(RTC->ALRMBR);
  }
  /* Fill the structure with the read parameters */
  RTC_AlarmStruct->RTC_AlarmTime.RTC_Hours = (uint32_t)((tmpreg & (RTC_ALRMAR_HT | \
                                                     RTC_ALRMAR_HU)) >> 16);
  RTC_AlarmStruct->RTC_AlarmTime.RTC_Minutes = (uint32_t)((tmpreg & (
      RTC_ALRMAR_MNT | \
                                                     RTC_ALRMAR_MNU)) >> 8);
  RTC_AlarmStruct->RTC_AlarmTime.RTC_Seconds = (uint32_t)(tmpreg & (
      RTC_ALRMAR_ST | \
                                                     RTC_ALRMAR_SU));
  RTC_AlarmStruct->RTC_AlarmTime.RTC_H12 = (uint32_t)((tmpreg & RTC_ALRMAR_PM) >> 16);
  RTC_AlarmStruct->RTC_AlarmDateWeekDay = (uint32_t)((tmpreg & (RTC_ALRMAR_DT |
      RTC_ALRMAR_DU)) >> 24);
  RTC_AlarmStruct->RTC_AlarmDateWeekDaySel = (uint32_t)(tmpreg &
      RTC_ALRMAR_WDSEL);
  RTC_AlarmStruct->RTC_AlarmMask = (uint32_t)(tmpreg & RTC_AlarmMask_All);
  if (RTC_Format == RTC_Format_BIN)
  {
    RTC_AlarmStruct->RTC_AlarmTime.RTC_Hours = RTC_Bcd2ToByte(RTC_AlarmStruct-> \
                                                        RTC_AlarmTime.RTC_Hours);
    RTC_AlarmStruct->RTC_AlarmTime.RTC_Minutes = RTC_Bcd2ToByte(RTC_AlarmStruct-> \
                                                        RTC_AlarmTime.RTC_Minutes);
    RTC_AlarmStruct->RTC_AlarmTime.RTC_Seconds = RTC_Bcd2ToByte(RTC_AlarmStruct-> \
                                                        RTC_AlarmTime.RTC_Seconds);
    RTC_AlarmStruct->RTC_AlarmDateWeekDay = RTC_Bcd2ToByte(RTC_AlarmStruct->
      RTC_AlarmDateWeekDay);
  }
}
RTC_GetAlarmSubSecond()
uint32_t RTC_GetAlarmSubSecond (uint32_t RTC_Alarm)
Gets the RTC Alarm Subseconds value.
Parameters
RTC_Alarm specifies the alarm to be read. This parameter can be one of the following values:
RTC_Alarm_A: to select Alarm A
RTC_Alarm_B: to select Alarm B
None
Return values
RTC Alarm Subseconds value.
Definition at line 1418 of file stm32f4xx_rtc.c.
{
  uint32_t tmpreg = 0;
  
  /* Get the RTC_ALRMxR register */
  if (RTC_Alarm == RTC_Alarm_A)
  {
    tmpreg = (uint32_t)((RTC->ALRMASSR) & RTC_ALRMASSR_SS);
  }
  else
  {
    tmpreg = (uint32_t)((RTC->ALRMBSSR) & RTC_ALRMBSSR_SS);
  }
  
  return (tmpreg);
}
RTC_GetDate()
void RTC_GetDate (uint32_t RTC_Format, RTC_DateTypeDef * RTC_DateStruct)
Get the RTC current date.
Parameters
RTC_Format specifies the format of the returned parameters. This parameter can be one of the following values:
RTC_Format_BIN: Binary data format
RTC_Format_BCD: BCD data format
RTC_DateStruct pointer to a RTC_DateTypeDef structure that will contain the returned current date configuration.
Return values
None
Definition at line 1028 of file stm32f4xx_rtc.c.
References RTC_Bcd2ToByte(), RTC_DateTypeDef::RTC_Date, RTC_DateTypeDef::RTC_Month, RTC_DateTypeDef::RTC_WeekDay, and RTC_DateTypeDef::RTC_Year.
{
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_RTC_FORMAT(RTC_Format));
  
  /* Get the RTC_TR register */
  tmpreg = (uint32_t)(RTC->DR & RTC_DR_RESERVED_MASK);
  /* Fill the structure fields with the read parameters */
  RTC_DateStruct->RTC_Year = (uint8_t)((tmpreg & (RTC_DR_YT | RTC_DR_YU)) >> 16);
  RTC_DateStruct->RTC_Month = (uint8_t)((tmpreg & (RTC_DR_MT | RTC_DR_MU)) >> 8);
  RTC_DateStruct->RTC_Date = (uint8_t)(tmpreg & (RTC_DR_DT | RTC_DR_DU));
  RTC_DateStruct->RTC_WeekDay = (uint8_t)((tmpreg & (RTC_DR_WDU)) >> 13);
  /* Check the input parameters format */
  if (RTC_Format == RTC_Format_BIN)
  {
    /* Convert the structure parameters to Binary format */
    RTC_DateStruct->RTC_Year = (uint8_t)RTC_Bcd2ToByte(RTC_DateStruct->RTC_Year);
    RTC_DateStruct->RTC_Month = (uint8_t)RTC_Bcd2ToByte(RTC_DateStruct->
      RTC_Month);
    RTC_DateStruct->RTC_Date = (uint8_t)RTC_Bcd2ToByte(RTC_DateStruct->RTC_Date);
  }
}
RTC_GetFlagStatus()
 FlagStatus RTC_GetFlagStatus (uint32_t RTC_FLAG)
Checks whether the specified RTC flag is set or not.
Parameters
RTC_FLAG specifies the flag to check. This parameter can be one of the following values:
RTC_FLAG_TAMP1F: Tamper 1 event flag
RTC_FLAG_TSOVF: Time Stamp OverFlow flag
RTC_FLAG_TSF: Time Stamp event flag
RTC_FLAG_WUTF: WakeUp Timer flag
RTC_FLAG_ALRBF: Alarm B flag
RTC_FLAG_ALRAF: Alarm A flag
RTC_FLAG_INITF: Initialization mode flag
RTC_FLAG_RSF: Registers Synchronized flag
RTC_FLAG_INITS: Registers Configured flag
RTC_FLAG_WUTWF: WakeUp Timer Write flag
RTC_FLAG_ALRBWF: Alarm B Write flag
RTC_FLAG_ALRAWF: Alarm A write flag
Return values
The new state of RTC_FLAG (SET or RESET).
Definition at line 2576 of file stm32f4xx_rtc.c.
References RESET, and SET.
{
  FlagStatus bitstatus = RESET;
  uint32_t tmpreg = 0;
  
  /* Check the parameters */
  assert_param(IS_RTC_GET_FLAG(RTC_FLAG));
  
  /* Get all the flags */
  tmpreg = (uint32_t)(RTC->ISR & RTC_FLAGS_MASK);
  
  /* Return the status of the flag */
  if ((tmpreg & RTC_FLAG) != (uint32_t)RESET)
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  return bitstatus;
}
RTC_GetITStatus()
 ITStatus RTC_GetITStatus (uint32_t RTC_IT)
Checks whether the specified RTC interrupt has occurred or not.
Parameters
RTC_IT specifies the RTC interrupt source to check. This parameter can be one of the following values:
RTC_IT_TS: Time Stamp interrupt
RTC_IT_WUT: WakeUp Timer interrupt
RTC_IT_ALRB: Alarm B interrupt
RTC_IT_ALRA: Alarm A interrupt
RTC_IT_TAMP1: Tamper 1 event interrupt
Return values
The new state of RTC_IT (SET or RESET).
Definition at line 2632 of file stm32f4xx_rtc.c.
References RESET, and SET.
{
  ITStatus bitstatus = RESET;
  uint32_t tmpreg = 0, enablestatus = 0;
 
  /* Check the parameters */
  assert_param(IS_RTC_GET_IT(RTC_IT));
  
  /* Get the TAMPER Interrupt enable bit and pending bit */
  tmpreg = (uint32_t)(RTC->TAFCR & (RTC_TAFCR_TAMPIE));
 
  /* Get the Interrupt enable Status */
  enablestatus = (uint32_t)((RTC->CR & RTC_IT) | (tmpreg & (RTC_IT >> 15)));
  
  /* Get the Interrupt pending bit */
  tmpreg = (uint32_t)((RTC->ISR & (uint32_t)(RTC_IT >> 4)));
  
  /* Get the status of the Interrupt */
  if ((enablestatus != (uint32_t)RESET) && ((tmpreg & 0x0000FFFF) != (uint32_t)
      RESET))
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  return bitstatus;
}
RTC_GetStoreOperation()
uint32_t RTC_GetStoreOperation (void)
Returns the RTC Day Light Saving stored operation.
Parameters
None
Return values
RTC Day Light Saving stored operation.
RTC_StoreOperation_Reset
RTC_StoreOperation_Set
Definition at line 1631 of file stm32f4xx_rtc.c.
{
  return (RTC->CR & RTC_CR_BCK);
}
RTC_GetSubSecond()
uint32_t RTC_GetSubSecond (void)
Gets the RTC current Calendar Subseconds value.
Note
This function freeze the Time and Date registers after reading the SSR register.
Parameters
None
Return values
RTC current Calendar Subseconds value.
Definition at line 901 of file stm32f4xx_rtc.c.
{
  uint32_t tmpreg = 0;
  
  /* Get subseconds values from the correspondent registers*/
  tmpreg = (uint32_t)(RTC->SSR);
  
  /* Read DR register to unfroze calendar registers */
  (void) (RTC->DR);
  
  return (tmpreg);
}
RTC_GetTime()
void RTC_GetTime (uint32_t RTC_Format, RTC_TimeTypeDef * RTC_TimeStruct)
Get the RTC current Time.
Parameters
RTC_Format specifies the format of the returned parameters. This parameter can be one of the following values:
RTC_Format_BIN: Binary data format
RTC_Format_BCD: BCD data format
RTC_TimeStruct pointer to a RTC_TimeTypeDef structure that will contain the returned current time configuration.
Return values
None
Definition at line 868 of file stm32f4xx_rtc.c.
References RTC_Bcd2ToByte(), RTC_TimeTypeDef::RTC_H12, RTC_TimeTypeDef::RTC_Hours, RTC_TimeTypeDef::RTC_Minutes, and RTC_TimeTypeDef::RTC_Seconds.
{
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_RTC_FORMAT(RTC_Format));
  /* Get the RTC_TR register */
  tmpreg = (uint32_t)(RTC->TR & RTC_TR_RESERVED_MASK);
  
  /* Fill the structure fields with the read parameters */
  RTC_TimeStruct->RTC_Hours = (uint8_t)((tmpreg & (RTC_TR_HT | RTC_TR_HU)) >> 16);
  RTC_TimeStruct->RTC_Minutes = (uint8_t)((tmpreg & (RTC_TR_MNT | RTC_TR_MNU)) >>8);
  RTC_TimeStruct->RTC_Seconds = (uint8_t)(tmpreg & (RTC_TR_ST | RTC_TR_SU));
  RTC_TimeStruct->RTC_H12 = (uint8_t)((tmpreg & (RTC_TR_PM)) >> 16);
  /* Check the input parameters format */
  if (RTC_Format == RTC_Format_BIN)
  {
    /* Convert the structure parameters to Binary format */
    RTC_TimeStruct->RTC_Hours = (uint8_t)RTC_Bcd2ToByte(RTC_TimeStruct->
      RTC_Hours);
    RTC_TimeStruct->RTC_Minutes = (uint8_t)RTC_Bcd2ToByte(RTC_TimeStruct->
      RTC_Minutes);
    RTC_TimeStruct->RTC_Seconds = (uint8_t)RTC_Bcd2ToByte(RTC_TimeStruct->
      RTC_Seconds);
  }
}
RTC_GetTimeStamp()
void RTC_GetTimeStamp (uint32_t RTC_Format, RTC_TimeTypeDef * RTC_StampTimeStruct, RTC_DateTypeDef * RTC_StampDateStruct)
Get the RTC TimeStamp value and masks.
Parameters
RTC_Format specifies the format of the output parameters. This parameter can be one of the following values:
RTC_Format_BIN: Binary data format
RTC_Format_BCD: BCD data format
RTC_StampTimeStruct pointer to a RTC_TimeTypeDef structure that will contains the TimeStamp time values.
RTC_StampDateStruct pointer to a RTC_DateTypeDef structure that will contains the TimeStamp date values.
Return values
None
Definition at line 1999 of file stm32f4xx_rtc.c.
References RTC_Bcd2ToByte(), RTC_DateTypeDef::RTC_Date, RTC_TimeTypeDef::RTC_H12, RTC_TimeTypeDef::RTC_Hours, RTC_TimeTypeDef::RTC_Minutes, RTC_DateTypeDef::RTC_Month, RTC_TimeTypeDef::RTC_Seconds, RTC_DateTypeDef::RTC_WeekDay, and RTC_DateTypeDef::RTC_Year.
{
  uint32_t tmptime = 0, tmpdate = 0;
  /* Check the parameters */
  assert_param(IS_RTC_FORMAT(RTC_Format));
  /* Get the TimeStamp time and date registers values */
  tmptime = (uint32_t)(RTC->TSTR & RTC_TR_RESERVED_MASK);
  tmpdate = (uint32_t)(RTC->TSDR & RTC_DR_RESERVED_MASK);
  /* Fill the Time structure fields with the read parameters */
  RTC_StampTimeStruct->RTC_Hours = (uint8_t)((tmptime & (RTC_TR_HT | RTC_TR_HU)) >> 16);
  RTC_StampTimeStruct->RTC_Minutes = (uint8_t)((tmptime & (RTC_TR_MNT |
      RTC_TR_MNU)) >> 8);
  RTC_StampTimeStruct->RTC_Seconds = (uint8_t)(tmptime & (RTC_TR_ST | RTC_TR_SU));
  RTC_StampTimeStruct->RTC_H12 = (uint8_t)((tmptime & (RTC_TR_PM)) >> 16);
  /* Fill the Date structure fields with the read parameters */
  RTC_StampDateStruct->RTC_Year = 0;
  RTC_StampDateStruct->RTC_Month = (uint8_t)((tmpdate & (RTC_DR_MT | RTC_DR_MU)) >> 8);
  RTC_StampDateStruct->RTC_Date = (uint8_t)(tmpdate & (RTC_DR_DT | RTC_DR_DU));
  RTC_StampDateStruct->RTC_WeekDay = (uint8_t)((tmpdate & (RTC_DR_WDU)) >> 13);
  /* Check the input parameters format */
  if (RTC_Format == RTC_Format_BIN)
  {
    /* Convert the Time structure parameters to Binary format */
    RTC_StampTimeStruct->RTC_Hours = (uint8_t)RTC_Bcd2ToByte(RTC_StampTimeStruct->
      RTC_Hours);
    RTC_StampTimeStruct->RTC_Minutes = (uint8_t)RTC_Bcd2ToByte(RTC_StampTimeStruct->
      RTC_Minutes);
    RTC_StampTimeStruct->RTC_Seconds = (uint8_t)RTC_Bcd2ToByte(RTC_StampTimeStruct->
      RTC_Seconds);
    /* Convert the Date structure parameters to Binary format */
    RTC_StampDateStruct->RTC_Month = (uint8_t)RTC_Bcd2ToByte(RTC_StampDateStruct->
      RTC_Month);
    RTC_StampDateStruct->RTC_Date = (uint8_t)RTC_Bcd2ToByte(RTC_StampDateStruct->
      RTC_Date);
    RTC_StampDateStruct->RTC_WeekDay = (uint8_t)RTC_Bcd2ToByte(RTC_StampDateStruct->
      RTC_WeekDay);
  }
}
RTC_GetTimeStampSubSecond()
uint32_t RTC_GetTimeStampSubSecond (void)
Get the RTC timestamp Subseconds value.
Parameters
None
Return values
RTC current timestamp Subseconds value.
Definition at line 2043 of file stm32f4xx_rtc.c.
{
  /* Get timestamp subseconds values from the correspondent registers */
  return (uint32_t)(RTC->TSSSR);
}
RTC_GetWakeUpCounter()
uint32_t RTC_GetWakeUpCounter (void)
Returns the RTC WakeUp timer counter value.
Parameters
None
Return values
The RTC WakeUp Counter value.
Definition at line 1515 of file stm32f4xx_rtc.c.
{
  /* Get the counter value */
  return ((uint32_t)(RTC->WUTR & RTC_WUTR_WUT));
}
RTC_Init()
 ErrorStatus RTC_Init (RTC_InitTypeDef * RTC_InitStruct)
Initializes the RTC registers according to the specified parameters in RTC_InitStruct.
Parameters
RTC_InitStruct pointer to a RTC_InitTypeDef structure that contains the configuration information for the RTC peripheral.
Note
The RTC Prescaler register is write protected and can be written in initialization mode only.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC registers are initialized
ERROR: RTC registers are not initialized
Definition at line 445 of file stm32f4xx_rtc.c.
References ERROR, RTC_EnterInitMode(), RTC_ExitInitMode(), and SUCCESS.
{
  ErrorStatus status = ERROR;
  
  /* Check the parameters */
  assert_param(IS_RTC_HOUR_FORMAT(RTC_InitStruct->RTC_HourFormat));
  assert_param(IS_RTC_ASYNCH_PREDIV(RTC_InitStruct->RTC_AsynchPrediv));
  assert_param(IS_RTC_SYNCH_PREDIV(RTC_InitStruct->RTC_SynchPrediv));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    /* Clear RTC CR FMT Bit */
    RTC->CR &= ((uint32_t)~(RTC_CR_FMT));
    /* Set RTC_CR register */
    RTC->CR |= ((uint32_t)(RTC_InitStruct->RTC_HourFormat));
  
    /* Configure the RTC PRER */
    RTC->PRER = (uint32_t)(RTC_InitStruct->RTC_SynchPrediv);
    RTC->PRER |= (uint32_t)(RTC_InitStruct->RTC_AsynchPrediv << 16);
    /* Exit Initialization mode */
    RTC_ExitInitMode();
    status = SUCCESS;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_ITConfig()
void RTC_ITConfig (uint32_t RTC_IT, FunctionalState NewState)
Enables or disables the specified RTC interrupts.
Parameters
RTC_IT specifies the RTC interrupt sources to be enabled or disabled. This parameter can be any combination of the following values:
RTC_IT_TS: Time Stamp interrupt mask
RTC_IT_WUT: WakeUp Timer interrupt mask
RTC_IT_ALRB: Alarm B interrupt mask
RTC_IT_ALRA: Alarm A interrupt mask
RTC_IT_TAMP: Tamper event interrupt mask
NewState new state of the specified RTC interrupts. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 2530 of file stm32f4xx_rtc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_RTC_CONFIG_IT(RTC_IT));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  if (NewState != DISABLE)
  {
    /* Configure the Interrupts in the RTC_CR register */
    RTC->CR |= (uint32_t)(RTC_IT & ~RTC_TAFCR_TAMPIE);
    /* Configure the Tamper Interrupt in the RTC_TAFCR */
    RTC->TAFCR |= (uint32_t)(RTC_IT & RTC_TAFCR_TAMPIE);
  }
  else
  {
    /* Configure the Interrupts in the RTC_CR register */
    RTC->CR &= (uint32_t)~(RTC_IT & (uint32_t)~RTC_TAFCR_TAMPIE);
    /* Configure the Tamper Interrupt in the RTC_TAFCR */
    RTC->TAFCR &= (uint32_t)~(RTC_IT & RTC_TAFCR_TAMPIE);
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_OutputConfig()
void RTC_OutputConfig (uint32_t RTC_Output, uint32_t RTC_OutputPolarity)
Configures the RTC output source (AFO_ALARM).
Parameters
RTC_Output Specifies which signal will be routed to the RTC output. This parameter can be one of the following values:
RTC_Output_Disable: No output selected
RTC_Output_AlarmA: signal of AlarmA mapped to output
RTC_Output_AlarmB: signal of AlarmB mapped to output
RTC_Output_WakeUp: signal of WakeUp mapped to output
RTC_OutputPolarity Specifies the polarity of the output signal. This parameter can be one of the following:
RTC_OutputPolarity_High: The output pin is high when the ALRAF/ALRBF/WUTF is high (depending on OSEL)
RTC_OutputPolarity_Low: The output pin is low when the ALRAF/ALRBF/WUTF is high (depending on OSEL)
Return values
None
Definition at line 1670 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_OUTPUT(RTC_Output));
  assert_param(IS_RTC_OUTPUT_POL(RTC_OutputPolarity));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Clear the bits to be configured */
  RTC->CR &= (uint32_t)~(RTC_CR_OSEL | RTC_CR_POL);
  /* Configure the output selection and polarity */
  RTC->CR |= (uint32_t)(RTC_Output | RTC_OutputPolarity);
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_OutputTypeConfig()
void RTC_OutputTypeConfig (uint32_t RTC_OutputType)
Configures the RTC Output Pin mode.
Parameters
RTC_OutputType specifies the RTC Output (PC13) pin mode. This parameter can be one of the following values:
RTC_OutputType_OpenDrain: RTC Output (PC13) is configured in Open Drain mode.
RTC_OutputType_PushPull: RTC Output (PC13) is configured in Push Pull mode.
Return values
None
Definition at line 2373 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_OUTPUT_TYPE(RTC_OutputType));
  
  RTC->TAFCR &= (uint32_t)~(RTC_TAFCR_ALARMOUTTYPE);
  RTC->TAFCR |= (uint32_t)(RTC_OutputType);
}
RTC_ReadBackupRegister()
uint32_t RTC_ReadBackupRegister (uint32_t RTC_BKP_DR)
Reads data from the specified RTC Backup data Register.
Parameters
RTC_BKP_DR RTC Backup data Register number. This parameter can be: RTC_BKP_DRx where x can be from 0 to 19 to specify the register.
Return values
None
Definition at line 2297 of file stm32f4xx_rtc.c.
{
  __IO uint32_t tmp = 0;
  
  /* Check the parameters */
  assert_param(IS_RTC_BKP(RTC_BKP_DR));
  tmp = RTC_BASE + 0x50;
  tmp += (RTC_BKP_DR * 4);
  
  /* Read the specified register */
  return (*(__IO uint32_t *)tmp);
}
RTC_RefClockCmd()
 ErrorStatus RTC_RefClockCmd (FunctionalState NewState)
Enables or disables the RTC reference clock detection.
Parameters
NewState new state of the RTC reference clock. This parameter can be: ENABLE or DISABLE.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC reference clock detection is enabled
ERROR: RTC reference clock detection is disabled
Definition at line 650 of file stm32f4xx_rtc.c.
References DISABLE, ERROR, RTC_EnterInitMode(), RTC_ExitInitMode(), and SUCCESS.
{
  ErrorStatus status = ERROR;
  
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
    
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    if (NewState != DISABLE)
    {
      /* Enable the RTC reference clock detection */
      RTC->CR |= RTC_CR_REFCKON;
    }
    else
    {
      /* Disable the RTC reference clock detection */
      RTC->CR &= ~RTC_CR_REFCKON;
    }
    /* Exit Initialization mode */
    RTC_ExitInitMode();
    
    status = SUCCESS;
  }
  
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_SetAlarm()
void RTC_SetAlarm (uint32_t RTC_Format, uint32_t RTC_Alarm, RTC_AlarmTypeDef * RTC_AlarmStruct)
Set the specified RTC Alarm.
Note
The Alarm register can only be written when the corresponding Alarm is disabled (Use the RTC_AlarmCmd(DISABLE)).
Parameters
RTC_Format specifies the format of the returned parameters. This parameter can be one of the following values:
RTC_Format_BIN: Binary data format
RTC_Format_BCD: BCD data format
RTC_Alarm specifies the alarm to be configured. This parameter can be one of the following values:
RTC_Alarm_A: to select Alarm A
RTC_Alarm_B: to select Alarm B
RTC_AlarmStruct pointer to a RTC_AlarmTypeDef structure that contains the alarm configuration parameters.
Return values
None
Definition at line 1088 of file stm32f4xx_rtc.c.
References RTC_AlarmTypeDef::RTC_AlarmDateWeekDay, RTC_AlarmTypeDef::RTC_AlarmDateWeekDaySel, RTC_AlarmTypeDef::RTC_AlarmMask, RTC_AlarmTypeDef::RTC_AlarmTime, RTC_Bcd2ToByte(), RTC_ByteToBcd2(), RTC_TimeTypeDef::RTC_H12, RTC_TimeTypeDef::RTC_Hours, RTC_TimeTypeDef::RTC_Minutes, and RTC_TimeTypeDef::RTC_Seconds.
{
  uint32_t tmpreg = 0;
  
  /* Check the parameters */
  assert_param(IS_RTC_FORMAT(RTC_Format));
  assert_param(IS_RTC_ALARM(RTC_Alarm));
  assert_param(IS_ALARM_MASK(RTC_AlarmStruct->RTC_AlarmMask));
  assert_param(IS_RTC_ALARM_DATE_WEEKDAY_SEL(RTC_AlarmStruct->
      RTC_AlarmDateWeekDaySel));
  if (RTC_Format == RTC_Format_BIN)
  {
    if ((RTC->CR & RTC_CR_FMT) != (uint32_t)RESET)
    {
      assert_param(IS_RTC_HOUR12(RTC_AlarmStruct->RTC_AlarmTime.RTC_Hours));
      assert_param(IS_RTC_H12(RTC_AlarmStruct->RTC_AlarmTime.RTC_H12));
    }
    else
    {
      RTC_AlarmStruct->RTC_AlarmTime.RTC_H12 = 0x00;
      assert_param(IS_RTC_HOUR24(RTC_AlarmStruct->RTC_AlarmTime.RTC_Hours));
    }
    assert_param(IS_RTC_MINUTES(RTC_AlarmStruct->RTC_AlarmTime.RTC_Minutes));
    assert_param(IS_RTC_SECONDS(RTC_AlarmStruct->RTC_AlarmTime.RTC_Seconds));
    
    if(RTC_AlarmStruct->RTC_AlarmDateWeekDaySel == RTC_AlarmDateWeekDaySel_Date)
    {
      assert_param(IS_RTC_ALARM_DATE_WEEKDAY_DATE(RTC_AlarmStruct->
      RTC_AlarmDateWeekDay));
    }
    else
    {
      assert_param(IS_RTC_ALARM_DATE_WEEKDAY_WEEKDAY(RTC_AlarmStruct->
      RTC_AlarmDateWeekDay));
    }
  }
  else
  {
    if ((RTC->CR & RTC_CR_FMT) != (uint32_t)RESET)
    {
      tmpreg = RTC_Bcd2ToByte(RTC_AlarmStruct->RTC_AlarmTime.RTC_Hours);
      assert_param(IS_RTC_HOUR12(tmpreg));
      assert_param(IS_RTC_H12(RTC_AlarmStruct->RTC_AlarmTime.RTC_H12));
    }
    else
    {
      RTC_AlarmStruct->RTC_AlarmTime.RTC_H12 = 0x00;
      assert_param(IS_RTC_HOUR24(RTC_Bcd2ToByte(RTC_AlarmStruct->RTC_AlarmTime.
      RTC_Hours)));
    }
    
    assert_param(IS_RTC_MINUTES(RTC_Bcd2ToByte(RTC_AlarmStruct->RTC_AlarmTime.
      RTC_Minutes)));
    assert_param(IS_RTC_SECONDS(RTC_Bcd2ToByte(RTC_AlarmStruct->RTC_AlarmTime.
      RTC_Seconds)));
    
    if(RTC_AlarmStruct->RTC_AlarmDateWeekDaySel == RTC_AlarmDateWeekDaySel_Date)
    {
      tmpreg = RTC_Bcd2ToByte(RTC_AlarmStruct->RTC_AlarmDateWeekDay);
      assert_param(IS_RTC_ALARM_DATE_WEEKDAY_DATE(tmpreg));
    }
    else
    {
      tmpreg = RTC_Bcd2ToByte(RTC_AlarmStruct->RTC_AlarmDateWeekDay);
      assert_param(IS_RTC_ALARM_DATE_WEEKDAY_WEEKDAY(tmpreg));
    }
  }
  /* Check the input parameters format */
  if (RTC_Format != RTC_Format_BIN)
  {
    tmpreg = (((uint32_t)(RTC_AlarmStruct->RTC_AlarmTime.RTC_Hours) << 16) | \
              ((uint32_t)(RTC_AlarmStruct->RTC_AlarmTime.RTC_Minutes) << 8) | \
              ((uint32_t)RTC_AlarmStruct->RTC_AlarmTime.RTC_Seconds) | \
              ((uint32_t)(RTC_AlarmStruct->RTC_AlarmTime.RTC_H12) << 16) | \
              ((uint32_t)(RTC_AlarmStruct->RTC_AlarmDateWeekDay) << 24) | \
              ((uint32_t)RTC_AlarmStruct->RTC_AlarmDateWeekDaySel) | \
              ((uint32_t)RTC_AlarmStruct->RTC_AlarmMask));
  }
  else
  {
    tmpreg = (((uint32_t)RTC_ByteToBcd2(RTC_AlarmStruct->RTC_AlarmTime.RTC_Hours) << 16) | \
              ((uint32_t)RTC_ByteToBcd2(RTC_AlarmStruct->RTC_AlarmTime.
      RTC_Minutes) << 8) | \
              ((uint32_t)RTC_ByteToBcd2(RTC_AlarmStruct->RTC_AlarmTime.
      RTC_Seconds)) | \
              ((uint32_t)(RTC_AlarmStruct->RTC_AlarmTime.RTC_H12) << 16) | \
              ((uint32_t)RTC_ByteToBcd2(RTC_AlarmStruct->RTC_AlarmDateWeekDay) << 24) | \
              ((uint32_t)RTC_AlarmStruct->RTC_AlarmDateWeekDaySel) | \
              ((uint32_t)RTC_AlarmStruct->RTC_AlarmMask));
  }
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Configure the Alarm register */
  if (RTC_Alarm == RTC_Alarm_A)
  {
    RTC->ALRMAR = (uint32_t)tmpreg;
  }
  else
  {
    RTC->ALRMBR = (uint32_t)tmpreg;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_SetDate()
 ErrorStatus RTC_SetDate (uint32_t RTC_Format, RTC_DateTypeDef * RTC_DateStruct)
Set the RTC current date.
Parameters
RTC_Format specifies the format of the entered parameters. This parameter can be one of the following values:
RTC_Format_BIN: Binary data format
RTC_Format_BCD: BCD data format
RTC_DateStruct pointer to a RTC_DateTypeDef structure that contains the date configuration information for the RTC.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC Date register is configured
ERROR: RTC Date register is not configured
Definition at line 926 of file stm32f4xx_rtc.c.
References ERROR, RTC_Bcd2ToByte(), RTC_ByteToBcd2(), RTC_DateTypeDef::RTC_Date, RTC_EnterInitMode(), RTC_ExitInitMode(), RTC_DateTypeDef::RTC_Month, RTC_WaitForSynchro(), RTC_DateTypeDef::RTC_WeekDay, RTC_DateTypeDef::RTC_Year, and SUCCESS.
{
  uint32_t tmpreg = 0;
  ErrorStatus status = ERROR;
  
  /* Check the parameters */
  assert_param(IS_RTC_FORMAT(RTC_Format));
  if ((RTC_Format == RTC_Format_BIN) && ((RTC_DateStruct->RTC_Month & 0x10) == 0x10))
  {
    RTC_DateStruct->RTC_Month = (RTC_DateStruct->RTC_Month & (uint32_t)~(0x10)) + 0x0A;
  }
  if (RTC_Format == RTC_Format_BIN)
  {
    assert_param(IS_RTC_YEAR(RTC_DateStruct->RTC_Year));
    assert_param(IS_RTC_MONTH(RTC_DateStruct->RTC_Month));
    assert_param(IS_RTC_DATE(RTC_DateStruct->RTC_Date));
  }
  else
  {
    assert_param(IS_RTC_YEAR(RTC_Bcd2ToByte(RTC_DateStruct->RTC_Year)));
    tmpreg = RTC_Bcd2ToByte(RTC_DateStruct->RTC_Month);
    assert_param(IS_RTC_MONTH(tmpreg));
    tmpreg = RTC_Bcd2ToByte(RTC_DateStruct->RTC_Date);
    assert_param(IS_RTC_DATE(tmpreg));
  }
  assert_param(IS_RTC_WEEKDAY(RTC_DateStruct->RTC_WeekDay));
  /* Check the input parameters format */
  if (RTC_Format != RTC_Format_BIN)
  {
    tmpreg = ((((uint32_t)RTC_DateStruct->RTC_Year) << 16) | \
              (((uint32_t)RTC_DateStruct->RTC_Month) << 8) | \
              ((uint32_t)RTC_DateStruct->RTC_Date) | \
              (((uint32_t)RTC_DateStruct->RTC_WeekDay) << 13));
  }
  else
  {
    tmpreg = (((uint32_t)RTC_ByteToBcd2(RTC_DateStruct->RTC_Year) << 16) | \
              ((uint32_t)RTC_ByteToBcd2(RTC_DateStruct->RTC_Month) << 8) | \
              ((uint32_t)RTC_ByteToBcd2(RTC_DateStruct->RTC_Date)) | \
              ((uint32_t)RTC_DateStruct->RTC_WeekDay << 13));
  }
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    /* Set the RTC_DR register */
    RTC->DR = (uint32_t)(tmpreg & RTC_DR_RESERVED_MASK);
    /* Exit Initialization mode */
    RTC_ExitInitMode();
    if(RTC_WaitForSynchro() == ERROR)
    {
      status = ERROR;
    }
    else
    {
      status = SUCCESS;
    }
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_SetTime()
 ErrorStatus RTC_SetTime (uint32_t RTC_Format, RTC_TimeTypeDef * RTC_TimeStruct)
Set the RTC current time.
Parameters
RTC_Format specifies the format of the entered parameters. This parameter can be one of the following values:
RTC_Format_BIN: Binary data format
RTC_Format_BCD: BCD data format
RTC_TimeStruct pointer to a RTC_TimeTypeDef structure that contains the time configuration information for the RTC.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC Time register is configured
ERROR: RTC Time register is not configured
Definition at line 753 of file stm32f4xx_rtc.c.
References ERROR, RTC_ByteToBcd2(), RTC_EnterInitMode(), RTC_ExitInitMode(), RTC_TimeTypeDef::RTC_H12, RTC_TimeTypeDef::RTC_Hours, RTC_TimeTypeDef::RTC_Minutes, RTC_TimeTypeDef::RTC_Seconds, RTC_WaitForSynchro(), and SUCCESS.
{
  uint32_t tmpreg = 0;
  ErrorStatus status = ERROR;
    
  /* Check the parameters */
  assert_param(IS_RTC_FORMAT(RTC_Format));
  
  if (RTC_Format == RTC_Format_BIN)
  {
    if ((RTC->CR & RTC_CR_FMT) != (uint32_t)RESET)
    {
      assert_param(IS_RTC_HOUR12(RTC_TimeStruct->RTC_Hours));
      assert_param(IS_RTC_H12(RTC_TimeStruct->RTC_H12));
    }
    else
    {
      RTC_TimeStruct->RTC_H12 = 0x00;
      assert_param(IS_RTC_HOUR24(RTC_TimeStruct->RTC_Hours));
    }
    assert_param(IS_RTC_MINUTES(RTC_TimeStruct->RTC_Minutes));
    assert_param(IS_RTC_SECONDS(RTC_TimeStruct->RTC_Seconds));
  }
  else
  {
    if ((RTC->CR & RTC_CR_FMT) != (uint32_t)RESET)
    {
      tmpreg = RTC_Bcd2ToByte(RTC_TimeStruct->RTC_Hours);
      assert_param(IS_RTC_HOUR12(tmpreg));
      assert_param(IS_RTC_H12(RTC_TimeStruct->RTC_H12));
    }
    else
    {
      RTC_TimeStruct->RTC_H12 = 0x00;
      assert_param(IS_RTC_HOUR24(RTC_Bcd2ToByte(RTC_TimeStruct->RTC_Hours)));
    }
    assert_param(IS_RTC_MINUTES(RTC_Bcd2ToByte(RTC_TimeStruct->RTC_Minutes)));
    assert_param(IS_RTC_SECONDS(RTC_Bcd2ToByte(RTC_TimeStruct->RTC_Seconds)));
  }
  
  /* Check the input parameters format */
  if (RTC_Format != RTC_Format_BIN)
  {
    tmpreg = (((uint32_t)(RTC_TimeStruct->RTC_Hours) << 16) | \
             ((uint32_t)(RTC_TimeStruct->RTC_Minutes) << 8) | \
             ((uint32_t)RTC_TimeStruct->RTC_Seconds) | \
             ((uint32_t)(RTC_TimeStruct->RTC_H12) << 16));
  }
  else
  {
    tmpreg = (uint32_t)(((uint32_t)RTC_ByteToBcd2(RTC_TimeStruct->RTC_Hours) << 16) | \
                   ((uint32_t)RTC_ByteToBcd2(RTC_TimeStruct->RTC_Minutes) << 8) | \
                   ((uint32_t)RTC_ByteToBcd2(RTC_TimeStruct->RTC_Seconds)) | \
                   (((uint32_t)RTC_TimeStruct->RTC_H12) << 16));
  }
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    /* Set the RTC_TR register */
    RTC->TR = (uint32_t)(tmpreg & RTC_TR_RESERVED_MASK);
    /* Exit Initialization mode */
    RTC_ExitInitMode();
    if(RTC_WaitForSynchro() == ERROR)
    {
      status = ERROR;
    }
    else
    {
      status = SUCCESS;
    }
  
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
    
  return status;
}
RTC_SetWakeUpCounter()
void RTC_SetWakeUpCounter (uint32_t RTC_WakeUpCounter)
Configures the RTC Wakeup counter.
Note
The RTC WakeUp counter can only be written when the RTC WakeUp is disabled (Use the RTC_WakeUpCmd(DISABLE)).
Parameters
RTC_WakeUpCounter specifies the WakeUp counter. This parameter can be a value from 0x0000 to 0xFFFF.
Return values
None
Definition at line 1494 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_WAKEUP_COUNTER(RTC_WakeUpCounter));
  
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  /* Configure the Wakeup Timer counter */
  RTC->WUTR = (uint32_t)RTC_WakeUpCounter;
  
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_SmoothCalibConfig()
 ErrorStatus RTC_SmoothCalibConfig (uint32_t RTC_SmoothCalibPeriod, uint32_t RTC_SmoothCalibPlusPulses, uint32_t RTC_SmouthCalibMinusPulsesValue)
Configures the Smooth Calibration Settings.
Parameters
RTC_SmoothCalibPeriod : Select the Smooth Calibration Period. This parameter can be can be one of the following values:
RTC_SmoothCalibPeriod_32sec : The smooth calibration periode is 32s.
RTC_SmoothCalibPeriod_16sec : The smooth calibration periode is 16s.
RTC_SmoothCalibPeriod_8sec : The smooth calibartion periode is 8s.
RTC_SmoothCalibPlusPulses : Select to Set or reset the CALP bit. This parameter can be one of the following values:
RTC_SmoothCalibPlusPulses_Set : Add one RTCCLK puls every 2**11 pulses.
RTC_SmoothCalibPlusPulses_Reset: No RTCCLK pulses are added.
RTC_SmouthCalibMinusPulsesValue Select the value of CALM[8:0] bits. This parameter can be one any value from 0 to 0x000001FF.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC Calib registers are configured
ERROR: RTC Calib registers are not configured
Definition at line 1879 of file stm32f4xx_rtc.c.
References ERROR.
{
  ErrorStatus status = ERROR;
  uint32_t recalpfcount = 0;
  /* Check the parameters */
  assert_param(IS_RTC_SMOOTH_CALIB_PERIOD(RTC_SmoothCalibPeriod));
  assert_param(IS_RTC_SMOOTH_CALIB_PLUS(RTC_SmoothCalibPlusPulses));
  assert_param(IS_RTC_SMOOTH_CALIB_MINUS(RTC_SmouthCalibMinusPulsesValue));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  /* check if a calibration is pending*/
  if ((RTC->ISR & RTC_ISR_RECALPF) != RESET)
  {
    /* wait until the Calibration is completed*/
    while (((RTC->ISR & RTC_ISR_RECALPF) != RESET) && (recalpfcount !=
      RECALPF_TIMEOUT))
    {
      recalpfcount++;
    }
  }
  /* check if the calibration pending is completed or if there is no calibration operation at all*/
  if ((RTC->ISR & RTC_ISR_RECALPF) == RESET)
  {
    /* Configure the Smooth calibration settings */
    RTC->CALR = (uint32_t)((uint32_t)RTC_SmoothCalibPeriod | (uint32_t)RTC_SmoothCalibPlusPulses | (
      uint32_t)RTC_SmouthCalibMinusPulsesValue);
    status = SUCCESS;
  }
  else
  {
    status = ERROR;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return (ErrorStatus)(status);
}
RTC_StructInit()
void RTC_StructInit (RTC_InitTypeDef * RTC_InitStruct)
Fills each RTC_InitStruct member with its default value.
Parameters
RTC_InitStruct pointer to a RTC_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 491 of file stm32f4xx_rtc.c.
References RTC_InitTypeDef::RTC_AsynchPrediv, RTC_InitTypeDef::RTC_HourFormat, and RTC_InitTypeDef::RTC_SynchPrediv.
{
  /* Initialize the RTC_HourFormat member */
  RTC_InitStruct->RTC_HourFormat = RTC_HourFormat_24;
    
  /* Initialize the RTC_AsynchPrediv member */
  RTC_InitStruct->RTC_AsynchPrediv = (uint32_t)0x7F;
  /* Initialize the RTC_SynchPrediv member */
  RTC_InitStruct->RTC_SynchPrediv = (uint32_t)0xFF;
}
RTC_SynchroShiftConfig()
 ErrorStatus RTC_SynchroShiftConfig (uint32_t RTC_ShiftAdd1S, uint32_t RTC_ShiftSubFS)
Configures the Synchronization Shift Control Settings.
Note
When REFCKON is set, firmware must not write to Shift control register
Parameters
RTC_ShiftAdd1S : Select to add or not 1 second to the time Calendar. This parameter can be one of the following values :
RTC_ShiftAdd1S_Set : Add one second to the clock calendar.
RTC_ShiftAdd1S_Reset: No effect.
RTC_ShiftSubFS Select the number of Second Fractions to Substitute. This parameter can be one any value from 0 to 0x7FFF.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC Shift registers are configured
ERROR: RTC Shift registers are not configured
Definition at line 2411 of file stm32f4xx_rtc.c.
References ERROR.
{
  ErrorStatus status = ERROR;
  uint32_t shpfcount = 0;
  /* Check the parameters */
  assert_param(IS_RTC_SHIFT_ADD1S(RTC_ShiftAdd1S));
  assert_param(IS_RTC_SHIFT_SUBFS(RTC_ShiftSubFS));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  /* Check if a Shift is pending*/
  if ((RTC->ISR & RTC_ISR_SHPF) != RESET)
  {
    /* Wait until the shift is completed*/
    while (((RTC->ISR & RTC_ISR_SHPF) != RESET) && (shpfcount != SHPF_TIMEOUT))
    {
      shpfcount++;
    }
  }
  /* Check if the Shift pending is completed or if there is no Shift operation at all*/
  if ((RTC->ISR & RTC_ISR_SHPF) == RESET)
  {
    /* check if the reference clock detection is disabled */
    if((RTC->CR & RTC_CR_REFCKON) == RESET)
    {
      /* Configure the Shift settings */
      RTC->SHIFTR = (uint32_t)(uint32_t)(RTC_ShiftSubFS) | (uint32_t)(RTC_ShiftAdd1S);
    
      if(RTC_WaitForSynchro() == ERROR)
      {
        status = ERROR;
      }
      else
      {
        status = SUCCESS;
      }
    }
    else
    {
      status = ERROR;
    }
  }
  else
  {
    status = ERROR;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return (ErrorStatus)(status);
}
RTC_TamperCmd()
void RTC_TamperCmd (uint32_t RTC_Tamper, FunctionalState NewState)
Enables or Disables the Tamper detection.
Parameters
RTC_Tamper Selected tamper pin. This parameter can be RTC_Tamper_1.
NewState new state of the tamper pin. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 2104 of file stm32f4xx_rtc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_RTC_TAMPER(RTC_Tamper));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the selected Tamper pin */
    RTC->TAFCR |= (uint32_t)RTC_Tamper;
  }
  else
  {
    /* Disable the selected Tamper pin */
    RTC->TAFCR &= (uint32_t)~RTC_Tamper;
  }
}
RTC_TamperFilterConfig()
void RTC_TamperFilterConfig (uint32_t RTC_TamperFilter)
Configures the Tampers Filter.
Parameters
RTC_TamperFilter Specifies the tampers filter. This parameter can be one of the following values:
RTC_TamperFilter_Disable: Tamper filter is disabled.
RTC_TamperFilter_2Sample: Tamper is activated after 2 consecutive samples at the active level
RTC_TamperFilter_4Sample: Tamper is activated after 4 consecutive samples at the active level
RTC_TamperFilter_8Sample: Tamper is activated after 8 consecutive samples at the active level
Return values
None
Definition at line 2135 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_TAMPER_FILTER(RTC_TamperFilter));
   
  /* Clear TAMPFLT[1:0] bits in the RTC_TAFCR register */
  RTC->TAFCR &= (uint32_t)~(RTC_TAFCR_TAMPFLT);
  /* Configure the RTC_TAFCR register */
  RTC->TAFCR |= (uint32_t)RTC_TamperFilter;
}
RTC_TamperPinSelection()
void RTC_TamperPinSelection (uint32_t RTC_TamperPin)
Selects the RTC Tamper Pin.
Parameters
RTC_TamperPin specifies the RTC Tamper Pin. This parameter can be one of the following values:
RTC_TamperPin_PC13: PC13 is selected as RTC Tamper Pin.
RTC_TamperPin_PI8: PI8 is selected as RTC Tamper Pin.
Return values
None
Definition at line 2337 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_TAMPER_PIN(RTC_TamperPin));
  
  RTC->TAFCR &= (uint32_t)~(RTC_TAFCR_TAMPINSEL);
  RTC->TAFCR |= (uint32_t)(RTC_TamperPin);
}
RTC_TamperPinsPrechargeDuration()
void RTC_TamperPinsPrechargeDuration (uint32_t RTC_TamperPrechargeDuration)
Configures the Tampers Pins input Precharge Duration.
Parameters
RTC_TamperPrechargeDuration Specifies the Tampers Pins input Precharge Duration. This parameter can be one of the following values:
RTC_TamperPrechargeDuration_1RTCCLK: Tamper pins are pre-charged before sampling during 1 RTCCLK cycle
RTC_TamperPrechargeDuration_2RTCCLK: Tamper pins are pre-charged before sampling during 2 RTCCLK cycle
RTC_TamperPrechargeDuration_4RTCCLK: Tamper pins are pre-charged before sampling during 4 RTCCLK cycle
RTC_TamperPrechargeDuration_8RTCCLK: Tamper pins are pre-charged before sampling during 8 RTCCLK cycle
Return values
None
Definition at line 2192 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_TAMPER_PRECHARGE_DURATION(RTC_TamperPrechargeDuration));
   
  /* Clear TAMPPRCH[1:0] bits in the RTC_TAFCR register */
  RTC->TAFCR &= (uint32_t)~(RTC_TAFCR_TAMPPRCH);
  /* Configure the RTC_TAFCR register */
  RTC->TAFCR |= (uint32_t)RTC_TamperPrechargeDuration;
}
RTC_TamperPullUpCmd()
void RTC_TamperPullUpCmd (FunctionalState NewState)
Enables or Disables the Precharge of Tamper pin.
Parameters
NewState new state of tamper pull up. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 2235 of file stm32f4xx_rtc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
 if (NewState != DISABLE)
  {
    /* Enable precharge of the selected Tamper pin */
    RTC->TAFCR &= (uint32_t)~RTC_TAFCR_TAMPPUDIS;
  }
  else
  {
    /* Disable precharge of the selected Tamper pin */
    RTC->TAFCR |= (uint32_t)RTC_TAFCR_TAMPPUDIS;
  }
}
RTC_TamperSamplingFreqConfig()
void RTC_TamperSamplingFreqConfig (uint32_t RTC_TamperSamplingFreq)
Configures the Tampers Sampling Frequency.
Parameters
RTC_TamperSamplingFreq Specifies the tampers Sampling Frequency. This parameter can be one of the following values:
RTC_TamperSamplingFreq_RTCCLK_Div32768: Each of the tamper inputs are sampled with a frequency = RTCCLK / 32768
RTC_TamperSamplingFreq_RTCCLK_Div16384: Each of the tamper inputs are sampled with a frequency = RTCCLK / 16384
RTC_TamperSamplingFreq_RTCCLK_Div8192: Each of the tamper inputs are sampled with a frequency = RTCCLK / 8192
RTC_TamperSamplingFreq_RTCCLK_Div4096: Each of the tamper inputs are sampled with a frequency = RTCCLK / 4096
RTC_TamperSamplingFreq_RTCCLK_Div2048: Each of the tamper inputs are sampled with a frequency = RTCCLK / 2048
RTC_TamperSamplingFreq_RTCCLK_Div1024: Each of the tamper inputs are sampled with a frequency = RTCCLK / 1024
RTC_TamperSamplingFreq_RTCCLK_Div512: Each of the tamper inputs are sampled with a frequency = RTCCLK / 512
RTC_TamperSamplingFreq_RTCCLK_Div256: Each of the tamper inputs are sampled with a frequency = RTCCLK / 256
Return values
None
Definition at line 2169 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_TAMPER_SAMPLING_FREQ(RTC_TamperSamplingFreq));
 
  /* Clear TAMPFREQ[2:0] bits in the RTC_TAFCR register */
  RTC->TAFCR &= (uint32_t)~(RTC_TAFCR_TAMPFREQ);
  /* Configure the RTC_TAFCR register */
  RTC->TAFCR |= (uint32_t)RTC_TamperSamplingFreq;
}
RTC_TamperTriggerConfig()
void RTC_TamperTriggerConfig (uint32_t RTC_Tamper, uint32_t RTC_TamperTrigger)
Configures the select Tamper pin edge.
Parameters
RTC_Tamper Selected tamper pin. This parameter can be RTC_Tamper_1.
RTC_TamperTrigger Specifies the trigger on the tamper pin that stimulates tamper event. This parameter can be one of the following values:
RTC_TamperTrigger_RisingEdge: Rising Edge of the tamper pin causes tamper event.
RTC_TamperTrigger_FallingEdge: Falling Edge of the tamper pin causes tamper event.
RTC_TamperTrigger_LowLevel: Low Level of the tamper pin causes tamper event.
RTC_TamperTrigger_HighLevel: High Level of the tamper pin causes tamper event.
Return values
None
Definition at line 2078 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_TAMPER(RTC_Tamper));
  assert_param(IS_RTC_TAMPER_TRIGGER(RTC_TamperTrigger));
 
  if (RTC_TamperTrigger == RTC_TamperTrigger_RisingEdge)
  {
    /* Configure the RTC_TAFCR register */
    RTC->TAFCR &= (uint32_t)((uint32_t)~(RTC_Tamper << 1));
  }
  else
  {
    /* Configure the RTC_TAFCR register */
    RTC->TAFCR |= (uint32_t)(RTC_Tamper << 1);
  }
}
RTC_TimeStampCmd()
void RTC_TimeStampCmd (uint32_t RTC_TimeStampEdge, FunctionalState NewState)
Enables or Disables the RTC TimeStamp functionality with the specified time stamp pin stimulating edge.
Parameters
RTC_TimeStampEdge Specifies the pin edge on which the TimeStamp is activated. This parameter can be one of the following:
RTC_TimeStampEdge_Rising: the Time stamp event occurs on the rising edge of the related pin.
RTC_TimeStampEdge_Falling: the Time stamp event occurs on the falling edge of the related pin.
NewState new state of the TimeStamp. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1955 of file stm32f4xx_rtc.c.
References DISABLE.
{
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_RTC_TIMESTAMP_EDGE(RTC_TimeStampEdge));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  /* Get the RTC_CR register and clear the bits to be configured */
  tmpreg = (uint32_t)(RTC->CR & (uint32_t)~(RTC_CR_TSEDGE | RTC_CR_TSE));
  /* Get the new configuration */
  if (NewState != DISABLE)
  {
    tmpreg |= (uint32_t)(RTC_TimeStampEdge | RTC_CR_TSE);
  }
  else
  {
    tmpreg |= (uint32_t)(RTC_TimeStampEdge);
  }
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Configure the Time Stamp TSEDGE and Enable bits */
  RTC->CR = (uint32_t)tmpreg;
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_TimeStampOnTamperDetectionCmd()
void RTC_TimeStampOnTamperDetectionCmd (FunctionalState NewState)
Enables or Disables the TimeStamp on Tamper Detection Event.
Note
The timestamp is valid even the TSE bit in tamper control register is reset.
Parameters
NewState new state of the timestamp on tamper event. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 2212 of file stm32f4xx_rtc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
   
  if (NewState != DISABLE)
  {
    /* Save timestamp on tamper detection event */
    RTC->TAFCR |= (uint32_t)RTC_TAFCR_TAMPTS;
  }
  else
  {
    /* Tamper detection does not cause a timestamp to be saved */
    RTC->TAFCR &= (uint32_t)~RTC_TAFCR_TAMPTS;
  }
}
RTC_TimeStampPinSelection()
void RTC_TimeStampPinSelection (uint32_t RTC_TimeStampPin)
Selects the RTC TimeStamp Pin.
Parameters
RTC_TimeStampPin specifies the RTC TimeStamp Pin. This parameter can be one of the following values:
RTC_TimeStampPin_PC13: PC13 is selected as RTC TimeStamp Pin.
RTC_TimeStampPin_PI8: PI8 is selected as RTC TimeStamp Pin.
Return values
None
Definition at line 2354 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_TIMESTAMP_PIN(RTC_TimeStampPin));
  
  RTC->TAFCR &= (uint32_t)~(RTC_TAFCR_TSINSEL);
  RTC->TAFCR |= (uint32_t)(RTC_TimeStampPin);
}
RTC_TimeStructInit()
void RTC_TimeStructInit (RTC_TimeTypeDef * RTC_TimeStruct)
Fills each RTC_TimeStruct member with its default value (Time = 00h:00min:00sec).
Parameters
RTC_TimeStruct pointer to a RTC_TimeTypeDef structure which will be initialized.
Return values
None
Definition at line 849 of file stm32f4xx_rtc.c.
References RTC_TimeTypeDef::RTC_H12, RTC_TimeTypeDef::RTC_Hours, RTC_TimeTypeDef::RTC_Minutes, and RTC_TimeTypeDef::RTC_Seconds.
{
  /* Time = 00h:00min:00sec */
  RTC_TimeStruct->RTC_H12 = RTC_H12_AM;
  RTC_TimeStruct->RTC_Hours = 0;
  RTC_TimeStruct->RTC_Minutes = 0;
  RTC_TimeStruct->RTC_Seconds = 0;
}
RTC_WaitForSynchro()
 ErrorStatus RTC_WaitForSynchro (void)
Waits until the RTC Time and Date registers (RTC_TR and RTC_DR) are synchronized with RTC APB clock.
Note
The RTC Resynchronization mode is write protected, use the RTC_WriteProtectionCmd(DISABLE) before calling this function.
To read the calendar through the shadow registers after Calendar initialization, calendar update or after wakeup from low power modes the software must first clear the RSF flag. The software must then wait until it is set again before reading the calendar, which means that the calendar registers have been correctly copied into the RTC_TR and RTC_DR shadow registers.
Parameters
None
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC registers are synchronised
ERROR: RTC registers are not synchronised
Definition at line 607 of file stm32f4xx_rtc.c.
References ERROR.
Referenced by RTC_SetDate(), and RTC_SetTime().
{
  __IO uint32_t synchrocounter = 0;
  ErrorStatus status = ERROR;
  uint32_t synchrostatus = 0x00;
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
    
  /* Clear RSF flag */
  RTC->ISR &= (uint32_t)RTC_RSF_MASK;
    
  /* Wait the registers to be synchronised */
  do
  {
    synchrostatus = RTC->ISR & RTC_ISR_RSF;
    synchrocounter++;
  } while((synchrocounter != SYNCHRO_TIMEOUT) && (synchrostatus == 0x00));
    
  if ((RTC->ISR & RTC_ISR_RSF) != RESET)
  {
    status = SUCCESS;
  }
  else
  {
    status = ERROR;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
    
  return (status);
}
RTC_WakeUpClockConfig()
void RTC_WakeUpClockConfig (uint32_t RTC_WakeUpClock)
Configures the RTC Wakeup clock source.
Note
The WakeUp Clock source can only be changed when the RTC WakeUp is disabled (Use the RTC_WakeUpCmd(DISABLE)).
Parameters
RTC_WakeUpClock Wakeup Clock source. This parameter can be one of the following values:
RTC_WakeUpClock_RTCCLK_Div16: RTC Wakeup Counter Clock = RTCCLK/16
RTC_WakeUpClock_RTCCLK_Div8: RTC Wakeup Counter Clock = RTCCLK/8
RTC_WakeUpClock_RTCCLK_Div4: RTC Wakeup Counter Clock = RTCCLK/4
RTC_WakeUpClock_RTCCLK_Div2: RTC Wakeup Counter Clock = RTCCLK/2
RTC_WakeUpClock_CK_SPRE_16bits: RTC Wakeup Counter Clock = CK_SPRE
RTC_WakeUpClock_CK_SPRE_17bits: RTC Wakeup Counter Clock = CK_SPRE
Return values
None
Definition at line 1467 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_WAKEUP_CLOCK(RTC_WakeUpClock));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Clear the Wakeup Timer clock source bits in CR register */
  RTC->CR &= (uint32_t)~RTC_CR_WUCKSEL;
  /* Configure the clock source */
  RTC->CR |= (uint32_t)RTC_WakeUpClock;
  
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_WakeUpCmd()
 ErrorStatus RTC_WakeUpCmd (FunctionalState NewState)
Enables or Disables the RTC WakeUp timer.
Parameters
NewState new state of the WakeUp timer. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1527 of file stm32f4xx_rtc.c.
References DISABLE, ERROR, and SUCCESS.
{
  __IO uint32_t wutcounter = 0x00;
  uint32_t wutwfstatus = 0x00;
  ErrorStatus status = ERROR;
  
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  if (NewState != DISABLE)
  {
    /* Enable the Wakeup Timer */
    RTC->CR |= (uint32_t)RTC_CR_WUTE;
    status = SUCCESS;
  }
  else
  {
    /* Disable the Wakeup Timer */
    RTC->CR &= (uint32_t)~RTC_CR_WUTE;
    /* Wait till RTC WUTWF flag is set and if Time out is reached exit */
    do
    {
      wutwfstatus = RTC->ISR & RTC_ISR_WUTWF;
      wutcounter++;
    } while((wutcounter != INITMODE_TIMEOUT) && (wutwfstatus == 0x00));
    
    if ((RTC->ISR & RTC_ISR_WUTWF) == RESET)
    {
      status = ERROR;
    }
    else
    {
      status = SUCCESS;
    }
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_WriteBackupRegister()
void RTC_WriteBackupRegister (uint32_t RTC_BKP_DR, uint32_t Data)
Writes a data in a specified RTC Backup data register.
Parameters
RTC_BKP_DR RTC Backup data Register number. This parameter can be: RTC_BKP_DRx where x can be from 0 to 19 to specify the register.
Data Data to be written in the specified RTC Backup data register.
Return values
None
Definition at line 2276 of file stm32f4xx_rtc.c.
{
  __IO uint32_t tmp = 0;
  
  /* Check the parameters */
  assert_param(IS_RTC_BKP(RTC_BKP_DR));
  tmp = RTC_BASE + 0x50;
  tmp += (RTC_BKP_DR * 4);
  /* Write the specified register */
  *(__IO uint32_t *)tmp = (uint32_t)Data;
}
RTC_WriteProtectionCmd()
void RTC_WriteProtectionCmd (FunctionalState NewState)
Enables or disables the RTC registers write protection.
Note
All the RTC registers are write protected except for RTC_ISR[13:8], RTC_TAFCR and RTC_BKPxR.
Writing a wrong key reactivates the write protection.
The protection mechanism is not affected by system reset.
Parameters
NewState new state of the write protection. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 513 of file stm32f4xx_rtc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
    
  if (NewState != DISABLE)
  {
    /* Enable the write protection for RTC registers */
    RTC->WPR = 0xFF;
  }
  else
  {
    /* Disable the write protection for RTC registers */
    RTC->WPR = 0xCA;
    RTC->WPR = 0x53;
  }
}