EXTI
EXTI driver modules.
Modules
 EXTI_Exported_Constants
 EXTI_Private_Functions
Classes
struct EXTI_InitTypeDef
EXTI Init Structure definition.
Macros
#define EXTI_LINENONE ((uint32_t)0x00000) /* No interrupt selected */
#define IS_EXTI_MODE(MODE) (((MODE) == EXTI_Mode_Interrupt) || ((MODE) == EXTI_Mode_Event))
#define IS_EXTI_TRIGGER(TRIGGER)
Enumerations
enum EXTIMode_TypeDef { EXTI_Mode_Interrupt = 0x00,
 EXTI_Mode_Event = 0x04
 }
EXTI mode enumeration.
enum EXTITrigger_TypeDef { EXTI_Trigger_Rising = 0x08,
 EXTI_Trigger_Falling = 0x0C,
 EXTI_Trigger_Rising_Falling = 0x10
 }
EXTI Trigger enumeration.
Functions
void EXTI_DeInit (void)
Deinitializes the EXTI peripheral registers to their default reset values.
void EXTI_Init (EXTI_InitTypeDef *EXTI_InitStruct)
Initializes the EXTI peripheral according to the specified parameters in the EXTI_InitStruct.
void EXTI_StructInit (EXTI_InitTypeDef *EXTI_InitStruct)
Fills each EXTI_InitStruct member with its reset value.
void EXTI_GenerateSWInterrupt (uint32_t EXTI_Line)
Generates a Software interrupt on selected EXTI line.
 FlagStatus EXTI_GetFlagStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line flag is set or not.
void EXTI_ClearFlag (uint32_t EXTI_Line)
Clears the EXTI's line pending flags.
 ITStatus EXTI_GetITStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line is asserted or not.
void EXTI_ClearITPendingBit (uint32_t EXTI_Line)
Clears the EXTI's line pending bits.
Detailed Description
EXTI driver modules.
Macro Definition Documentation
EXTI_LINENONE
#define EXTI_LINENONE ((uint32_t)0x00000) /* No interrupt selected */
Definition at line 75 of file stm32f4xx_exti.c.
IS_EXTI_MODE
#define IS_EXTI_MODE(MODE) (((MODE) == EXTI_Mode_Interrupt) || ((MODE) == EXTI_Mode_Event))
Definition at line 54 of file stm32f4xx_exti.h.
IS_EXTI_TRIGGER
#define IS_EXTI_TRIGGER(TRIGGER)
Value:
(((TRIGGER) == EXTI_Trigger_Rising) || \
                                  ((TRIGGER) == EXTI_Trigger_Falling) || \
                                  ((TRIGGER) == EXTI_Trigger_Rising_Falling))
Definition at line 67 of file stm32f4xx_exti.h.
Enumeration Type Documentation
EXTIMode_TypeDef
enum EXTIMode_TypeDef
EXTI mode enumeration.
Enumerator
EXTI_Mode_Interrupt
EXTI_Mode_Event
Definition at line 48 of file stm32f4xx_exti.h.
{
  EXTI_Mode_Interrupt = 0x00,
  EXTI_Mode_Event = 0x04
}EXTIMode_TypeDef;
EXTITrigger_TypeDef
enum EXTITrigger_TypeDef
EXTI Trigger enumeration.
Enumerator
EXTI_Trigger_Rising
EXTI_Trigger_Falling
EXTI_Trigger_Rising_Falling
Definition at line 60 of file stm32f4xx_exti.h.
{
  EXTI_Trigger_Rising = 0x08,
  EXTI_Trigger_Falling = 0x0C,
  EXTI_Trigger_Rising_Falling = 0x10
}EXTITrigger_TypeDef;
Function Documentation
EXTI_ClearFlag()
void EXTI_ClearFlag (uint32_t EXTI_Line)
Clears the EXTI's line pending flags.
Parameters
EXTI_Line specifies the EXTI lines flags to clear. This parameter can be any combination of EXTI_Linex where x can be (0..22)
Return values
None
Definition at line 243 of file stm32f4xx_exti.c.
{
  /* Check the parameters */
  assert_param(IS_EXTI_LINE(EXTI_Line));
  
  EXTI->PR = EXTI_Line;
}
EXTI_ClearITPendingBit()
void EXTI_ClearITPendingBit (uint32_t EXTI_Line)
Clears the EXTI's line pending bits.
Parameters
EXTI_Line specifies the EXTI lines to clear. This parameter can be any combination of EXTI_Linex where x can be (0..22)
Return values
None
Definition at line 282 of file stm32f4xx_exti.c.
Referenced by DisableInvInterrupt(), EXTI1_IRQHandler(), and InvIntHandler().
{
  /* Check the parameters */
  assert_param(IS_EXTI_LINE(EXTI_Line));
  
  EXTI->PR = EXTI_Line;
}
EXTI_DeInit()
void EXTI_DeInit (void)
Deinitializes the EXTI peripheral registers to their default reset values.
Parameters
None
Return values
None
Definition at line 103 of file stm32f4xx_exti.c.
{
  EXTI->IMR = 0x00000000;
  EXTI->EMR = 0x00000000;
  EXTI->RTSR = 0x00000000;
  EXTI->FTSR = 0x00000000;
  EXTI->PR = 0x007FFFFF;
}
EXTI_GenerateSWInterrupt()
void EXTI_GenerateSWInterrupt (uint32_t EXTI_Line)
Generates a Software interrupt on selected EXTI line.
Parameters
EXTI_Line specifies the EXTI line on which the software interrupt will be generated. This parameter can be any combination of EXTI_Linex where x can be (0..22)
Return values
None
Definition at line 190 of file stm32f4xx_exti.c.
{
  /* Check the parameters */
  assert_param(IS_EXTI_LINE(EXTI_Line));
  
  EXTI->SWIER |= EXTI_Line;
}
EXTI_GetFlagStatus()
 FlagStatus EXTI_GetFlagStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line flag is set or not.
Parameters
EXTI_Line specifies the EXTI line flag to check. This parameter can be EXTI_Linex where x can be(0..22)
Return values
The new state of EXTI_Line (SET or RESET).
Definition at line 220 of file stm32f4xx_exti.c.
References RESET.
{
  FlagStatus bitstatus = RESET;
  /* Check the parameters */
  assert_param(IS_GET_EXTI_LINE(EXTI_Line));
  
  if ((EXTI->PR & EXTI_Line) != (uint32_t)RESET)
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  return bitstatus;
}
EXTI_GetITStatus()
 ITStatus EXTI_GetITStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line is asserted or not.
Parameters
EXTI_Line specifies the EXTI line to check. This parameter can be EXTI_Linex where x can be(0..22)
Return values
The new state of EXTI_Line (SET or RESET).
Definition at line 257 of file stm32f4xx_exti.c.
References RESET.
{
  ITStatus bitstatus = RESET;
  uint32_t enablestatus = 0;
  /* Check the parameters */
  assert_param(IS_GET_EXTI_LINE(EXTI_Line));
  
  enablestatus = EXTI->IMR & EXTI_Line;
  if (((EXTI->PR & EXTI_Line) != (uint32_t)RESET) && (enablestatus != (uint32_t)RESET))
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  return bitstatus;
}
EXTI_Init()
void EXTI_Init (EXTI_InitTypeDef * EXTI_InitStruct)
Initializes the EXTI peripheral according to the specified parameters in the EXTI_InitStruct.
Parameters
EXTI_InitStruct pointer to a EXTI_InitTypeDef structure that contains the configuration information for the EXTI peripheral.
Return values
None
Definition at line 119 of file stm32f4xx_exti.c.
References DISABLE, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_InitTypeDef::EXTI_Mode, EXTI_InitTypeDef::EXTI_Trigger, and EXTI_Trigger_Rising_Falling.
Referenced by DisableInvInterrupt(), EnableInvInterrupt(), GPIO_Config(), and STM_EVAL_PBInit().
{
  uint32_t tmp = 0;
  /* Check the parameters */
  assert_param(IS_EXTI_MODE(EXTI_InitStruct->EXTI_Mode));
  assert_param(IS_EXTI_TRIGGER(EXTI_InitStruct->EXTI_Trigger));
  assert_param(IS_EXTI_LINE(EXTI_InitStruct->EXTI_Line));
  assert_param(IS_FUNCTIONAL_STATE(EXTI_InitStruct->EXTI_LineCmd));
  tmp = (uint32_t)EXTI_BASE;
     
  if (EXTI_InitStruct->EXTI_LineCmd != DISABLE)
  {
    /* Clear EXTI line configuration */
    EXTI->IMR &= ~EXTI_InitStruct->EXTI_Line;
    EXTI->EMR &= ~EXTI_InitStruct->EXTI_Line;
    
    tmp += EXTI_InitStruct->EXTI_Mode;
    *(__IO uint32_t *) tmp |= EXTI_InitStruct->EXTI_Line;
    /* Clear Rising Falling edge configuration */
    EXTI->RTSR &= ~EXTI_InitStruct->EXTI_Line;
    EXTI->FTSR &= ~EXTI_InitStruct->EXTI_Line;
    
    /* Select the trigger for the selected external interrupts */
    if (EXTI_InitStruct->EXTI_Trigger == EXTI_Trigger_Rising_Falling)
    {
      /* Rising Falling edge */
      EXTI->RTSR |= EXTI_InitStruct->EXTI_Line;
      EXTI->FTSR |= EXTI_InitStruct->EXTI_Line;
    }
    else
    {
      tmp = (uint32_t)EXTI_BASE;
      tmp += EXTI_InitStruct->EXTI_Trigger;
      *(__IO uint32_t *) tmp |= EXTI_InitStruct->EXTI_Line;
    }
  }
  else
  {
    tmp += EXTI_InitStruct->EXTI_Mode;
    /* Disable the selected external lines */
    *(__IO uint32_t *) tmp &= ~EXTI_InitStruct->EXTI_Line;
  }
}
EXTI_StructInit()
void EXTI_StructInit (EXTI_InitTypeDef * EXTI_InitStruct)
Fills each EXTI_InitStruct member with its reset value.
Parameters
EXTI_InitStruct pointer to a EXTI_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 175 of file stm32f4xx_exti.c.
References DISABLE, EXTI_InitTypeDef::EXTI_Line, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_InitTypeDef::EXTI_Mode, EXTI_Mode_Interrupt, EXTI_InitTypeDef::EXTI_Trigger, and EXTI_Trigger_Falling.
{
  EXTI_InitStruct->EXTI_Line = EXTI_LINENONE;
  EXTI_InitStruct->EXTI_Mode = EXTI_Mode_Interrupt;
  EXTI_InitStruct->EXTI_Trigger = EXTI_Trigger_Falling;
  EXTI_InitStruct->EXTI_LineCmd = DISABLE;
}