Interrupts and flags management functions
Interrupts and flags management functions.
Functions
 FlagStatus EXTI_GetFlagStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line flag is set or not.
void EXTI_ClearFlag (uint32_t EXTI_Line)
Clears the EXTI's line pending flags.
 ITStatus EXTI_GetITStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line is asserted or not.
void EXTI_ClearITPendingBit (uint32_t EXTI_Line)
Clears the EXTI's line pending bits.
Detailed Description
Interrupts and flags management functions.
 ===============================================================================
                  Interrupts and flags management functions
 ===============================================================================  
Function Documentation
EXTI_ClearFlag()
void EXTI_ClearFlag (uint32_t EXTI_Line)
Clears the EXTI's line pending flags.
Parameters
EXTI_Line specifies the EXTI lines flags to clear. This parameter can be any combination of EXTI_Linex where x can be (0..22)
Return values
None
Definition at line 243 of file stm32f4xx_exti.c.
{
  /* Check the parameters */
  assert_param(IS_EXTI_LINE(EXTI_Line));
  
  EXTI->PR = EXTI_Line;
}
EXTI_ClearITPendingBit()
void EXTI_ClearITPendingBit (uint32_t EXTI_Line)
Clears the EXTI's line pending bits.
Parameters
EXTI_Line specifies the EXTI lines to clear. This parameter can be any combination of EXTI_Linex where x can be (0..22)
Return values
None
Definition at line 282 of file stm32f4xx_exti.c.
Referenced by DisableInvInterrupt(), EXTI1_IRQHandler(), and InvIntHandler().
{
  /* Check the parameters */
  assert_param(IS_EXTI_LINE(EXTI_Line));
  
  EXTI->PR = EXTI_Line;
}
EXTI_GetFlagStatus()
 FlagStatus EXTI_GetFlagStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line flag is set or not.
Parameters
EXTI_Line specifies the EXTI line flag to check. This parameter can be EXTI_Linex where x can be(0..22)
Return values
The new state of EXTI_Line (SET or RESET).
Definition at line 220 of file stm32f4xx_exti.c.
References RESET.
{
  FlagStatus bitstatus = RESET;
  /* Check the parameters */
  assert_param(IS_GET_EXTI_LINE(EXTI_Line));
  
  if ((EXTI->PR & EXTI_Line) != (uint32_t)RESET)
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  return bitstatus;
}
EXTI_GetITStatus()
 ITStatus EXTI_GetITStatus (uint32_t EXTI_Line)
Checks whether the specified EXTI line is asserted or not.
Parameters
EXTI_Line specifies the EXTI line to check. This parameter can be EXTI_Linex where x can be(0..22)
Return values
The new state of EXTI_Line (SET or RESET).
Definition at line 257 of file stm32f4xx_exti.c.
References RESET.
{
  ITStatus bitstatus = RESET;
  uint32_t enablestatus = 0;
  /* Check the parameters */
  assert_param(IS_GET_EXTI_LINE(EXTI_Line));
  
  enablestatus = EXTI->IMR & EXTI_Line;
  if (((EXTI->PR & EXTI_Line) != (uint32_t)RESET) && (enablestatus != (uint32_t)RESET))
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  return bitstatus;
}