SYSCFG
SYSCFG driver modules.
Modules
 SYSCFG_Exported_Constants
 SYSCFG_Private_Functions
Macros
#define SYSCFG_OFFSET (SYSCFG_BASE - PERIPH_BASE)
#define PMC_OFFSET (SYSCFG_OFFSET + 0x04)
#define MII_RMII_SEL_BitNumber ((uint8_t)0x17)
#define PMC_MII_RMII_SEL_BB (PERIPH_BB_BASE + (PMC_OFFSET * 32) + (MII_RMII_SEL_BitNumber * 4))
#define CMPCR_OFFSET (SYSCFG_OFFSET + 0x20)
#define CMP_PD_BitNumber ((uint8_t)0x00)
#define CMPCR_CMP_PD_BB (PERIPH_BB_BASE + (CMPCR_OFFSET * 32) + (CMP_PD_BitNumber * 4))
Functions
void SYSCFG_DeInit (void)
Deinitializes the Alternate Functions (remap and EXTI configuration) registers to their default reset values.
void SYSCFG_MemoryRemapConfig (uint8_t SYSCFG_MemoryRemap)
Changes the mapping of the specified pin.
void SYSCFG_EXTILineConfig (uint8_t EXTI_PortSourceGPIOx, uint8_t EXTI_PinSourcex)
Selects the GPIO pin used as EXTI Line.
void SYSCFG_ETH_MediaInterfaceConfig (uint32_t SYSCFG_ETH_MediaInterface)
Selects the ETHERNET media interface.
void SYSCFG_CompensationCellCmd (FunctionalState NewState)
Enables or disables the I/O Compensation Cell.
 FlagStatus SYSCFG_GetCompensationCellStatus (void)
Checks whether the I/O Compensation Cell ready flag is set or not.
Detailed Description
SYSCFG driver modules.
Macro Definition Documentation
CMP_PD_BitNumber
#define CMP_PD_BitNumber ((uint8_t)0x00)
Definition at line 68 of file stm32f4xx_syscfg.c.
CMPCR_CMP_PD_BB
#define CMPCR_CMP_PD_BB (PERIPH_BB_BASE + (CMPCR_OFFSET * 32) + (CMP_PD_BitNumber * 4))
Definition at line 69 of file stm32f4xx_syscfg.c.
CMPCR_OFFSET
#define CMPCR_OFFSET (SYSCFG_OFFSET + 0x20)
Definition at line 67 of file stm32f4xx_syscfg.c.
MII_RMII_SEL_BitNumber
#define MII_RMII_SEL_BitNumber ((uint8_t)0x17)
Definition at line 62 of file stm32f4xx_syscfg.c.
PMC_MII_RMII_SEL_BB
#define PMC_MII_RMII_SEL_BB (PERIPH_BB_BASE + (PMC_OFFSET * 32) + (MII_RMII_SEL_BitNumber * 4))
Definition at line 63 of file stm32f4xx_syscfg.c.
PMC_OFFSET
#define PMC_OFFSET (SYSCFG_OFFSET + 0x04)
Definition at line 61 of file stm32f4xx_syscfg.c.
SYSCFG_OFFSET
#define SYSCFG_OFFSET (SYSCFG_BASE - PERIPH_BASE)
Definition at line 58 of file stm32f4xx_syscfg.c.
Function Documentation
SYSCFG_CompensationCellCmd()
void SYSCFG_CompensationCellCmd (FunctionalState NewState)
Enables or disables the I/O Compensation Cell.
Note
The I/O compensation cell can be used only when the device supply voltage ranges from 2.4 to 3.6 V.
Parameters
NewState new state of the I/O Compensation Cell. This parameter can be one of the following values:
ENABLE: I/O compensation cell enabled
DISABLE: I/O compensation cell power-down mode
Return values
None
Definition at line 157 of file stm32f4xx_syscfg.c.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  *(__IO uint32_t *) CMPCR_CMP_PD_BB = (uint32_t)NewState;
}
SYSCFG_DeInit()
void SYSCFG_DeInit (void)
Deinitializes the Alternate Functions (remap and EXTI configuration) registers to their default reset values.
Parameters
None
Return values
None
Definition at line 86 of file stm32f4xx_syscfg.c.
References DISABLE, ENABLE, and RCC_APB2PeriphResetCmd().
{
   RCC_APB2PeriphResetCmd(RCC_APB2Periph_SYSCFG, ENABLE);
   RCC_APB2PeriphResetCmd(RCC_APB2Periph_SYSCFG, DISABLE);
}
SYSCFG_ETH_MediaInterfaceConfig()
void SYSCFG_ETH_MediaInterfaceConfig (uint32_t SYSCFG_ETH_MediaInterface)
Selects the ETHERNET media interface.
Parameters
SYSCFG_ETH_MediaInterface specifies the Media Interface mode. This parameter can be one of the following values:
SYSCFG_ETH_MediaInterface_MII: MII mode selected
SYSCFG_ETH_MediaInterface_RMII: RMII mode selected
Return values
None
Definition at line 140 of file stm32f4xx_syscfg.c.
{
  assert_param(IS_SYSCFG_ETH_MEDIA_INTERFACE(SYSCFG_ETH_MediaInterface));
  /* Configure MII_RMII selection bit */
  *(__IO uint32_t *) PMC_MII_RMII_SEL_BB = SYSCFG_ETH_MediaInterface;
}
SYSCFG_EXTILineConfig()
void SYSCFG_EXTILineConfig (uint8_t EXTI_PortSourceGPIOx, uint8_t EXTI_PinSourcex)
Selects the GPIO pin used as EXTI Line.
Parameters
EXTI_PortSourceGPIOx : selects the GPIO port to be used as source for EXTI lines where x can be (A..I).
EXTI_PinSourcex specifies the EXTI line to be configured. This parameter can be EXTI_PinSourcex where x can be (0..15, except for EXTI_PortSourceGPIOI x can be (0..11).
Return values
None
Definition at line 119 of file stm32f4xx_syscfg.c.
Referenced by GPIO_Config(), and STM_EVAL_PBInit().
{
  uint32_t tmp = 0x00;
  /* Check the parameters */
  assert_param(IS_EXTI_PORT_SOURCE(EXTI_PortSourceGPIOx));
  assert_param(IS_EXTI_PIN_SOURCE(EXTI_PinSourcex));
  tmp = ((uint32_t)0x0F) << (0x04 * (EXTI_PinSourcex & (uint8_t)0x03));
  SYSCFG->EXTICR[EXTI_PinSourcex >> 0x02] &= ~tmp;
  SYSCFG->EXTICR[EXTI_PinSourcex >> 0x02] |= (((uint32_t)EXTI_PortSourceGPIOx) << (0x04 * (EXTI_PinSourcex
      & (uint8_t)0x03)));
}
SYSCFG_GetCompensationCellStatus()
 FlagStatus SYSCFG_GetCompensationCellStatus (void)
Checks whether the I/O Compensation Cell ready flag is set or not.
Parameters
None
Return values
The new state of the I/O Compensation Cell ready flag (SET or RESET)
Definition at line 170 of file stm32f4xx_syscfg.c.
References RESET.
{
  FlagStatus bitstatus = RESET;
    
  if ((SYSCFG->CMPCR & SYSCFG_CMPCR_READY) != (uint32_t)RESET)
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  return bitstatus;
}
SYSCFG_MemoryRemapConfig()
void SYSCFG_MemoryRemapConfig (uint8_t SYSCFG_MemoryRemap)
Changes the mapping of the specified pin.
Parameters
SYSCFG_Memory selects the memory remapping. This parameter can be one of the following values:
SYSCFG_MemoryRemap_Flash: Main Flash memory mapped at 0x00000000
SYSCFG_MemoryRemap_SystemFlash: System Flash memory mapped at 0x00000000
SYSCFG_MemoryRemap_FSMC: FSMC (Bank1 (NOR/PSRAM 1 and 2) mapped at 0x00000000
SYSCFG_MemoryRemap_SRAM: Embedded SRAM (112kB) mapped at 0x00000000
Return values
None
Definition at line 102 of file stm32f4xx_syscfg.c.
{
  /* Check the parameters */
  assert_param(IS_SYSCFG_MEMORY_REMAP_CONFING(SYSCFG_MemoryRemap));
  SYSCFG->MEMRMP = SYSCFG_MemoryRemap;
}