RCC
RCC driver modules.
Modules
 RCC_Exported_Constants
 RCC_Private_Functions
Classes
struct RCC_ClocksTypeDef
Macros
#define RCC_OFFSET (RCC_BASE - PERIPH_BASE)
#define CR_OFFSET (RCC_OFFSET + 0x00)
#define HSION_BitNumber 0x00
#define CR_HSION_BB (PERIPH_BB_BASE + (CR_OFFSET * 32) + (HSION_BitNumber * 4))
#define CSSON_BitNumber 0x13
#define CR_CSSON_BB (PERIPH_BB_BASE + (CR_OFFSET * 32) + (CSSON_BitNumber * 4))
#define PLLON_BitNumber 0x18
#define CR_PLLON_BB (PERIPH_BB_BASE + (CR_OFFSET * 32) + (PLLON_BitNumber * 4))
#define PLLI2SON_BitNumber 0x1A
#define CR_PLLI2SON_BB (PERIPH_BB_BASE + (CR_OFFSET * 32) + (PLLI2SON_BitNumber * 4))
#define CFGR_OFFSET (RCC_OFFSET + 0x08)
#define I2SSRC_BitNumber 0x17
#define CFGR_I2SSRC_BB (PERIPH_BB_BASE + (CFGR_OFFSET * 32) + (I2SSRC_BitNumber * 4))
#define BDCR_OFFSET (RCC_OFFSET + 0x70)
#define RTCEN_BitNumber 0x0F
#define BDCR_RTCEN_BB (PERIPH_BB_BASE + (BDCR_OFFSET * 32) + (RTCEN_BitNumber * 4))
#define BDRST_BitNumber 0x10
#define BDCR_BDRST_BB (PERIPH_BB_BASE + (BDCR_OFFSET * 32) + (BDRST_BitNumber * 4))
#define CSR_OFFSET (RCC_OFFSET + 0x74)
#define LSION_BitNumber 0x00
#define CSR_LSION_BB (PERIPH_BB_BASE + (CSR_OFFSET * 32) + (LSION_BitNumber * 4))
#define CFGR_MCO2_RESET_MASK ((uint32_t)0x07FFFFFF)
#define CFGR_MCO1_RESET_MASK ((uint32_t)0xF89FFFFF)
#define FLAG_MASK ((uint8_t)0x1F)
#define CR_BYTE3_ADDRESS ((uint32_t)0x40023802)
#define CIR_BYTE2_ADDRESS ((uint32_t)(RCC_BASE + 0x0C + 0x01))
#define CIR_BYTE3_ADDRESS ((uint32_t)(RCC_BASE + 0x0C + 0x02))
#define BDCR_ADDRESS (PERIPH_BASE + BDCR_OFFSET)
Functions
void RCC_DeInit (void)
Resets the RCC clock configuration to the default reset state.
void RCC_HSEConfig (uint8_t RCC_HSE)
Configures the External High Speed oscillator (HSE).
 ErrorStatus RCC_WaitForHSEStartUp (void)
Waits for HSE start-up.
void RCC_AdjustHSICalibrationValue (uint8_t HSICalibrationValue)
Adjusts the Internal High Speed oscillator (HSI) calibration value.
void RCC_HSICmd (FunctionalState NewState)
Enables or disables the Internal High Speed oscillator (HSI).
void RCC_LSEConfig (uint8_t RCC_LSE)
Configures the External Low Speed oscillator (LSE).
void RCC_LSICmd (FunctionalState NewState)
Enables or disables the Internal Low Speed oscillator (LSI).
void RCC_PLLConfig (uint32_t RCC_PLLSource, uint32_t PLLM, uint32_t PLLN, uint32_t PLLP, uint32_t PLLQ)
Configures the main PLL clock source, multiplication and division factors.
void RCC_PLLCmd (FunctionalState NewState)
Enables or disables the main PLL.
void RCC_PLLI2SConfig (uint32_t PLLI2SN, uint32_t PLLI2SR)
Configures the PLLI2S clock multiplication and division factors.
void RCC_PLLI2SCmd (FunctionalState NewState)
Enables or disables the PLLI2S.
void RCC_ClockSecuritySystemCmd (FunctionalState NewState)
Enables or disables the Clock Security System.
void RCC_MCO1Config (uint32_t RCC_MCO1Source, uint32_t RCC_MCO1Div)
Selects the clock source to output on MCO1 pin(PA8).
void RCC_MCO2Config (uint32_t RCC_MCO2Source, uint32_t RCC_MCO2Div)
Selects the clock source to output on MCO2 pin(PC9).
void RCC_SYSCLKConfig (uint32_t RCC_SYSCLKSource)
Configures the system clock (SYSCLK).
uint8_t RCC_GetSYSCLKSource (void)
Returns the clock source used as system clock.
void RCC_HCLKConfig (uint32_t RCC_SYSCLK)
Configures the AHB clock (HCLK).
void RCC_PCLK1Config (uint32_t RCC_HCLK)
Configures the Low Speed APB clock (PCLK1).
void RCC_PCLK2Config (uint32_t RCC_HCLK)
Configures the High Speed APB clock (PCLK2).
void RCC_GetClocksFreq (RCC_ClocksTypeDef *RCC_Clocks)
Returns the frequencies of different on chip clocks; SYSCLK, HCLK, PCLK1 and PCLK2.
void RCC_RTCCLKConfig (uint32_t RCC_RTCCLKSource)
Configures the RTC clock (RTCCLK).
void RCC_RTCCLKCmd (FunctionalState NewState)
Enables or disables the RTC clock.
void RCC_BackupResetCmd (FunctionalState NewState)
Forces or releases the Backup domain reset.
void RCC_I2SCLKConfig (uint32_t RCC_I2SCLKSource)
Configures the I2S clock source (I2SCLK).
void RCC_AHB1PeriphClockCmd (uint32_t RCC_AHB1Periph, FunctionalState NewState)
Enables or disables the AHB1 peripheral clock.
void RCC_AHB2PeriphClockCmd (uint32_t RCC_AHB2Periph, FunctionalState NewState)
Enables or disables the AHB2 peripheral clock.
void RCC_AHB3PeriphClockCmd (uint32_t RCC_AHB3Periph, FunctionalState NewState)
Enables or disables the AHB3 peripheral clock.
void RCC_APB1PeriphClockCmd (uint32_t RCC_APB1Periph, FunctionalState NewState)
Enables or disables the Low Speed APB (APB1) peripheral clock.
void RCC_APB2PeriphClockCmd (uint32_t RCC_APB2Periph, FunctionalState NewState)
Enables or disables the High Speed APB (APB2) peripheral clock.
void RCC_AHB1PeriphResetCmd (uint32_t RCC_AHB1Periph, FunctionalState NewState)
Forces or releases AHB1 peripheral reset.
void RCC_AHB2PeriphResetCmd (uint32_t RCC_AHB2Periph, FunctionalState NewState)
Forces or releases AHB2 peripheral reset.
void RCC_AHB3PeriphResetCmd (uint32_t RCC_AHB3Periph, FunctionalState NewState)
Forces or releases AHB3 peripheral reset.
void RCC_APB1PeriphResetCmd (uint32_t RCC_APB1Periph, FunctionalState NewState)
Forces or releases Low Speed APB (APB1) peripheral reset.
void RCC_APB2PeriphResetCmd (uint32_t RCC_APB2Periph, FunctionalState NewState)
Forces or releases High Speed APB (APB2) peripheral reset.
void RCC_AHB1PeriphClockLPModeCmd (uint32_t RCC_AHB1Periph, FunctionalState NewState)
Enables or disables the AHB1 peripheral clock during Low Power (Sleep) mode.
void RCC_AHB2PeriphClockLPModeCmd (uint32_t RCC_AHB2Periph, FunctionalState NewState)
Enables or disables the AHB2 peripheral clock during Low Power (Sleep) mode.
void RCC_AHB3PeriphClockLPModeCmd (uint32_t RCC_AHB3Periph, FunctionalState NewState)
Enables or disables the AHB3 peripheral clock during Low Power (Sleep) mode.
void RCC_APB1PeriphClockLPModeCmd (uint32_t RCC_APB1Periph, FunctionalState NewState)
Enables or disables the APB1 peripheral clock during Low Power (Sleep) mode.
void RCC_APB2PeriphClockLPModeCmd (uint32_t RCC_APB2Periph, FunctionalState NewState)
Enables or disables the APB2 peripheral clock during Low Power (Sleep) mode.
void RCC_ITConfig (uint8_t RCC_IT, FunctionalState NewState)
Enables or disables the specified RCC interrupts.
 FlagStatus RCC_GetFlagStatus (uint8_t RCC_FLAG)
Checks whether the specified RCC flag is set or not.
void RCC_ClearFlag (void)
Clears the RCC reset flags. The reset flags are: RCC_FLAG_PINRST, RCC_FLAG_PORRST, RCC_FLAG_SFTRST, RCC_FLAG_IWDGRST, RCC_FLAG_WWDGRST, RCC_FLAG_LPWRRST.
 ITStatus RCC_GetITStatus (uint8_t RCC_IT)
Checks whether the specified RCC interrupt has occurred or not.
void RCC_ClearITPendingBit (uint8_t RCC_IT)
Clears the RCC's interrupt pending bits.
Variables
static __I uint8_t APBAHBPrescTable [16] = {0, 0, 0, 0, 1, 2, 3, 4, 1, 2, 3, 4, 6, 7, 8, 9}
Detailed Description
RCC driver modules.
Macro Definition Documentation
BDCR_ADDRESS
#define BDCR_ADDRESS (PERIPH_BASE + BDCR_OFFSET)
Definition at line 123 of file stm32f4xx_rcc.c.
BDCR_BDRST_BB
#define BDCR_BDRST_BB (PERIPH_BB_BASE + (BDCR_OFFSET * 32) + (BDRST_BitNumber * 4))
Definition at line 99 of file stm32f4xx_rcc.c.
BDCR_OFFSET
#define BDCR_OFFSET (RCC_OFFSET + 0x70)
Definition at line 94 of file stm32f4xx_rcc.c.
BDCR_RTCEN_BB
#define BDCR_RTCEN_BB (PERIPH_BB_BASE + (BDCR_OFFSET * 32) + (RTCEN_BitNumber * 4))
Definition at line 96 of file stm32f4xx_rcc.c.
BDRST_BitNumber
#define BDRST_BitNumber 0x10
Definition at line 98 of file stm32f4xx_rcc.c.
CFGR_I2SSRC_BB
#define CFGR_I2SSRC_BB (PERIPH_BB_BASE + (CFGR_OFFSET * 32) + (I2SSRC_BitNumber * 4))
Definition at line 90 of file stm32f4xx_rcc.c.
CFGR_MCO1_RESET_MASK
#define CFGR_MCO1_RESET_MASK ((uint32_t)0xF89FFFFF)
Definition at line 108 of file stm32f4xx_rcc.c.
CFGR_MCO2_RESET_MASK
#define CFGR_MCO2_RESET_MASK ((uint32_t)0x07FFFFFF)
Definition at line 107 of file stm32f4xx_rcc.c.
CFGR_OFFSET
#define CFGR_OFFSET (RCC_OFFSET + 0x08)
Definition at line 88 of file stm32f4xx_rcc.c.
CIR_BYTE2_ADDRESS
#define CIR_BYTE2_ADDRESS ((uint32_t)(RCC_BASE + 0x0C + 0x01))
Definition at line 117 of file stm32f4xx_rcc.c.
CIR_BYTE3_ADDRESS
#define CIR_BYTE3_ADDRESS ((uint32_t)(RCC_BASE + 0x0C + 0x02))
Definition at line 120 of file stm32f4xx_rcc.c.
CR_BYTE3_ADDRESS
#define CR_BYTE3_ADDRESS ((uint32_t)0x40023802)
Definition at line 114 of file stm32f4xx_rcc.c.
CR_CSSON_BB
#define CR_CSSON_BB (PERIPH_BB_BASE + (CR_OFFSET * 32) + (CSSON_BitNumber * 4))
Definition at line 78 of file stm32f4xx_rcc.c.
CR_HSION_BB
#define CR_HSION_BB (PERIPH_BB_BASE + (CR_OFFSET * 32) + (HSION_BitNumber * 4))
Definition at line 75 of file stm32f4xx_rcc.c.
CR_OFFSET
#define CR_OFFSET (RCC_OFFSET + 0x00)
Definition at line 73 of file stm32f4xx_rcc.c.
CR_PLLI2SON_BB
#define CR_PLLI2SON_BB (PERIPH_BB_BASE + (CR_OFFSET * 32) + (PLLI2SON_BitNumber * 4))
Definition at line 84 of file stm32f4xx_rcc.c.
CR_PLLON_BB
#define CR_PLLON_BB (PERIPH_BB_BASE + (CR_OFFSET * 32) + (PLLON_BitNumber * 4))
Definition at line 81 of file stm32f4xx_rcc.c.
CSR_LSION_BB
#define CSR_LSION_BB (PERIPH_BB_BASE + (CSR_OFFSET * 32) + (LSION_BitNumber * 4))
Definition at line 104 of file stm32f4xx_rcc.c.
CSR_OFFSET
#define CSR_OFFSET (RCC_OFFSET + 0x74)
Definition at line 102 of file stm32f4xx_rcc.c.
CSSON_BitNumber
#define CSSON_BitNumber 0x13
Definition at line 77 of file stm32f4xx_rcc.c.
FLAG_MASK
#define FLAG_MASK ((uint8_t)0x1F)
Definition at line 111 of file stm32f4xx_rcc.c.
HSION_BitNumber
#define HSION_BitNumber 0x00
Definition at line 74 of file stm32f4xx_rcc.c.
I2SSRC_BitNumber
#define I2SSRC_BitNumber 0x17
Definition at line 89 of file stm32f4xx_rcc.c.
LSION_BitNumber
#define LSION_BitNumber 0x00
Definition at line 103 of file stm32f4xx_rcc.c.
PLLI2SON_BitNumber
#define PLLI2SON_BitNumber 0x1A
Definition at line 83 of file stm32f4xx_rcc.c.
PLLON_BitNumber
#define PLLON_BitNumber 0x18
Definition at line 80 of file stm32f4xx_rcc.c.
RCC_OFFSET
#define RCC_OFFSET (RCC_BASE - PERIPH_BASE)
Definition at line 70 of file stm32f4xx_rcc.c.
RTCEN_BitNumber
#define RTCEN_BitNumber 0x0F
Definition at line 95 of file stm32f4xx_rcc.c.
Function Documentation
RCC_AdjustHSICalibrationValue()
void RCC_AdjustHSICalibrationValue (uint8_t HSICalibrationValue)
Adjusts the Internal High Speed oscillator (HSI) calibration value.
Note
The calibration is used to compensate for the variations in voltage and temperature that influence the frequency of the internal HSI RC.
Parameters
HSICalibrationValue specifies the calibration trimming value. This parameter must be a number between 0 and 0x1F.
Return values
None
Definition at line 292 of file stm32f4xx_rcc.c.
{
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_RCC_CALIBRATION_VALUE(HSICalibrationValue));
  tmpreg = RCC->CR;
  /* Clear HSITRIM[4:0] bits */
  tmpreg &= ~RCC_CR_HSITRIM;
  /* Set the HSITRIM[4:0] bits according to HSICalibrationValue value */
  tmpreg |= (uint32_t)HSICalibrationValue << 3;
  /* Store the new value */
  RCC->CR = tmpreg;
}
RCC_AHB1PeriphClockCmd()
void RCC_AHB1PeriphClockCmd (uint32_t RCC_AHB1Periph, FunctionalState NewState)
Enables or disables the AHB1 peripheral clock.
Note
After reset, the peripheral clock (used for registers read/write access) is disabled and the application software has to enable this clock before using it.
Parameters
RCC_AHBPeriph specifies the AHB1 peripheral to gates its clock. This parameter can be any combination of the following values:
RCC_AHB1Periph_GPIOA: GPIOA clock
RCC_AHB1Periph_GPIOB: GPIOB clock
RCC_AHB1Periph_GPIOC: GPIOC clock
RCC_AHB1Periph_GPIOD: GPIOD clock
RCC_AHB1Periph_GPIOE: GPIOE clock
RCC_AHB1Periph_GPIOF: GPIOF clock
RCC_AHB1Periph_GPIOG: GPIOG clock
RCC_AHB1Periph_GPIOG: GPIOG clock
RCC_AHB1Periph_GPIOI: GPIOI clock
RCC_AHB1Periph_CRC: CRC clock
RCC_AHB1Periph_BKPSRAM: BKPSRAM interface clock
RCC_AHB1Periph_CCMDATARAMEN CCM data RAM interface clock
RCC_AHB1Periph_DMA1: DMA1 clock
RCC_AHB1Periph_DMA2: DMA2 clock
RCC_AHB1Periph_ETH_MAC: Ethernet MAC clock
RCC_AHB1Periph_ETH_MAC_Tx: Ethernet Transmission clock
RCC_AHB1Periph_ETH_MAC_Rx: Ethernet Reception clock
RCC_AHB1Periph_ETH_MAC_PTP: Ethernet PTP clock
RCC_AHB1Periph_OTG_HS: USB OTG HS clock
RCC_AHB1Periph_OTG_HS_ULPI: USB OTG HS ULPI clock
NewState new state of the specified peripheral clock. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1085 of file stm32f4xx_rcc.c.
References DISABLE.
Referenced by GPIO_Config(), I2cMaster_Init(), STM_EVAL_LEDInit(), STM_EVAL_PBInit(), and USART_Config().
{
  /* Check the parameters */
  assert_param(IS_RCC_AHB1_CLOCK_PERIPH(RCC_AHB1Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->AHB1ENR |= RCC_AHB1Periph;
  }
  else
  {
    RCC->AHB1ENR &= ~RCC_AHB1Periph;
  }
}
RCC_AHB1PeriphClockLPModeCmd()
void RCC_AHB1PeriphClockLPModeCmd (uint32_t RCC_AHB1Periph, FunctionalState NewState)
Enables or disables the AHB1 peripheral clock during Low Power (Sleep) mode.
Note
Peripheral clock gating in SLEEP mode can be used to further reduce power consumption.
After wakeup from SLEEP mode, the peripheral clock is enabled again.
By default, all peripheral clocks are enabled during SLEEP mode.
Parameters
RCC_AHBPeriph specifies the AHB1 peripheral to gates its clock. This parameter can be any combination of the following values:
RCC_AHB1Periph_GPIOA: GPIOA clock
RCC_AHB1Periph_GPIOB: GPIOB clock
RCC_AHB1Periph_GPIOC: GPIOC clock
RCC_AHB1Periph_GPIOD: GPIOD clock
RCC_AHB1Periph_GPIOE: GPIOE clock
RCC_AHB1Periph_GPIOF: GPIOF clock
RCC_AHB1Periph_GPIOG: GPIOG clock
RCC_AHB1Periph_GPIOG: GPIOG clock
RCC_AHB1Periph_GPIOI: GPIOI clock
RCC_AHB1Periph_CRC: CRC clock
RCC_AHB1Periph_BKPSRAM: BKPSRAM interface clock
RCC_AHB1Periph_DMA1: DMA1 clock
RCC_AHB1Periph_DMA2: DMA2 clock
RCC_AHB1Periph_ETH_MAC: Ethernet MAC clock
RCC_AHB1Periph_ETH_MAC_Tx: Ethernet Transmission clock
RCC_AHB1Periph_ETH_MAC_Rx: Ethernet Reception clock
RCC_AHB1Periph_ETH_MAC_PTP: Ethernet PTP clock
RCC_AHB1Periph_OTG_HS: USB OTG HS clock
RCC_AHB1Periph_OTG_HS_ULPI: USB OTG HS ULPI clock
NewState new state of the specified peripheral clock. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1455 of file stm32f4xx_rcc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_RCC_AHB1_LPMODE_PERIPH(RCC_AHB1Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->AHB1LPENR |= RCC_AHB1Periph;
  }
  else
  {
    RCC->AHB1LPENR &= ~RCC_AHB1Periph;
  }
}
RCC_AHB1PeriphResetCmd()
void RCC_AHB1PeriphResetCmd (uint32_t RCC_AHB1Periph, FunctionalState NewState)
Forces or releases AHB1 peripheral reset.
Parameters
RCC_AHB1Periph specifies the AHB1 peripheral to reset. This parameter can be any combination of the following values:
RCC_AHB1Periph_GPIOA: GPIOA clock
RCC_AHB1Periph_GPIOB: GPIOB clock
RCC_AHB1Periph_GPIOC: GPIOC clock
RCC_AHB1Periph_GPIOD: GPIOD clock
RCC_AHB1Periph_GPIOE: GPIOE clock
RCC_AHB1Periph_GPIOF: GPIOF clock
RCC_AHB1Periph_GPIOG: GPIOG clock
RCC_AHB1Periph_GPIOG: GPIOG clock
RCC_AHB1Periph_GPIOI: GPIOI clock
RCC_AHB1Periph_CRC: CRC clock
RCC_AHB1Periph_DMA1: DMA1 clock
RCC_AHB1Periph_DMA2: DMA2 clock
RCC_AHB1Periph_ETH_MAC: Ethernet MAC clock
RCC_AHB1Periph_OTG_HS: USB OTG HS clock
NewState new state of the specified peripheral reset. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1273 of file stm32f4xx_rcc.c.
References DISABLE.
Referenced by GPIO_DeInit().
{
  /* Check the parameters */
  assert_param(IS_RCC_AHB1_RESET_PERIPH(RCC_AHB1Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->AHB1RSTR |= RCC_AHB1Periph;
  }
  else
  {
    RCC->AHB1RSTR &= ~RCC_AHB1Periph;
  }
}
RCC_AHB2PeriphClockCmd()
void RCC_AHB2PeriphClockCmd (uint32_t RCC_AHB2Periph, FunctionalState NewState)
Enables or disables the AHB2 peripheral clock.
Note
After reset, the peripheral clock (used for registers read/write access) is disabled and the application software has to enable this clock before using it.
Parameters
RCC_AHBPeriph specifies the AHB2 peripheral to gates its clock. This parameter can be any combination of the following values:
RCC_AHB2Periph_DCMI: DCMI clock
RCC_AHB2Periph_CRYP: CRYP clock
RCC_AHB2Periph_HASH: HASH clock
RCC_AHB2Periph_RNG: RNG clock
RCC_AHB2Periph_OTG_FS: USB OTG FS clock
NewState new state of the specified peripheral clock. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1117 of file stm32f4xx_rcc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_RCC_AHB2_PERIPH(RCC_AHB2Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->AHB2ENR |= RCC_AHB2Periph;
  }
  else
  {
    RCC->AHB2ENR &= ~RCC_AHB2Periph;
  }
}
RCC_AHB2PeriphClockLPModeCmd()
void RCC_AHB2PeriphClockLPModeCmd (uint32_t RCC_AHB2Periph, FunctionalState NewState)
Enables or disables the AHB2 peripheral clock during Low Power (Sleep) mode.
Note
Peripheral clock gating in SLEEP mode can be used to further reduce power consumption.
After wakeup from SLEEP mode, the peripheral clock is enabled again.
By default, all peripheral clocks are enabled during SLEEP mode.
Parameters
RCC_AHBPeriph specifies the AHB2 peripheral to gates its clock. This parameter can be any combination of the following values:
RCC_AHB2Periph_DCMI: DCMI clock
RCC_AHB2Periph_CRYP: CRYP clock
RCC_AHB2Periph_HASH: HASH clock
RCC_AHB2Periph_RNG: RNG clock
RCC_AHB2Periph_OTG_FS: USB OTG FS clock
NewState new state of the specified peripheral clock. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1487 of file stm32f4xx_rcc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_RCC_AHB2_PERIPH(RCC_AHB2Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->AHB2LPENR |= RCC_AHB2Periph;
  }
  else
  {
    RCC->AHB2LPENR &= ~RCC_AHB2Periph;
  }
}
RCC_AHB2PeriphResetCmd()
void RCC_AHB2PeriphResetCmd (uint32_t RCC_AHB2Periph, FunctionalState NewState)
Forces or releases AHB2 peripheral reset.
Parameters
RCC_AHB2Periph specifies the AHB2 peripheral to reset. This parameter can be any combination of the following values:
RCC_AHB2Periph_DCMI: DCMI clock
RCC_AHB2Periph_CRYP: CRYP clock
RCC_AHB2Periph_HASH: HASH clock
RCC_AHB2Periph_RNG: RNG clock
RCC_AHB2Periph_OTG_FS: USB OTG FS clock
NewState new state of the specified peripheral reset. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1302 of file stm32f4xx_rcc.c.
References DISABLE.
Referenced by CRYP_DeInit(), HASH_DeInit(), and RNG_DeInit().
{
  /* Check the parameters */
  assert_param(IS_RCC_AHB2_PERIPH(RCC_AHB2Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->AHB2RSTR |= RCC_AHB2Periph;
  }
  else
  {
    RCC->AHB2RSTR &= ~RCC_AHB2Periph;
  }
}
RCC_AHB3PeriphClockCmd()
void RCC_AHB3PeriphClockCmd (uint32_t RCC_AHB3Periph, FunctionalState NewState)
Enables or disables the AHB3 peripheral clock.
Note
After reset, the peripheral clock (used for registers read/write access) is disabled and the application software has to enable this clock before using it.
Parameters
RCC_AHBPeriph specifies the AHB3 peripheral to gates its clock. This parameter must be: RCC_AHB3Periph_FSMC
NewState new state of the specified peripheral clock. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1144 of file stm32f4xx_rcc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_RCC_AHB3_PERIPH(RCC_AHB3Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->AHB3ENR |= RCC_AHB3Periph;
  }
  else
  {
    RCC->AHB3ENR &= ~RCC_AHB3Periph;
  }
}
RCC_AHB3PeriphClockLPModeCmd()
void RCC_AHB3PeriphClockLPModeCmd (uint32_t RCC_AHB3Periph, FunctionalState NewState)
Enables or disables the AHB3 peripheral clock during Low Power (Sleep) mode.
Note
Peripheral clock gating in SLEEP mode can be used to further reduce power consumption.
After wakeup from SLEEP mode, the peripheral clock is enabled again.
By default, all peripheral clocks are enabled during SLEEP mode.
Parameters
RCC_AHBPeriph specifies the AHB3 peripheral to gates its clock. This parameter must be: RCC_AHB3Periph_FSMC
NewState new state of the specified peripheral clock. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1514 of file stm32f4xx_rcc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_RCC_AHB3_PERIPH(RCC_AHB3Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->AHB3LPENR |= RCC_AHB3Periph;
  }
  else
  {
    RCC->AHB3LPENR &= ~RCC_AHB3Periph;
  }
}
RCC_AHB3PeriphResetCmd()
void RCC_AHB3PeriphResetCmd (uint32_t RCC_AHB3Periph, FunctionalState NewState)
Forces or releases AHB3 peripheral reset.
Parameters
RCC_AHB3Periph specifies the AHB3 peripheral to reset. This parameter must be: RCC_AHB3Periph_FSMC
NewState new state of the specified peripheral reset. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1326 of file stm32f4xx_rcc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_RCC_AHB3_PERIPH(RCC_AHB3Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->AHB3RSTR |= RCC_AHB3Periph;
  }
  else
  {
    RCC->AHB3RSTR &= ~RCC_AHB3Periph;
  }
}
RCC_APB1PeriphClockCmd()
void RCC_APB1PeriphClockCmd (uint32_t RCC_APB1Periph, FunctionalState NewState)
Enables or disables the Low Speed APB (APB1) peripheral clock.
Note
After reset, the peripheral clock (used for registers read/write access) is disabled and the application software has to enable this clock before using it.
Parameters
RCC_APB1Periph specifies the APB1 peripheral to gates its clock. This parameter can be any combination of the following values:
RCC_APB1Periph_TIM2: TIM2 clock
RCC_APB1Periph_TIM3: TIM3 clock
RCC_APB1Periph_TIM4: TIM4 clock
RCC_APB1Periph_TIM5: TIM5 clock
RCC_APB1Periph_TIM6: TIM6 clock
RCC_APB1Periph_TIM7: TIM7 clock
RCC_APB1Periph_TIM12: TIM12 clock
RCC_APB1Periph_TIM13: TIM13 clock
RCC_APB1Periph_TIM14: TIM14 clock
RCC_APB1Periph_WWDG: WWDG clock
RCC_APB1Periph_SPI2: SPI2 clock
RCC_APB1Periph_SPI3: SPI3 clock
RCC_APB1Periph_USART2: USART2 clock
RCC_APB1Periph_USART3: USART3 clock
RCC_APB1Periph_UART4: UART4 clock
RCC_APB1Periph_UART5: UART5 clock
RCC_APB1Periph_I2C1: I2C1 clock
RCC_APB1Periph_I2C2: I2C2 clock
RCC_APB1Periph_I2C3: I2C3 clock
RCC_APB1Periph_CAN1: CAN1 clock
RCC_APB1Periph_CAN2: CAN2 clock
RCC_APB1Periph_PWR: PWR clock
RCC_APB1Periph_DAC: DAC clock
NewState new state of the specified peripheral clock. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1194 of file stm32f4xx_rcc.c.
References DISABLE.
Referenced by board_init(), and I2cMaster_Init().
{
  /* Check the parameters */
  assert_param(IS_RCC_APB1_PERIPH(RCC_APB1Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->APB1ENR |= RCC_APB1Periph;
  }
  else
  {
    RCC->APB1ENR &= ~RCC_APB1Periph;
  }
}
RCC_APB1PeriphClockLPModeCmd()
void RCC_APB1PeriphClockLPModeCmd (uint32_t RCC_APB1Periph, FunctionalState NewState)
Enables or disables the APB1 peripheral clock during Low Power (Sleep) mode.
Note
Peripheral clock gating in SLEEP mode can be used to further reduce power consumption.
After wakeup from SLEEP mode, the peripheral clock is enabled again.
By default, all peripheral clocks are enabled during SLEEP mode.
Parameters
RCC_APB1Periph specifies the APB1 peripheral to gates its clock. This parameter can be any combination of the following values:
RCC_APB1Periph_TIM2: TIM2 clock
RCC_APB1Periph_TIM3: TIM3 clock
RCC_APB1Periph_TIM4: TIM4 clock
RCC_APB1Periph_TIM5: TIM5 clock
RCC_APB1Periph_TIM6: TIM6 clock
RCC_APB1Periph_TIM7: TIM7 clock
RCC_APB1Periph_TIM12: TIM12 clock
RCC_APB1Periph_TIM13: TIM13 clock
RCC_APB1Periph_TIM14: TIM14 clock
RCC_APB1Periph_WWDG: WWDG clock
RCC_APB1Periph_SPI2: SPI2 clock
RCC_APB1Periph_SPI3: SPI3 clock
RCC_APB1Periph_USART2: USART2 clock
RCC_APB1Periph_USART3: USART3 clock
RCC_APB1Periph_UART4: UART4 clock
RCC_APB1Periph_UART5: UART5 clock
RCC_APB1Periph_I2C1: I2C1 clock
RCC_APB1Periph_I2C2: I2C2 clock
RCC_APB1Periph_I2C3: I2C3 clock
RCC_APB1Periph_CAN1: CAN1 clock
RCC_APB1Periph_CAN2: CAN2 clock
RCC_APB1Periph_PWR: PWR clock
RCC_APB1Periph_DAC: DAC clock
NewState new state of the specified peripheral clock. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1564 of file stm32f4xx_rcc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_RCC_APB1_PERIPH(RCC_APB1Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->APB1LPENR |= RCC_APB1Periph;
  }
  else
  {
    RCC->APB1LPENR &= ~RCC_APB1Periph;
  }
}
RCC_APB1PeriphResetCmd()
void RCC_APB1PeriphResetCmd (uint32_t RCC_APB1Periph, FunctionalState NewState)
Forces or releases Low Speed APB (APB1) peripheral reset.
Parameters
RCC_APB1Periph specifies the APB1 peripheral to reset. This parameter can be any combination of the following values:
RCC_APB1Periph_TIM2: TIM2 clock
RCC_APB1Periph_TIM3: TIM3 clock
RCC_APB1Periph_TIM4: TIM4 clock
RCC_APB1Periph_TIM5: TIM5 clock
RCC_APB1Periph_TIM6: TIM6 clock
RCC_APB1Periph_TIM7: TIM7 clock
RCC_APB1Periph_TIM12: TIM12 clock
RCC_APB1Periph_TIM13: TIM13 clock
RCC_APB1Periph_TIM14: TIM14 clock
RCC_APB1Periph_WWDG: WWDG clock
RCC_APB1Periph_SPI2: SPI2 clock
RCC_APB1Periph_SPI3: SPI3 clock
RCC_APB1Periph_USART2: USART2 clock
RCC_APB1Periph_USART3: USART3 clock
RCC_APB1Periph_UART4: UART4 clock
RCC_APB1Periph_UART5: UART5 clock
RCC_APB1Periph_I2C1: I2C1 clock
RCC_APB1Periph_I2C2: I2C2 clock
RCC_APB1Periph_I2C3: I2C3 clock
RCC_APB1Periph_CAN1: CAN1 clock
RCC_APB1Periph_CAN2: CAN2 clock
RCC_APB1Periph_PWR: PWR clock
RCC_APB1Periph_DAC: DAC clock
NewState new state of the specified peripheral reset. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1373 of file stm32f4xx_rcc.c.
References DISABLE.
Referenced by CAN_DeInit(), DAC_DeInit(), I2C_DeInit(), PWR_DeInit(), SPI_I2S_DeInit(), TIM_DeInit(), USART_DeInit(), and WWDG_DeInit().
{
  /* Check the parameters */
  assert_param(IS_RCC_APB1_PERIPH(RCC_APB1Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->APB1RSTR |= RCC_APB1Periph;
  }
  else
  {
    RCC->APB1RSTR &= ~RCC_APB1Periph;
  }
}
RCC_APB2PeriphClockCmd()
void RCC_APB2PeriphClockCmd (uint32_t RCC_APB2Periph, FunctionalState NewState)
Enables or disables the High Speed APB (APB2) peripheral clock.
Note
After reset, the peripheral clock (used for registers read/write access) is disabled and the application software has to enable this clock before using it.
Parameters
RCC_APB2Periph specifies the APB2 peripheral to gates its clock. This parameter can be any combination of the following values:
RCC_APB2Periph_TIM1: TIM1 clock
RCC_APB2Periph_TIM8: TIM8 clock
RCC_APB2Periph_USART1: USART1 clock
RCC_APB2Periph_USART6: USART6 clock
RCC_APB2Periph_ADC1: ADC1 clock
RCC_APB2Periph_ADC2: ADC2 clock
RCC_APB2Periph_ADC3: ADC3 clock
RCC_APB2Periph_SDIO: SDIO clock
RCC_APB2Periph_SPI1: SPI1 clock
RCC_APB2Periph_SYSCFG: SYSCFG clock
RCC_APB2Periph_TIM9: TIM9 clock
RCC_APB2Periph_TIM10: TIM10 clock
RCC_APB2Periph_TIM11: TIM11 clock
NewState new state of the specified peripheral clock. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1234 of file stm32f4xx_rcc.c.
References DISABLE.
Referenced by GPIO_Config(), STM_EVAL_PBInit(), and USART_Config().
{
  /* Check the parameters */
  assert_param(IS_RCC_APB2_PERIPH(RCC_APB2Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->APB2ENR |= RCC_APB2Periph;
  }
  else
  {
    RCC->APB2ENR &= ~RCC_APB2Periph;
  }
}
RCC_APB2PeriphClockLPModeCmd()
void RCC_APB2PeriphClockLPModeCmd (uint32_t RCC_APB2Periph, FunctionalState NewState)
Enables or disables the APB2 peripheral clock during Low Power (Sleep) mode.
Note
Peripheral clock gating in SLEEP mode can be used to further reduce power consumption.
After wakeup from SLEEP mode, the peripheral clock is enabled again.
By default, all peripheral clocks are enabled during SLEEP mode.
Parameters
RCC_APB2Periph specifies the APB2 peripheral to gates its clock. This parameter can be any combination of the following values:
RCC_APB2Periph_TIM1: TIM1 clock
RCC_APB2Periph_TIM8: TIM8 clock
RCC_APB2Periph_USART1: USART1 clock
RCC_APB2Periph_USART6: USART6 clock
RCC_APB2Periph_ADC1: ADC1 clock
RCC_APB2Periph_ADC2: ADC2 clock
RCC_APB2Periph_ADC3: ADC3 clock
RCC_APB2Periph_SDIO: SDIO clock
RCC_APB2Periph_SPI1: SPI1 clock
RCC_APB2Periph_SYSCFG: SYSCFG clock
RCC_APB2Periph_TIM9: TIM9 clock
RCC_APB2Periph_TIM10: TIM10 clock
RCC_APB2Periph_TIM11: TIM11 clock
NewState new state of the specified peripheral clock. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1604 of file stm32f4xx_rcc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_RCC_APB2_PERIPH(RCC_APB2Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->APB2LPENR |= RCC_APB2Periph;
  }
  else
  {
    RCC->APB2LPENR &= ~RCC_APB2Periph;
  }
}
RCC_APB2PeriphResetCmd()
void RCC_APB2PeriphResetCmd (uint32_t RCC_APB2Periph, FunctionalState NewState)
Forces or releases High Speed APB (APB2) peripheral reset.
Parameters
RCC_APB2Periph specifies the APB2 peripheral to reset. This parameter can be any combination of the following values:
RCC_APB2Periph_TIM1: TIM1 clock
RCC_APB2Periph_TIM8: TIM8 clock
RCC_APB2Periph_USART1: USART1 clock
RCC_APB2Periph_USART6: USART6 clock
RCC_APB2Periph_ADC1: ADC1 clock
RCC_APB2Periph_ADC2: ADC2 clock
RCC_APB2Periph_ADC3: ADC3 clock
RCC_APB2Periph_SDIO: SDIO clock
RCC_APB2Periph_SPI1: SPI1 clock
RCC_APB2Periph_SYSCFG: SYSCFG clock
RCC_APB2Periph_TIM9: TIM9 clock
RCC_APB2Periph_TIM10: TIM10 clock
RCC_APB2Periph_TIM11: TIM11 clock
NewState new state of the specified peripheral reset. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1409 of file stm32f4xx_rcc.c.
References DISABLE.
Referenced by ADC_DeInit(), SDIO_DeInit(), SPI_I2S_DeInit(), SYSCFG_DeInit(), TIM_DeInit(), and USART_DeInit().
{
  /* Check the parameters */
  assert_param(IS_RCC_APB2_RESET_PERIPH(RCC_APB2Periph));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    RCC->APB2RSTR |= RCC_APB2Periph;
  }
  else
  {
    RCC->APB2RSTR &= ~RCC_APB2Periph;
  }
}
RCC_BackupResetCmd()
void RCC_BackupResetCmd (FunctionalState NewState)
Forces or releases the Backup domain reset.
Note
This function resets the RTC peripheral (including the backup registers) and the RTC clock source selection in RCC_CSR register.
The BKPSRAM is not affected by this reset.
Parameters
NewState new state of the Backup domain reset. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1029 of file stm32f4xx_rcc.c.
Referenced by board_init().
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  *(__IO uint32_t *) BDCR_BDRST_BB = (uint32_t)NewState;
}
RCC_ClearFlag()
void RCC_ClearFlag (void)
Clears the RCC reset flags. The reset flags are: RCC_FLAG_PINRST, RCC_FLAG_PORRST, RCC_FLAG_SFTRST, RCC_FLAG_IWDGRST, RCC_FLAG_WWDGRST, RCC_FLAG_LPWRRST.
Parameters
None
Return values
None
Definition at line 1730 of file stm32f4xx_rcc.c.
{
  /* Set RMVF bit to clear the reset flags */
  RCC->CSR |= RCC_CSR_RMVF;
}
RCC_ClearITPendingBit()
void RCC_ClearITPendingBit (uint8_t RCC_IT)
Clears the RCC's interrupt pending bits.
Parameters
RCC_IT specifies the interrupt pending bit to clear. This parameter can be any combination of the following values:
RCC_IT_LSIRDY: LSI ready interrupt
RCC_IT_LSERDY: LSE ready interrupt
RCC_IT_HSIRDY: HSI ready interrupt
RCC_IT_HSERDY: HSE ready interrupt
RCC_IT_PLLRDY: main PLL ready interrupt
RCC_IT_PLLI2SRDY: PLLI2S ready interrupt
RCC_IT_CSS: Clock Security System interrupt
Return values
None
Definition at line 1782 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_RCC_CLEAR_IT(RCC_IT));
  /* Perform Byte access to RCC_CIR[23:16] bits to clear the selected interrupt
     pending bits */
  *(__IO uint8_t *) CIR_BYTE3_ADDRESS = RCC_IT;
}
RCC_ClockSecuritySystemCmd()
void RCC_ClockSecuritySystemCmd (FunctionalState NewState)
Enables or disables the Clock Security System.
Note
If a failure is detected on the HSE oscillator clock, this oscillator is automatically disabled and an interrupt is generated to inform the software about the failure (Clock Security System Interrupt, CSSI), allowing the MCU to perform rescue operations. The CSSI is linked to the Cortex-M4 NMI (Non-Maskable Interrupt) exception vector.
Parameters
NewState new state of the Clock Security System. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 518 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  *(__IO uint32_t *) CR_CSSON_BB = (uint32_t)NewState;
}
RCC_DeInit()
void RCC_DeInit (void)
Resets the RCC clock configuration to the default reset state.
Note
The default reset state of the clock configuration is given below:
HSI ON and used as system clock source
HSE, PLL and PLLI2S OFF
AHB, APB1 and APB2 prescaler set to 1.
CSS, MCO1 and MCO2 OFF
All interrupts disabled
This function doesn't modify the configuration of the
Peripheral clocks
LSI, LSE and RTC clocks
Parameters
None
Return values
None
Definition at line 196 of file stm32f4xx_rcc.c.
{
  /* Set HSION bit */
  RCC->CR |= (uint32_t)0x00000001;
  /* Reset CFGR register */
  RCC->CFGR = 0x00000000;
  /* Reset HSEON, CSSON and PLLON bits */
  RCC->CR &= (uint32_t)0xFEF6FFFF;
  /* Reset PLLCFGR register */
  RCC->PLLCFGR = 0x24003010;
  /* Reset HSEBYP bit */
  RCC->CR &= (uint32_t)0xFFFBFFFF;
  /* Disable all interrupts */
  RCC->CIR = 0x00000000;
}
RCC_GetClocksFreq()
void RCC_GetClocksFreq (RCC_ClocksTypeDef * RCC_Clocks)
Returns the frequencies of different on chip clocks; SYSCLK, HCLK, PCLK1 and PCLK2.
Note
The system frequency computed by this function is not the real frequency in the chip. It is calculated based on the predefined constant and the selected clock source:
If SYSCLK source is HSI, function returns values based on HSI_VALUE(*)
If SYSCLK source is HSE, function returns values based on HSE_VALUE(**)
If SYSCLK source is PLL, function returns values based on HSE_VALUE(**) or HSI_VALUE(*) multiplied/divided by the PLL factors.
(*) HSI_VALUE is a constant defined in stm32f4xx.h file (default value 16 MHz) but the real value may vary depending on the variations in voltage and temperature.
(**) HSE_VALUE is a constant defined in stm32f4xx.h file (default value 25 MHz), user has to ensure that HSE_VALUE is same as the real frequency of the crystal used. Otherwise, this function may have wrong result.
The result of this function could be not correct when using fractional value for HSE crystal.
Parameters
RCC_Clocks pointer to a RCC_ClocksTypeDef structure which will hold the clocks frequencies.
Note
This function can be used by the user application to compute the baudrate for the communication peripherals or configure other parameters.
Each time SYSCLK, HCLK, PCLK1 and/or PCLK2 clock changes, this function must be called to update the structure's field. Otherwise, any configuration based on this function will be incorrect.
Return values
None
Definition at line 855 of file stm32f4xx_rcc.c.
References RCC_ClocksTypeDef::HCLK_Frequency, RCC_ClocksTypeDef::PCLK1_Frequency, RCC_ClocksTypeDef::PCLK2_Frequency, and RCC_ClocksTypeDef::SYSCLK_Frequency.
Referenced by I2C_Init(), TIM4_IRQHandler(), and USART_Init().
{
  uint32_t tmp = 0, presc = 0, pllvco = 0, pllp = 2, pllsource = 0, pllm = 2;
  /* Get SYSCLK source -------------------------------------------------------*/
  tmp = RCC->CFGR & RCC_CFGR_SWS;
  switch (tmp)
  {
    case 0x00: /* HSI used as system clock source */
      RCC_Clocks->SYSCLK_Frequency = HSI_VALUE;
      break;
    case 0x04: /* HSE used as system clock source */
      RCC_Clocks->SYSCLK_Frequency = HSE_VALUE;
      break;
    case 0x08: /* PLL used as system clock source */
      /* PLL_VCO = (HSE_VALUE or HSI_VALUE / PLLM) * PLLN
         SYSCLK = PLL_VCO / PLLP
         */
      pllsource = (RCC->PLLCFGR & RCC_PLLCFGR_PLLSRC) >> 22;
      pllm = RCC->PLLCFGR & RCC_PLLCFGR_PLLM;
      
      if (pllsource != 0)
      {
        /* HSE used as PLL clock source */
        pllvco = (HSE_VALUE / pllm) * ((RCC->PLLCFGR & RCC_PLLCFGR_PLLN) >> 6);
      }
      else
      {
        /* HSI used as PLL clock source */
        pllvco = (HSI_VALUE / pllm) * ((RCC->PLLCFGR & RCC_PLLCFGR_PLLN) >> 6);
      }
      pllp = (((RCC->PLLCFGR & RCC_PLLCFGR_PLLP) >>16) + 1) *2;
      RCC_Clocks->SYSCLK_Frequency = pllvco/pllp;
      break;
    default:
      RCC_Clocks->SYSCLK_Frequency = HSI_VALUE;
      break;
  }
  /* Compute HCLK, PCLK1 and PCLK2 clocks frequencies ------------------------*/
  /* Get HCLK prescaler */
  tmp = RCC->CFGR & RCC_CFGR_HPRE;
  tmp = tmp >> 4;
  presc = APBAHBPrescTable[tmp];
  /* HCLK clock frequency */
  RCC_Clocks->HCLK_Frequency = RCC_Clocks->SYSCLK_Frequency >> presc;
  /* Get PCLK1 prescaler */
  tmp = RCC->CFGR & RCC_CFGR_PPRE1;
  tmp = tmp >> 10;
  presc = APBAHBPrescTable[tmp];
  /* PCLK1 clock frequency */
  RCC_Clocks->PCLK1_Frequency = RCC_Clocks->HCLK_Frequency >> presc;
  /* Get PCLK2 prescaler */
  tmp = RCC->CFGR & RCC_CFGR_PPRE2;
  tmp = tmp >> 13;
  presc = APBAHBPrescTable[tmp];
  /* PCLK2 clock frequency */
  RCC_Clocks->PCLK2_Frequency = RCC_Clocks->HCLK_Frequency >> presc;
}
RCC_GetFlagStatus()
 FlagStatus RCC_GetFlagStatus (uint8_t RCC_FLAG)
Checks whether the specified RCC flag is set or not.
Parameters
RCC_FLAG specifies the flag to check. This parameter can be one of the following values:
RCC_FLAG_HSIRDY: HSI oscillator clock ready
RCC_FLAG_HSERDY: HSE oscillator clock ready
RCC_FLAG_PLLRDY: main PLL clock ready
RCC_FLAG_PLLI2SRDY: PLLI2S clock ready
RCC_FLAG_LSERDY: LSE oscillator clock ready
RCC_FLAG_LSIRDY: LSI oscillator clock ready
RCC_FLAG_BORRST: POR/PDR or BOR reset
RCC_FLAG_PINRST: Pin reset
RCC_FLAG_PORRST: POR/PDR reset
RCC_FLAG_SFTRST: Software reset
RCC_FLAG_IWDGRST: Independent Watchdog reset
RCC_FLAG_WWDGRST: Window Watchdog reset
RCC_FLAG_LPWRRST: Low Power reset
Return values
The new state of RCC_FLAG (SET or RESET).
Definition at line 1685 of file stm32f4xx_rcc.c.
References RESET, and SET.
Referenced by RCC_WaitForHSEStartUp().
{
  uint32_t tmp = 0;
  uint32_t statusreg = 0;
  FlagStatus bitstatus = RESET;
  /* Check the parameters */
  assert_param(IS_RCC_FLAG(RCC_FLAG));
  /* Get the RCC register index */
  tmp = RCC_FLAG >> 5;
  if (tmp == 1) /* The flag to check is in CR register */
  {
    statusreg = RCC->CR;
  }
  else if (tmp == 2) /* The flag to check is in BDCR register */
  {
    statusreg = RCC->BDCR;
  }
  else /* The flag to check is in CSR register */
  {
    statusreg = RCC->CSR;
  }
  /* Get the flag position */
  tmp = RCC_FLAG & FLAG_MASK;
  if ((statusreg & ((uint32_t)1 << tmp)) != (uint32_t)RESET)
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  /* Return the flag status */
  return bitstatus;
}
RCC_GetITStatus()
 ITStatus RCC_GetITStatus (uint8_t RCC_IT)
Checks whether the specified RCC interrupt has occurred or not.
Parameters
RCC_IT specifies the RCC interrupt source to check. This parameter can be one of the following values:
RCC_IT_LSIRDY: LSI ready interrupt
RCC_IT_LSERDY: LSE ready interrupt
RCC_IT_HSIRDY: HSI ready interrupt
RCC_IT_HSERDY: HSE ready interrupt
RCC_IT_PLLRDY: main PLL ready interrupt
RCC_IT_PLLI2SRDY: PLLI2S ready interrupt
RCC_IT_CSS: Clock Security System interrupt
Return values
The new state of RCC_IT (SET or RESET).
Definition at line 1749 of file stm32f4xx_rcc.c.
References RESET.
{
  ITStatus bitstatus = RESET;
  /* Check the parameters */
  assert_param(IS_RCC_GET_IT(RCC_IT));
  /* Check the status of the specified RCC interrupt */
  if ((RCC->CIR & RCC_IT) != (uint32_t)RESET)
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  /* Return the RCC_IT status */
  return bitstatus;
}
RCC_GetSYSCLKSource()
uint8_t RCC_GetSYSCLKSource (void)
Returns the clock source used as system clock.
Parameters
None
Return values
The clock source used as system clock. The returned value can be one of the following:
0x00: HSI used as system clock
0x04: HSE used as system clock
0x08: PLL used as system clock
Definition at line 715 of file stm32f4xx_rcc.c.
{
  return ((uint8_t)(RCC->CFGR & RCC_CFGR_SWS));
}
RCC_HCLKConfig()
void RCC_HCLKConfig (uint32_t RCC_SYSCLK)
Configures the AHB clock (HCLK).
Note
Depending on the device voltage range, the software has to set correctly these bits to ensure that HCLK not exceed the maximum allowed frequency (for more details refer to section above `CPU, AHB and APB busses clocks configuration functions`)
Parameters
RCC_SYSCLK defines the AHB clock divider. This clock is derived from the system clock (SYSCLK). This parameter can be one of the following values:
RCC_SYSCLK_Div1: AHB clock = SYSCLK
RCC_SYSCLK_Div2: AHB clock = SYSCLK/2
RCC_SYSCLK_Div4: AHB clock = SYSCLK/4
RCC_SYSCLK_Div8: AHB clock = SYSCLK/8
RCC_SYSCLK_Div16: AHB clock = SYSCLK/16
RCC_SYSCLK_Div64: AHB clock = SYSCLK/64
RCC_SYSCLK_Div128: AHB clock = SYSCLK/128
RCC_SYSCLK_Div256: AHB clock = SYSCLK/256
RCC_SYSCLK_Div512: AHB clock = SYSCLK/512
Return values
None
Definition at line 740 of file stm32f4xx_rcc.c.
{
  uint32_t tmpreg = 0;
  
  /* Check the parameters */
  assert_param(IS_RCC_HCLK(RCC_SYSCLK));
  tmpreg = RCC->CFGR;
  /* Clear HPRE[3:0] bits */
  tmpreg &= ~RCC_CFGR_HPRE;
  /* Set HPRE[3:0] bits according to RCC_SYSCLK value */
  tmpreg |= RCC_SYSCLK;
  /* Store the new value */
  RCC->CFGR = tmpreg;
}
RCC_HSEConfig()
void RCC_HSEConfig (uint8_t RCC_HSE)
Configures the External High Speed oscillator (HSE).
Note
After enabling the HSE (RCC_HSE_ON or RCC_HSE_Bypass), the application software should wait on HSERDY flag to be set indicating that HSE clock is stable and can be used to clock the PLL and/or system clock.
HSE state can not be changed if it is used directly or through the PLL as system clock. In this case, you have to select another source of the system clock then change the HSE state (ex. disable it).
The HSE is stopped by hardware when entering STOP and STANDBY modes.
This function reset the CSSON bit, so if the Clock security system(CSS) was previously enabled you have to enable it again after calling this function.
Parameters
RCC_HSE specifies the new state of the HSE. This parameter can be one of the following values:
RCC_HSE_OFF: turn OFF the HSE oscillator, HSERDY flag goes low after 6 HSE oscillator clock cycles.
RCC_HSE_ON: turn ON the HSE oscillator
RCC_HSE_Bypass: HSE oscillator bypassed with external clock
Return values
None
Definition at line 237 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_RCC_HSE(RCC_HSE));
  /* Reset HSEON and HSEBYP bits before configuring the HSE ------------------*/
  *(__IO uint8_t *) CR_BYTE3_ADDRESS = RCC_HSE_OFF;
  /* Set the new HSE configuration -------------------------------------------*/
  *(__IO uint8_t *) CR_BYTE3_ADDRESS = RCC_HSE;
}
RCC_HSICmd()
void RCC_HSICmd (FunctionalState NewState)
Enables or disables the Internal High Speed oscillator (HSI).
Note
The HSI is stopped by hardware when entering STOP and STANDBY modes. It is used (enabled by hardware) as system clock source after startup from Reset, wakeup from STOP and STANDBY mode, or in case of failure of the HSE used directly or indirectly as system clock (if the Clock Security System CSS is enabled).
HSI can not be stopped if it is used as system clock source. In this case, you have to select another source of the system clock then stop the HSI.
After enabling the HSI, the application software should wait on HSIRDY flag to be set indicating that HSI clock is stable and can be used as system clock source.
Parameters
NewState new state of the HSI. This parameter can be: ENABLE or DISABLE.
Note
When the HSI is stopped, HSIRDY flag goes low after 6 HSI oscillator clock cycles.
Return values
None
Definition at line 328 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  *(__IO uint32_t *) CR_HSION_BB = (uint32_t)NewState;
}
RCC_I2SCLKConfig()
void RCC_I2SCLKConfig (uint32_t RCC_I2SCLKSource)
Configures the I2S clock source (I2SCLK).
Note
This function must be called before enabling the I2S APB clock.
Parameters
RCC_I2SCLKSource specifies the I2S clock source. This parameter can be one of the following values:
RCC_I2S2CLKSource_PLLI2S: PLLI2S clock used as I2S clock source
RCC_I2S2CLKSource_Ext: External clock mapped on the I2S_CKIN pin used as I2S clock source
Return values
None
Definition at line 1046 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_RCC_I2SCLK_SOURCE(RCC_I2SCLKSource));
  *(__IO uint32_t *) CFGR_I2SSRC_BB = RCC_I2SCLKSource;
}
RCC_ITConfig()
void RCC_ITConfig (uint8_t RCC_IT, FunctionalState NewState)
Enables or disables the specified RCC interrupts.
Parameters
RCC_IT specifies the RCC interrupt sources to be enabled or disabled. This parameter can be any combination of the following values:
RCC_IT_LSIRDY: LSI ready interrupt
RCC_IT_LSERDY: LSE ready interrupt
RCC_IT_HSIRDY: HSI ready interrupt
RCC_IT_HSERDY: HSE ready interrupt
RCC_IT_PLLRDY: main PLL ready interrupt
RCC_IT_PLLI2SRDY: PLLI2S ready interrupt
NewState new state of the specified RCC interrupts. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1649 of file stm32f4xx_rcc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_RCC_IT(RCC_IT));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Perform Byte access to RCC_CIR[14:8] bits to enable the selected interrupts */
    *(__IO uint8_t *) CIR_BYTE2_ADDRESS |= RCC_IT;
  }
  else
  {
    /* Perform Byte access to RCC_CIR[14:8] bits to disable the selected interrupts */
    *(__IO uint8_t *) CIR_BYTE2_ADDRESS &= (uint8_t)~RCC_IT;
  }
}
RCC_LSEConfig()
void RCC_LSEConfig (uint8_t RCC_LSE)
Configures the External Low Speed oscillator (LSE).
Note
As the LSE is in the Backup domain and write access is denied to this domain after reset, you have to enable write access using PWR_BackupAccessCmd(ENABLE) function before to configure the LSE (to be done once after reset).
After enabling the LSE (RCC_LSE_ON or RCC_LSE_Bypass), the application software should wait on LSERDY flag to be set indicating that LSE clock is stable and can be used to clock the RTC.
Parameters
RCC_LSE specifies the new state of the LSE. This parameter can be one of the following values:
RCC_LSE_OFF: turn OFF the LSE oscillator, LSERDY flag goes low after 6 LSE oscillator clock cycles.
RCC_LSE_ON: turn ON the LSE oscillator
RCC_LSE_Bypass: LSE oscillator bypassed with external clock
Return values
None
Definition at line 353 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_RCC_LSE(RCC_LSE));
  /* Reset LSEON and LSEBYP bits before configuring the LSE ------------------*/
  /* Reset LSEON bit */
  *(__IO uint8_t *) BDCR_ADDRESS = RCC_LSE_OFF;
  /* Reset LSEBYP bit */
  *(__IO uint8_t *) BDCR_ADDRESS = RCC_LSE_OFF;
  /* Configure LSE (RCC_LSE_OFF is already covered by the code section above) */
  switch (RCC_LSE)
  {
    case RCC_LSE_ON:
      /* Set LSEON bit */
      *(__IO uint8_t *) BDCR_ADDRESS = RCC_LSE_ON;
      break;
    case RCC_LSE_Bypass:
      /* Set LSEBYP and LSEON bits */
      *(__IO uint8_t *) BDCR_ADDRESS = RCC_LSE_Bypass | RCC_LSE_ON;
      break;
    default:
      break;
  }
}
RCC_LSICmd()
void RCC_LSICmd (FunctionalState NewState)
Enables or disables the Internal Low Speed oscillator (LSI).
Note
After enabling the LSI, the application software should wait on LSIRDY flag to be set indicating that LSI clock is stable and can be used to clock the IWDG and/or the RTC.
LSI can not be disabled if the IWDG is running.
Parameters
NewState new state of the LSI. This parameter can be: ENABLE or DISABLE.
Note
When the LSI is stopped, LSIRDY flag goes low after 6 LSI oscillator clock cycles.
Return values
None
Definition at line 393 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  *(__IO uint32_t *) CSR_LSION_BB = (uint32_t)NewState;
}
RCC_MCO1Config()
void RCC_MCO1Config (uint32_t RCC_MCO1Source, uint32_t RCC_MCO1Div)
Selects the clock source to output on MCO1 pin(PA8).
Note
PA8 should be configured in alternate function mode.
Parameters
RCC_MCO1Source specifies the clock source to output. This parameter can be one of the following values:
RCC_MCO1Source_HSI: HSI clock selected as MCO1 source
RCC_MCO1Source_LSE: LSE clock selected as MCO1 source
RCC_MCO1Source_HSE: HSE clock selected as MCO1 source
RCC_MCO1Source_PLLCLK: main PLL clock selected as MCO1 source
RCC_MCO1Div specifies the MCO1 prescaler. This parameter can be one of the following values:
RCC_MCO1Div_1: no division applied to MCO1 clock
RCC_MCO1Div_2: division by 2 applied to MCO1 clock
RCC_MCO1Div_3: division by 3 applied to MCO1 clock
RCC_MCO1Div_4: division by 4 applied to MCO1 clock
RCC_MCO1Div_5: division by 5 applied to MCO1 clock
Return values
None
Definition at line 543 of file stm32f4xx_rcc.c.
{
  uint32_t tmpreg = 0;
  
  /* Check the parameters */
  assert_param(IS_RCC_MCO1SOURCE(RCC_MCO1Source));
  assert_param(IS_RCC_MCO1DIV(RCC_MCO1Div));
  tmpreg = RCC->CFGR;
  /* Clear MCO1[1:0] and MCO1PRE[2:0] bits */
  tmpreg &= CFGR_MCO1_RESET_MASK;
  /* Select MCO1 clock source and prescaler */
  tmpreg |= RCC_MCO1Source | RCC_MCO1Div;
  /* Store the new value */
  RCC->CFGR = tmpreg;
}
RCC_MCO2Config()
void RCC_MCO2Config (uint32_t RCC_MCO2Source, uint32_t RCC_MCO2Div)
Selects the clock source to output on MCO2 pin(PC9).
Note
PC9 should be configured in alternate function mode.
Parameters
RCC_MCO2Source specifies the clock source to output. This parameter can be one of the following values:
RCC_MCO2Source_SYSCLK: System clock (SYSCLK) selected as MCO2 source
RCC_MCO2Source_PLLI2SCLK: PLLI2S clock selected as MCO2 source
RCC_MCO2Source_HSE: HSE clock selected as MCO2 source
RCC_MCO2Source_PLLCLK: main PLL clock selected as MCO2 source
RCC_MCO2Div specifies the MCO2 prescaler. This parameter can be one of the following values:
RCC_MCO2Div_1: no division applied to MCO2 clock
RCC_MCO2Div_2: division by 2 applied to MCO2 clock
RCC_MCO2Div_3: division by 3 applied to MCO2 clock
RCC_MCO2Div_4: division by 4 applied to MCO2 clock
RCC_MCO2Div_5: division by 5 applied to MCO2 clock
Return values
None
Definition at line 581 of file stm32f4xx_rcc.c.
{
  uint32_t tmpreg = 0;
  
  /* Check the parameters */
  assert_param(IS_RCC_MCO2SOURCE(RCC_MCO2Source));
  assert_param(IS_RCC_MCO2DIV(RCC_MCO2Div));
  
  tmpreg = RCC->CFGR;
  
  /* Clear MCO2 and MCO2PRE[2:0] bits */
  tmpreg &= CFGR_MCO2_RESET_MASK;
  /* Select MCO2 clock source and prescaler */
  tmpreg |= RCC_MCO2Source | RCC_MCO2Div;
  /* Store the new value */
  RCC->CFGR = tmpreg;
}
RCC_PCLK1Config()
void RCC_PCLK1Config (uint32_t RCC_HCLK)
Configures the Low Speed APB clock (PCLK1).
Parameters
RCC_HCLK defines the APB1 clock divider. This clock is derived from the AHB clock (HCLK). This parameter can be one of the following values:
RCC_HCLK_Div1: APB1 clock = HCLK
RCC_HCLK_Div2: APB1 clock = HCLK/2
RCC_HCLK_Div4: APB1 clock = HCLK/4
RCC_HCLK_Div8: APB1 clock = HCLK/8
RCC_HCLK_Div16: APB1 clock = HCLK/16
Return values
None
Definition at line 772 of file stm32f4xx_rcc.c.
{
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_RCC_PCLK(RCC_HCLK));
  tmpreg = RCC->CFGR;
  /* Clear PPRE1[2:0] bits */
  tmpreg &= ~RCC_CFGR_PPRE1;
  /* Set PPRE1[2:0] bits according to RCC_HCLK value */
  tmpreg |= RCC_HCLK;
  /* Store the new value */
  RCC->CFGR = tmpreg;
}
RCC_PCLK2Config()
void RCC_PCLK2Config (uint32_t RCC_HCLK)
Configures the High Speed APB clock (PCLK2).
Parameters
RCC_HCLK defines the APB2 clock divider. This clock is derived from the AHB clock (HCLK). This parameter can be one of the following values:
RCC_HCLK_Div1: APB2 clock = HCLK
RCC_HCLK_Div2: APB2 clock = HCLK/2
RCC_HCLK_Div4: APB2 clock = HCLK/4
RCC_HCLK_Div8: APB2 clock = HCLK/8
RCC_HCLK_Div16: APB2 clock = HCLK/16
Return values
None
Definition at line 803 of file stm32f4xx_rcc.c.
{
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_RCC_PCLK(RCC_HCLK));
  tmpreg = RCC->CFGR;
  /* Clear PPRE2[2:0] bits */
  tmpreg &= ~RCC_CFGR_PPRE2;
  /* Set PPRE2[2:0] bits according to RCC_HCLK value */
  tmpreg |= RCC_HCLK << 3;
  /* Store the new value */
  RCC->CFGR = tmpreg;
}
RCC_PLLCmd()
void RCC_PLLCmd (FunctionalState NewState)
Enables or disables the main PLL.
Note
After enabling the main PLL, the application software should wait on PLLRDY flag to be set indicating that PLL clock is stable and can be used as system clock source.
The main PLL can not be disabled if it is used as system clock source
The main PLL is disabled by hardware when entering STOP and STANDBY modes.
Parameters
NewState new state of the main PLL. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 459 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  *(__IO uint32_t *) CR_PLLON_BB = (uint32_t)NewState;
}
RCC_PLLConfig()
void RCC_PLLConfig (uint32_t RCC_PLLSource, uint32_t PLLM, uint32_t PLLN, uint32_t PLLP, uint32_t PLLQ)
Configures the main PLL clock source, multiplication and division factors.
Note
This function must be used only when the main PLL is disabled.
Parameters
RCC_PLLSource specifies the PLL entry clock source. This parameter can be one of the following values:
RCC_PLLSource_HSI: HSI oscillator clock selected as PLL clock entry
RCC_PLLSource_HSE: HSE oscillator clock selected as PLL clock entry
Note
This clock source (RCC_PLLSource) is common for the main PLL and PLLI2S.
Parameters
PLLM specifies the division factor for PLL VCO input clock This parameter must be a number between 0 and 63.
Note
You have to set the PLLM parameter correctly to ensure that the VCO input frequency ranges from 1 to 2 MHz. It is recommended to select a frequency of 2 MHz to limit PLL jitter.
Parameters
PLLN specifies the multiplication factor for PLL VCO output clock This parameter must be a number between 192 and 432.
Note
You have to set the PLLN parameter correctly to ensure that the VCO output frequency is between 192 and 432 MHz.
Parameters
PLLP specifies the division factor for main system clock (SYSCLK) This parameter must be a number in the range {2, 4, 6, or 8}.
Note
You have to set the PLLP parameter correctly to not exceed 168 MHz on the System clock frequency.
Parameters
PLLQ specifies the division factor for OTG FS, SDIO and RNG clocks This parameter must be a number between 4 and 15.
Note
If the USB OTG FS is used in your application, you have to set the PLLQ parameter correctly to have 48 MHz clock for the USB. However, the SDIO and RNG need a frequency lower than or equal to 48 MHz to work correctly.
Return values
None
Definition at line 436 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_RCC_PLL_SOURCE(RCC_PLLSource));
  assert_param(IS_RCC_PLLM_VALUE(PLLM));
  assert_param(IS_RCC_PLLN_VALUE(PLLN));
  assert_param(IS_RCC_PLLP_VALUE(PLLP));
  assert_param(IS_RCC_PLLQ_VALUE(PLLQ));
  RCC->PLLCFGR = PLLM | (PLLN << 6) | (((PLLP >> 1) -1) << 16) | (RCC_PLLSource) |
                 (PLLQ << 24);
}
RCC_PLLI2SCmd()
void RCC_PLLI2SCmd (FunctionalState NewState)
Enables or disables the PLLI2S.
Note
The PLLI2S is disabled by hardware when entering STOP and STANDBY modes.
Parameters
NewState new state of the PLLI2S. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 500 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  *(__IO uint32_t *) CR_PLLI2SON_BB = (uint32_t)NewState;
}
RCC_PLLI2SConfig()
void RCC_PLLI2SConfig (uint32_t PLLI2SN, uint32_t PLLI2SR)
Configures the PLLI2S clock multiplication and division factors.
Note
This function must be used only when the PLLI2S is disabled.
PLLI2S clock source is common with the main PLL (configured in RCC_PLLConfig function)
Parameters
PLLI2SN specifies the multiplication factor for PLLI2S VCO output clock This parameter must be a number between 192 and 432.
Note
You have to set the PLLI2SN parameter correctly to ensure that the VCO output frequency is between 192 and 432 MHz.
Parameters
PLLI2SR specifies the division factor for I2S clock This parameter must be a number between 2 and 7.
Note
You have to set the PLLI2SR parameter correctly to not exceed 192 MHz on the I2S clock frequency.
Return values
None
Definition at line 485 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_RCC_PLLI2SN_VALUE(PLLI2SN));
  assert_param(IS_RCC_PLLI2SR_VALUE(PLLI2SR));
  RCC->PLLI2SCFGR = (PLLI2SN << 6) | (PLLI2SR << 28);
}
RCC_RTCCLKCmd()
void RCC_RTCCLKCmd (FunctionalState NewState)
Enables or disables the RTC clock.
Note
This function must be used only after the RTC clock source was selected using the RCC_RTCCLKConfig function.
Parameters
NewState new state of the RTC clock. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1012 of file stm32f4xx_rcc.c.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  *(__IO uint32_t *) BDCR_RTCEN_BB = (uint32_t)NewState;
}
RCC_RTCCLKConfig()
void RCC_RTCCLKConfig (uint32_t RCC_RTCCLKSource)
Configures the RTC clock (RTCCLK).
Note
As the RTC clock configuration bits are in the Backup domain and write access is denied to this domain after reset, you have to enable write access using PWR_BackupAccessCmd(ENABLE) function before to configure the RTC clock source (to be done once after reset).
Once the RTC clock is configured it can't be changed unless the Backup domain is reset using RCC_BackupResetCmd() function, or by a Power On Reset (POR).
Parameters
RCC_RTCCLKSource specifies the RTC clock source. This parameter can be one of the following values:
RCC_RTCCLKSource_LSE: LSE selected as RTC clock
RCC_RTCCLKSource_LSI: LSI selected as RTC clock
RCC_RTCCLKSource_HSE_Divx: HSE clock divided by x selected as RTC clock, where x:[2,31]
Note
If the LSE or LSI is used as RTC clock source, the RTC continues to work in STOP and STANDBY modes, and can be used as wakeup source. However, when the HSE clock is used as RTC clock source, the RTC cannot be used in STOP and STANDBY modes.
The maximum input clock frequency for RTC is 1MHz (when using HSE as RTC clock source).
Return values
None
Definition at line 980 of file stm32f4xx_rcc.c.
{
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_RCC_RTCCLK_SOURCE(RCC_RTCCLKSource));
  if ((RCC_RTCCLKSource & 0x00000300) == 0x00000300)
  { /* If HSE is selected as RTC clock source, configure HSE division factor for RTC clock */
    tmpreg = RCC->CFGR;
    /* Clear RTCPRE[4:0] bits */
    tmpreg &= ~RCC_CFGR_RTCPRE;
    /* Configure HSE division factor for RTC clock */
    tmpreg |= (RCC_RTCCLKSource & 0xFFFFCFF);
    /* Store the new value */
    RCC->CFGR = tmpreg;
  }
    
  /* Select the RTC clock source */
  RCC->BDCR |= (RCC_RTCCLKSource & 0x00000FFF);
}
RCC_SYSCLKConfig()
void RCC_SYSCLKConfig (uint32_t RCC_SYSCLKSource)
Configures the system clock (SYSCLK).
Note
The HSI is used (enabled by hardware) as system clock source after startup from Reset, wake-up from STOP and STANDBY mode, or in case of failure of the HSE used directly or indirectly as system clock (if the Clock Security System CSS is enabled).
A switch from one clock source to another occurs only if the target clock source is ready (clock stable after startup delay or PLL locked). If a clock source which is not yet ready is selected, the switch will occur when the clock source will be ready. You can use RCC_GetSYSCLKSource() function to know which clock is currently used as system clock source.
Parameters
RCC_SYSCLKSource specifies the clock source used as system clock. This parameter can be one of the following values:
RCC_SYSCLKSource_HSI: HSI selected as system clock source
RCC_SYSCLKSource_HSE: HSE selected as system clock source
RCC_SYSCLKSource_PLLCLK: PLL selected as system clock source
Return values
None
Definition at line 687 of file stm32f4xx_rcc.c.
{
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_RCC_SYSCLK_SOURCE(RCC_SYSCLKSource));
  tmpreg = RCC->CFGR;
  /* Clear SW[1:0] bits */
  tmpreg &= ~RCC_CFGR_SW;
  /* Set SW[1:0] bits according to RCC_SYSCLKSource value */
  tmpreg |= RCC_SYSCLKSource;
  /* Store the new value */
  RCC->CFGR = tmpreg;
}
RCC_WaitForHSEStartUp()
 ErrorStatus RCC_WaitForHSEStartUp (void)
Waits for HSE start-up.
Note
This functions waits on HSERDY flag to be set and return SUCCESS if this flag is set, otherwise returns ERROR if the timeout is reached and this flag is not set. The timeout value is defined by the constant HSE_STARTUP_TIMEOUT in stm32f4xx.h file. You can tailor it depending on the HSE crystal used in your application.
Parameters
None
Return values
An ErrorStatus enumeration value:
SUCCESS: HSE oscillator is stable and ready to use
ERROR: HSE oscillator not yet ready
Definition at line 261 of file stm32f4xx_rcc.c.
References ERROR, RCC_GetFlagStatus(), RESET, and SUCCESS.
{
  __IO uint32_t startupcounter = 0;
  ErrorStatus status = ERROR;
  FlagStatus hsestatus = RESET;
  /* Wait till HSE is ready and if Time out is reached exit */
  do
  {
    hsestatus = RCC_GetFlagStatus(RCC_FLAG_HSERDY);
    startupcounter++;
  } while((startupcounter != HSE_STARTUP_TIMEOUT) && (hsestatus == RESET));
  if (RCC_GetFlagStatus(RCC_FLAG_HSERDY) != RESET)
  {
    status = SUCCESS;
  }
  else
  {
    status = ERROR;
  }
  return (status);
}
Variable Documentation
APBAHBPrescTable
__I uint8_t APBAHBPrescTable[16] = {0, 0, 0, 0, 1, 2, 3, 4, 1, 2, 3, 4, 6, 7, 8, 9} [static]
Definition at line 127 of file stm32f4xx_rcc.c.