Initialization and Configuration functions
Initialization and Configuration functions.
Functions
 ErrorStatus RTC_DeInit (void)
Deinitializes the RTC registers to their default reset values.
 ErrorStatus RTC_Init (RTC_InitTypeDef *RTC_InitStruct)
Initializes the RTC registers according to the specified parameters in RTC_InitStruct.
void RTC_StructInit (RTC_InitTypeDef *RTC_InitStruct)
Fills each RTC_InitStruct member with its default value.
void RTC_WriteProtectionCmd (FunctionalState NewState)
Enables or disables the RTC registers write protection.
 ErrorStatus RTC_EnterInitMode (void)
Enters the RTC Initialization mode.
void RTC_ExitInitMode (void)
Exits the RTC Initialization mode.
 ErrorStatus RTC_WaitForSynchro (void)
Waits until the RTC Time and Date registers (RTC_TR and RTC_DR) are synchronized with RTC APB clock.
 ErrorStatus RTC_RefClockCmd (FunctionalState NewState)
Enables or disables the RTC reference clock detection.
void RTC_BypassShadowCmd (FunctionalState NewState)
Enables or Disables the Bypass Shadow feature.
Detailed Description
Initialization and Configuration functions.
 ===============================================================================
                 Initialization and Configuration functions
 ===============================================================================

  This section provide functions allowing to initialize and configure the RTC
  Prescaler (Synchronous and Asynchronous), RTC Hour format, disable RTC registers
  Write protection, enter and exit the RTC initialization mode, RTC registers
  synchronization check and reference clock detection enable.
  
  1. The RTC Prescaler is programmed to generate the RTC 1Hz time base. It is
     split into 2 programmable prescalers to minimize power consumption.
     - A 7-bit asynchronous prescaler and A 13-bit synchronous prescaler.
     - When both prescalers are used, it is recommended to configure the asynchronous
       prescaler to a high value to minimize consumption.

  2. All RTC registers are Write protected. Writing to the RTC registers
     is enabled by writing a key into the Write Protection register, RTC_WPR.

  3. To Configure the RTC Calendar, user application should enter initialization
     mode. In this mode, the calendar counter is stopped and its value can be 
     updated. When the initialization sequence is complete, the calendar restarts 
     counting after 4 RTCCLK cycles.

  4. To read the calendar through the shadow registers after Calendar initialization,
     calendar update or after wakeup from low power modes the software must first 
     clear the RSF flag. The software must then wait until it is set again before 
     reading the calendar, which means that the calendar registers have been 
     correctly copied into the RTC_TR and RTC_DR shadow registers.
     The RTC_WaitForSynchro() function implements the above software sequence 
     (RSF clear and RSF check).
Function Documentation
RTC_BypassShadowCmd()
void RTC_BypassShadowCmd (FunctionalState NewState)
Enables or Disables the Bypass Shadow feature.
Note
When the Bypass Shadow is enabled the calendar value are taken directly from the Calendar counter.
Parameters
NewState new state of the Bypass Shadow feature. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 698 of file stm32f4xx_rtc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  if (NewState != DISABLE)
  {
    /* Set the BYPSHAD bit */
    RTC->CR |= (uint8_t)RTC_CR_BYPSHAD;
  }
  else
  {
    /* Reset the BYPSHAD bit */
    RTC->CR &= (uint8_t)~RTC_CR_BYPSHAD;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_DeInit()
 ErrorStatus RTC_DeInit (void)
Deinitializes the RTC registers to their default reset values.
Note
This function doesn't reset the RTC Clock source and RTC Backup Data registers.
Parameters
None
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC registers are deinitialized
ERROR: RTC registers are not deinitialized
Definition at line 367 of file stm32f4xx_rtc.c.
References ERROR, and RTC_EnterInitMode().
{
  __IO uint32_t wutcounter = 0x00;
  uint32_t wutwfstatus = 0x00;
  ErrorStatus status = ERROR;
  
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    /* Reset TR, DR and CR registers */
    RTC->TR = (uint32_t)0x00000000;
    RTC->DR = (uint32_t)0x00002101;
    /* Reset All CR bits except CR[2:0] */
    RTC->CR &= (uint32_t)0x00000007;
  
    /* Wait till RTC WUTWF flag is set and if Time out is reached exit */
    do
    {
      wutwfstatus = RTC->ISR & RTC_ISR_WUTWF;
      wutcounter++;
    } while((wutcounter != INITMODE_TIMEOUT) && (wutwfstatus == 0x00));
    
    if ((RTC->ISR & RTC_ISR_WUTWF) == RESET)
    {
      status = ERROR;
    }
    else
    {
      /* Reset all RTC CR register bits */
      RTC->CR &= (uint32_t)0x00000000;
      RTC->WUTR = (uint32_t)0x0000FFFF;
      RTC->PRER = (uint32_t)0x007F00FF;
      RTC->CALIBR = (uint32_t)0x00000000;
      RTC->ALRMAR = (uint32_t)0x00000000;
      RTC->ALRMBR = (uint32_t)0x00000000;
      
      /* Reset ISR register and exit initialization mode */
      RTC->ISR = (uint32_t)0x00000000;
      
      /* Reset Tamper and alternate functions configuration register */
      RTC->TAFCR = 0x00000000;
  
      if(RTC_WaitForSynchro() == ERROR)
      {
        status = ERROR;
      }
      else
      {
        status = SUCCESS;
      }
    }
  }
  
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_EnterInitMode()
 ErrorStatus RTC_EnterInitMode (void)
Enters the RTC Initialization mode.
Note
The RTC Initialization mode is write protected, use the RTC_WriteProtectionCmd(DISABLE) before calling this function.
Parameters
None
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC is in Init mode
ERROR: RTC is not in Init mode
Definition at line 540 of file stm32f4xx_rtc.c.
References ERROR.
Referenced by RTC_CoarseCalibCmd(), RTC_CoarseCalibConfig(), RTC_DeInit(), RTC_Init(), RTC_RefClockCmd(), RTC_SetDate(), and RTC_SetTime().
{
  __IO uint32_t initcounter = 0x00;
  ErrorStatus status = ERROR;
  uint32_t initstatus = 0x00;
     
  /* Check if the Initialization mode is set */
  if ((RTC->ISR & RTC_ISR_INITF) == (uint32_t)RESET)
  {
    /* Set the Initialization mode */
    RTC->ISR = (uint32_t)RTC_INIT_MASK;
    
    /* Wait till RTC is in INIT state and if Time out is reached exit */
    do
    {
      initstatus = RTC->ISR & RTC_ISR_INITF;
      initcounter++;
    } while((initcounter != INITMODE_TIMEOUT) && (initstatus == 0x00));
    
    if ((RTC->ISR & RTC_ISR_INITF) != RESET)
    {
      status = SUCCESS;
    }
    else
    {
      status = ERROR;
    }
  }
  else
  {
    status = SUCCESS;
  }
    
  return (status);
}
RTC_ExitInitMode()
void RTC_ExitInitMode (void)
Exits the RTC Initialization mode.
Note
When the initialization sequence is complete, the calendar restarts counting after 4 RTCCLK cycles.
The RTC Initialization mode is write protected, use the RTC_WriteProtectionCmd(DISABLE) before calling this function.
Parameters
None
Return values
None
Definition at line 585 of file stm32f4xx_rtc.c.
Referenced by RTC_CoarseCalibCmd(), RTC_CoarseCalibConfig(), RTC_Init(), RTC_RefClockCmd(), RTC_SetDate(), and RTC_SetTime().
{
  /* Exit Initialization mode */
  RTC->ISR &= (uint32_t)~RTC_ISR_INIT;
}
RTC_Init()
 ErrorStatus RTC_Init (RTC_InitTypeDef * RTC_InitStruct)
Initializes the RTC registers according to the specified parameters in RTC_InitStruct.
Parameters
RTC_InitStruct pointer to a RTC_InitTypeDef structure that contains the configuration information for the RTC peripheral.
Note
The RTC Prescaler register is write protected and can be written in initialization mode only.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC registers are initialized
ERROR: RTC registers are not initialized
Definition at line 445 of file stm32f4xx_rtc.c.
References ERROR, RTC_EnterInitMode(), RTC_ExitInitMode(), and SUCCESS.
{
  ErrorStatus status = ERROR;
  
  /* Check the parameters */
  assert_param(IS_RTC_HOUR_FORMAT(RTC_InitStruct->RTC_HourFormat));
  assert_param(IS_RTC_ASYNCH_PREDIV(RTC_InitStruct->RTC_AsynchPrediv));
  assert_param(IS_RTC_SYNCH_PREDIV(RTC_InitStruct->RTC_SynchPrediv));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    /* Clear RTC CR FMT Bit */
    RTC->CR &= ((uint32_t)~(RTC_CR_FMT));
    /* Set RTC_CR register */
    RTC->CR |= ((uint32_t)(RTC_InitStruct->RTC_HourFormat));
  
    /* Configure the RTC PRER */
    RTC->PRER = (uint32_t)(RTC_InitStruct->RTC_SynchPrediv);
    RTC->PRER |= (uint32_t)(RTC_InitStruct->RTC_AsynchPrediv << 16);
    /* Exit Initialization mode */
    RTC_ExitInitMode();
    status = SUCCESS;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_RefClockCmd()
 ErrorStatus RTC_RefClockCmd (FunctionalState NewState)
Enables or disables the RTC reference clock detection.
Parameters
NewState new state of the RTC reference clock. This parameter can be: ENABLE or DISABLE.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC reference clock detection is enabled
ERROR: RTC reference clock detection is disabled
Definition at line 650 of file stm32f4xx_rtc.c.
References DISABLE, ERROR, RTC_EnterInitMode(), RTC_ExitInitMode(), and SUCCESS.
{
  ErrorStatus status = ERROR;
  
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
    
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    if (NewState != DISABLE)
    {
      /* Enable the RTC reference clock detection */
      RTC->CR |= RTC_CR_REFCKON;
    }
    else
    {
      /* Disable the RTC reference clock detection */
      RTC->CR &= ~RTC_CR_REFCKON;
    }
    /* Exit Initialization mode */
    RTC_ExitInitMode();
    
    status = SUCCESS;
  }
  
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_StructInit()
void RTC_StructInit (RTC_InitTypeDef * RTC_InitStruct)
Fills each RTC_InitStruct member with its default value.
Parameters
RTC_InitStruct pointer to a RTC_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 491 of file stm32f4xx_rtc.c.
References RTC_InitTypeDef::RTC_AsynchPrediv, RTC_InitTypeDef::RTC_HourFormat, and RTC_InitTypeDef::RTC_SynchPrediv.
{
  /* Initialize the RTC_HourFormat member */
  RTC_InitStruct->RTC_HourFormat = RTC_HourFormat_24;
    
  /* Initialize the RTC_AsynchPrediv member */
  RTC_InitStruct->RTC_AsynchPrediv = (uint32_t)0x7F;
  /* Initialize the RTC_SynchPrediv member */
  RTC_InitStruct->RTC_SynchPrediv = (uint32_t)0xFF;
}
RTC_WaitForSynchro()
 ErrorStatus RTC_WaitForSynchro (void)
Waits until the RTC Time and Date registers (RTC_TR and RTC_DR) are synchronized with RTC APB clock.
Note
The RTC Resynchronization mode is write protected, use the RTC_WriteProtectionCmd(DISABLE) before calling this function.
To read the calendar through the shadow registers after Calendar initialization, calendar update or after wakeup from low power modes the software must first clear the RSF flag. The software must then wait until it is set again before reading the calendar, which means that the calendar registers have been correctly copied into the RTC_TR and RTC_DR shadow registers.
Parameters
None
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC registers are synchronised
ERROR: RTC registers are not synchronised
Definition at line 607 of file stm32f4xx_rtc.c.
References ERROR.
Referenced by RTC_SetDate(), and RTC_SetTime().
{
  __IO uint32_t synchrocounter = 0;
  ErrorStatus status = ERROR;
  uint32_t synchrostatus = 0x00;
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
    
  /* Clear RSF flag */
  RTC->ISR &= (uint32_t)RTC_RSF_MASK;
    
  /* Wait the registers to be synchronised */
  do
  {
    synchrostatus = RTC->ISR & RTC_ISR_RSF;
    synchrocounter++;
  } while((synchrocounter != SYNCHRO_TIMEOUT) && (synchrostatus == 0x00));
    
  if ((RTC->ISR & RTC_ISR_RSF) != RESET)
  {
    status = SUCCESS;
  }
  else
  {
    status = ERROR;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
    
  return (status);
}
RTC_WriteProtectionCmd()
void RTC_WriteProtectionCmd (FunctionalState NewState)
Enables or disables the RTC registers write protection.
Note
All the RTC registers are write protected except for RTC_ISR[13:8], RTC_TAFCR and RTC_BKPxR.
Writing a wrong key reactivates the write protection.
The protection mechanism is not affected by system reset.
Parameters
NewState new state of the write protection. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 513 of file stm32f4xx_rtc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
    
  if (NewState != DISABLE)
  {
    /* Enable the write protection for RTC registers */
    RTC->WPR = 0xFF;
  }
  else
  {
    /* Disable the write protection for RTC registers */
    RTC->WPR = 0xCA;
    RTC->WPR = 0x53;
  }
}