TIM_PWM_Input
Functions
void NMI_Handler (void)
This function handles NMI exception.
void MemManage_Handler (void)
This function handles Hard Fault exception.
void BusFault_Handler (void)
This function handles Bus Fault exception.
void UsageFault_Handler (void)
This function handles Usage Fault exception.
void DebugMon_Handler (void)
This function handles Debug Monitor exception.
void SVC_Handler (void)
This function handles SVCall exception.
void TIM4_IRQHandler (void)
This function handles PendSV_Handler exception.
void EXTI1_IRQHandler (void)
This function handles external interrupts generated by MPU.
Variables
__IO uint16_t IC2Value = 0
__IO uint16_t DutyCycle = 0
__IO uint32_t Frequency = 0
Detailed Description
Function Documentation
BusFault_Handler()
void BusFault_Handler (void)
This function handles Bus Fault exception.
Parameters
None
Return values
None
Definition at line 93 of file stm32f4xx_it.c.
{
  /* Go to infinite loop when Bus Fault exception occurs */
  while (1)
  {}
}
DebugMon_Handler()
void DebugMon_Handler (void)
This function handles Debug Monitor exception.
Parameters
None
Return values
None
Definition at line 117 of file stm32f4xx_it.c.
{}
EXTI1_IRQHandler()
void EXTI1_IRQHandler (void)
This function handles external interrupts generated by MPU.
Parameters
None
Return values
None
Definition at line 191 of file stm32f4xx_it.c.
References EXTI_ClearITPendingBit(), and gyro_data_ready_cb().
{
  /* Handle new gyro*/
  gyro_data_ready_cb();
  EXTI_ClearITPendingBit(EXTI_Line1);
}
MemManage_Handler()
void MemManage_Handler (void)
This function handles Hard Fault exception.
Parameters
None
Return values
None This function handles Memory Manage exception.
Parameters
None
Return values
None
Definition at line 81 of file stm32f4xx_it.c.
{
  /* Go to infinite loop when Memory Manage exception occurs */
  while (1)
  {}
}
NMI_Handler()
void NMI_Handler (void)
This function handles NMI exception.
Parameters
None
Return values
None
Definition at line 60 of file stm32f4xx_it.c.
{
}
SVC_Handler()
void SVC_Handler (void)
This function handles SVCall exception.
Parameters
None
Return values
None
Definition at line 125 of file stm32f4xx_it.c.
{}
TIM4_IRQHandler()
void TIM4_IRQHandler (void)
This function handles PendSV_Handler exception.
Parameters
None
Return values
None This function handles SysTick Handler.
Parameters
None
Return values
None This function handles TIM4 global interrupt request.
Parameters
None
Return values
None
Definition at line 157 of file stm32f4xx_it.c.
References RCC_GetClocksFreq(), and TIM_ClearITPendingBit().
{
  RCC_ClocksTypeDef RCC_Clocks;
  RCC_GetClocksFreq(&RCC_Clocks);
  /* Clear TIM4 Capture compare interrupt pending bit */
  TIM_ClearITPendingBit(TIM4, TIM_IT_CC2);
  /* Get the Input Capture value */
  IC2Value = TIM_GetCapture2(TIM4);
  if (IC2Value != 0)
  {
    /* Duty cycle computation */
    DutyCycle = (TIM_GetCapture1(TIM4) * 100) / IC2Value;
    /* Frequency computation
       TIM4 counter clock = (RCC_Clocks.HCLK_Frequency)/2 */
    Frequency = (RCC_Clocks.HCLK_Frequency)/2 / IC2Value;
  }
  else
  {
    DutyCycle = 0;
    Frequency = 0;
  }
}
UsageFault_Handler()
void UsageFault_Handler (void)
This function handles Usage Fault exception.
Parameters
None
Return values
None
Definition at line 105 of file stm32f4xx_it.c.
{
  /* Go to infinite loop when Usage Fault exception occurs */
  while (1)
  {}
}
Variable Documentation
DutyCycle
__IO uint16_t DutyCycle = 0
Definition at line 45 of file stm32f4xx_it.c.
Frequency
__IO uint32_t Frequency = 0
Definition at line 46 of file stm32f4xx_it.c.
IC2Value
__IO uint16_t IC2Value = 0
Definition at line 44 of file stm32f4xx_it.c.