EMPL
Embedded Motion Processing Library.
Files
file main.c
Test app for eMPL using the Motion Driver DMP image.
Classes
struct rx_s
struct hal_s
struct platform_data_s
Macros
#define PRINT_ACCEL (0x01)
#define PRINT_GYRO (0x02)
#define PRINT_QUAT (0x04)
#define PRINT_COMPASS (0x08)
#define PRINT_EULER (0x10)
#define PRINT_ROT_MAT (0x20)
#define PRINT_HEADING (0x40)
#define PRINT_PEDO (0x80)
#define PRINT_LINEAR_ACCEL (0x100)
#define PRINT_GRAVITY_VECTOR (0x200)
#define ACCEL_ON (0x01)
#define GYRO_ON (0x02)
#define COMPASS_ON (0x04)
#define MOTION (0)
#define NO_MOTION (1)
#define DEFAULT_MPU_HZ (20)
#define FLASH_SIZE (512)
#define FLASH_MEM_START ((void*)0x1800)
#define PEDO_READ_MS (1000)
#define TEMP_READ_MS (500)
#define COMPASS_READ_MS (100)
Functions
static void read_from_mpl (void)
static void setup_gyro (void)
static void tap_cb (unsigned char direction, unsigned char count)
static void android_orient_cb (unsigned char orientation)
static void run_self_test (void)
static void handle_input (void)
void gyro_data_ready_cb (void)
int main (void)
main entry point.
Variables
volatile uint32_t hal_timestamp = 0
timestamp variable initialize, its for count tick
unsigned char header [3]
unsigned char cmd
unsigned char lp_accel_mode
unsigned char sensors
unsigned char dmp_on
unsigned char wait_for_tap
volatile unsigned char new_gyro
unsigned char motion_int_mode
unsigned long no_dmp_hz
unsigned long next_pedo_ms
unsigned long next_temp_ms
unsigned long next_compass_ms
unsigned int report
unsigned short dmp_features
struct rx_s rx
static struct hal_s hal = {0}
volatile unsigned char rx_new
Usart Receive variable init.
unsigned char * mpl_key = (unsigned char*)`eMPL 5.1`
signed char orientation [9]
static struct platform_data_s gyro_pdata
Detailed Description
Embedded Motion Processing Library.
Macro Definition Documentation
ACCEL_ON
#define ACCEL_ON (0x01)
Definition at line 44 of file main.c.
COMPASS_ON
#define COMPASS_ON (0x04)
Definition at line 46 of file main.c.
COMPASS_READ_MS
#define COMPASS_READ_MS (100)
Definition at line 59 of file main.c.
DEFAULT_MPU_HZ
#define DEFAULT_MPU_HZ (20)
Starting sampling rate.
Definition at line 52 of file main.c.
FLASH_MEM_START
#define FLASH_MEM_START ((void*)0x1800)
Definition at line 55 of file main.c.
FLASH_SIZE
#define FLASH_SIZE (512)
Definition at line 54 of file main.c.
GYRO_ON
#define GYRO_ON (0x02)
Definition at line 45 of file main.c.
MOTION
#define MOTION (0)
Definition at line 48 of file main.c.
NO_MOTION
#define NO_MOTION (1)
Definition at line 49 of file main.c.
PEDO_READ_MS
#define PEDO_READ_MS (1000)
Definition at line 57 of file main.c.
PRINT_ACCEL
#define PRINT_ACCEL (0x01)
Includes ------------------------------------------------------------------
Private typedef -----------------------------------------------------------
Data read from MPL.
Definition at line 32 of file main.c.
PRINT_COMPASS
#define PRINT_COMPASS (0x08)
Definition at line 35 of file main.c.
PRINT_EULER
#define PRINT_EULER (0x10)
Definition at line 36 of file main.c.
PRINT_GRAVITY_VECTOR
#define PRINT_GRAVITY_VECTOR (0x200)
Definition at line 41 of file main.c.
PRINT_GYRO
#define PRINT_GYRO (0x02)
Definition at line 33 of file main.c.
PRINT_HEADING
#define PRINT_HEADING (0x40)
Definition at line 38 of file main.c.
PRINT_LINEAR_ACCEL
#define PRINT_LINEAR_ACCEL (0x100)
Definition at line 40 of file main.c.
PRINT_PEDO
#define PRINT_PEDO (0x80)
Definition at line 39 of file main.c.
PRINT_QUAT
#define PRINT_QUAT (0x04)
Definition at line 34 of file main.c.
PRINT_ROT_MAT
#define PRINT_ROT_MAT (0x20)
Definition at line 37 of file main.c.
TEMP_READ_MS
#define TEMP_READ_MS (500)
Definition at line 58 of file main.c.
Function Documentation
android_orient_cb()
static void android_orient_cb (unsigned char orientation) [static]
If you want to connect IMU with Android mobile device via bluetooth then this function should be called
Definition at line 310 of file main.c.
{
    switch (orientation) {
    case ANDROID_ORIENT_PORTRAIT:
        MPL_LOGI("Portrait\n");
        break;
    case ANDROID_ORIENT_LANDSCAPE:
        MPL_LOGI("Landscape\n");
        break;
    case ANDROID_ORIENT_REVERSE_PORTRAIT:
        MPL_LOGI("Reverse Portrait\n");
        break;
    case ANDROID_ORIENT_REVERSE_LANDSCAPE:
        MPL_LOGI("Reverse Landscape\n");
        break;
    default:
        return;
    }
}
gyro_data_ready_cb()
void gyro_data_ready_cb (void)
Every time new gyro data is available, this function is called in an ISR context. In this example, it sets a flag protecting the FIFO read function.
Definition at line 651 of file main.c.
References hal, and hal_s::new_gyro.
Referenced by EXTI1_IRQHandler().
{
    hal.new_gyro = 1;
}
handle_input()
static void handle_input (void) [static]
These commands turn off individual sensors.
The commands send individual sensor data or fused data to the PC.
This command prints out the value of each gyro register for debugging. If logging is disabled, this function has no effect.
When LP accel mode is enabled, the driver automatically configures the hardware for latched interrupts. However, the MCU sometimes misses the rising/falling edge, and the hal.new_gyro flag is never set. To avoid getting locked in this state, we're overriding the
TODO: The MCU supports level-triggered interrupts.
The hardware self test can be run without any interaction with the MPL since it's completely localized in the gyro driver. Logging is assumed to be enabled; otherwise, a couple LEDs could probably be used here to display the test results.
Let MPL know that contiguity was broken.
Depending on your application, sensor data may be needed at a faster or slower rate. These commands can speed up or slow down the rate at which the sensor data is pushed to the MPL.
In this example, the compass rate is never changed.
Set hardware to interrupt on gesture event only. This feature is useful for keeping the MCU asleep until the DMP detects as a tap or orientation event.
Set hardware to interrupt periodically.
Toggle pedometer display.
Reset pedometer.
LP accel is not compatible with the DMP.
Toggle DMP.
Restore FIFO settings.
When the DMP is used, the hardware sampling rate is fixed at 200Hz, and the DMP is configured to downsample the FIFO output using the function dmp_set_fifo_rate. However, when the DMP is turned off, the sampling rate remains at 200Hz. This could be handled in inv_mpu.c, but it would need to know that inv_mpu_dmp_motion_driver.c exists. To avoid this, we'll just put the extra logic in the application layer.
Preserve current FIFO rate.
Test the motion interrupt hardware feature.
not enabled for 6050 product
Toggle LP quaternion. The DMP features can be enabled/disabled at runtime. Use this same approach for other features.
Definition at line 408 of file main.c.
References rx_s::cmd, hal_s::dmp_on, hal, hal_s::lp_accel_mode, hal_s::motion_int_mode, hal_s::report, run_self_test(), hal_s::rx, hal_s::sensors, setup_gyro(), and USART_ReceiveData().
Referenced by main().
{
  
    char c = USART_ReceiveData(USART1);
    //char c = USART_ReceiveData(USART2);
    switch (c) {
    case '8':
        hal.sensors ^= ACCEL_ON;
        setup_gyro();
        if (!(hal.sensors & ACCEL_ON))
            inv_accel_was_turned_off();
        break;
    case '9':
        hal.sensors ^= GYRO_ON;
        setup_gyro();
        if (!(hal.sensors & GYRO_ON))
            inv_gyro_was_turned_off();
        break;
#ifdef COMPASS_ENABLED
    case '0':
        hal.sensors ^= COMPASS_ON;
        setup_gyro();
        if (!(hal.sensors & COMPASS_ON))
            inv_compass_was_turned_off();
        break;
#endif
    case 'a':
        hal.report ^= PRINT_ACCEL;
        break;
    case 'g':
        hal.report ^= PRINT_GYRO;
        break;
#ifdef COMPASS_ENABLED
    case 'c':
        hal.report ^= PRINT_COMPASS;
        break;
#endif
    case 'e':
        hal.report ^= PRINT_EULER;
        break;
    case 'r':
        hal.report ^= PRINT_ROT_MAT;
        break;
    case 'q':
        hal.report ^= PRINT_QUAT;
        break;
    case 'h':
        hal.report ^= PRINT_HEADING;
        break;
    case 'i':
        hal.report ^= PRINT_LINEAR_ACCEL;
        break;
    case 'o':
        hal.report ^= PRINT_GRAVITY_VECTOR;
        break;
#ifdef COMPASS_ENABLED
    case 'w':
        send_status_compass();
        break;
#endif
    case 'd':
        mpu_reg_dump();
        break;
    /* Test out low-power accel mode. */
    case 'p':
        if (hal.dmp_on)
            /* LP accel is not compatible with the DMP. */
            break;
        mpu_lp_accel_mode(20);
        mpu_set_int_latched(0);
        hal.sensors &= ~(GYRO_ON|COMPASS_ON);
        hal.sensors |= ACCEL_ON;
        hal.lp_accel_mode = 1;
        inv_gyro_was_turned_off();
        inv_compass_was_turned_off();
        break;
    case 't':
        run_self_test();
        inv_accel_was_turned_off();
        inv_gyro_was_turned_off();
        inv_compass_was_turned_off();
        break;
    case '1':
        if (hal.dmp_on) {
            dmp_set_fifo_rate(10);
            inv_set_quat_sample_rate(100000L);
        } else
            mpu_set_sample_rate(10);
        inv_set_gyro_sample_rate(100000L);
        inv_set_accel_sample_rate(100000L);
        break;
    case '2':
        if (hal.dmp_on) {
            dmp_set_fifo_rate(20);
            inv_set_quat_sample_rate(50000L);
        } else
            mpu_set_sample_rate(20);
        inv_set_gyro_sample_rate(50000L);
        inv_set_accel_sample_rate(50000L);
        break;
    case '3':
        if (hal.dmp_on) {
            dmp_set_fifo_rate(40);
            inv_set_quat_sample_rate(25000L);
        } else
            mpu_set_sample_rate(40);
        inv_set_gyro_sample_rate(25000L);
        inv_set_accel_sample_rate(25000L);
        break;
    case '4':
        if (hal.dmp_on) {
            dmp_set_fifo_rate(50);
            inv_set_quat_sample_rate(20000L);
        } else
            mpu_set_sample_rate(50);
        inv_set_gyro_sample_rate(20000L);
        inv_set_accel_sample_rate(20000L);
        break;
    case '5':
        if (hal.dmp_on) {
            dmp_set_fifo_rate(100);
            inv_set_quat_sample_rate(10000L);
        } else
            mpu_set_sample_rate(100);
        inv_set_gyro_sample_rate(10000L);
        inv_set_accel_sample_rate(10000L);
        break;
    case ',':
        dmp_set_interrupt_mode(DMP_INT_GESTURE);
        break;
    case '.':
        dmp_set_interrupt_mode(DMP_INT_CONTINUOUS);
        break;
    case '6':
        hal.report ^= PRINT_PEDO;
        break;
    case '7':
        dmp_set_pedometer_step_count(0);
        dmp_set_pedometer_walk_time(0);
        break;
    case 'f':
        if (hal.lp_accel_mode)
            return;
        if (hal.dmp_on) {
            unsigned short dmp_rate;
            unsigned char mask = 0;
            hal.dmp_on = 0;
            mpu_set_dmp_state(0);
            if (hal.sensors & ACCEL_ON)
                mask |= INV_XYZ_ACCEL;
            if (hal.sensors & GYRO_ON)
                mask |= INV_XYZ_GYRO;
            if (hal.sensors & COMPASS_ON)
                mask |= INV_XYZ_COMPASS;
            mpu_configure_fifo(mask);
            dmp_get_fifo_rate(&dmp_rate);
            mpu_set_sample_rate(dmp_rate);
            inv_quaternion_sensor_was_turned_off();
            MPL_LOGI("DMP disabled.\n");
        } else {
            unsigned short sample_rate;
            hal.dmp_on = 1;
            mpu_get_sample_rate(&sample_rate);
            dmp_set_fifo_rate(sample_rate);
            inv_set_quat_sample_rate(1000000L / sample_rate);
            mpu_set_dmp_state(1);
            MPL_LOGI("DMP enabled.\n");
        }
        break;
    case 'm':
    #ifndef MPU6050
    hal.motion_int_mode = 1;
    #endif
        break;
    case 'v':
        hal.dmp_features ^= DMP_FEATURE_6X_LP_QUAT;
        dmp_enable_feature(hal.dmp_features);
        if (!(hal.dmp_features & DMP_FEATURE_6X_LP_QUAT)) {
            inv_quaternion_sensor_was_turned_off();
            MPL_LOGI("LP quaternion disabled.\n");
        } else
            MPL_LOGI("LP quaternion enabled.\n");
        break;
    default:
        break;
    }
    hal.rx.cmd = 0;
}
main()
int main (void)
main entry point.
Parameters None
Return values
void None
Required preconditions: None
Variable Declaration
If you're not using an MPU9150 AND you're not using DMP features, this function will place all slaves on the primary bus. mpu_set_bypass(1);
Compute 6-axis and 9-axis quaternions.
The MPL expects compass data at a constant rate (matching the rate passed to inv_set_compass_sample_rate). If this is an issue for your application, call this function, and the MPL will depend on the timestamps passed to inv_build_compass instead.
inv_9x_fusion_use_timestamps(1);
This function has been deprecated. inv_enable_no_gyro_fusion();
Update gyro biases when not in motion. WARNING: These algorithms are mutually exclusive.
inv_enable_motion_no_motion();
inv_set_no_motion_time(1000);
Update gyro biases when temperature changes.
This algorithm updates the accel biases when in motion. A more accurate bias measurement can be made when running the self-test (see case 't' in handle_input), but this algorithm can be enabled if the self-test can't be executed in your application.
inv_enable_in_use_auto_calibration();
If you need to estimate your heading before the compass is calibrated, enable this algorithm. It becomes useless after a good figure-eight is detected, so we'll just leave it out to save memory. inv_enable_heading_from_gyro();
Allows use of the MPL APIs in read_from_mpl.
Get/set hardware configuration. Start gyro.
Wake up all sensors.
Push both gyro and accel data into the FIFO.
Read back configuration in case it was set improperly.
Sync driver configuration with MPL.
Sample rate expected in microseconds.
Set chip-to-body orientation matrix. Set hardware units to dps/g's/degrees scaling factor.
Initialize HAL state variables.
Compass reads are handled by scheduler.
To initialize the DMP:
Call dmp_load_motion_driver_firmware(). This pushes the DMP image in inv_mpu_dmp_motion_driver.h into the MPU memory.
Push the gyro and accel orientation matrix to the DMP.
Register gesture callbacks. Don't worry, these callbacks won't be executed unless the corresponding feature is enabled.
Call dmp_enable_feature(mask) to enable different features.
Call dmp_set_fifo_rate(freq) to select a DMP output rate.
Call any feature-specific control functions.
To enable the DMP, just call mpu_set_dmp_state(1). This function can be called repeatedly to enable and disable the DMP at runtime.
The following is a short summary of the features supported in the DMP image provided in inv_mpu_dmp_motion_driver.c: DMP_FEATURE_LP_QUAT: Generate a gyro-only quaternion on the DMP at 200Hz. Integrating the gyro data at higher rates reduces numerical errors (compared to integration on the MCU at a lower sampling rate). DMP_FEATURE_6X_LP_QUAT: Generate a gyro/accel quaternion on the DMP at 200Hz. Cannot be used in combination with DMP_FEATURE_LP_QUAT. DMP_FEATURE_TAP: Detect taps along the X, Y, and Z axes. DMP_FEATURE_ANDROID_ORIENT: Google's screen rotation algorithm. Triggers an event at the four orientations where the screen should rotate. DMP_FEATURE_GYRO_CAL: Calibrates the gyro data after eight seconds of no motion. DMP_FEATURE_SEND_RAW_ACCEL: Add raw accelerometer data to the FIFO. DMP_FEATURE_SEND_RAW_GYRO: Add raw gyro data to the FIFO. DMP_FEATURE_SEND_CAL_GYRO: Add calibrated gyro data to the FIFO. Cannot be used in combination with DMP_FEATURE_SEND_RAW_GYRO.
Known Bug - DMP when enabled will sample sensor data at 200Hz and output to FIFO at the rate specified in the dmp_set_fifo_rate API. The DMP will then sent an interrupt once a sample has been put into the FIFO. Therefore if the dmp_set_fifo_rate is at 25Hz there will be a 25Hz interrupt from the MPU device.
There is a known issue in which if you do not enable DMP_FEATURE_TAP then the interrupts will be at 200Hz even if fifo rate is set at a different rate. To avoid this issue include the DMP_FEATURE_TAP
DMP sensor fusion works only with gyro at +-2000dps and accel +-2G
A byte has been received via USART. See handle_input for a list of valid commands.
Temperature data doesn't need to be read with every gyro sample. Let's make them timer-based like the compass reads.
Enable motion interrupt.
Notify the MPL that contiguity was broken.
Wait for the MPU interrupt.
Restore the previous sensor configuration.
This function gets new data from the FIFO when the DMP is in use. The FIFO can contain any combination of gyro, accel, quaternion, and gesture data. The sensors parameter tells the caller which data fields were actually populated with new data. For example, if sensors == (INV_XYZ_GYRO | INV_WXYZ_QUAT), then the FIFO isn't being filled with accel data. The driver parses the gesture data to determine if a gesture event has occurred; on an event, the application will be notified via a callback (assuming that a callback function was properly registered). The more parameter is non-zero if there are leftover packets in the FIFO.
Push the new data to the MPL.
Temperature only used for gyro temp comp.
This function gets new data from the FIFO. The FIFO can contain gyro, accel, both, or neither. The sensors parameter tells the caller which data fields were actually populated with new data. For example, if sensors == INV_XYZ_GYRO, then the FIFO isn't being filled with accel data. The more parameter is non-zero if there are leftover packets in the FIFO. The HAL can use this information to increase the frequency at which this function is called.
Push the new data to the MPL.
Temperature only used for gyro temp comp.
This function reads bias-compensated sensor data and sensor fusion outputs from the MPL. The outputs are formatted as seen in eMPL_outputs.c. This function only needs to be called at the rate requested by the host.
Definition at line 665 of file main.c.
References board_init(), rx_s::cmd, hal_s::dmp_on, get_tick_count(), hal, handle_input(), hal_s::lp_accel_mode, hal_s::motion_int_mode, hal_s::new_gyro, hal_s::next_compass_ms, hal_s::next_pedo_ms, hal_s::next_temp_ms, read_from_mpl(), hal_s::report, hal_s::rx, hal_s::sensors, USART_ClearITPendingBit(), and USART_GetITStatus().
{
    inv_error_t result;
    unsigned char accel_fsr, new_temp = 0;
    unsigned short gyro_rate, gyro_fsr;
    unsigned long timestamp;
    struct int_param_s int_param;
#ifdef COMPASS_ENABLED
    unsigned char new_compass = 0;
    unsigned short compass_fsr;
#endif
    board_init();
 
  result = mpu_init(&int_param);
  if (result) {
      MPL_LOGE("Could not initialize gyro.\n");
  }
  else {
      MPL_LOGE("Initialise gyro successful.\n");
    }
  
  result = inv_init_mpl();
  if (result) {
      MPL_LOGE("Could not initialize MPL.\n");
  }
  else {
      MPL_LOGE("Initialise MPL successful.\n");
  }
    inv_enable_quaternion();
    inv_enable_9x_sensor_fusion();
    inv_enable_fast_nomot();
    inv_enable_gyro_tc();
#ifdef COMPASS_ENABLED
    inv_enable_vector_compass_cal();
    inv_enable_magnetic_disturbance();
#endif
    inv_enable_eMPL_outputs();
  result = inv_start_mpl();
  if (result == INV_ERROR_NOT_AUTHORIZED) {
      while (1) {
          MPL_LOGE("Not authorized.\n");
      }
  }
  if (result) {
      MPL_LOGE("Could not start the MPL.\n");
  }
#ifdef COMPASS_ENABLED
    mpu_set_sensors(INV_XYZ_GYRO | INV_XYZ_ACCEL | INV_XYZ_COMPASS);
#else
    mpu_set_sensors(INV_XYZ_GYRO | INV_XYZ_ACCEL);
#endif
    mpu_configure_fifo(INV_XYZ_GYRO | INV_XYZ_ACCEL);
    mpu_set_sample_rate(DEFAULT_MPU_HZ);
#ifdef COMPASS_ENABLED
    mpu_set_compass_sample_rate(1000 / COMPASS_READ_MS);
#endif
    mpu_get_sample_rate(&gyro_rate);
    mpu_get_gyro_fsr(&gyro_fsr);
    mpu_get_accel_fsr(&accel_fsr);
#ifdef COMPASS_ENABLED
    mpu_get_compass_fsr(&compass_fsr);
#endif
    inv_set_gyro_sample_rate(1000000L / gyro_rate);
    inv_set_accel_sample_rate(1000000L / gyro_rate);
#ifdef COMPASS_ENABLED
    /* The compass rate is independent of the gyro and accel rates. As long as
     * inv_set_compass_sample_rate is called with the correct value, the 9-axis
     * fusion algorithm's compass correction gain will work properly.
     */
    inv_set_compass_sample_rate(COMPASS_READ_MS * 1000L);
#endif
    inv_set_gyro_orientation_and_scale(
            inv_orientation_matrix_to_scalar(gyro_pdata.orientation),
            (long)gyro_fsr<<15);
    inv_set_accel_orientation_and_scale(
            inv_orientation_matrix_to_scalar(gyro_pdata.orientation),
            (long)accel_fsr<<15);
#ifdef COMPASS_ENABLED
    inv_set_compass_orientation_and_scale(
            inv_orientation_matrix_to_scalar(compass_pdata.orientation),
            (long)compass_fsr<<15);
#endif
#ifdef COMPASS_ENABLED
    hal.sensors = ACCEL_ON | GYRO_ON | COMPASS_ON;
#else
    hal.sensors = ACCEL_ON | GYRO_ON;
#endif
    hal.dmp_on = 0;
    hal.report = 0;
    hal.rx.cmd = 0;
    hal.next_pedo_ms = 0;
    hal.next_compass_ms = 0;
    hal.next_temp_ms = 0;
  get_tick_count(&timestamp);
    dmp_load_motion_driver_firmware();
    dmp_set_orientation(
        inv_orientation_matrix_to_scalar(gyro_pdata.orientation));
    dmp_register_tap_cb(tap_cb);
    dmp_register_android_orient_cb(android_orient_cb);
    hal.dmp_features = DMP_FEATURE_6X_LP_QUAT | DMP_FEATURE_TAP |
        DMP_FEATURE_ANDROID_ORIENT | DMP_FEATURE_SEND_RAW_ACCEL | DMP_FEATURE_SEND_CAL_GYRO |
        DMP_FEATURE_GYRO_CAL;
    dmp_enable_feature(hal.dmp_features);
    dmp_set_fifo_rate(DEFAULT_MPU_HZ);
    mpu_set_dmp_state(1);
    hal.dmp_on = 1;
  while(1){
    
    unsigned long sensor_timestamp;
    int new_data = 0;
    if (USART_GetITStatus(USART1, USART_IT_RXNE)) {
    //if (USART_GetITStatus(USART2, USART_IT_RXNE)) {
        USART_ClearITPendingBit(USART1, USART_IT_RXNE);
        //USART_ClearITPendingBit(USART2, USART_IT_RXNE);
        handle_input();
    }
    get_tick_count(&timestamp);
#ifdef COMPASS_ENABLED
        if ((timestamp > hal.next_compass_ms) && !hal.lp_accel_mode &&
            hal.new_gyro && (hal.sensors & COMPASS_ON)) {
            hal.next_compass_ms = timestamp + COMPASS_READ_MS;
            new_compass = 1;
        }
#endif
        if (timestamp > hal.next_temp_ms) {
            hal.next_temp_ms = timestamp + TEMP_READ_MS;
            new_temp = 1;
        }
    if (hal.motion_int_mode) {
        mpu_lp_motion_interrupt(500, 1, 5);
        inv_accel_was_turned_off();
        inv_gyro_was_turned_off();
        inv_compass_was_turned_off();
        inv_quaternion_sensor_was_turned_off();
        while (!hal.new_gyro) {}
        mpu_lp_motion_interrupt(0, 0, 0);
        hal.motion_int_mode = 0;
    }
    if (!hal.sensors || !hal.new_gyro) {
        continue;
    }
        if (hal.new_gyro && hal.lp_accel_mode) {
            short accel_short[3];
            long accel[3];
            mpu_get_accel_reg(accel_short, &sensor_timestamp);
            accel[0] = (long)accel_short[0];
            accel[1] = (long)accel_short[1];
            accel[2] = (long)accel_short[2];
            inv_build_accel(accel, 0, sensor_timestamp);
            new_data = 1;
            hal.new_gyro = 0;
        } else if (hal.new_gyro && hal.dmp_on) {
            short gyro[3], accel_short[3], sensors;
            unsigned char more;
            long accel[3], quat[4], temperature;
            dmp_read_fifo(gyro, accel_short, quat, &sensor_timestamp, &sensors, &more);
            if (!more)
                hal.new_gyro = 0;
            if (sensors & INV_XYZ_GYRO) {
                inv_build_gyro(gyro, sensor_timestamp);
                new_data = 1;
                if (new_temp) {
                    new_temp = 0;
                    mpu_get_temperature(&temperature, &sensor_timestamp);
                    inv_build_temp(temperature, sensor_timestamp);
                }
            }
            if (sensors & INV_XYZ_ACCEL) {
                accel[0] = (long)accel_short[0];
                accel[1] = (long)accel_short[1];
                accel[2] = (long)accel_short[2];
                inv_build_accel(accel, 0, sensor_timestamp);
                new_data = 1;
            }
            if (sensors & INV_WXYZ_QUAT) {
                inv_build_quat(quat, 0, sensor_timestamp);
                new_data = 1;
            }
        } else if (hal.new_gyro) {
            short gyro[3], accel_short[3];
            unsigned char sensors, more;
            long accel[3], temperature;
            hal.new_gyro = 0;
            mpu_read_fifo(gyro, accel_short, &sensor_timestamp,
                &sensors, &more);
            if (more)
                hal.new_gyro = 1;
            if (sensors & INV_XYZ_GYRO) {
                inv_build_gyro(gyro, sensor_timestamp);
                new_data = 1;
                if (new_temp) {
                    new_temp = 0;
                    mpu_get_temperature(&temperature, &sensor_timestamp);
                    inv_build_temp(temperature, sensor_timestamp);
                }
            }
            if (sensors & INV_XYZ_ACCEL) {
                accel[0] = (long)accel_short[0];
                accel[1] = (long)accel_short[1];
                accel[2] = (long)accel_short[2];
                inv_build_accel(accel, 0, sensor_timestamp);
                new_data = 1;
            }
        }
#ifdef COMPASS_ENABLED
        if (new_compass) {
            short compass_short[3];
            long compass[3];
            new_compass = 0;
            if (!mpu_get_compass_reg(compass_short, &sensor_timestamp)) {
                compass[0] = (long)compass_short[0];
                compass[1] = (long)compass_short[1];
                compass[2] = (long)compass_short[2];
                inv_build_compass(compass, 0, sensor_timestamp);
            }
            new_data = 1;
        }
#endif
        if (new_data) {
            inv_execute_on_data();
            read_from_mpl();
        }
    }
}
read_from_mpl()
static void read_from_mpl (void) [static]
Compass calibration for MPU9150
Private define ------------------------------------------------------------ CLocal Variable init
Sends a quaternion packet to the PC. Since this is used by the Python test app to visually represent a 3D quaternion, it's sent each time the MPL has new data.
Specific data packets can be sent or suppressed using USB commands.
Whenever the MPL detects a change in motion state, the application can be notified. For this example, we use an LED to represent the current motion state.
Definition at line 143 of file main.c.
References get_tick_count(), hal, hal_s::next_pedo_ms, and hal_s::report.
Referenced by main().
{
    long msg, data[9];
    int8_t accuracy;
    unsigned long timestamp;
    float float_data[3] = {0};
    if (inv_get_sensor_type_quat(data, &accuracy, (inv_time_t*)&timestamp)) {
        eMPL_send_quat(data);
        if (hal.report & PRINT_QUAT)
            eMPL_send_data(PACKET_DATA_QUAT, data);
    }
    if (hal.report & PRINT_ACCEL) {
        if (inv_get_sensor_type_accel(data, &accuracy,
            (inv_time_t*)&timestamp))
            eMPL_send_data(PACKET_DATA_ACCEL, data);
    }
    if (hal.report & PRINT_GYRO) {
        if (inv_get_sensor_type_gyro(data, &accuracy,
            (inv_time_t*)&timestamp))
            eMPL_send_data(PACKET_DATA_GYRO, data);
    }
#ifdef COMPASS_ENABLED
    if (hal.report & PRINT_COMPASS) {
        if (inv_get_sensor_type_compass(data, &accuracy,
            (inv_time_t*)&timestamp))
            eMPL_send_data(PACKET_DATA_COMPASS, data);
    }
#endif
    if (hal.report & PRINT_EULER) {
        if (inv_get_sensor_type_euler(data, &accuracy,
            (inv_time_t*)&timestamp))
            eMPL_send_data(PACKET_DATA_EULER, data);
    }
    if (hal.report & PRINT_ROT_MAT) {
        if (inv_get_sensor_type_rot_mat(data, &accuracy,
            (inv_time_t*)&timestamp))
            eMPL_send_data(PACKET_DATA_ROT, data);
    }
    if (hal.report & PRINT_HEADING) {
        if (inv_get_sensor_type_heading(data, &accuracy,
            (inv_time_t*)&timestamp))
            eMPL_send_data(PACKET_DATA_HEADING, data);
    }
    if (hal.report & PRINT_LINEAR_ACCEL) {
        if (inv_get_sensor_type_linear_acceleration(float_data, &accuracy, (inv_time_t*)&timestamp)) {
            MPL_LOGI("Linear Accel: %7.5f %7.5f %7.5f\r\n",
                    float_data[0], float_data[1], float_data[2]);
         }
    }
    if (hal.report & PRINT_GRAVITY_VECTOR) {
            if (inv_get_sensor_type_gravity(float_data, &accuracy,
                (inv_time_t*)&timestamp))
                MPL_LOGI("Gravity Vector: %7.5f %7.5f %7.5f\r\n",
                        float_data[0], float_data[1], float_data[2]);
    }
    if (hal.report & PRINT_PEDO) {
        unsigned long timestamp;
        get_tick_count(&timestamp);
        if (timestamp > hal.next_pedo_ms) {
            hal.next_pedo_ms = timestamp + PEDO_READ_MS;
            unsigned long step_count, walk_time;
            dmp_get_pedometer_step_count(&step_count);
            dmp_get_pedometer_walk_time(&walk_time);
            MPL_LOGI("Walked %ld steps over %ld milliseconds..\n", step_count,
            walk_time);
        }
    }
    msg = inv_get_message_level_0(INV_MSG_MOTION_EVENT |
            INV_MSG_NO_MOTION_EVENT);
    if (msg) {
        if (msg & INV_MSG_MOTION_EVENT) {
            MPL_LOGI("Motion!\n");
        } else if (msg & INV_MSG_NO_MOTION_EVENT) {
            MPL_LOGI("No motion!\n");
        }
    }
}
run_self_test()
static void run_self_test (void) [inline], [static]
Self Test Function Test passed. We can trust the gyro data here, so now we need to update calibrated data
Definition at line 333 of file main.c.
Referenced by handle_input().
{
    int result;
    long gyro[3], accel[3];
#if defined (MPU6500) || defined (MPU9250)
    result = mpu_run_6500_self_test(gyro, accel, 0);
#elif defined (MPU6050) || defined (MPU9150)
    result = mpu_run_self_test(gyro, accel);
#endif
    if (result == 0x7) {
    MPL_LOGI("Passed!\n");
        MPL_LOGI("accel: %7.4f %7.4f %7.4f\n",
                    accel[0]/65536.f,
                    accel[1]/65536.f,
                    accel[2]/65536.f);
        MPL_LOGI("gyro: %7.4f %7.4f %7.4f\n",
                    gyro[0]/65536.f,
                    gyro[1]/65536.f,
                    gyro[2]/65536.f);
#ifdef USE_CAL_HW_REGISTERS
        unsigned char i = 0;
        for(i = 0; i<3; i++) {
            gyro[i] = (long)(gyro[i] * 32.8f); //convert to +-1000dps
            accel[i] *= 2048.f; //convert to +-16G
            accel[i] = accel[i] >> 16;
            gyro[i] = (long)(gyro[i] >> 16);
        }
        mpu_set_gyro_bias_reg(gyro);
#if defined (MPU6500) || defined (MPU9250)
        mpu_set_accel_bias_6500_reg(accel);
#elif defined (MPU6050) || defined (MPU9150)
        mpu_set_accel_bias_6050_reg(accel);
#endif
#else
        /* Push the calibrated data to the MPL library.
         *
         * MPL expects biases in hardware units << 16, but self test returns
         * biases in g's << 16.
         */
        unsigned short accel_sens;
        float gyro_sens;
        mpu_get_accel_sens(&accel_sens);
        accel[0] *= accel_sens;
        accel[1] *= accel_sens;
        accel[2] *= accel_sens;
        inv_set_accel_bias(accel, 3);
        mpu_get_gyro_sens(&gyro_sens);
        gyro[0] = (long) (gyro[0] * gyro_sens);
        gyro[1] = (long) (gyro[1] * gyro_sens);
        gyro[2] = (long) (gyro[2] * gyro_sens);
        inv_set_gyro_bias(gyro, 3);
#endif
    }
    else {
            if (!(result & 0x1))
                MPL_LOGE("Gyro failed.\n");
            if (!(result & 0x2))
                MPL_LOGE("Accel failed.\n");
            if (!(result & 0x4))
                MPL_LOGE("Compass failed.\n");
     }
}
setup_gyro()
static void setup_gyro (void) [static]
Handle sensor on/off combinations. If you need a power transition, this function should be called with a mask of the sensors still enabled. The driver turns off any sensors excluded from this mask.
Switching out of LP accel, notify MPL of new accel sampling rate.
Definition at line 249 of file main.c.
References hal, hal_s::lp_accel_mode, and hal_s::sensors.
Referenced by handle_input().
{
    unsigned char mask = 0, lp_accel_was_on = 0;
    if (hal.sensors & ACCEL_ON)
        mask |= INV_XYZ_ACCEL;
    if (hal.sensors & GYRO_ON) {
        mask |= INV_XYZ_GYRO;
        lp_accel_was_on |= hal.lp_accel_mode;
    }
#ifdef COMPASS_ENABLED
    if (hal.sensors & COMPASS_ON) {
        mask |= INV_XYZ_COMPASS;
        lp_accel_was_on |= hal.lp_accel_mode;
    }
#endif
    mpu_set_sensors(mask);
    mpu_configure_fifo(mask);
    if (lp_accel_was_on) {
        unsigned short rate;
        hal.lp_accel_mode = 0;
        mpu_get_sample_rate(&rate);
        inv_set_accel_sample_rate(1000000L / rate);
    }
}
tap_cb()
static void tap_cb (unsigned char direction, unsigned char count) [static]
Definition at line 279 of file main.c.
{
    switch (direction) {
    case TAP_X_UP:
        MPL_LOGI("Tap X+ ");
        break;
    case TAP_X_DOWN:
        MPL_LOGI("Tap X- ");
        break;
    case TAP_Y_UP:
        MPL_LOGI("Tap Y+ ");
        break;
    case TAP_Y_DOWN:
        MPL_LOGI("Tap Y- ");
        break;
    case TAP_Z_UP:
        MPL_LOGI("Tap Z+ ");
        break;
    case TAP_Z_DOWN:
        MPL_LOGI("Tap Z- ");
        break;
    default:
        return;
    }
    MPL_LOGI("x%d\n", count);
    return;
}
Variable Documentation
cmd
unsigned char cmd
Definition at line 63 of file main.c.
Referenced by handle_input(), and main().
dmp_features
unsigned short dmp_features
Definition at line 78 of file main.c.
dmp_on
unsigned char dmp_on
Definition at line 69 of file main.c.
Referenced by handle_input(), and main().
gyro_pdata
struct platform_data_s gyro_pdata [static]
Initial value:
= {
    .orientation = { 1, 0, 0,
                     0, 1, 0,
                     0, 0, 1}
}
The sensors can be mounted onto the board in any orientation. The mounting matrix seen below tells the MPL how to rotate the raw data from the driver(s). TODO: The following matrices refer to the configuration on internal test boards at Invensense. If needed, please modify the matrices to match the chip-to-body matrix for your particular set up.
Definition at line 102 of file main.c.
hal
struct hal_s hal = {0} [static]
Definition at line 81 of file main.c.
Referenced by gyro_data_ready_cb(), handle_input(), main(), read_from_mpl(), and setup_gyro().
hal_timestamp
volatile uint32_t hal_timestamp = 0
timestamp variable initialize, its for count tick
Definition at line 43 of file main.c.
header
unsigned char header[3]
Definition at line 62 of file main.c.
lp_accel_mode
unsigned char lp_accel_mode
Definition at line 67 of file main.c.
Referenced by handle_input(), main(), and setup_gyro().
motion_int_mode
unsigned char motion_int_mode
Definition at line 72 of file main.c.
Referenced by handle_input(), and main().
mpl_key
unsigned char* mpl_key = (unsigned char*)`eMPL 5.1`
Definition at line 88 of file main.c.
new_gyro
volatile unsigned char new_gyro
Definition at line 71 of file main.c.
Referenced by gyro_data_ready_cb(), and main().
next_compass_ms
unsigned long next_compass_ms
Definition at line 76 of file main.c.
Referenced by main().
next_pedo_ms
unsigned long next_pedo_ms
Definition at line 74 of file main.c.
Referenced by main(), and read_from_mpl().
next_temp_ms
unsigned long next_temp_ms
Definition at line 75 of file main.c.
Referenced by main().
no_dmp_hz
unsigned long no_dmp_hz
Definition at line 73 of file main.c.
orientation
signed char orientation[9]
Definition at line 92 of file main.c.
report
unsigned int report
Definition at line 77 of file main.c.
Referenced by handle_input(), main(), and read_from_mpl().
rx
struct rx_s rx
Definition at line 79 of file main.c.
Referenced by handle_input(), and main().
rx_new
volatile unsigned char rx_new
Usart Receive variable init.
USB RX binary semaphore. Actually, it's just a flag. Not included in struct because it's declared extern elsewhere.
Definition at line 86 of file main.c.
sensors
unsigned char sensors
Definition at line 68 of file main.c.
Referenced by handle_input(), main(), and setup_gyro().
wait_for_tap
unsigned char wait_for_tap
Definition at line 70 of file main.c.