STM32F4_DISCOVERY_LOW_LEVEL_Private_Functions
Functions
void STM_EVAL_LEDInit (Led_TypeDef Led)
Configures LED GPIO.
void STM_EVAL_LEDOn (Led_TypeDef Led)
Turns selected LED On.
void STM_EVAL_LEDOff (Led_TypeDef Led)
Turns selected LED Off.
void STM_EVAL_LEDToggle (Led_TypeDef Led)
Toggles the selected LED.
void STM_EVAL_PBInit (Button_TypeDef Button, ButtonMode_TypeDef Button_Mode)
Configures Button GPIO and EXTI Line.
uint32_t STM_EVAL_PBGetState (Button_TypeDef Button)
Returns the selected Button state.
Detailed Description
Function Documentation
STM_EVAL_LEDInit()
void STM_EVAL_LEDInit (Led_TypeDef Led)
Configures LED GPIO.
Parameters
Led Specifies the Led to be configured. This parameter can be one of following parameters:
LED4
LED3
LED5
LED6
Return values
None
Definition at line 121 of file stm32f4_discovery.c.
References ENABLE, GPIO_CLK, GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_OUT, GPIO_InitTypeDef::GPIO_OType, GPIO_OType_PP, GPIO_PIN, GPIO_InitTypeDef::GPIO_Pin, GPIO_PORT, GPIO_InitTypeDef::GPIO_PuPd, GPIO_PuPd_UP, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_50MHz, and RCC_AHB1PeriphClockCmd().
{
  GPIO_InitTypeDef GPIO_InitStructure;
  
  /* Enable the GPIO_LED Clock */
  RCC_AHB1PeriphClockCmd(GPIO_CLK[Led], ENABLE);
  /* Configure the GPIO_LED pin */
  GPIO_InitStructure.GPIO_Pin = GPIO_PIN[Led];
  GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
  GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
  GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
  GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
  GPIO_Init(GPIO_PORT[Led], &GPIO_InitStructure);
}
STM_EVAL_LEDOff()
void STM_EVAL_LEDOff (Led_TypeDef Led)
Turns selected LED Off.
Parameters
Led Specifies the Led to be set off. This parameter can be one of following parameters:
LED4
LED3
LED5
LED6
Return values
None
Definition at line 162 of file stm32f4_discovery.c.
{
  GPIO_PORT[Led]->BSRRH = GPIO_PIN[Led];
}
STM_EVAL_LEDOn()
void STM_EVAL_LEDOn (Led_TypeDef Led)
Turns selected LED On.
Parameters
Led Specifies the Led to be set on. This parameter can be one of following parameters:
LED4
LED3
LED5
LED6
Return values
None
Definition at line 147 of file stm32f4_discovery.c.
{
  GPIO_PORT[Led]->BSRRL = GPIO_PIN[Led];
}
STM_EVAL_LEDToggle()
void STM_EVAL_LEDToggle (Led_TypeDef Led)
Toggles the selected LED.
Parameters
Led Specifies the Led to be toggled. This parameter can be one of following parameters:
LED4
LED3
LED5
LED6
Return values
None
Definition at line 177 of file stm32f4_discovery.c.
{
  GPIO_PORT[Led]->ODR ^= GPIO_PIN[Led];
}
STM_EVAL_PBGetState()
uint32_t STM_EVAL_PBGetState (Button_TypeDef Button)
Returns the selected Button state.
Parameters
Button Specifies the Button to be checked. This parameter should be: BUTTON_USER
Return values
The Button GPIO pin value.
Definition at line 237 of file stm32f4_discovery.c.
References BUTTON_PIN, BUTTON_PORT, and GPIO_ReadInputDataBit().
{
  return GPIO_ReadInputDataBit(BUTTON_PORT[Button], BUTTON_PIN[Button]);
}
STM_EVAL_PBInit()
void STM_EVAL_PBInit (Button_TypeDef Button, ButtonMode_TypeDef Button_Mode)
Configures Button GPIO and EXTI Line.
Parameters
Button Specifies the Button to be configured. This parameter should be: BUTTON_USER
Button_Mode Specifies Button mode. This parameter can be one of following parameters:
BUTTON_MODE_GPIO: Button will be used as simple IO
BUTTON_MODE_EXTI: Button will be connected to EXTI line with interrupt generation capability
Return values
None
Definition at line 193 of file stm32f4_discovery.c.
References BUTTON_CLK, BUTTON_EXTI_LINE, BUTTON_IRQn, BUTTON_MODE_EXTI, BUTTON_PIN, BUTTON_PIN_SOURCE, BUTTON_PORT, BUTTON_PORT_SOURCE, ENABLE, EXTI_Init(), EXTI_InitTypeDef::EXTI_Line, EXTI_InitTypeDef::EXTI_LineCmd, EXTI_InitTypeDef::EXTI_Mode, EXTI_Mode_Interrupt, EXTI_InitTypeDef::EXTI_Trigger, EXTI_Trigger_Rising, GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_IN, GPIO_InitTypeDef::GPIO_Pin, GPIO_InitTypeDef::GPIO_PuPd, GPIO_PuPd_NOPULL, NVIC_Init(), NVIC_InitTypeDef::NVIC_IRQChannel, NVIC_InitTypeDef::NVIC_IRQChannelCmd, NVIC_InitTypeDef::NVIC_IRQChannelPreemptionPriority, NVIC_InitTypeDef::NVIC_IRQChannelSubPriority, RCC_AHB1PeriphClockCmd(), RCC_APB2PeriphClockCmd(), and SYSCFG_EXTILineConfig().
{
  GPIO_InitTypeDef GPIO_InitStructure;
  EXTI_InitTypeDef EXTI_InitStructure;
  NVIC_InitTypeDef NVIC_InitStructure;
  /* Enable the BUTTON Clock */
  RCC_AHB1PeriphClockCmd(BUTTON_CLK[Button], ENABLE);
  RCC_APB2PeriphClockCmd(RCC_APB2Periph_SYSCFG, ENABLE);
  /* Configure Button pin as input */
  GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;
  GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
  GPIO_InitStructure.GPIO_Pin = BUTTON_PIN[Button];
  GPIO_Init(BUTTON_PORT[Button], &GPIO_InitStructure);
  if (Button_Mode == BUTTON_MODE_EXTI)
  {
    /* Connect Button EXTI Line to Button GPIO Pin */
    SYSCFG_EXTILineConfig(BUTTON_PORT_SOURCE[Button], BUTTON_PIN_SOURCE[Button]);
    /* Configure Button EXTI line */
    EXTI_InitStructure.EXTI_Line = BUTTON_EXTI_LINE[Button];
    EXTI_InitStructure.EXTI_Mode = EXTI_Mode_Interrupt;
    EXTI_InitStructure.EXTI_Trigger = EXTI_Trigger_Rising;
    EXTI_InitStructure.EXTI_LineCmd = ENABLE;
    EXTI_Init(&EXTI_InitStructure);
    /* Enable and set Button EXTI Interrupt to the lowest priority */
    NVIC_InitStructure.NVIC_IRQChannel = BUTTON_IRQn[Button];
    NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0x0F;
    NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0x0F;
    NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
    NVIC_Init(&NVIC_InitStructure);
  }
}