FLASH Memory Programming functions
FLASH Memory Programming functions.
Functions
void FLASH_Unlock (void)
Unlocks the FLASH control register access.
void FLASH_Lock (void)
Locks the FLASH control register access.
 FLASH_Status FLASH_EraseSector (uint32_t FLASH_Sector, uint8_t VoltageRange)
Erases a specified FLASH Sector.
 FLASH_Status FLASH_EraseAllSectors (uint8_t VoltageRange)
Erases all FLASH Sectors.
 FLASH_Status FLASH_ProgramDoubleWord (uint32_t Address, uint64_t Data)
Programs a double word (64-bit) at a specified address.
 FLASH_Status FLASH_ProgramWord (uint32_t Address, uint32_t Data)
Programs a word (32-bit) at a specified address.
 FLASH_Status FLASH_ProgramHalfWord (uint32_t Address, uint16_t Data)
Programs a half word (16-bit) at a specified address.
 FLASH_Status FLASH_ProgramByte (uint32_t Address, uint8_t Data)
Programs a byte (8-bit) at a specified address.
Detailed Description
FLASH Memory Programming functions.
 ===============================================================================
                      FLASH Memory Programming functions
 ===============================================================================   

   This group includes the following functions:
    - void FLASH_Unlock(void)
    - void FLASH_Lock(void)
    - FLASH_Status FLASH_EraseSector(uint32_t FLASH_Sector, uint8_t VoltageRange)
    - FLASH_Status FLASH_EraseAllSectors(uint8_t VoltageRange)
    - FLASH_Status FLASH_ProgramDoubleWord(uint32_t Address, uint64_t Data)
    - FLASH_Status FLASH_ProgramWord(uint32_t Address, uint32_t Data)
    - FLASH_Status FLASH_ProgramHalfWord(uint32_t Address, uint16_t Data)
    - FLASH_Status FLASH_ProgramByte(uint32_t Address, uint8_t Data)
   
   Any operation of erase or program should follow these steps:
   1. Call the FLASH_Unlock() function to enable the FLASH control register access

   2. Call the desired function to erase sector(s) or program data

   3. Call the FLASH_Lock() function to disable the FLASH control register access
      (recommended to protect the FLASH memory against possible unwanted operation)
Function Documentation
FLASH_EraseAllSectors()
 FLASH_Status FLASH_EraseAllSectors (uint8_t VoltageRange)
Erases all FLASH Sectors.
Parameters
VoltageRange The device voltage range which defines the erase parallelism. This parameter can be one of the following values:
VoltageRange_1: when the device voltage range is 1.8V to 2.1V, the operation will be done by byte (8-bit)
VoltageRange_2: when the device voltage range is 2.1V to 2.7V, the operation will be done by half word (16-bit)
VoltageRange_3: when the device voltage range is 2.7V to 3.6V, the operation will be done by word (32-bit)
VoltageRange_4: when the device voltage range is 2.7V to 3.6V + External Vpp, the operation will be done by double word (64-bit)
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 406 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  uint32_t tmp_psize = 0x0;
  FLASH_Status status = FLASH_COMPLETE;
  
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  assert_param(IS_VOLTAGERANGE(VoltageRange));
  
  if(VoltageRange == VoltageRange_1)
  {
     tmp_psize = FLASH_PSIZE_BYTE;
  }
  else if(VoltageRange == VoltageRange_2)
  {
    tmp_psize = FLASH_PSIZE_HALF_WORD;
  }
  else if(VoltageRange == VoltageRange_3)
  {
    tmp_psize = FLASH_PSIZE_WORD;
  }
  else
  {
    tmp_psize = FLASH_PSIZE_DOUBLE_WORD;
  }
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to erase all sectors */
     FLASH->CR &= CR_PSIZE_MASK;
     FLASH->CR |= tmp_psize;
     FLASH->CR |= FLASH_CR_MER;
     FLASH->CR |= FLASH_CR_STRT;
    
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    /* if the erase operation is completed, disable the MER Bit */
    FLASH->CR &= (~FLASH_CR_MER);
  }
  /* Return the Erase Status */
  return status;
}
FLASH_EraseSector()
 FLASH_Status FLASH_EraseSector (uint32_t FLASH_Sector, uint8_t VoltageRange)
Erases a specified FLASH Sector.
Parameters
FLASH_Sector The Sector number to be erased. This parameter can be a value between FLASH_Sector_0 and FLASH_Sector_11
VoltageRange The device voltage range which defines the erase parallelism. This parameter can be one of the following values:
VoltageRange_1: when the device voltage range is 1.8V to 2.1V, the operation will be done by byte (8-bit)
VoltageRange_2: when the device voltage range is 2.1V to 2.7V, the operation will be done by half word (16-bit)
VoltageRange_3: when the device voltage range is 2.7V to 3.6V, the operation will be done by word (32-bit)
VoltageRange_4: when the device voltage range is 2.7V to 3.6V + External Vpp, the operation will be done by double word (64-bit)
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 341 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  uint32_t tmp_psize = 0x0;
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_FLASH_SECTOR(FLASH_Sector));
  assert_param(IS_VOLTAGERANGE(VoltageRange));
  
  if(VoltageRange == VoltageRange_1)
  {
     tmp_psize = FLASH_PSIZE_BYTE;
  }
  else if(VoltageRange == VoltageRange_2)
  {
    tmp_psize = FLASH_PSIZE_HALF_WORD;
  }
  else if(VoltageRange == VoltageRange_3)
  {
    tmp_psize = FLASH_PSIZE_WORD;
  }
  else
  {
    tmp_psize = FLASH_PSIZE_DOUBLE_WORD;
  }
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to erase the sector */
    FLASH->CR &= CR_PSIZE_MASK;
    FLASH->CR |= tmp_psize;
    FLASH->CR &= SECTOR_MASK;
    FLASH->CR |= FLASH_CR_SER | FLASH_Sector;
    FLASH->CR |= FLASH_CR_STRT;
    
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    
    /* if the erase operation is completed, disable the SER Bit */
    FLASH->CR &= (~FLASH_CR_SER);
    FLASH->CR &= SECTOR_MASK;
  }
  /* Return the Erase Status */
  return status;
}
FLASH_Lock()
void FLASH_Lock (void)
Locks the FLASH control register access.
Parameters
None
Return values
None
Definition at line 315 of file stm32f4xx_flash.c.
{
  /* Set the LOCK Bit to lock the FLASH Registers access */
  FLASH->CR |= FLASH_CR_LOCK;
}
FLASH_ProgramByte()
 FLASH_Status FLASH_ProgramByte (uint32_t Address, uint8_t Data)
Programs a byte (8-bit) at a specified address.
Note
This function can be used within all the device supply voltage ranges.
Parameters
Address specifies the address to be programmed. This parameter can be any address in Program memory zone or in OTP zone.
Data specifies the data to be programmed.
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 573 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_FLASH_ADDRESS(Address));
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to program the new data */
    FLASH->CR &= CR_PSIZE_MASK;
    FLASH->CR |= FLASH_PSIZE_BYTE;
    FLASH->CR |= FLASH_CR_PG;
  
    *(__IO uint8_t*)Address = Data;
        
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    /* if the program operation is completed, disable the PG Bit */
    FLASH->CR &= (~FLASH_CR_PG);
  }
  /* Return the Program Status */
  return status;
}
FLASH_ProgramDoubleWord()
 FLASH_Status FLASH_ProgramDoubleWord (uint32_t Address, uint64_t Data)
Programs a double word (64-bit) at a specified address.
Note
This function must be used when the device voltage range is from 2.7V to 3.6V and an External Vpp is present.
Parameters
Address specifies the address to be programmed.
Data specifies the data to be programmed.
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 459 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_FLASH_ADDRESS(Address));
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to program the new data */
    FLASH->CR &= CR_PSIZE_MASK;
    FLASH->CR |= FLASH_PSIZE_DOUBLE_WORD;
    FLASH->CR |= FLASH_CR_PG;
  
    *(__IO uint64_t*)Address = Data;
        
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    /* if the program operation is completed, disable the PG Bit */
    FLASH->CR &= (~FLASH_CR_PG);
  }
  /* Return the Program Status */
  return status;
}
FLASH_ProgramHalfWord()
 FLASH_Status FLASH_ProgramHalfWord (uint32_t Address, uint16_t Data)
Programs a half word (16-bit) at a specified address.
Note
This function must be used when the device voltage range is from 2.1V to 3.6V.
Parameters
Address specifies the address to be programmed. This parameter can be any address in Program memory zone or in OTP zone.
Data specifies the data to be programmed.
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 535 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_FLASH_ADDRESS(Address));
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to program the new data */
    FLASH->CR &= CR_PSIZE_MASK;
    FLASH->CR |= FLASH_PSIZE_HALF_WORD;
    FLASH->CR |= FLASH_CR_PG;
  
    *(__IO uint16_t*)Address = Data;
        
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    /* if the program operation is completed, disable the PG Bit */
    FLASH->CR &= (~FLASH_CR_PG);
  }
  /* Return the Program Status */
  return status;
}
FLASH_ProgramWord()
 FLASH_Status FLASH_ProgramWord (uint32_t Address, uint32_t Data)
Programs a word (32-bit) at a specified address.
Parameters
Address specifies the address to be programmed. This parameter can be any address in Program memory zone or in OTP zone.
Note
This function must be used when the device voltage range is from 2.7V to 3.6V.
Parameters
Data specifies the data to be programmed.
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 497 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_FLASH_ADDRESS(Address));
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to program the new data */
    FLASH->CR &= CR_PSIZE_MASK;
    FLASH->CR |= FLASH_PSIZE_WORD;
    FLASH->CR |= FLASH_CR_PG;
  
    *(__IO uint32_t*)Address = Data;
        
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    /* if the program operation is completed, disable the PG Bit */
    FLASH->CR &= (~FLASH_CR_PG);
  }
  /* Return the Program Status */
  return status;
}
FLASH_Unlock()
void FLASH_Unlock (void)
Unlocks the FLASH control register access.
Parameters
None
Return values
None
Definition at line 300 of file stm32f4xx_flash.c.
{
  if((FLASH->CR & FLASH_CR_LOCK) != RESET)
  {
    /* Authorize the FLASH Registers access */
    FLASH->KEYR = FLASH_KEY1;
    FLASH->KEYR = FLASH_KEY2;
  }
}