CRYP
CRYP driver modules.
Modules
 CRYP_Exported_Constants
 CRYP_Private_Functions
Classes
struct CRYP_InitTypeDef
CRYP Init structure definition.
struct CRYP_KeyInitTypeDef
CRYP Key(s) structure definition.
struct CRYP_IVInitTypeDef
CRYP Initialization Vectors (IV) structure definition.
struct CRYP_Context
CRYP context swapping structure definition.
Macros
#define FLAG_MASK ((uint8_t)0x20)
#define MAX_TIMEOUT ((uint16_t)0xFFFF)
#define AESBUSY_TIMEOUT ((uint32_t) 0x00010000)
#define DESBUSY_TIMEOUT ((uint32_t) 0x00010000)
#define TDESBUSY_TIMEOUT ((uint32_t) 0x00010000)
Functions
void CRYP_DeInit (void)
Deinitializes the CRYP peripheral registers to their default reset values.
void CRYP_Init (CRYP_InitTypeDef *CRYP_InitStruct)
Initializes the CRYP peripheral according to the specified parameters in the CRYP_InitStruct.
void CRYP_StructInit (CRYP_InitTypeDef *CRYP_InitStruct)
Fills each CRYP_InitStruct member with its default value.
void CRYP_KeyInit (CRYP_KeyInitTypeDef *CRYP_KeyInitStruct)
Initializes the CRYP Keys according to the specified parameters in the CRYP_KeyInitStruct.
void CRYP_KeyStructInit (CRYP_KeyInitTypeDef *CRYP_KeyInitStruct)
Fills each CRYP_KeyInitStruct member with its default value.
void CRYP_IVInit (CRYP_IVInitTypeDef *CRYP_IVInitStruct)
Initializes the CRYP Initialization Vectors(IV) according to the specified parameters in the CRYP_IVInitStruct.
void CRYP_IVStructInit (CRYP_IVInitTypeDef *CRYP_IVInitStruct)
Fills each CRYP_IVInitStruct member with its default value.
void CRYP_Cmd (FunctionalState NewState)
Enables or disables the CRYP peripheral.
void CRYP_DataIn (uint32_t Data)
Writes data in the Data Input register (DIN).
uint32_t CRYP_DataOut (void)
Returns the last data entered into the output FIFO.
void CRYP_FIFOFlush (void)
Flushes the IN and OUT FIFOs (that is read and write pointers of the FIFOs are reset)
 ErrorStatus CRYP_SaveContext (CRYP_Context *CRYP_ContextSave, CRYP_KeyInitTypeDef *CRYP_KeyInitStruct)
Saves the CRYP peripheral Context.
void CRYP_RestoreContext (CRYP_Context *CRYP_ContextRestore)
Restores the CRYP peripheral Context.
void CRYP_DMACmd (uint8_t CRYP_DMAReq, FunctionalState NewState)
Enables or disables the CRYP DMA interface.
void CRYP_ITConfig (uint8_t CRYP_IT, FunctionalState NewState)
Enables or disables the specified CRYP interrupts.
 ITStatus CRYP_GetITStatus (uint8_t CRYP_IT)
Checks whether the specified CRYP interrupt has occurred or not.
 FlagStatus CRYP_GetFlagStatus (uint8_t CRYP_FLAG)
Checks whether the specified CRYP flag is set or not.
 ErrorStatus CRYP_AES_ECB (uint8_t Mode, uint8_t *Key, uint16_t Keysize, uint8_t *Input, uint32_t Ilength, uint8_t *Output)
Encrypt and decrypt using AES in ECB Mode.
 ErrorStatus CRYP_AES_CBC (uint8_t Mode, uint8_t InitVectors[16], uint8_t *Key, uint16_t Keysize, uint8_t *Input, uint32_t Ilength, uint8_t *Output)
Encrypt and decrypt using AES in CBC Mode.
 ErrorStatus CRYP_AES_CTR (uint8_t Mode, uint8_t InitVectors[16], uint8_t *Key, uint16_t Keysize, uint8_t *Input, uint32_t Ilength, uint8_t *Output)
Encrypt and decrypt using AES in CTR Mode.
 ErrorStatus CRYP_TDES_ECB (uint8_t Mode, uint8_t Key[24], uint8_t *Input, uint32_t Ilength, uint8_t *Output)
Encrypt and decrypt using TDES in ECB Mode.
 ErrorStatus CRYP_TDES_CBC (uint8_t Mode, uint8_t Key[24], uint8_t InitVectors[8], uint8_t *Input, uint32_t Ilength, uint8_t *Output)
Encrypt and decrypt using TDES in CBC Mode.
 ErrorStatus CRYP_DES_ECB (uint8_t Mode, uint8_t Key[8], uint8_t *Input, uint32_t Ilength, uint8_t *Output)
Encrypt and decrypt using DES in ECB Mode.
 ErrorStatus CRYP_DES_CBC (uint8_t Mode, uint8_t Key[8], uint8_t InitVectors[8], uint8_t *Input, uint32_t Ilength, uint8_t *Output)
Encrypt and decrypt using DES in CBC Mode.
Detailed Description
CRYP driver modules.
Macro Definition Documentation
AESBUSY_TIMEOUT
#define AESBUSY_TIMEOUT ((uint32_t) 0x00010000)
Definition at line 59 of file stm32f4xx_cryp_aes.c.
DESBUSY_TIMEOUT
#define DESBUSY_TIMEOUT ((uint32_t) 0x00010000)
Definition at line 57 of file stm32f4xx_cryp_des.c.
FLAG_MASK
#define FLAG_MASK ((uint8_t)0x20)
Definition at line 173 of file stm32f4xx_cryp.c.
MAX_TIMEOUT
#define MAX_TIMEOUT ((uint16_t)0xFFFF)
Definition at line 174 of file stm32f4xx_cryp.c.
TDESBUSY_TIMEOUT
#define TDESBUSY_TIMEOUT ((uint32_t) 0x00010000)
Definition at line 57 of file stm32f4xx_cryp_tdes.c.
Function Documentation
CRYP_AES_CBC()
 ErrorStatus CRYP_AES_CBC (uint8_t Mode, uint8_t InitVectors[16], uint8_t * Key, uint16_t Keysize, uint8_t * Input, uint32_t Ilength, uint8_t * Output)
Encrypt and decrypt using AES in CBC Mode.
Parameters
Mode encryption or decryption Mode. This parameter can be one of the following values:
MODE_ENCRYPT: Encryption
MODE_DECRYPT: Decryption
InitVectors Initialisation Vectors used for AES algorithm.
Key Key used for AES algorithm.
Keysize length of the Key, must be a 128, 192 or 256.
Input pointer to the Input buffer.
Ilength length of the Input buffer, must be a multiple of 16.
Output pointer to the returned buffer.
Return values
An ErrorStatus enumeration value:
SUCCESS: Operation done
ERROR: Operation failed
Definition at line 279 of file stm32f4xx_cryp_aes.c.
References CRYP_InitTypeDef::CRYP_AlgoDir, CRYP_InitTypeDef::CRYP_AlgoMode, CRYP_Cmd(), CRYP_InitTypeDef::CRYP_DataType, CRYP_FIFOFlush(), CRYP_Init(), CRYP_IVInit(), CRYP_KeyInit(), CRYP_InitTypeDef::CRYP_KeySize, CRYP_KeyStructInit(), DISABLE, ENABLE, and SUCCESS.
{
  CRYP_InitTypeDef AES_CRYP_InitStructure;
  CRYP_KeyInitTypeDef AES_CRYP_KeyInitStructure;
  CRYP_IVInitTypeDef AES_CRYP_IVInitStructure;
  __IO uint32_t counter = 0;
  uint32_t busystatus = 0;
  ErrorStatus status = SUCCESS;
  uint32_t keyaddr = (uint32_t)Key;
  uint32_t inputaddr = (uint32_t)Input;
  uint32_t outputaddr = (uint32_t)Output;
  uint32_t ivaddr = (uint32_t)InitVectors;
  uint32_t i = 0;
  /* Crypto structures initialisation*/
  CRYP_KeyStructInit(&AES_CRYP_KeyInitStructure);
  switch(Keysize)
  {
    case 128:
    AES_CRYP_InitStructure.CRYP_KeySize = CRYP_KeySize_128b;
    AES_CRYP_KeyInitStructure.CRYP_Key2Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Right= __REV(*(uint32_t*)(keyaddr));
    break;
    case 192:
    AES_CRYP_InitStructure.CRYP_KeySize = CRYP_KeySize_192b;
    AES_CRYP_KeyInitStructure.CRYP_Key1Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key1Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Right= __REV(*(uint32_t*)(keyaddr));
    break;
    case 256:
    AES_CRYP_InitStructure.CRYP_KeySize = CRYP_KeySize_256b;
    AES_CRYP_KeyInitStructure.CRYP_Key0Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key0Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key1Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key1Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Right= __REV(*(uint32_t*)(keyaddr));
    break;
    default:
    break;
  }
  /* CRYP Initialization Vectors */
  AES_CRYP_IVInitStructure.CRYP_IV0Left = __REV(*(uint32_t*)(ivaddr));
  ivaddr+=4;
  AES_CRYP_IVInitStructure.CRYP_IV0Right= __REV(*(uint32_t*)(ivaddr));
  ivaddr+=4;
  AES_CRYP_IVInitStructure.CRYP_IV1Left = __REV(*(uint32_t*)(ivaddr));
  ivaddr+=4;
  AES_CRYP_IVInitStructure.CRYP_IV1Right= __REV(*(uint32_t*)(ivaddr));
  /*------------------ AES Decryption ------------------*/
  if(Mode == MODE_DECRYPT) /* AES decryption */
  {
    /* Flush IN/OUT FIFOs */
    CRYP_FIFOFlush();
    /* Crypto Init for Key preparation for decryption process */
    AES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Decrypt;
    AES_CRYP_InitStructure.CRYP_AlgoMode = CRYP_AlgoMode_AES_Key;
    AES_CRYP_InitStructure.CRYP_DataType = CRYP_DataType_32b;
    CRYP_Init(&AES_CRYP_InitStructure);
    /* Key Initialisation */
    CRYP_KeyInit(&AES_CRYP_KeyInitStructure);
    /* Enable Crypto processor */
    CRYP_Cmd(ENABLE);
    /* wait until the Busy flag is RESET */
    do
    {
      busystatus = CRYP_GetFlagStatus(CRYP_FLAG_BUSY);
      counter++;
    }while ((counter != AESBUSY_TIMEOUT) && (busystatus != RESET));
    if (busystatus != RESET)
   {
       status = ERROR;
    }
    else
    {
      /* Crypto Init for decryption process */
      AES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Decrypt;
    }
  }
  /*------------------ AES Encryption ------------------*/
  else /* AES encryption */
  {
    CRYP_KeyInit(&AES_CRYP_KeyInitStructure);
    /* Crypto Init for Encryption process */
    AES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Encrypt;
  }
  AES_CRYP_InitStructure.CRYP_AlgoMode = CRYP_AlgoMode_AES_CBC;
  AES_CRYP_InitStructure.CRYP_DataType = CRYP_DataType_8b;
  CRYP_Init(&AES_CRYP_InitStructure);
  /* CRYP Initialization Vectors */
  CRYP_IVInit(&AES_CRYP_IVInitStructure);
  /* Flush IN/OUT FIFOs */
  CRYP_FIFOFlush();
  /* Enable Crypto processor */
  CRYP_Cmd(ENABLE);
  for(i=0; ((i<Ilength) && (status != ERROR)); i+=16)
  {
    /* Write the Input block in the IN FIFO */
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    /* Wait until the complete message has been processed */
    counter = 0;
    do
    {
      busystatus = CRYP_GetFlagStatus(CRYP_FLAG_BUSY);
      counter++;
    }while ((counter != AESBUSY_TIMEOUT) && (busystatus != RESET));
    if (busystatus != RESET)
   {
       status = ERROR;
    }
    else
    {
      /* Read the Output block from the Output FIFO */
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
    }
  }
  /* Disable Crypto */
  CRYP_Cmd(DISABLE);
  return status;
}
CRYP_AES_CTR()
 ErrorStatus CRYP_AES_CTR (uint8_t Mode, uint8_t InitVectors[16], uint8_t * Key, uint16_t Keysize, uint8_t * Input, uint32_t Ilength, uint8_t * Output)
Encrypt and decrypt using AES in CTR Mode.
Parameters
Mode encryption or decryption Mode. This parameter can be one of the following values:
MODE_ENCRYPT: Encryption
MODE_DECRYPT: Decryption
InitVectors Initialisation Vectors used for AES algorithm.
Key Key used for AES algorithm.
Keysize length of the Key, must be a 128, 192 or 256.
Input pointer to the Input buffer.
Ilength length of the Input buffer, must be a multiple of 16.
Output pointer to the returned buffer.
Return values
An ErrorStatus enumeration value:
SUCCESS: Operation done
ERROR: Operation failed
Definition at line 475 of file stm32f4xx_cryp_aes.c.
References CRYP_InitTypeDef::CRYP_AlgoDir, CRYP_InitTypeDef::CRYP_AlgoMode, CRYP_Cmd(), CRYP_InitTypeDef::CRYP_DataType, CRYP_FIFOFlush(), CRYP_Init(), CRYP_IVInit(), CRYP_KeyInit(), CRYP_InitTypeDef::CRYP_KeySize, CRYP_KeyStructInit(), DISABLE, ENABLE, and SUCCESS.
{
  CRYP_InitTypeDef AES_CRYP_InitStructure;
  CRYP_KeyInitTypeDef AES_CRYP_KeyInitStructure;
  CRYP_IVInitTypeDef AES_CRYP_IVInitStructure;
  __IO uint32_t counter = 0;
  uint32_t busystatus = 0;
  ErrorStatus status = SUCCESS;
  uint32_t keyaddr = (uint32_t)Key;
  uint32_t inputaddr = (uint32_t)Input;
  uint32_t outputaddr = (uint32_t)Output;
  uint32_t ivaddr = (uint32_t)InitVectors;
  uint32_t i = 0;
  /* Crypto structures initialisation*/
  CRYP_KeyStructInit(&AES_CRYP_KeyInitStructure);
  switch(Keysize)
  {
    case 128:
    AES_CRYP_InitStructure.CRYP_KeySize = CRYP_KeySize_128b;
    AES_CRYP_KeyInitStructure.CRYP_Key2Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Right= __REV(*(uint32_t*)(keyaddr));
    break;
    case 192:
    AES_CRYP_InitStructure.CRYP_KeySize = CRYP_KeySize_192b;
    AES_CRYP_KeyInitStructure.CRYP_Key1Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key1Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Right= __REV(*(uint32_t*)(keyaddr));
    break;
    case 256:
    AES_CRYP_InitStructure.CRYP_KeySize = CRYP_KeySize_256b;
    AES_CRYP_KeyInitStructure.CRYP_Key0Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key0Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key1Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key1Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Right= __REV(*(uint32_t*)(keyaddr));
    break;
    default:
    break;
  }
  /* CRYP Initialization Vectors */
  AES_CRYP_IVInitStructure.CRYP_IV0Left = __REV(*(uint32_t*)(ivaddr));
  ivaddr+=4;
  AES_CRYP_IVInitStructure.CRYP_IV0Right= __REV(*(uint32_t*)(ivaddr));
  ivaddr+=4;
  AES_CRYP_IVInitStructure.CRYP_IV1Left = __REV(*(uint32_t*)(ivaddr));
  ivaddr+=4;
  AES_CRYP_IVInitStructure.CRYP_IV1Right= __REV(*(uint32_t*)(ivaddr));
  /* Key Initialisation */
  CRYP_KeyInit(&AES_CRYP_KeyInitStructure);
  /*------------------ AES Decryption ------------------*/
  if(Mode == MODE_DECRYPT) /* AES decryption */
  {
    /* Crypto Init for decryption process */
    AES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Decrypt;
  }
  /*------------------ AES Encryption ------------------*/
  else /* AES encryption */
  {
    /* Crypto Init for Encryption process */
    AES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Encrypt;
  }
  AES_CRYP_InitStructure.CRYP_AlgoMode = CRYP_AlgoMode_AES_CTR;
  AES_CRYP_InitStructure.CRYP_DataType = CRYP_DataType_8b;
  CRYP_Init(&AES_CRYP_InitStructure);
  /* CRYP Initialization Vectors */
  CRYP_IVInit(&AES_CRYP_IVInitStructure);
  /* Flush IN/OUT FIFOs */
  CRYP_FIFOFlush();
  /* Enable Crypto processor */
  CRYP_Cmd(ENABLE);
  for(i=0; ((i<Ilength) && (status != ERROR)); i+=16)
  {
    /* Write the Input block in the IN FIFO */
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    /* Wait until the complete message has been processed */
    counter = 0;
    do
    {
      busystatus = CRYP_GetFlagStatus(CRYP_FLAG_BUSY);
      counter++;
    }while ((counter != AESBUSY_TIMEOUT) && (busystatus != RESET));
    if (busystatus != RESET)
   {
       status = ERROR;
    }
    else
    {
      /* Read the Output block from the Output FIFO */
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
    }
  }
  /* Disable Crypto */
  CRYP_Cmd(DISABLE);
  return status;
}
CRYP_AES_ECB()
 ErrorStatus CRYP_AES_ECB (uint8_t Mode, uint8_t * Key, uint16_t Keysize, uint8_t * Input, uint32_t Ilength, uint8_t * Output)
Encrypt and decrypt using AES in ECB Mode.
Parameters
Mode encryption or decryption Mode. This parameter can be one of the following values:
MODE_ENCRYPT: Encryption
MODE_DECRYPT: Decryption
Key Key used for AES algorithm.
Keysize length of the Key, must be a 128, 192 or 256.
Input pointer to the Input buffer.
Ilength length of the Input buffer, must be a multiple of 16.
Output pointer to the returned buffer.
Return values
An ErrorStatus enumeration value:
SUCCESS: Operation done
ERROR: Operation failed
Definition at line 98 of file stm32f4xx_cryp_aes.c.
References CRYP_InitTypeDef::CRYP_AlgoDir, CRYP_InitTypeDef::CRYP_AlgoMode, CRYP_Cmd(), CRYP_InitTypeDef::CRYP_DataType, CRYP_FIFOFlush(), CRYP_Init(), CRYP_KeyInit(), CRYP_InitTypeDef::CRYP_KeySize, CRYP_KeyStructInit(), DISABLE, ENABLE, and SUCCESS.
{
  CRYP_InitTypeDef AES_CRYP_InitStructure;
  CRYP_KeyInitTypeDef AES_CRYP_KeyInitStructure;
  __IO uint32_t counter = 0;
  uint32_t busystatus = 0;
  ErrorStatus status = SUCCESS;
  uint32_t keyaddr = (uint32_t)Key;
  uint32_t inputaddr = (uint32_t)Input;
  uint32_t outputaddr = (uint32_t)Output;
  uint32_t i = 0;
  /* Crypto structures initialisation*/
  CRYP_KeyStructInit(&AES_CRYP_KeyInitStructure);
  switch(Keysize)
  {
    case 128:
    AES_CRYP_InitStructure.CRYP_KeySize = CRYP_KeySize_128b;
    AES_CRYP_KeyInitStructure.CRYP_Key2Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Right= __REV(*(uint32_t*)(keyaddr));
    break;
    case 192:
    AES_CRYP_InitStructure.CRYP_KeySize = CRYP_KeySize_192b;
    AES_CRYP_KeyInitStructure.CRYP_Key1Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key1Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Right= __REV(*(uint32_t*)(keyaddr));
    break;
    case 256:
    AES_CRYP_InitStructure.CRYP_KeySize = CRYP_KeySize_256b;
    AES_CRYP_KeyInitStructure.CRYP_Key0Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key0Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key1Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key1Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key2Right= __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Left = __REV(*(uint32_t*)(keyaddr));
    keyaddr+=4;
    AES_CRYP_KeyInitStructure.CRYP_Key3Right= __REV(*(uint32_t*)(keyaddr));
    break;
    default:
    break;
  }
  /*------------------ AES Decryption ------------------*/
  if(Mode == MODE_DECRYPT) /* AES decryption */
  {
    /* Flush IN/OUT FIFOs */
    CRYP_FIFOFlush();
    /* Crypto Init for Key preparation for decryption process */
    AES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Decrypt;
    AES_CRYP_InitStructure.CRYP_AlgoMode = CRYP_AlgoMode_AES_Key;
    AES_CRYP_InitStructure.CRYP_DataType = CRYP_DataType_32b;
    CRYP_Init(&AES_CRYP_InitStructure);
    /* Key Initialisation */
    CRYP_KeyInit(&AES_CRYP_KeyInitStructure);
    /* Enable Crypto processor */
    CRYP_Cmd(ENABLE);
    /* wait until the Busy flag is RESET */
    do
    {
      busystatus = CRYP_GetFlagStatus(CRYP_FLAG_BUSY);
      counter++;
    }while ((counter != AESBUSY_TIMEOUT) && (busystatus != RESET));
    if (busystatus != RESET)
   {
       status = ERROR;
    }
    else
    {
      /* Crypto Init for decryption process */
      AES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Decrypt;
    }
  }
  /*------------------ AES Encryption ------------------*/
  else /* AES encryption */
  {
    CRYP_KeyInit(&AES_CRYP_KeyInitStructure);
    /* Crypto Init for Encryption process */
    AES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Encrypt;
  }
  AES_CRYP_InitStructure.CRYP_AlgoMode = CRYP_AlgoMode_AES_ECB;
  AES_CRYP_InitStructure.CRYP_DataType = CRYP_DataType_8b;
  CRYP_Init(&AES_CRYP_InitStructure);
  /* Flush IN/OUT FIFOs */
  CRYP_FIFOFlush();
  /* Enable Crypto processor */
  CRYP_Cmd(ENABLE);
  for(i=0; ((i<Ilength) && (status != ERROR)); i+=16)
  {
    /* Write the Input block in the IN FIFO */
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    /* Wait until the complete message has been processed */
    counter = 0;
    do
    {
      busystatus = CRYP_GetFlagStatus(CRYP_FLAG_BUSY);
      counter++;
    }while ((counter != AESBUSY_TIMEOUT) && (busystatus != RESET));
    if (busystatus != RESET)
   {
       status = ERROR;
    }
    else
    {
      /* Read the Output block from the Output FIFO */
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
    }
  }
  /* Disable Crypto */
  CRYP_Cmd(DISABLE);
  return status;
}
CRYP_Cmd()
void CRYP_Cmd (FunctionalState NewState)
Enables or disables the CRYP peripheral.
Parameters
NewState new state of the CRYP peripheral. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 370 of file stm32f4xx_cryp.c.
References DISABLE.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the Cryptographic processor */
    CRYP->CR |= CRYP_CR_CRYPEN;
  }
  else
  {
    /* Disable the Cryptographic processor */
    CRYP->CR &= ~CRYP_CR_CRYPEN;
  }
}
CRYP_DataIn()
void CRYP_DataIn (uint32_t Data)
Writes data in the Data Input register (DIN).
Note
After the DIN register has been read once or several times, the FIFO must be flushed (using CRYP_FIFOFlush() function).
Parameters
Data data to write in Data Input register
Return values
None
Definition at line 413 of file stm32f4xx_cryp.c.
{
  CRYP->DR = Data;
}
CRYP_DataOut()
uint32_t CRYP_DataOut (void)
Returns the last data entered into the output FIFO.
Parameters
None
Return values
Last data entered into the output FIFO.
Definition at line 423 of file stm32f4xx_cryp.c.
{
  return CRYP->DOUT;
}
CRYP_DeInit()
void CRYP_DeInit (void)
Deinitializes the CRYP peripheral registers to their default reset values.
Parameters
None
Return values
None
Definition at line 215 of file stm32f4xx_cryp.c.
References DISABLE, ENABLE, and RCC_AHB2PeriphResetCmd().
{
  /* Enable CRYP reset state */
  RCC_AHB2PeriphResetCmd(RCC_AHB2Periph_CRYP, ENABLE);
  /* Release CRYP from reset state */
  RCC_AHB2PeriphResetCmd(RCC_AHB2Periph_CRYP, DISABLE);
}
CRYP_DES_CBC()
 ErrorStatus CRYP_DES_CBC (uint8_t Mode, uint8_t Key[8], uint8_t InitVectors[8], uint8_t * Input, uint32_t Ilength, uint8_t * Output)
Encrypt and decrypt using DES in CBC Mode.
Parameters
Mode encryption or decryption Mode. This parameter can be one of the following values:
MODE_ENCRYPT: Encryption
MODE_DECRYPT: Decryption
Key Key used for DES algorithm.
InitVectors Initialisation Vectors used for DES algorithm.
Ilength length of the Input buffer, must be a multiple of 8.
Input pointer to the Input buffer.
Output pointer to the returned buffer.
Return values
An ErrorStatus enumeration value:
SUCCESS: Operation done
ERROR: Operation failed
Definition at line 189 of file stm32f4xx_cryp_des.c.
References CRYP_InitTypeDef::CRYP_AlgoDir, CRYP_InitTypeDef::CRYP_AlgoMode, CRYP_Cmd(), CRYP_InitTypeDef::CRYP_DataType, CRYP_FIFOFlush(), CRYP_Init(), CRYP_IVInit(), CRYP_KeyInit(), CRYP_KeyStructInit(), DISABLE, ENABLE, and SUCCESS.
{
  CRYP_InitTypeDef DES_CRYP_InitStructure;
  CRYP_KeyInitTypeDef DES_CRYP_KeyInitStructure;
  CRYP_IVInitTypeDef DES_CRYP_IVInitStructure;
  __IO uint32_t counter = 0;
  uint32_t busystatus = 0;
  ErrorStatus status = SUCCESS;
  uint32_t keyaddr = (uint32_t)Key;
  uint32_t inputaddr = (uint32_t)Input;
  uint32_t outputaddr = (uint32_t)Output;
  uint32_t ivaddr = (uint32_t)InitVectors;
  uint32_t i = 0;
  /* Crypto structures initialisation*/
  CRYP_KeyStructInit(&DES_CRYP_KeyInitStructure);
  /* Crypto Init for Encryption process */
  if(Mode == MODE_ENCRYPT) /* DES encryption */
  {
     DES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Encrypt;
  }
  else /*if(Mode == MODE_DECRYPT)*/ /* DES decryption */
  {
     DES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Decrypt;
  }
  DES_CRYP_InitStructure.CRYP_AlgoMode = CRYP_AlgoMode_DES_CBC;
  DES_CRYP_InitStructure.CRYP_DataType = CRYP_DataType_8b;
  CRYP_Init(&DES_CRYP_InitStructure);
  /* Key Initialisation */
  DES_CRYP_KeyInitStructure.CRYP_Key1Left = __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  DES_CRYP_KeyInitStructure.CRYP_Key1Right= __REV(*(uint32_t*)(keyaddr));
  CRYP_KeyInit(& DES_CRYP_KeyInitStructure);
  /* Initialization Vectors */
  DES_CRYP_IVInitStructure.CRYP_IV0Left = __REV(*(uint32_t*)(ivaddr));
  ivaddr+=4;
  DES_CRYP_IVInitStructure.CRYP_IV0Right= __REV(*(uint32_t*)(ivaddr));
  CRYP_IVInit(&DES_CRYP_IVInitStructure);
  /* Flush IN/OUT FIFO */
  CRYP_FIFOFlush();
  
  /* Enable Crypto processor */
  CRYP_Cmd(ENABLE);
  for(i=0; ((i<Ilength) && (status != ERROR)); i+=8)
  {
    /* Write the Input block in the Input FIFO */
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    /* Wait until the complete message has been processed */
    counter = 0;
    do
    {
      busystatus = CRYP_GetFlagStatus(CRYP_FLAG_BUSY);
      counter++;
    }while ((counter != DESBUSY_TIMEOUT) && (busystatus != RESET));
    if (busystatus != RESET)
   {
       status = ERROR;
    }
    else
    {
      /* Read the Output block from the Output FIFO */
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
    }
  }
  /* Disable Crypto */
  CRYP_Cmd(DISABLE);
  return status;
}
CRYP_DES_ECB()
 ErrorStatus CRYP_DES_ECB (uint8_t Mode, uint8_t Key[8], uint8_t * Input, uint32_t Ilength, uint8_t * Output)
Encrypt and decrypt using DES in ECB Mode.
Parameters
Mode encryption or decryption Mode. This parameter can be one of the following values:
MODE_ENCRYPT: Encryption
MODE_DECRYPT: Decryption
Key Key used for DES algorithm.
Ilength length of the Input buffer, must be a multiple of 8.
Input pointer to the Input buffer.
Output pointer to the returned buffer.
Return values
An ErrorStatus enumeration value:
SUCCESS: Operation done
ERROR: Operation failed
Definition at line 94 of file stm32f4xx_cryp_des.c.
References CRYP_InitTypeDef::CRYP_AlgoDir, CRYP_InitTypeDef::CRYP_AlgoMode, CRYP_Cmd(), CRYP_InitTypeDef::CRYP_DataType, CRYP_FIFOFlush(), CRYP_Init(), CRYP_KeyInit(), CRYP_KeyStructInit(), DISABLE, ENABLE, and SUCCESS.
{
  CRYP_InitTypeDef DES_CRYP_InitStructure;
  CRYP_KeyInitTypeDef DES_CRYP_KeyInitStructure;
  __IO uint32_t counter = 0;
  uint32_t busystatus = 0;
  ErrorStatus status = SUCCESS;
  uint32_t keyaddr = (uint32_t)Key;
  uint32_t inputaddr = (uint32_t)Input;
  uint32_t outputaddr = (uint32_t)Output;
  uint32_t i = 0;
  /* Crypto structures initialisation*/
  CRYP_KeyStructInit(&DES_CRYP_KeyInitStructure);
  /* Crypto Init for Encryption process */
  if(Mode == MODE_ENCRYPT) /* DES encryption */
  {
     DES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Encrypt;
  }
  else/* if(Mode == MODE_DECRYPT)*/ /* DES decryption */
  {
     DES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Decrypt;
  }
  DES_CRYP_InitStructure.CRYP_AlgoMode = CRYP_AlgoMode_DES_ECB;
  DES_CRYP_InitStructure.CRYP_DataType = CRYP_DataType_8b;
  CRYP_Init(&DES_CRYP_InitStructure);
  /* Key Initialisation */
  DES_CRYP_KeyInitStructure.CRYP_Key1Left = __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  DES_CRYP_KeyInitStructure.CRYP_Key1Right= __REV(*(uint32_t*)(keyaddr));
  CRYP_KeyInit(& DES_CRYP_KeyInitStructure);
  /* Flush IN/OUT FIFO */
  CRYP_FIFOFlush();
  /* Enable Crypto processor */
  CRYP_Cmd(ENABLE);
  for(i=0; ((i<Ilength) && (status != ERROR)); i+=8)
  {
    /* Write the Input block in the Input FIFO */
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
/* Wait until the complete message has been processed */
    counter = 0;
    do
    {
      busystatus = CRYP_GetFlagStatus(CRYP_FLAG_BUSY);
      counter++;
    }while ((counter != DESBUSY_TIMEOUT) && (busystatus != RESET));
    if (busystatus != RESET)
   {
       status = ERROR;
    }
    else
    {
      /* Read the Output block from the Output FIFO */
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
    }
  }
  /* Disable Crypto */
  CRYP_Cmd(DISABLE);
  return status;
}
CRYP_DMACmd()
void CRYP_DMACmd (uint8_t CRYP_DMAReq, FunctionalState NewState)
Enables or disables the CRYP DMA interface.
Parameters
CRYP_DMAReq specifies the CRYP DMA transfer request to be enabled or disabled. This parameter can be any combination of the following values:
CRYP_DMAReq_DataOUT: DMA for outgoing(Tx) data transfer
CRYP_DMAReq_DataIN: DMA for incoming(Rx) data transfer
NewState new state of the selected CRYP DMA transfer request. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 612 of file stm32f4xx_cryp.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_CRYP_DMAREQ(CRYP_DMAReq));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the selected CRYP DMA request */
    CRYP->DMACR |= CRYP_DMAReq;
  }
  else
  {
    /* Disable the selected CRYP DMA request */
    CRYP->DMACR &= (uint8_t)~CRYP_DMAReq;
  }
}
CRYP_FIFOFlush()
void CRYP_FIFOFlush (void)
Flushes the IN and OUT FIFOs (that is read and write pointers of the FIFOs are reset)
Note
The FIFOs must be flushed only when BUSY flag is reset.
Parameters
None
Return values
None
Definition at line 358 of file stm32f4xx_cryp.c.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().
{
  /* Reset the read and write pointers of the FIFOs */
  CRYP->CR |= CRYP_CR_FFLUSH;
}
CRYP_GetFlagStatus()
 FlagStatus CRYP_GetFlagStatus (uint8_t CRYP_FLAG)
Checks whether the specified CRYP flag is set or not.
Parameters
CRYP_FLAG specifies the CRYP flag to check. This parameter can be one of the following values:
CRYP_FLAG_IFEM: Input FIFO Empty flag.
CRYP_FLAG_IFNF: Input FIFO Not Full flag.
CRYP_FLAG_OFNE: Output FIFO Not Empty flag.
CRYP_FLAG_OFFU: Output FIFO Full flag.
CRYP_FLAG_BUSY: Busy flag.
CRYP_FLAG_OUTRIS: Output FIFO raw interrupt flag.
CRYP_FLAG_INRIS: Input FIFO raw interrupt flag.
Return values
The new state of CRYP_FLAG (SET or RESET).
Definition at line 799 of file stm32f4xx_cryp.c.
References RESET, and SET.
{
  FlagStatus bitstatus = RESET;
  uint32_t tempreg = 0;
  /* Check the parameters */
  assert_param(IS_CRYP_GET_FLAG(CRYP_FLAG));
  /* check if the FLAG is in RISR register */
  if ((CRYP_FLAG & FLAG_MASK) != 0x00)
  {
    tempreg = CRYP->RISR;
  }
  else /* The FLAG is in SR register */
  {
    tempreg = CRYP->SR;
  }
  /* Check the status of the specified CRYP flag */
  if ((tempreg & CRYP_FLAG) != (uint8_t)RESET)
  {
    /* CRYP_FLAG is set */
    bitstatus = SET;
  }
  else
  {
    /* CRYP_FLAG is reset */
    bitstatus = RESET;
  }
  /* Return the CRYP_FLAG status */
  return bitstatus;
}
CRYP_GetITStatus()
 ITStatus CRYP_GetITStatus (uint8_t CRYP_IT)
Checks whether the specified CRYP interrupt has occurred or not.
Note
This function checks the status of the masked interrupt (i.e the interrupt should be previously enabled).
Parameters
CRYP_IT specifies the CRYP (masked) interrupt source to check. This parameter can be one of the following values:
CRYP_IT_INI: Input FIFO interrupt
CRYP_IT_OUTI: Output FIFO interrupt
Return values
The new state of CRYP_IT (SET or RESET).
Definition at line 765 of file stm32f4xx_cryp.c.
References RESET.
{
  ITStatus bitstatus = RESET;
  /* Check the parameters */
  assert_param(IS_CRYP_GET_IT(CRYP_IT));
  /* Check the status of the specified CRYP interrupt */
  if ((CRYP->MISR & CRYP_IT) != (uint8_t)RESET)
  {
    /* CRYP_IT is set */
    bitstatus = SET;
  }
  else
  {
    /* CRYP_IT is reset */
    bitstatus = RESET;
  }
  /* Return the CRYP_IT status */
  return bitstatus;
}
CRYP_Init()
void CRYP_Init (CRYP_InitTypeDef * CRYP_InitStruct)
Initializes the CRYP peripheral according to the specified parameters in the CRYP_InitStruct.
Parameters
CRYP_InitStruct pointer to a CRYP_InitTypeDef structure that contains the configuration information for the CRYP peripheral.
Return values
None
Definition at line 231 of file stm32f4xx_cryp.c.
References CRYP_InitTypeDef::CRYP_AlgoMode.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().
{
  /* Check the parameters */
  assert_param(IS_CRYP_ALGOMODE(CRYP_InitStruct->CRYP_AlgoMode));
  assert_param(IS_CRYP_DATATYPE(CRYP_InitStruct->CRYP_DataType));
  assert_param(IS_CRYP_ALGODIR(CRYP_InitStruct->CRYP_AlgoDir));
  /* Select Algorithm mode*/
  CRYP->CR &= ~CRYP_CR_ALGOMODE;
  CRYP->CR |= CRYP_InitStruct->CRYP_AlgoMode;
  /* Select dataType */
  CRYP->CR &= ~CRYP_CR_DATATYPE;
  CRYP->CR |= CRYP_InitStruct->CRYP_DataType;
  /* select Key size (used only with AES algorithm) */
  if ((CRYP_InitStruct->CRYP_AlgoMode == CRYP_AlgoMode_AES_ECB) ||
      (CRYP_InitStruct->CRYP_AlgoMode == CRYP_AlgoMode_AES_CBC) ||
      (CRYP_InitStruct->CRYP_AlgoMode == CRYP_AlgoMode_AES_CTR) ||
      (CRYP_InitStruct->CRYP_AlgoMode == CRYP_AlgoMode_AES_Key))
  {
    assert_param(IS_CRYP_KEYSIZE(CRYP_InitStruct->CRYP_KeySize));
    CRYP->CR &= ~CRYP_CR_KEYSIZE;
    CRYP->CR |= CRYP_InitStruct->CRYP_KeySize; /* Key size and value must be
                                                  configured once the key has
                                                  been prepared */
  }
  /* Select data Direction */
  CRYP->CR &= ~CRYP_CR_ALGODIR;
  CRYP->CR |= CRYP_InitStruct->CRYP_AlgoDir;
}
CRYP_ITConfig()
void CRYP_ITConfig (uint8_t CRYP_IT, FunctionalState NewState)
Enables or disables the specified CRYP interrupts.
Parameters
CRYP_IT specifies the CRYP interrupt source to be enabled or disabled. This parameter can be any combination of the following values:
CRYP_IT_INI: Input FIFO interrupt
CRYP_IT_OUTI: Output FIFO interrupt
NewState new state of the specified CRYP interrupt. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 737 of file stm32f4xx_cryp.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_CRYP_CONFIG_IT(CRYP_IT));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the selected CRYP interrupt */
    CRYP->IMSCR |= CRYP_IT;
  }
  else
  {
    /* Disable the selected CRYP interrupt */
    CRYP->IMSCR &= (uint8_t)~CRYP_IT;
  }
}
CRYP_IVInit()
void CRYP_IVInit (CRYP_IVInitTypeDef * CRYP_IVInitStruct)
Initializes the CRYP Initialization Vectors(IV) according to the specified parameters in the CRYP_IVInitStruct.
Parameters
CRYP_IVInitStruct pointer to a CRYP_IVInitTypeDef structure that contains the configuration information for the CRYP Initialization Vectors(IV).
Return values
None
Definition at line 329 of file stm32f4xx_cryp.c.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_DES_CBC(), and CRYP_TDES_CBC().
{
  CRYP->IV0LR = CRYP_IVInitStruct->CRYP_IV0Left;
  CRYP->IV0RR = CRYP_IVInitStruct->CRYP_IV0Right;
  CRYP->IV1LR = CRYP_IVInitStruct->CRYP_IV1Left;
  CRYP->IV1RR = CRYP_IVInitStruct->CRYP_IV1Right;
}
CRYP_IVStructInit()
void CRYP_IVStructInit (CRYP_IVInitTypeDef * CRYP_IVInitStruct)
Fills each CRYP_IVInitStruct member with its default value.
Parameters
CRYP_IVInitStruct pointer to a CRYP_IVInitTypeDef Initialization Vectors(IV) structure which will be initialized.
Return values
None
Definition at line 343 of file stm32f4xx_cryp.c.
References CRYP_IVInitTypeDef::CRYP_IV0Left, CRYP_IVInitTypeDef::CRYP_IV0Right, CRYP_IVInitTypeDef::CRYP_IV1Left, and CRYP_IVInitTypeDef::CRYP_IV1Right.
{
  CRYP_IVInitStruct->CRYP_IV0Left = 0;
  CRYP_IVInitStruct->CRYP_IV0Right = 0;
  CRYP_IVInitStruct->CRYP_IV1Left = 0;
  CRYP_IVInitStruct->CRYP_IV1Right = 0;
}
CRYP_KeyInit()
void CRYP_KeyInit (CRYP_KeyInitTypeDef * CRYP_KeyInitStruct)
Initializes the CRYP Keys according to the specified parameters in the CRYP_KeyInitStruct.
Parameters
CRYP_KeyInitStruct pointer to a CRYP_KeyInitTypeDef structure that contains the configuration information for the CRYP Keys.
Return values
None
Definition at line 292 of file stm32f4xx_cryp.c.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().
{
  /* Key Initialisation */
  CRYP->K0LR = CRYP_KeyInitStruct->CRYP_Key0Left;
  CRYP->K0RR = CRYP_KeyInitStruct->CRYP_Key0Right;
  CRYP->K1LR = CRYP_KeyInitStruct->CRYP_Key1Left;
  CRYP->K1RR = CRYP_KeyInitStruct->CRYP_Key1Right;
  CRYP->K2LR = CRYP_KeyInitStruct->CRYP_Key2Left;
  CRYP->K2RR = CRYP_KeyInitStruct->CRYP_Key2Right;
  CRYP->K3LR = CRYP_KeyInitStruct->CRYP_Key3Left;
  CRYP->K3RR = CRYP_KeyInitStruct->CRYP_Key3Right;
}
CRYP_KeyStructInit()
void CRYP_KeyStructInit (CRYP_KeyInitTypeDef * CRYP_KeyInitStruct)
Fills each CRYP_KeyInitStruct member with its default value.
Parameters
CRYP_KeyInitStruct pointer to a CRYP_KeyInitTypeDef structure which will be initialized.
Return values
None
Definition at line 311 of file stm32f4xx_cryp.c.
References CRYP_KeyInitTypeDef::CRYP_Key0Left, CRYP_KeyInitTypeDef::CRYP_Key0Right, CRYP_KeyInitTypeDef::CRYP_Key1Left, CRYP_KeyInitTypeDef::CRYP_Key1Right, CRYP_KeyInitTypeDef::CRYP_Key2Left, CRYP_KeyInitTypeDef::CRYP_Key2Right, CRYP_KeyInitTypeDef::CRYP_Key3Left, and CRYP_KeyInitTypeDef::CRYP_Key3Right.
Referenced by CRYP_AES_CBC(), CRYP_AES_CTR(), CRYP_AES_ECB(), CRYP_DES_CBC(), CRYP_DES_ECB(), CRYP_TDES_CBC(), and CRYP_TDES_ECB().
{
  CRYP_KeyInitStruct->CRYP_Key0Left = 0;
  CRYP_KeyInitStruct->CRYP_Key0Right = 0;
  CRYP_KeyInitStruct->CRYP_Key1Left = 0;
  CRYP_KeyInitStruct->CRYP_Key1Right = 0;
  CRYP_KeyInitStruct->CRYP_Key2Left = 0;
  CRYP_KeyInitStruct->CRYP_Key2Right = 0;
  CRYP_KeyInitStruct->CRYP_Key3Left = 0;
  CRYP_KeyInitStruct->CRYP_Key3Right = 0;
}
CRYP_RestoreContext()
void CRYP_RestoreContext (CRYP_Context * CRYP_ContextRestore)
Restores the CRYP peripheral Context.
Note
Since teh DMA transfer is stopped in CRYP_SaveContext() function, after restoring the context, you have to enable the DMA again (if the DMA was previously used).
Parameters
CRYP_ContextRestore pointer to a CRYP_Context structure that contains the repository for saved context.
Note
The data that were saved during context saving must be rewrited into the IN FIFO.
Return values
None
Definition at line 551 of file stm32f4xx_cryp.c.
{
  /* Configure the processor with the saved configuration */
  CRYP->CR = CRYP_ContextRestore->CR_bits9to2;
  /* restore The key value */
  CRYP->K0LR = CRYP_ContextRestore->CRYP_K0LR;
  CRYP->K0RR = CRYP_ContextRestore->CRYP_K0RR;
  CRYP->K1LR = CRYP_ContextRestore->CRYP_K1LR;
  CRYP->K1RR = CRYP_ContextRestore->CRYP_K1RR;
  CRYP->K2LR = CRYP_ContextRestore->CRYP_K2LR;
  CRYP->K2RR = CRYP_ContextRestore->CRYP_K2RR;
  CRYP->K3LR = CRYP_ContextRestore->CRYP_K3LR;
  CRYP->K3RR = CRYP_ContextRestore->CRYP_K3RR;
  /* and the initialization vectors. */
  CRYP->IV0LR = CRYP_ContextRestore->CRYP_IV0LR;
  CRYP->IV0RR = CRYP_ContextRestore->CRYP_IV0RR;
  CRYP->IV1LR = CRYP_ContextRestore->CRYP_IV1LR;
  CRYP->IV1RR = CRYP_ContextRestore->CRYP_IV1RR;
  /* Enable the cryptographic processor */
  CRYP->CR |= CRYP_CR_CRYPEN;
}
CRYP_SaveContext()
 ErrorStatus CRYP_SaveContext (CRYP_Context * CRYP_ContextSave, CRYP_KeyInitTypeDef * CRYP_KeyInitStruct)
Saves the CRYP peripheral Context.
Note
This function stops DMA transfer before to save the context. After restoring the context, you have to enable the DMA again (if the DMA was previously used).
Parameters
CRYP_ContextSave pointer to a CRYP_Context structure that contains the repository for current context.
CRYP_KeyInitStruct pointer to a CRYP_KeyInitTypeDef structure that contains the configuration information for the CRYP Keys.
Return values
None
Definition at line 466 of file stm32f4xx_cryp.c.
References ERROR.
{
  __IO uint32_t timeout = 0;
  uint32_t ckeckmask = 0, bitstatus;
  ErrorStatus status = ERROR;
  /* Stop DMA transfers on the IN FIFO by clearing the DIEN bit in the CRYP_DMACR */
  CRYP->DMACR &= ~(uint32_t)CRYP_DMACR_DIEN;
    
  /* Wait until both the IN and OUT FIFOs are empty
    (IFEM=1 and OFNE=0 in the CRYP_SR register) and the
     BUSY bit is cleared. */
  if ((CRYP->CR & (uint32_t)(CRYP_CR_ALGOMODE_TDES_ECB |
      CRYP_CR_ALGOMODE_TDES_CBC)) != (uint32_t)0)/* TDES */
  {
    ckeckmask = CRYP_SR_IFEM | CRYP_SR_BUSY ;
  }
  else /* AES or DES */
  {
    ckeckmask = CRYP_SR_IFEM | CRYP_SR_BUSY | CRYP_SR_OFNE;
  }
   
  do
  {
    bitstatus = CRYP->SR & ckeckmask;
    timeout++;
  }
  while ((timeout != MAX_TIMEOUT) && (bitstatus != CRYP_SR_IFEM));
     
  if ((CRYP->SR & ckeckmask) != CRYP_SR_IFEM)
  {
    status = ERROR;
  }
  else
  {
    /* Stop DMA transfers on the OUT FIFO by
       - writing the DOEN bit to 0 in the CRYP_DMACR register
       - and clear the CRYPEN bit. */
    CRYP->DMACR &= ~(uint32_t)CRYP_DMACR_DOEN;
    CRYP->CR &= ~(uint32_t)CRYP_CR_CRYPEN;
    /* Save the current configuration (bits [9:2] in the CRYP_CR register) */
    CRYP_ContextSave->CR_bits9to2 = CRYP->CR & (CRYP_CR_KEYSIZE |
                                                 CRYP_CR_DATATYPE |
                                                 CRYP_CR_ALGOMODE |
                                                 CRYP_CR_ALGODIR);
    /* and, if not in ECB mode, the initialization vectors. */
    CRYP_ContextSave->CRYP_IV0LR = CRYP->IV0LR;
    CRYP_ContextSave->CRYP_IV0RR = CRYP->IV0RR;
    CRYP_ContextSave->CRYP_IV1LR = CRYP->IV1LR;
    CRYP_ContextSave->CRYP_IV1RR = CRYP->IV1RR;
    /* save The key value */
    CRYP_ContextSave->CRYP_K0LR = CRYP_KeyInitStruct->CRYP_Key0Left;
    CRYP_ContextSave->CRYP_K0RR = CRYP_KeyInitStruct->CRYP_Key0Right;
    CRYP_ContextSave->CRYP_K1LR = CRYP_KeyInitStruct->CRYP_Key1Left;
    CRYP_ContextSave->CRYP_K1RR = CRYP_KeyInitStruct->CRYP_Key1Right;
    CRYP_ContextSave->CRYP_K2LR = CRYP_KeyInitStruct->CRYP_Key2Left;
    CRYP_ContextSave->CRYP_K2RR = CRYP_KeyInitStruct->CRYP_Key2Right;
    CRYP_ContextSave->CRYP_K3LR = CRYP_KeyInitStruct->CRYP_Key3Left;
    CRYP_ContextSave->CRYP_K3RR = CRYP_KeyInitStruct->CRYP_Key3Right;
   /* When needed, save the DMA status (pointers for IN and OUT messages,
      number of remaining bytes, etc.) */
     
    status = SUCCESS;
  }
   return status;
}
CRYP_StructInit()
void CRYP_StructInit (CRYP_InitTypeDef * CRYP_InitStruct)
Fills each CRYP_InitStruct member with its default value.
Parameters
CRYP_InitStruct pointer to a CRYP_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 270 of file stm32f4xx_cryp.c.
References CRYP_InitTypeDef::CRYP_AlgoDir, CRYP_InitTypeDef::CRYP_AlgoMode, CRYP_InitTypeDef::CRYP_DataType, and CRYP_InitTypeDef::CRYP_KeySize.
{
  /* Initialize the CRYP_AlgoDir member */
  CRYP_InitStruct->CRYP_AlgoDir = CRYP_AlgoDir_Encrypt;
  /* initialize the CRYP_AlgoMode member */
  CRYP_InitStruct->CRYP_AlgoMode = CRYP_AlgoMode_TDES_ECB;
  /* initialize the CRYP_DataType member */
  CRYP_InitStruct->CRYP_DataType = CRYP_DataType_32b;
  
  /* Initialize the CRYP_KeySize member */
  CRYP_InitStruct->CRYP_KeySize = CRYP_KeySize_128b;
}
CRYP_TDES_CBC()
 ErrorStatus CRYP_TDES_CBC (uint8_t Mode, uint8_t Key[24], uint8_t InitVectors[8], uint8_t * Input, uint32_t Ilength, uint8_t * Output)
Encrypt and decrypt using TDES in CBC Mode.
Parameters
Mode encryption or decryption Mode. This parameter can be one of the following values:
MODE_ENCRYPT: Encryption
MODE_DECRYPT: Decryption
Key Key used for TDES algorithm.
InitVectors Initialisation Vectors used for TDES algorithm.
Input pointer to the Input buffer.
Ilength length of the Input buffer, must be a multiple of 8.
Output pointer to the returned buffer.
Return values
An ErrorStatus enumeration value:
SUCCESS: Operation done
ERROR: Operation failed
Definition at line 198 of file stm32f4xx_cryp_tdes.c.
References CRYP_InitTypeDef::CRYP_AlgoDir, CRYP_InitTypeDef::CRYP_AlgoMode, CRYP_Cmd(), CRYP_InitTypeDef::CRYP_DataType, CRYP_FIFOFlush(), CRYP_Init(), CRYP_IVInit(), CRYP_KeyInit(), CRYP_KeyStructInit(), DISABLE, ENABLE, and SUCCESS.
{
  CRYP_InitTypeDef TDES_CRYP_InitStructure;
  CRYP_KeyInitTypeDef TDES_CRYP_KeyInitStructure;
  CRYP_IVInitTypeDef TDES_CRYP_IVInitStructure;
  __IO uint32_t counter = 0;
  uint32_t busystatus = 0;
  ErrorStatus status = SUCCESS;
  uint32_t keyaddr = (uint32_t)Key;
  uint32_t inputaddr = (uint32_t)Input;
  uint32_t outputaddr = (uint32_t)Output;
  uint32_t ivaddr = (uint32_t)InitVectors;
  uint32_t i = 0;
  /* Crypto structures initialisation*/
  CRYP_KeyStructInit(&TDES_CRYP_KeyInitStructure);
  /* Crypto Init for Encryption process */
  if(Mode == MODE_ENCRYPT) /* TDES encryption */
  {
    TDES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Encrypt;
  }
  else
  {
    TDES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Decrypt;
  }
  TDES_CRYP_InitStructure.CRYP_AlgoMode = CRYP_AlgoMode_TDES_CBC;
  TDES_CRYP_InitStructure.CRYP_DataType = CRYP_DataType_8b;
  CRYP_Init(&TDES_CRYP_InitStructure);
  /* Key Initialisation */
  TDES_CRYP_KeyInitStructure.CRYP_Key1Left = __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  TDES_CRYP_KeyInitStructure.CRYP_Key1Right= __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  TDES_CRYP_KeyInitStructure.CRYP_Key2Left = __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  TDES_CRYP_KeyInitStructure.CRYP_Key2Right= __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  TDES_CRYP_KeyInitStructure.CRYP_Key3Left = __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  TDES_CRYP_KeyInitStructure.CRYP_Key3Right= __REV(*(uint32_t*)(keyaddr));
  CRYP_KeyInit(& TDES_CRYP_KeyInitStructure);
  /* Initialization Vectors */
  TDES_CRYP_IVInitStructure.CRYP_IV0Left = __REV(*(uint32_t*)(ivaddr));
  ivaddr+=4;
  TDES_CRYP_IVInitStructure.CRYP_IV0Right= __REV(*(uint32_t*)(ivaddr));
  CRYP_IVInit(&TDES_CRYP_IVInitStructure);
  /* Flush IN/OUT FIFO */
  CRYP_FIFOFlush();
  /* Enable Crypto processor */
  CRYP_Cmd(ENABLE);
  for(i=0; ((i<Ilength) && (status != ERROR)); i+=8)
  {
    /* Write the Input block in the Input FIFO */
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    /* Wait until the complete message has been processed */
    counter = 0;
    do
    {
      busystatus = CRYP_GetFlagStatus(CRYP_FLAG_BUSY);
      counter++;
    }while ((counter != TDESBUSY_TIMEOUT) && (busystatus != RESET));
    if (busystatus != RESET)
   {
       status = ERROR;
    }
    else
    {
      /* Read the Output block from the Output FIFO */
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
    }
  }
  /* Disable Crypto */
  CRYP_Cmd(DISABLE);
  return status;
}
CRYP_TDES_ECB()
 ErrorStatus CRYP_TDES_ECB (uint8_t Mode, uint8_t Key[24], uint8_t * Input, uint32_t Ilength, uint8_t * Output)
Encrypt and decrypt using TDES in ECB Mode.
Parameters
Mode encryption or decryption Mode. This parameter can be one of the following values:
MODE_ENCRYPT: Encryption
MODE_DECRYPT: Decryption
Key Key used for TDES algorithm.
Ilength length of the Input buffer, must be a multiple of 8.
Input pointer to the Input buffer.
Output pointer to the returned buffer.
Return values
An ErrorStatus enumeration value:
SUCCESS: Operation done
ERROR: Operation failed
Definition at line 96 of file stm32f4xx_cryp_tdes.c.
References CRYP_InitTypeDef::CRYP_AlgoDir, CRYP_InitTypeDef::CRYP_AlgoMode, CRYP_Cmd(), CRYP_InitTypeDef::CRYP_DataType, CRYP_FIFOFlush(), CRYP_Init(), CRYP_KeyInit(), CRYP_KeyStructInit(), DISABLE, ENABLE, and SUCCESS.
{
  CRYP_InitTypeDef TDES_CRYP_InitStructure;
  CRYP_KeyInitTypeDef TDES_CRYP_KeyInitStructure;
  __IO uint32_t counter = 0;
  uint32_t busystatus = 0;
  ErrorStatus status = SUCCESS;
  uint32_t keyaddr = (uint32_t)Key;
  uint32_t inputaddr = (uint32_t)Input;
  uint32_t outputaddr = (uint32_t)Output;
  uint32_t i = 0;
  /* Crypto structures initialisation*/
  CRYP_KeyStructInit(&TDES_CRYP_KeyInitStructure);
  /* Crypto Init for Encryption process */
  if(Mode == MODE_ENCRYPT) /* TDES encryption */
  {
     TDES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Encrypt;
  }
  else /*if(Mode == MODE_DECRYPT)*/ /* TDES decryption */
  {
     TDES_CRYP_InitStructure.CRYP_AlgoDir = CRYP_AlgoDir_Decrypt;
  }
  TDES_CRYP_InitStructure.CRYP_AlgoMode = CRYP_AlgoMode_TDES_ECB;
  TDES_CRYP_InitStructure.CRYP_DataType = CRYP_DataType_8b;
  CRYP_Init(&TDES_CRYP_InitStructure);
  /* Key Initialisation */
  TDES_CRYP_KeyInitStructure.CRYP_Key1Left = __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  TDES_CRYP_KeyInitStructure.CRYP_Key1Right= __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  TDES_CRYP_KeyInitStructure.CRYP_Key2Left = __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  TDES_CRYP_KeyInitStructure.CRYP_Key2Right= __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  TDES_CRYP_KeyInitStructure.CRYP_Key3Left = __REV(*(uint32_t*)(keyaddr));
  keyaddr+=4;
  TDES_CRYP_KeyInitStructure.CRYP_Key3Right= __REV(*(uint32_t*)(keyaddr));
  CRYP_KeyInit(& TDES_CRYP_KeyInitStructure);
  /* Flush IN/OUT FIFO */
  CRYP_FIFOFlush();
  /* Enable Crypto processor */
  CRYP_Cmd(ENABLE);
  for(i=0; ((i<Ilength) && (status != ERROR)); i+=8)
  {
    /* Write the Input block in the Input FIFO */
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    CRYP_DataIn(*(uint32_t*)(inputaddr));
    inputaddr+=4;
    /* Wait until the complete message has been processed */
    counter = 0;
    do
    {
      busystatus = CRYP_GetFlagStatus(CRYP_FLAG_BUSY);
      counter++;
    }while ((counter != TDESBUSY_TIMEOUT) && (busystatus != RESET));
    if (busystatus != RESET)
    {
       status = ERROR;
    }
    else
    {
      /* Read the Output block from the Output FIFO */
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
      *(uint32_t*)(outputaddr) = CRYP_DataOut();
      outputaddr+=4;
    }
  }
  /* Disable Crypto */
  CRYP_Cmd(DISABLE);
  return status;
}