Digital Calibration configuration functions
Coarse Calibration configuration functions.
Functions
 ErrorStatus RTC_CoarseCalibConfig (uint32_t RTC_CalibSign, uint32_t Value)
Configures the Coarse calibration parameters.
 ErrorStatus RTC_CoarseCalibCmd (FunctionalState NewState)
Enables or disables the Coarse calibration process.
void RTC_CalibOutputCmd (FunctionalState NewState)
Enables or disables the RTC clock to be output through the relative pin.
void RTC_CalibOutputConfig (uint32_t RTC_CalibOutput)
Configure the Calibration Pinout (RTC_CALIB) Selection (1Hz or 512Hz).
 ErrorStatus RTC_SmoothCalibConfig (uint32_t RTC_SmoothCalibPeriod, uint32_t RTC_SmoothCalibPlusPulses, uint32_t RTC_SmouthCalibMinusPulsesValue)
Configures the Smooth Calibration Settings.
Detailed Description
Coarse Calibration configuration functions.
 ===============================================================================
                  Digital Calibration configuration functions
 ===============================================================================  
Function Documentation
RTC_CalibOutputCmd()
void RTC_CalibOutputCmd (FunctionalState NewState)
Enables or disables the RTC clock to be output through the relative pin.
Parameters
NewState new state of the digital calibration Output. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1811 of file stm32f4xx_rtc.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  if (NewState != DISABLE)
  {
    /* Enable the RTC clock output */
    RTC->CR |= (uint32_t)RTC_CR_COE;
  }
  else
  {
    /* Disable the RTC clock output */
    RTC->CR &= (uint32_t)~RTC_CR_COE;
  }
  
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_CalibOutputConfig()
void RTC_CalibOutputConfig (uint32_t RTC_CalibOutput)
Configure the Calibration Pinout (RTC_CALIB) Selection (1Hz or 512Hz).
Parameters
RTC_CalibOutput : Select the Calibration output Selection . This parameter can be one of the following values:
RTC_CalibOutput_512Hz: A signal has a regular waveform at 512Hz.
RTC_CalibOutput_1Hz : A signal has a regular waveform at 1Hz.
Return values
None
Definition at line 1843 of file stm32f4xx_rtc.c.
{
  /* Check the parameters */
  assert_param(IS_RTC_CALIB_OUTPUT(RTC_CalibOutput));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  /*clear flags before config*/
  RTC->CR &= (uint32_t)~(RTC_CR_COSEL);
  /* Configure the RTC_CR register */
  RTC->CR |= (uint32_t)RTC_CalibOutput;
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
}
RTC_CoarseCalibCmd()
 ErrorStatus RTC_CoarseCalibCmd (FunctionalState NewState)
Enables or disables the Coarse calibration process.
Parameters
NewState new state of the Coarse calibration. This parameter can be: ENABLE or DISABLE.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC Coarse calibration are enabled/disabled
ERROR: RTC Coarse calibration are not enabled/disabled
Definition at line 1765 of file stm32f4xx_rtc.c.
References DISABLE, ERROR, RTC_EnterInitMode(), RTC_ExitInitMode(), and SUCCESS.
{
  ErrorStatus status = ERROR;
  
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    if (NewState != DISABLE)
    {
      /* Enable the Coarse Calibration */
      RTC->CR |= (uint32_t)RTC_CR_DCE;
    }
    else
    {
      /* Disable the Coarse Calibration */
      RTC->CR &= (uint32_t)~RTC_CR_DCE;
    }
    /* Exit Initialization mode */
    RTC_ExitInitMode();
    
    status = SUCCESS;
  }
  
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_CoarseCalibConfig()
 ErrorStatus RTC_CoarseCalibConfig (uint32_t RTC_CalibSign, uint32_t Value)
Configures the Coarse calibration parameters.
Parameters
RTC_CalibSign specifies the sign of the coarse calibration value. This parameter can be one of the following values:
RTC_CalibSign_Positive: The value sign is positive
RTC_CalibSign_Negative: The value sign is negative
Value value of coarse calibration expressed in ppm (coded on 5 bits).
Note
This Calibration value should be between 0 and 63 when using negative sign with a 2-ppm step.
This Calibration value should be between 0 and 126 when using positive sign with a 4-ppm step.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC Coarse calibration are initialized
ERROR: RTC Coarse calibration are not initialized
Definition at line 1724 of file stm32f4xx_rtc.c.
References ERROR, RTC_EnterInitMode(), RTC_ExitInitMode(), and SUCCESS.
{
  ErrorStatus status = ERROR;
   
  /* Check the parameters */
  assert_param(IS_RTC_CALIB_SIGN(RTC_CalibSign));
  assert_param(IS_RTC_CALIB_VALUE(Value));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  /* Set Initialization mode */
  if (RTC_EnterInitMode() == ERROR)
  {
    status = ERROR;
  }
  else
  {
    /* Set the coarse calibration value */
    RTC->CALIBR = (uint32_t)(RTC_CalibSign | Value);
    /* Exit Initialization mode */
    RTC_ExitInitMode();
    
    status = SUCCESS;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return status;
}
RTC_SmoothCalibConfig()
 ErrorStatus RTC_SmoothCalibConfig (uint32_t RTC_SmoothCalibPeriod, uint32_t RTC_SmoothCalibPlusPulses, uint32_t RTC_SmouthCalibMinusPulsesValue)
Configures the Smooth Calibration Settings.
Parameters
RTC_SmoothCalibPeriod : Select the Smooth Calibration Period. This parameter can be can be one of the following values:
RTC_SmoothCalibPeriod_32sec : The smooth calibration periode is 32s.
RTC_SmoothCalibPeriod_16sec : The smooth calibration periode is 16s.
RTC_SmoothCalibPeriod_8sec : The smooth calibartion periode is 8s.
RTC_SmoothCalibPlusPulses : Select to Set or reset the CALP bit. This parameter can be one of the following values:
RTC_SmoothCalibPlusPulses_Set : Add one RTCCLK puls every 2**11 pulses.
RTC_SmoothCalibPlusPulses_Reset: No RTCCLK pulses are added.
RTC_SmouthCalibMinusPulsesValue Select the value of CALM[8:0] bits. This parameter can be one any value from 0 to 0x000001FF.
Return values
An ErrorStatus enumeration value:
SUCCESS: RTC Calib registers are configured
ERROR: RTC Calib registers are not configured
Definition at line 1879 of file stm32f4xx_rtc.c.
References ERROR.
{
  ErrorStatus status = ERROR;
  uint32_t recalpfcount = 0;
  /* Check the parameters */
  assert_param(IS_RTC_SMOOTH_CALIB_PERIOD(RTC_SmoothCalibPeriod));
  assert_param(IS_RTC_SMOOTH_CALIB_PLUS(RTC_SmoothCalibPlusPulses));
  assert_param(IS_RTC_SMOOTH_CALIB_MINUS(RTC_SmouthCalibMinusPulsesValue));
  /* Disable the write protection for RTC registers */
  RTC->WPR = 0xCA;
  RTC->WPR = 0x53;
  
  /* check if a calibration is pending*/
  if ((RTC->ISR & RTC_ISR_RECALPF) != RESET)
  {
    /* wait until the Calibration is completed*/
    while (((RTC->ISR & RTC_ISR_RECALPF) != RESET) && (recalpfcount !=
      RECALPF_TIMEOUT))
    {
      recalpfcount++;
    }
  }
  /* check if the calibration pending is completed or if there is no calibration operation at all*/
  if ((RTC->ISR & RTC_ISR_RECALPF) == RESET)
  {
    /* Configure the Smooth calibration settings */
    RTC->CALR = (uint32_t)((uint32_t)RTC_SmoothCalibPeriod | (uint32_t)RTC_SmoothCalibPlusPulses | (
      uint32_t)RTC_SmouthCalibMinusPulsesValue);
    status = SUCCESS;
  }
  else
  {
    status = ERROR;
  }
  /* Enable the write protection for RTC registers */
  RTC->WPR = 0xFF;
  
  return (ErrorStatus)(status);
}