Interrupts and flags management functions
Interrupts and flags management functions.
Functions
void FLASH_ITConfig (uint32_t FLASH_IT, FunctionalState NewState)
Enables or disables the specified FLASH interrupts.
 FlagStatus FLASH_GetFlagStatus (uint32_t FLASH_FLAG)
Checks whether the specified FLASH flag is set or not.
void FLASH_ClearFlag (uint32_t FLASH_FLAG)
Clears the FLASH's pending flags.
 FLASH_Status FLASH_GetStatus (void)
Returns the FLASH Status.
 FLASH_Status FLASH_WaitForLastOperation (void)
Waits for a FLASH operation to complete.
Detailed Description
Interrupts and flags management functions.
 ===============================================================================
                  Interrupts and flags management functions
 ===============================================================================  
Function Documentation
FLASH_ClearFlag()
void FLASH_ClearFlag (uint32_t FLASH_FLAG)
Clears the FLASH's pending flags.
Parameters
FLASH_FLAG specifies the FLASH flags to clear. This parameter can be any combination of the following values:
FLASH_FLAG_EOP: FLASH End of Operation flag
FLASH_FLAG_OPERR: FLASH operation Error flag
FLASH_FLAG_WRPERR: FLASH Write protected error flag
FLASH_FLAG_PGAERR: FLASH Programming Alignment error flag
FLASH_FLAG_PGPERR: FLASH Programming Parallelism error flag
FLASH_FLAG_PGSERR: FLASH Programming Sequence error flag
Return values
None
Definition at line 964 of file stm32f4xx_flash.c.
{
  /* Check the parameters */
  assert_param(IS_FLASH_CLEAR_FLAG(FLASH_FLAG));
  
  /* Clear the flags */
  FLASH->SR = FLASH_FLAG;
}
FLASH_GetFlagStatus()
 FlagStatus FLASH_GetFlagStatus (uint32_t FLASH_FLAG)
Checks whether the specified FLASH flag is set or not.
Parameters
FLASH_FLAG specifies the FLASH flag to check. This parameter can be one of the following values:
FLASH_FLAG_EOP: FLASH End of Operation flag
FLASH_FLAG_OPERR: FLASH operation Error flag
FLASH_FLAG_WRPERR: FLASH Write protected error flag
FLASH_FLAG_PGAERR: FLASH Programming Alignment error flag
FLASH_FLAG_PGPERR: FLASH Programming Parallelism error flag
FLASH_FLAG_PGSERR: FLASH Programming Sequence error flag
FLASH_FLAG_BSY: FLASH Busy flag
Return values
The new state of FLASH_FLAG (SET or RESET).
Definition at line 934 of file stm32f4xx_flash.c.
References RESET.
{
  FlagStatus bitstatus = RESET;
  /* Check the parameters */
  assert_param(IS_FLASH_GET_FLAG(FLASH_FLAG));
  if((FLASH->SR & FLASH_FLAG) != (uint32_t)RESET)
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  /* Return the new state of FLASH_FLAG (SET or RESET) */
  return bitstatus;
}
FLASH_GetStatus()
 FLASH_Status FLASH_GetStatus (void)
Returns the FLASH Status.
Parameters
None
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 979 of file stm32f4xx_flash.c.
References FLASH_COMPLETE.
{
  FLASH_Status flashstatus = FLASH_COMPLETE;
  
  if((FLASH->SR & FLASH_FLAG_BSY) == FLASH_FLAG_BSY)
  {
    flashstatus = FLASH_BUSY;
  }
  else
  {
    if((FLASH->SR & FLASH_FLAG_WRPERR) != (uint32_t)0x00)
    {
      flashstatus = FLASH_ERROR_WRP;
    }
    else
    {
      if((FLASH->SR & (uint32_t)0xEF) != (uint32_t)0x00)
      {
        flashstatus = FLASH_ERROR_PROGRAM;
      }
      else
      {
        if((FLASH->SR & FLASH_FLAG_OPERR) != (uint32_t)0x00)
        {
          flashstatus = FLASH_ERROR_OPERATION;
        }
        else
        {
          flashstatus = FLASH_COMPLETE;
        }
      }
    }
  }
  /* Return the FLASH Status */
  return flashstatus;
}
FLASH_ITConfig()
void FLASH_ITConfig (uint32_t FLASH_IT, FunctionalState NewState)
Enables or disables the specified FLASH interrupts.
Parameters
FLASH_IT specifies the FLASH interrupt sources to be enabled or disabled. This parameter can be any combination of the following values:
FLASH_IT_ERR: FLASH Error Interrupt
FLASH_IT_EOP: FLASH end of operation Interrupt
Return values
None
Definition at line 903 of file stm32f4xx_flash.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FLASH_IT(FLASH_IT));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if(NewState != DISABLE)
  {
    /* Enable the interrupt sources */
    FLASH->CR |= FLASH_IT;
  }
  else
  {
    /* Disable the interrupt sources */
    FLASH->CR &= ~(uint32_t)FLASH_IT;
  }
}
FLASH_WaitForLastOperation()
 FLASH_Status FLASH_WaitForLastOperation (void)
Waits for a FLASH operation to complete.
Parameters
None
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 1022 of file stm32f4xx_flash.c.
Referenced by FLASH_EraseAllSectors(), FLASH_EraseSector(), FLASH_OB_Launch(), FLASH_OB_RDPConfig(), FLASH_OB_UserConfig(), FLASH_OB_WRPConfig(), FLASH_ProgramByte(), FLASH_ProgramDoubleWord(), FLASH_ProgramHalfWord(), and FLASH_ProgramWord().
{
  __IO FLASH_Status status = FLASH_COMPLETE;
   
  /* Check for the FLASH Status */
  status = FLASH_GetStatus();
  /* Wait for the FLASH operation to complete by polling on BUSY flag to be reset.
     Even if the FLASH operation fails, the BUSY flag will be reset and an error
     flag will be set */
  while(status == FLASH_BUSY)
  {
    status = FLASH_GetStatus();
  }
  /* Return the operation status */
  return status;
}