Clocks management functions
Clocks management functions.
Functions
void TIM_InternalClockConfig (TIM_TypeDef *TIMx)
Configures the TIMx internal Clock.
void TIM_ITRxExternalClockConfig (TIM_TypeDef *TIMx, uint16_t TIM_InputTriggerSource)
Configures the TIMx Internal Trigger as External Clock.
void TIM_TIxExternalClockConfig (TIM_TypeDef *TIMx, uint16_t TIM_TIxExternalCLKSource, uint16_t TIM_ICPolarity, uint16_t ICFilter)
Configures the TIMx Trigger as External Clock.
void TIM_ETRClockMode1Config (TIM_TypeDef *TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the External clock Mode1.
void TIM_ETRClockMode2Config (TIM_TypeDef *TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the External clock Mode2.
Detailed Description
Clocks management functions.
 ===============================================================================
                         Clocks management functions
 ===============================================================================  
Function Documentation
TIM_ETRClockMode1Config()
void TIM_ETRClockMode1Config (TIM_TypeDef * TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the External clock Mode1.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ExtTRGPrescaler The external Trigger Prescaler. This parameter can be one of the following values:
TIM_ExtTRGPSC_OFF: ETRP Prescaler OFF.
TIM_ExtTRGPSC_DIV2: ETRP frequency divided by 2.
TIM_ExtTRGPSC_DIV4: ETRP frequency divided by 4.
TIM_ExtTRGPSC_DIV8: ETRP frequency divided by 8.
TIM_ExtTRGPolarity The external Trigger Polarity. This parameter can be one of the following values:
TIM_ExtTRGPolarity_Inverted: active low or falling edge active.
TIM_ExtTRGPolarity_NonInverted: active high or rising edge active.
ExtTRGFilter External Trigger Filter. This parameter must be a value between 0x00 and 0x0F
Return values
None
Definition at line 2764 of file stm32f4xx_tim.c.
References TIM_ETRConfig().
{
  uint16_t tmpsmcr = 0;
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_EXT_PRESCALER(TIM_ExtTRGPrescaler));
  assert_param(IS_TIM_EXT_POLARITY(TIM_ExtTRGPolarity));
  assert_param(IS_TIM_EXT_FILTER(ExtTRGFilter));
  /* Configure the ETR Clock source */
  TIM_ETRConfig(TIMx, TIM_ExtTRGPrescaler, TIM_ExtTRGPolarity, ExtTRGFilter);
  
  /* Get the TIMx SMCR register value */
  tmpsmcr = TIMx->SMCR;
  /* Reset the SMS Bits */
  tmpsmcr &= (uint16_t)~TIM_SMCR_SMS;
  /* Select the External clock mode1 */
  tmpsmcr |= TIM_SlaveMode_External1;
  /* Select the Trigger selection : ETRF */
  tmpsmcr &= (uint16_t)~TIM_SMCR_TS;
  tmpsmcr |= TIM_TS_ETRF;
  /* Write to TIMx SMCR */
  TIMx->SMCR = tmpsmcr;
}
TIM_ETRClockMode2Config()
void TIM_ETRClockMode2Config (TIM_TypeDef * TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the External clock Mode2.
Parameters
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral.
TIM_ExtTRGPrescaler The external Trigger Prescaler. This parameter can be one of the following values:
TIM_ExtTRGPSC_OFF: ETRP Prescaler OFF.
TIM_ExtTRGPSC_DIV2: ETRP frequency divided by 2.
TIM_ExtTRGPSC_DIV4: ETRP frequency divided by 4.
TIM_ExtTRGPSC_DIV8: ETRP frequency divided by 8.
TIM_ExtTRGPolarity The external Trigger Polarity. This parameter can be one of the following values:
TIM_ExtTRGPolarity_Inverted: active low or falling edge active.
TIM_ExtTRGPolarity_NonInverted: active high or rising edge active.
ExtTRGFilter External Trigger Filter. This parameter must be a value between 0x00 and 0x0F
Return values
None
Definition at line 2811 of file stm32f4xx_tim.c.
References TIM_ETRConfig().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST3_PERIPH(TIMx));
  assert_param(IS_TIM_EXT_PRESCALER(TIM_ExtTRGPrescaler));
  assert_param(IS_TIM_EXT_POLARITY(TIM_ExtTRGPolarity));
  assert_param(IS_TIM_EXT_FILTER(ExtTRGFilter));
  /* Configure the ETR Clock source */
  TIM_ETRConfig(TIMx, TIM_ExtTRGPrescaler, TIM_ExtTRGPolarity, ExtTRGFilter);
  /* Enable the External clock mode2 */
  TIMx->SMCR |= TIM_SMCR_ECE;
}
TIM_InternalClockConfig()
void TIM_InternalClockConfig (TIM_TypeDef * TIMx)
Configures the TIMx internal Clock.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
Return values
None
Definition at line 2673 of file stm32f4xx_tim.c.
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  /* Disable slave mode to clock the prescaler directly with the internal clock */
  TIMx->SMCR &= (uint16_t)~TIM_SMCR_SMS;
}
TIM_ITRxExternalClockConfig()
void TIM_ITRxExternalClockConfig (TIM_TypeDef * TIMx, uint16_t TIM_InputTriggerSource)
Configures the TIMx Internal Trigger as External Clock.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9 or 12 to select the TIM peripheral.
TIM_InputTriggerSource Trigger source. This parameter can be one of the following values:
TIM_TS_ITR0: Internal Trigger 0
TIM_TS_ITR1: Internal Trigger 1
TIM_TS_ITR2: Internal Trigger 2
TIM_TS_ITR3: Internal Trigger 3
Return values
None
Definition at line 2694 of file stm32f4xx_tim.c.
References TIM_SelectInputTrigger().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST2_PERIPH(TIMx));
  assert_param(IS_TIM_INTERNAL_TRIGGER_SELECTION(TIM_InputTriggerSource));
  /* Select the Internal Trigger */
  TIM_SelectInputTrigger(TIMx, TIM_InputTriggerSource);
  /* Select the External clock mode1 */
  TIMx->SMCR |= TIM_SlaveMode_External1;
}
TIM_TIxExternalClockConfig()
void TIM_TIxExternalClockConfig (TIM_TypeDef * TIMx, uint16_t TIM_TIxExternalCLKSource, uint16_t TIM_ICPolarity, uint16_t ICFilter)
Configures the TIMx Trigger as External Clock.
Parameters
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13 or 14 to select the TIM peripheral.
TIM_TIxExternalCLKSource Trigger source. This parameter can be one of the following values:
TIM_TIxExternalCLK1Source_TI1ED: TI1 Edge Detector
TIM_TIxExternalCLK1Source_TI1: Filtered Timer Input 1
TIM_TIxExternalCLK1Source_TI2: Filtered Timer Input 2
TIM_ICPolarity specifies the TIx Polarity. This parameter can be one of the following values:
TIM_ICPolarity_Rising
TIM_ICPolarity_Falling
ICFilter specifies the filter value. This parameter must be a value between 0x0 and 0xF.
Return values
None
Definition at line 2724 of file stm32f4xx_tim.c.
References TI1_Config(), TI2_Config(), and TIM_SelectInputTrigger().
{
  /* Check the parameters */
  assert_param(IS_TIM_LIST1_PERIPH(TIMx));
  assert_param(IS_TIM_IC_POLARITY(TIM_ICPolarity));
  assert_param(IS_TIM_IC_FILTER(ICFilter));
  /* Configure the Timer Input Clock Source */
  if (TIM_TIxExternalCLKSource == TIM_TIxExternalCLK1Source_TI2)
  {
    TI2_Config(TIMx, TIM_ICPolarity, TIM_ICSelection_DirectTI, ICFilter);
  }
  else
  {
    TI1_Config(TIMx, TIM_ICPolarity, TIM_ICSelection_DirectTI, ICFilter);
  }
  /* Select the Trigger source */
  TIM_SelectInputTrigger(TIMx, TIM_TIxExternalCLKSource);
  /* Select the External clock mode1 */
  TIMx->SMCR |= TIM_SlaveMode_External1;
}