FLASH
FLASH driver modules.
Modules
 FLASH_Exported_Constants
 FLASH_Private_Functions
Macros
#define SECTOR_MASK ((uint32_t)0xFFFFFF07)
Enumerations
enum FLASH_Status {
 FLASH_BUSY = 1,
 FLASH_ERROR_PGS,
 FLASH_ERROR_PGP,
 FLASH_ERROR_PGA,
 FLASH_ERROR_WRP,
 FLASH_ERROR_PROGRAM,
 FLASH_ERROR_OPERATION,
 FLASH_COMPLETE
 }
FLASH Status.
Functions
void FLASH_SetLatency (uint32_t FLASH_Latency)
Sets the code latency value.
void FLASH_PrefetchBufferCmd (FunctionalState NewState)
Enables or disables the Prefetch Buffer.
void FLASH_InstructionCacheCmd (FunctionalState NewState)
Enables or disables the Instruction Cache feature.
void FLASH_DataCacheCmd (FunctionalState NewState)
Enables or disables the Data Cache feature.
void FLASH_InstructionCacheReset (void)
Resets the Instruction Cache.
void FLASH_DataCacheReset (void)
Resets the Data Cache.
void FLASH_Unlock (void)
Unlocks the FLASH control register access.
void FLASH_Lock (void)
Locks the FLASH control register access.
 FLASH_Status FLASH_EraseSector (uint32_t FLASH_Sector, uint8_t VoltageRange)
Erases a specified FLASH Sector.
 FLASH_Status FLASH_EraseAllSectors (uint8_t VoltageRange)
Erases all FLASH Sectors.
 FLASH_Status FLASH_ProgramDoubleWord (uint32_t Address, uint64_t Data)
Programs a double word (64-bit) at a specified address.
 FLASH_Status FLASH_ProgramWord (uint32_t Address, uint32_t Data)
Programs a word (32-bit) at a specified address.
 FLASH_Status FLASH_ProgramHalfWord (uint32_t Address, uint16_t Data)
Programs a half word (16-bit) at a specified address.
 FLASH_Status FLASH_ProgramByte (uint32_t Address, uint8_t Data)
Programs a byte (8-bit) at a specified address.
void FLASH_OB_Unlock (void)
Unlocks the FLASH Option Control Registers access.
void FLASH_OB_Lock (void)
Locks the FLASH Option Control Registers access.
void FLASH_OB_WRPConfig (uint32_t OB_WRP, FunctionalState NewState)
Enables or disables the write protection of the desired sectors.
void FLASH_OB_RDPConfig (uint8_t OB_RDP)
Sets the read protection level.
void FLASH_OB_UserConfig (uint8_t OB_IWDG, uint8_t OB_STOP, uint8_t OB_STDBY)
Programs the FLASH User Option Byte: IWDG_SW / RST_STOP / RST_STDBY.
void FLASH_OB_BORConfig (uint8_t OB_BOR)
Sets the BOR Level.
 FLASH_Status FLASH_OB_Launch (void)
Launch the option byte loading.
uint8_t FLASH_OB_GetUser (void)
Returns the FLASH User Option Bytes values.
uint16_t FLASH_OB_GetWRP (void)
Returns the FLASH Write Protection Option Bytes value.
 FlagStatus FLASH_OB_GetRDP (void)
Returns the FLASH Read Protection level.
uint8_t FLASH_OB_GetBOR (void)
Returns the FLASH BOR level.
void FLASH_ITConfig (uint32_t FLASH_IT, FunctionalState NewState)
Enables or disables the specified FLASH interrupts.
 FlagStatus FLASH_GetFlagStatus (uint32_t FLASH_FLAG)
Checks whether the specified FLASH flag is set or not.
void FLASH_ClearFlag (uint32_t FLASH_FLAG)
Clears the FLASH's pending flags.
 FLASH_Status FLASH_GetStatus (void)
Returns the FLASH Status.
 FLASH_Status FLASH_WaitForLastOperation (void)
Waits for a FLASH operation to complete.
Detailed Description
FLASH driver modules.
Macro Definition Documentation
SECTOR_MASK
#define SECTOR_MASK ((uint32_t)0xFFFFFF07)
Definition at line 83 of file stm32f4xx_flash.c.
Enumeration Type Documentation
FLASH_Status
enum FLASH_Status
FLASH Status.
Enumerator
FLASH_BUSY
FLASH_ERROR_PGS
FLASH_ERROR_PGP
FLASH_ERROR_PGA
FLASH_ERROR_WRP
FLASH_ERROR_PROGRAM
FLASH_ERROR_OPERATION
FLASH_COMPLETE
Definition at line 46 of file stm32f4xx_flash.h.
{
  FLASH_BUSY = 1,
  FLASH_ERROR_PGS,
  FLASH_ERROR_PGP,
  FLASH_ERROR_PGA,
  FLASH_ERROR_WRP,
  FLASH_ERROR_PROGRAM,
  FLASH_ERROR_OPERATION,
  FLASH_COMPLETE
}FLASH_Status;
Function Documentation
FLASH_ClearFlag()
void FLASH_ClearFlag (uint32_t FLASH_FLAG)
Clears the FLASH's pending flags.
Parameters
FLASH_FLAG specifies the FLASH flags to clear. This parameter can be any combination of the following values:
FLASH_FLAG_EOP: FLASH End of Operation flag
FLASH_FLAG_OPERR: FLASH operation Error flag
FLASH_FLAG_WRPERR: FLASH Write protected error flag
FLASH_FLAG_PGAERR: FLASH Programming Alignment error flag
FLASH_FLAG_PGPERR: FLASH Programming Parallelism error flag
FLASH_FLAG_PGSERR: FLASH Programming Sequence error flag
Return values
None
Definition at line 964 of file stm32f4xx_flash.c.
{
  /* Check the parameters */
  assert_param(IS_FLASH_CLEAR_FLAG(FLASH_FLAG));
  
  /* Clear the flags */
  FLASH->SR = FLASH_FLAG;
}
FLASH_DataCacheCmd()
void FLASH_DataCacheCmd (FunctionalState NewState)
Enables or disables the Data Cache feature.
Parameters
NewState new state of the Data Cache. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 224 of file stm32f4xx_flash.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if(NewState != DISABLE)
  {
    FLASH->ACR |= FLASH_ACR_DCEN;
  }
  else
  {
    FLASH->ACR &= (~FLASH_ACR_DCEN);
  }
}
FLASH_DataCacheReset()
void FLASH_DataCacheReset (void)
Resets the Data Cache.
Note
This function must be used only when the Data Cache is disabled.
Parameters
None
Return values
None
Definition at line 256 of file stm32f4xx_flash.c.
{
  FLASH->ACR |= FLASH_ACR_DCRST;
}
FLASH_EraseAllSectors()
 FLASH_Status FLASH_EraseAllSectors (uint8_t VoltageRange)
Erases all FLASH Sectors.
Parameters
VoltageRange The device voltage range which defines the erase parallelism. This parameter can be one of the following values:
VoltageRange_1: when the device voltage range is 1.8V to 2.1V, the operation will be done by byte (8-bit)
VoltageRange_2: when the device voltage range is 2.1V to 2.7V, the operation will be done by half word (16-bit)
VoltageRange_3: when the device voltage range is 2.7V to 3.6V, the operation will be done by word (32-bit)
VoltageRange_4: when the device voltage range is 2.7V to 3.6V + External Vpp, the operation will be done by double word (64-bit)
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 406 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  uint32_t tmp_psize = 0x0;
  FLASH_Status status = FLASH_COMPLETE;
  
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  assert_param(IS_VOLTAGERANGE(VoltageRange));
  
  if(VoltageRange == VoltageRange_1)
  {
     tmp_psize = FLASH_PSIZE_BYTE;
  }
  else if(VoltageRange == VoltageRange_2)
  {
    tmp_psize = FLASH_PSIZE_HALF_WORD;
  }
  else if(VoltageRange == VoltageRange_3)
  {
    tmp_psize = FLASH_PSIZE_WORD;
  }
  else
  {
    tmp_psize = FLASH_PSIZE_DOUBLE_WORD;
  }
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to erase all sectors */
     FLASH->CR &= CR_PSIZE_MASK;
     FLASH->CR |= tmp_psize;
     FLASH->CR |= FLASH_CR_MER;
     FLASH->CR |= FLASH_CR_STRT;
    
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    /* if the erase operation is completed, disable the MER Bit */
    FLASH->CR &= (~FLASH_CR_MER);
  }
  /* Return the Erase Status */
  return status;
}
FLASH_EraseSector()
 FLASH_Status FLASH_EraseSector (uint32_t FLASH_Sector, uint8_t VoltageRange)
Erases a specified FLASH Sector.
Parameters
FLASH_Sector The Sector number to be erased. This parameter can be a value between FLASH_Sector_0 and FLASH_Sector_11
VoltageRange The device voltage range which defines the erase parallelism. This parameter can be one of the following values:
VoltageRange_1: when the device voltage range is 1.8V to 2.1V, the operation will be done by byte (8-bit)
VoltageRange_2: when the device voltage range is 2.1V to 2.7V, the operation will be done by half word (16-bit)
VoltageRange_3: when the device voltage range is 2.7V to 3.6V, the operation will be done by word (32-bit)
VoltageRange_4: when the device voltage range is 2.7V to 3.6V + External Vpp, the operation will be done by double word (64-bit)
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 341 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  uint32_t tmp_psize = 0x0;
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_FLASH_SECTOR(FLASH_Sector));
  assert_param(IS_VOLTAGERANGE(VoltageRange));
  
  if(VoltageRange == VoltageRange_1)
  {
     tmp_psize = FLASH_PSIZE_BYTE;
  }
  else if(VoltageRange == VoltageRange_2)
  {
    tmp_psize = FLASH_PSIZE_HALF_WORD;
  }
  else if(VoltageRange == VoltageRange_3)
  {
    tmp_psize = FLASH_PSIZE_WORD;
  }
  else
  {
    tmp_psize = FLASH_PSIZE_DOUBLE_WORD;
  }
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to erase the sector */
    FLASH->CR &= CR_PSIZE_MASK;
    FLASH->CR |= tmp_psize;
    FLASH->CR &= SECTOR_MASK;
    FLASH->CR |= FLASH_CR_SER | FLASH_Sector;
    FLASH->CR |= FLASH_CR_STRT;
    
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    
    /* if the erase operation is completed, disable the SER Bit */
    FLASH->CR &= (~FLASH_CR_SER);
    FLASH->CR &= SECTOR_MASK;
  }
  /* Return the Erase Status */
  return status;
}
FLASH_GetFlagStatus()
 FlagStatus FLASH_GetFlagStatus (uint32_t FLASH_FLAG)
Checks whether the specified FLASH flag is set or not.
Parameters
FLASH_FLAG specifies the FLASH flag to check. This parameter can be one of the following values:
FLASH_FLAG_EOP: FLASH End of Operation flag
FLASH_FLAG_OPERR: FLASH operation Error flag
FLASH_FLAG_WRPERR: FLASH Write protected error flag
FLASH_FLAG_PGAERR: FLASH Programming Alignment error flag
FLASH_FLAG_PGPERR: FLASH Programming Parallelism error flag
FLASH_FLAG_PGSERR: FLASH Programming Sequence error flag
FLASH_FLAG_BSY: FLASH Busy flag
Return values
The new state of FLASH_FLAG (SET or RESET).
Definition at line 934 of file stm32f4xx_flash.c.
References RESET.
{
  FlagStatus bitstatus = RESET;
  /* Check the parameters */
  assert_param(IS_FLASH_GET_FLAG(FLASH_FLAG));
  if((FLASH->SR & FLASH_FLAG) != (uint32_t)RESET)
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  /* Return the new state of FLASH_FLAG (SET or RESET) */
  return bitstatus;
}
FLASH_GetStatus()
 FLASH_Status FLASH_GetStatus (void)
Returns the FLASH Status.
Parameters
None
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 979 of file stm32f4xx_flash.c.
References FLASH_COMPLETE.
{
  FLASH_Status flashstatus = FLASH_COMPLETE;
  
  if((FLASH->SR & FLASH_FLAG_BSY) == FLASH_FLAG_BSY)
  {
    flashstatus = FLASH_BUSY;
  }
  else
  {
    if((FLASH->SR & FLASH_FLAG_WRPERR) != (uint32_t)0x00)
    {
      flashstatus = FLASH_ERROR_WRP;
    }
    else
    {
      if((FLASH->SR & (uint32_t)0xEF) != (uint32_t)0x00)
      {
        flashstatus = FLASH_ERROR_PROGRAM;
      }
      else
      {
        if((FLASH->SR & FLASH_FLAG_OPERR) != (uint32_t)0x00)
        {
          flashstatus = FLASH_ERROR_OPERATION;
        }
        else
        {
          flashstatus = FLASH_COMPLETE;
        }
      }
    }
  }
  /* Return the FLASH Status */
  return flashstatus;
}
FLASH_InstructionCacheCmd()
void FLASH_InstructionCacheCmd (FunctionalState NewState)
Enables or disables the Instruction Cache feature.
Parameters
NewState new state of the Instruction Cache. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 203 of file stm32f4xx_flash.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if(NewState != DISABLE)
  {
    FLASH->ACR |= FLASH_ACR_ICEN;
  }
  else
  {
    FLASH->ACR &= (~FLASH_ACR_ICEN);
  }
}
FLASH_InstructionCacheReset()
void FLASH_InstructionCacheReset (void)
Resets the Instruction Cache.
Note
This function must be used only when the Instruction Cache is disabled.
Parameters
None
Return values
None
Definition at line 245 of file stm32f4xx_flash.c.
{
  FLASH->ACR |= FLASH_ACR_ICRST;
}
FLASH_ITConfig()
void FLASH_ITConfig (uint32_t FLASH_IT, FunctionalState NewState)
Enables or disables the specified FLASH interrupts.
Parameters
FLASH_IT specifies the FLASH interrupt sources to be enabled or disabled. This parameter can be any combination of the following values:
FLASH_IT_ERR: FLASH Error Interrupt
FLASH_IT_EOP: FLASH end of operation Interrupt
Return values
None
Definition at line 903 of file stm32f4xx_flash.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FLASH_IT(FLASH_IT));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if(NewState != DISABLE)
  {
    /* Enable the interrupt sources */
    FLASH->CR |= FLASH_IT;
  }
  else
  {
    /* Disable the interrupt sources */
    FLASH->CR &= ~(uint32_t)FLASH_IT;
  }
}
FLASH_Lock()
void FLASH_Lock (void)
Locks the FLASH control register access.
Parameters
None
Return values
None
Definition at line 315 of file stm32f4xx_flash.c.
{
  /* Set the LOCK Bit to lock the FLASH Registers access */
  FLASH->CR |= FLASH_CR_LOCK;
}
FLASH_OB_BORConfig()
void FLASH_OB_BORConfig (uint8_t OB_BOR)
Sets the BOR Level.
Parameters
OB_BOR specifies the Option Bytes BOR Reset Level. This parameter can be one of the following values:
OB_BOR_LEVEL3: Supply voltage ranges from 2.7 to 3.6 V
OB_BOR_LEVEL2: Supply voltage ranges from 2.4 to 2.7 V
OB_BOR_LEVEL1: Supply voltage ranges from 2.1 to 2.4 V
OB_BOR_OFF: Supply voltage ranges from 1.62 to 2.1 V
Return values
None
Definition at line 789 of file stm32f4xx_flash.c.
{
  /* Check the parameters */
  assert_param(IS_OB_BOR(OB_BOR));
  /* Set the BOR Level */
  *(__IO uint8_t *)OPTCR_BYTE0_ADDRESS &= (~FLASH_OPTCR_BOR_LEV);
  *(__IO uint8_t *)OPTCR_BYTE0_ADDRESS |= OB_BOR;
}
FLASH_OB_GetBOR()
uint8_t FLASH_OB_GetBOR (void)
Returns the FLASH BOR level.
Parameters
None
Return values
The FLASH BOR level:
OB_BOR_LEVEL3: Supply voltage ranges from 2.7 to 3.6 V
OB_BOR_LEVEL2: Supply voltage ranges from 2.4 to 2.7 V
OB_BOR_LEVEL1: Supply voltage ranges from 2.1 to 2.4 V
OB_BOR_OFF : Supply voltage ranges from 1.62 to 2.1 V
Definition at line 873 of file stm32f4xx_flash.c.
{
  /* Return the FLASH BOR level */
  return (uint8_t)(*(__IO uint8_t *)(OPTCR_BYTE0_ADDRESS) & (uint8_t)0x0C);
}
FLASH_OB_GetRDP()
 FlagStatus FLASH_OB_GetRDP (void)
Returns the FLASH Read Protection level.
Parameters
None
Return values
FLASH ReadOut Protection Status:
SET, when OB_RDP_Level_1 or OB_RDP_Level_2 is set
RESET, when OB_RDP_Level_0 is set
Definition at line 849 of file stm32f4xx_flash.c.
References RESET.
{
  FlagStatus readstatus = RESET;
  if ((*(__IO uint8_t*)(OPTCR_BYTE1_ADDRESS) != (uint8_t)OB_RDP_Level_0))
  {
    readstatus = SET;
  }
  else
  {
    readstatus = RESET;
  }
  return readstatus;
}
FLASH_OB_GetUser()
uint8_t FLASH_OB_GetUser (void)
Returns the FLASH User Option Bytes values.
Parameters
None
Return values
The FLASH User Option Bytes values: IWDG_SW(Bit0), RST_STOP(Bit1) and RST_STDBY(Bit2).
Definition at line 825 of file stm32f4xx_flash.c.
{
  /* Return the User Option Byte */
  return (uint8_t)(FLASH->OPTCR >> 5);
}
FLASH_OB_GetWRP()
uint16_t FLASH_OB_GetWRP (void)
Returns the FLASH Write Protection Option Bytes value.
Parameters
None
Return values
The FLASH Write Protection Option Bytes value
Definition at line 836 of file stm32f4xx_flash.c.
{
  /* Return the FLASH write protection Register value */
  return (*(__IO uint16_t *)(OPTCR_BYTE2_ADDRESS));
}
FLASH_OB_Launch()
 FLASH_Status FLASH_OB_Launch (void)
Launch the option byte loading.
Parameters
None
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 806 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  FLASH_Status status = FLASH_COMPLETE;
  /* Set the OPTSTRT bit in OPTCR register */
  *(__IO uint8_t *)OPTCR_BYTE0_ADDRESS |= FLASH_OPTCR_OPTSTRT;
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  return status;
}
FLASH_OB_Lock()
void FLASH_OB_Lock (void)
Locks the FLASH Option Control Registers access.
Parameters
None
Return values
None
Definition at line 673 of file stm32f4xx_flash.c.
{
  /* Set the OPTLOCK Bit to lock the FLASH Option Byte Registers access */
  FLASH->OPTCR |= FLASH_OPTCR_OPTLOCK;
}
FLASH_OB_RDPConfig()
void FLASH_OB_RDPConfig (uint8_t OB_RDP)
Sets the read protection level.
Parameters
OB_RDP specifies the read protection level. This parameter can be one of the following values:
OB_RDP_Level_0: No protection
OB_RDP_Level_1: Read protection of the memory
OB_RDP_Level_2: Full chip protection
!!!Warning!!! When enabling OB_RDP level 2 it's no more possible to go back to level 1 or 0
Return values
None
Definition at line 724 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_OB_RDP(OB_RDP));
  status = FLASH_WaitForLastOperation();
  if(status == FLASH_COMPLETE)
  {
    *(__IO uint8_t*)OPTCR_BYTE1_ADDRESS = OB_RDP;
  }
}
FLASH_OB_Unlock()
void FLASH_OB_Unlock (void)
Unlocks the FLASH Option Control Registers access.
Parameters
None
Return values
None
Definition at line 658 of file stm32f4xx_flash.c.
{
  if((FLASH->OPTCR & FLASH_OPTCR_OPTLOCK) != RESET)
  {
    /* Authorizes the Option Byte register programming */
    FLASH->OPTKEYR = FLASH_OPT_KEY1;
    FLASH->OPTKEYR = FLASH_OPT_KEY2;
  }
}
FLASH_OB_UserConfig()
void FLASH_OB_UserConfig (uint8_t OB_IWDG, uint8_t OB_STOP, uint8_t OB_STDBY)
Programs the FLASH User Option Byte: IWDG_SW / RST_STOP / RST_STDBY.
Parameters
OB_IWDG Selects the IWDG mode This parameter can be one of the following values:
OB_IWDG_SW: Software IWDG selected
OB_IWDG_HW: Hardware IWDG selected
OB_STOP Reset event when entering STOP mode. This parameter can be one of the following values:
OB_STOP_NoRST: No reset generated when entering in STOP
OB_STOP_RST: Reset generated when entering in STOP
OB_STDBY Reset event when entering Standby mode. This parameter can be one of the following values:
OB_STDBY_NoRST: No reset generated when entering in STANDBY
OB_STDBY_RST: Reset generated when entering in STANDBY
Return values
None
Definition at line 756 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  uint8_t optiontmp = 0xFF;
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_OB_IWDG_SOURCE(OB_IWDG));
  assert_param(IS_OB_STOP_SOURCE(OB_STOP));
  assert_param(IS_OB_STDBY_SOURCE(OB_STDBY));
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  
  if(status == FLASH_COMPLETE)
  {
    /* Mask OPTLOCK, OPTSTRT and BOR_LEV bits */
    optiontmp = (uint8_t)((*(__IO uint8_t *)OPTCR_BYTE0_ADDRESS) & (uint8_t)0x0F);
    /* Update User Option Byte */
    *(__IO uint8_t *)OPTCR_BYTE0_ADDRESS = OB_IWDG | (uint8_t)(OB_STDBY | (uint8_t)(OB_STOP | ((uint8_t)
      optiontmp)));
  }
}
FLASH_OB_WRPConfig()
void FLASH_OB_WRPConfig (uint32_t OB_WRP, FunctionalState NewState)
Enables or disables the write protection of the desired sectors.
Parameters
OB_WRP specifies the sector(s) to be write protected or unprotected. This parameter can be one of the following values:
OB_WRP: A value between OB_WRP_Sector0 and OB_WRP_Sector11
OB_WRP_Sector_All
Newstate new state of the Write Protection. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 689 of file stm32f4xx_flash.c.
References DISABLE, FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  FLASH_Status status = FLASH_COMPLETE;
  
  /* Check the parameters */
  assert_param(IS_OB_WRP(OB_WRP));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
    
  status = FLASH_WaitForLastOperation();
  if(status == FLASH_COMPLETE)
  {
    if(NewState != DISABLE)
    {
      *(__IO uint16_t*)OPTCR_BYTE2_ADDRESS &= (~OB_WRP);
    }
    else
    {
      *(__IO uint16_t*)OPTCR_BYTE2_ADDRESS |= (uint16_t)OB_WRP;
    }
  }
}
FLASH_PrefetchBufferCmd()
void FLASH_PrefetchBufferCmd (FunctionalState NewState)
Enables or disables the Prefetch Buffer.
Parameters
NewState new state of the Prefetch Buffer. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 181 of file stm32f4xx_flash.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  /* Enable or disable the Prefetch Buffer */
  if(NewState != DISABLE)
  {
    FLASH->ACR |= FLASH_ACR_PRFTEN;
  }
  else
  {
    FLASH->ACR &= (~FLASH_ACR_PRFTEN);
  }
}
FLASH_ProgramByte()
 FLASH_Status FLASH_ProgramByte (uint32_t Address, uint8_t Data)
Programs a byte (8-bit) at a specified address.
Note
This function can be used within all the device supply voltage ranges.
Parameters
Address specifies the address to be programmed. This parameter can be any address in Program memory zone or in OTP zone.
Data specifies the data to be programmed.
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 573 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_FLASH_ADDRESS(Address));
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to program the new data */
    FLASH->CR &= CR_PSIZE_MASK;
    FLASH->CR |= FLASH_PSIZE_BYTE;
    FLASH->CR |= FLASH_CR_PG;
  
    *(__IO uint8_t*)Address = Data;
        
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    /* if the program operation is completed, disable the PG Bit */
    FLASH->CR &= (~FLASH_CR_PG);
  }
  /* Return the Program Status */
  return status;
}
FLASH_ProgramDoubleWord()
 FLASH_Status FLASH_ProgramDoubleWord (uint32_t Address, uint64_t Data)
Programs a double word (64-bit) at a specified address.
Note
This function must be used when the device voltage range is from 2.7V to 3.6V and an External Vpp is present.
Parameters
Address specifies the address to be programmed.
Data specifies the data to be programmed.
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 459 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_FLASH_ADDRESS(Address));
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to program the new data */
    FLASH->CR &= CR_PSIZE_MASK;
    FLASH->CR |= FLASH_PSIZE_DOUBLE_WORD;
    FLASH->CR |= FLASH_CR_PG;
  
    *(__IO uint64_t*)Address = Data;
        
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    /* if the program operation is completed, disable the PG Bit */
    FLASH->CR &= (~FLASH_CR_PG);
  }
  /* Return the Program Status */
  return status;
}
FLASH_ProgramHalfWord()
 FLASH_Status FLASH_ProgramHalfWord (uint32_t Address, uint16_t Data)
Programs a half word (16-bit) at a specified address.
Note
This function must be used when the device voltage range is from 2.1V to 3.6V.
Parameters
Address specifies the address to be programmed. This parameter can be any address in Program memory zone or in OTP zone.
Data specifies the data to be programmed.
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 535 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_FLASH_ADDRESS(Address));
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to program the new data */
    FLASH->CR &= CR_PSIZE_MASK;
    FLASH->CR |= FLASH_PSIZE_HALF_WORD;
    FLASH->CR |= FLASH_CR_PG;
  
    *(__IO uint16_t*)Address = Data;
        
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    /* if the program operation is completed, disable the PG Bit */
    FLASH->CR &= (~FLASH_CR_PG);
  }
  /* Return the Program Status */
  return status;
}
FLASH_ProgramWord()
 FLASH_Status FLASH_ProgramWord (uint32_t Address, uint32_t Data)
Programs a word (32-bit) at a specified address.
Parameters
Address specifies the address to be programmed. This parameter can be any address in Program memory zone or in OTP zone.
Note
This function must be used when the device voltage range is from 2.7V to 3.6V.
Parameters
Data specifies the data to be programmed.
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 497 of file stm32f4xx_flash.c.
References FLASH_COMPLETE, and FLASH_WaitForLastOperation().
{
  FLASH_Status status = FLASH_COMPLETE;
  /* Check the parameters */
  assert_param(IS_FLASH_ADDRESS(Address));
  /* Wait for last operation to be completed */
  status = FLASH_WaitForLastOperation();
  
  if(status == FLASH_COMPLETE)
  {
    /* if the previous operation is completed, proceed to program the new data */
    FLASH->CR &= CR_PSIZE_MASK;
    FLASH->CR |= FLASH_PSIZE_WORD;
    FLASH->CR |= FLASH_CR_PG;
  
    *(__IO uint32_t*)Address = Data;
        
    /* Wait for last operation to be completed */
    status = FLASH_WaitForLastOperation();
    /* if the program operation is completed, disable the PG Bit */
    FLASH->CR &= (~FLASH_CR_PG);
  }
  /* Return the Program Status */
  return status;
}
FLASH_SetLatency()
void FLASH_SetLatency (uint32_t FLASH_Latency)
Sets the code latency value.
Parameters
FLASH_Latency specifies the FLASH Latency value. This parameter can be one of the following values:
FLASH_Latency_0: FLASH Zero Latency cycle
FLASH_Latency_1: FLASH One Latency cycle
FLASH_Latency_2: FLASH Two Latency cycles
FLASH_Latency_3: FLASH Three Latency cycles
FLASH_Latency_4: FLASH Four Latency cycles
FLASH_Latency_5: FLASH Five Latency cycles
FLASH_Latency_6: FLASH Six Latency cycles
FLASH_Latency_7: FLASH Seven Latency cycles
Return values
None
Definition at line 166 of file stm32f4xx_flash.c.
{
  /* Check the parameters */
  assert_param(IS_FLASH_LATENCY(FLASH_Latency));
  
  /* Perform Byte access to FLASH_ACR[8:0] to set the Latency value */
  *(__IO uint8_t *)ACR_BYTE0_ADDRESS = (uint8_t)FLASH_Latency;
}
FLASH_Unlock()
void FLASH_Unlock (void)
Unlocks the FLASH control register access.
Parameters
None
Return values
None
Definition at line 300 of file stm32f4xx_flash.c.
{
  if((FLASH->CR & FLASH_CR_LOCK) != RESET)
  {
    /* Authorize the FLASH Registers access */
    FLASH->KEYR = FLASH_KEY1;
    FLASH->KEYR = FLASH_KEY2;
  }
}
FLASH_WaitForLastOperation()
 FLASH_Status FLASH_WaitForLastOperation (void)
Waits for a FLASH operation to complete.
Parameters
None
Return values
FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PROGRAM, FLASH_ERROR_WRP, FLASH_ERROR_OPERATION or FLASH_COMPLETE.
Definition at line 1022 of file stm32f4xx_flash.c.
Referenced by FLASH_EraseAllSectors(), FLASH_EraseSector(), FLASH_OB_Launch(), FLASH_OB_RDPConfig(), FLASH_OB_UserConfig(), FLASH_OB_WRPConfig(), FLASH_ProgramByte(), FLASH_ProgramDoubleWord(), FLASH_ProgramHalfWord(), and FLASH_ProgramWord().
{
  __IO FLASH_Status status = FLASH_COMPLETE;
   
  /* Check for the FLASH Status */
  status = FLASH_GetStatus();
  /* Wait for the FLASH operation to complete by polling on BUSY flag to be reset.
     Even if the FLASH operation fails, the BUSY flag will be reset and an error
     flag will be set */
  while(status == FLASH_BUSY)
  {
    status = FLASH_GetStatus();
  }
  /* Return the operation status */
  return status;
}