GPIO
GPIO driver modules.
Modules
 GPIO_Exported_Constants
 GPIO_Private_Functions
Classes
struct GPIO_InitTypeDef
GPIO Init structure definition.
Macros
#define IS_GPIO_ALL_PERIPH(PERIPH)
#define IS_GPIO_MODE(MODE)
#define IS_GPIO_OTYPE(OTYPE) (((OTYPE) == GPIO_OType_PP) || ((OTYPE) == GPIO_OType_OD))
#define IS_GPIO_SPEED(SPEED)
#define IS_GPIO_PUPD(PUPD)
#define IS_GPIO_BIT_ACTION(ACTION) (((ACTION) == Bit_RESET) || ((ACTION) == Bit_SET))
Enumerations
enum GPIOMode_TypeDef { GPIO_Mode_IN = 0x00,
 GPIO_Mode_OUT = 0x01,
 GPIO_Mode_AF = 0x02,
 GPIO_Mode_AN = 0x03
 }
GPIO Configuration Mode enumeration.
enum GPIOOType_TypeDef { GPIO_OType_PP = 0x00,
 GPIO_OType_OD = 0x01
 }
GPIO Output type enumeration.
enum GPIOSpeed_TypeDef { GPIO_Speed_2MHz = 0x00,
 GPIO_Speed_25MHz = 0x01,
 GPIO_Speed_50MHz = 0x02,
 GPIO_Speed_100MHz = 0x03
 }
GPIO Output Maximum frequency enumeration.
enum GPIOPuPd_TypeDef { GPIO_PuPd_NOPULL = 0x00,
 GPIO_PuPd_UP = 0x01,
 GPIO_PuPd_DOWN = 0x02
 }
GPIO Configuration PullUp PullDown enumeration.
enum BitAction { Bit_RESET = 0,
 Bit_SET
 }
GPIO Bit SET and Bit RESET enumeration.
Functions
void GPIO_DeInit (GPIO_TypeDef *GPIOx)
Deinitializes the GPIOx peripheral registers to their default reset values.
void GPIO_Init (GPIO_TypeDef *GPIOx, GPIO_InitTypeDef *GPIO_InitStruct)
Initializes the GPIOx peripheral according to the specified parameters in the GPIO_InitStruct.
void GPIO_StructInit (GPIO_InitTypeDef *GPIO_InitStruct)
Fills each GPIO_InitStruct member with its default value.
void GPIO_PinLockConfig (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Locks GPIO Pins configuration registers.
uint8_t GPIO_ReadInputDataBit (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Reads the specified input port pin.
uint16_t GPIO_ReadInputData (GPIO_TypeDef *GPIOx)
Reads the specified GPIO input data port.
uint8_t GPIO_ReadOutputDataBit (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Reads the specified output data port bit.
uint16_t GPIO_ReadOutputData (GPIO_TypeDef *GPIOx)
Reads the specified GPIO output data port.
void GPIO_SetBits (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Sets the selected data port bits.
void GPIO_ResetBits (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Clears the selected data port bits.
void GPIO_WriteBit (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, BitAction BitVal)
Sets or clears the selected data port bit.
void GPIO_Write (GPIO_TypeDef *GPIOx, uint16_t PortVal)
Writes data to the specified GPIO data port.
void GPIO_ToggleBits (GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Toggles the specified GPIO pins..
void GPIO_PinAFConfig (GPIO_TypeDef *GPIOx, uint16_t GPIO_PinSource, uint8_t GPIO_AF)
Changes the mapping of the specified pin.
Detailed Description
GPIO driver modules.
Macro Definition Documentation
IS_GPIO_ALL_PERIPH
#define IS_GPIO_ALL_PERIPH(PERIPH)
Value:
(((PERIPH) == GPIOA) || \
                                    ((PERIPH) == GPIOB) || \
                                    ((PERIPH) == GPIOC) || \
                                    ((PERIPH) == GPIOD) || \
                                    ((PERIPH) == GPIOE) || \
                                    ((PERIPH) == GPIOF) || \
                                    ((PERIPH) == GPIOG) || \
                                    ((PERIPH) == GPIOH) || \
                                    ((PERIPH) == GPIOI))
Definition at line 44 of file stm32f4xx_gpio.h.
IS_GPIO_BIT_ACTION
#define IS_GPIO_BIT_ACTION(ACTION) (((ACTION) == Bit_RESET) || ((ACTION) == Bit_SET))
Definition at line 111 of file stm32f4xx_gpio.h.
IS_GPIO_MODE
#define IS_GPIO_MODE(MODE)
Value:
(((MODE) == GPIO_Mode_IN) || ((MODE) == GPIO_Mode_OUT) || \
                            ((MODE) == GPIO_Mode_AF)|| ((MODE) == GPIO_Mode_AN))
Definition at line 64 of file stm32f4xx_gpio.h.
IS_GPIO_OTYPE
#define IS_GPIO_OTYPE(OTYPE) (((OTYPE) == GPIO_OType_PP) || ((OTYPE) == GPIO_OType_OD))
Definition at line 75 of file stm32f4xx_gpio.h.
IS_GPIO_PUPD
#define IS_GPIO_PUPD(PUPD)
Value:
(((PUPD) == GPIO_PuPd_NOPULL) || ((PUPD) == GPIO_PuPd_UP) || \
                            ((PUPD) == GPIO_PuPd_DOWN))
Definition at line 100 of file stm32f4xx_gpio.h.
IS_GPIO_SPEED
#define IS_GPIO_SPEED(SPEED)
Value:
(((SPEED) == GPIO_Speed_2MHz) || ((SPEED) == GPIO_Speed_25MHz) || \
                              ((SPEED) == GPIO_Speed_50MHz)|| ((SPEED) ==
      GPIO_Speed_100MHz))
Definition at line 88 of file stm32f4xx_gpio.h.
Enumeration Type Documentation
BitAction
enum BitAction
GPIO Bit SET and Bit RESET enumeration.
Enumerator
Bit_RESET
Bit_SET
Definition at line 106 of file stm32f4xx_gpio.h.
{
  Bit_RESET = 0,
  Bit_SET
}BitAction;
GPIOMode_TypeDef
enum GPIOMode_TypeDef
GPIO Configuration Mode enumeration.
Enumerator
GPIO_Mode_IN GPIO Input Mode
GPIO_Mode_OUT GPIO Output Mode
GPIO_Mode_AF GPIO Alternate function Mode
GPIO_Mode_AN GPIO Analog Mode
Definition at line 57 of file stm32f4xx_gpio.h.
{
  GPIO_Mode_IN = 0x00,
  GPIO_Mode_OUT = 0x01,
  GPIO_Mode_AF = 0x02,
  GPIO_Mode_AN = 0x03
}GPIOMode_TypeDef;
GPIOOType_TypeDef
enum GPIOOType_TypeDef
GPIO Output type enumeration.
Enumerator
GPIO_OType_PP
GPIO_OType_OD
Definition at line 70 of file stm32f4xx_gpio.h.
{
  GPIO_OType_PP = 0x00,
  GPIO_OType_OD = 0x01
}GPIOOType_TypeDef;
GPIOPuPd_TypeDef
enum GPIOPuPd_TypeDef
GPIO Configuration PullUp PullDown enumeration.
Enumerator
GPIO_PuPd_NOPULL
GPIO_PuPd_UP
GPIO_PuPd_DOWN
Definition at line 94 of file stm32f4xx_gpio.h.
{
  GPIO_PuPd_NOPULL = 0x00,
  GPIO_PuPd_UP = 0x01,
  GPIO_PuPd_DOWN = 0x02
}GPIOPuPd_TypeDef;
GPIOSpeed_TypeDef
enum GPIOSpeed_TypeDef
GPIO Output Maximum frequency enumeration.
Enumerator
GPIO_Speed_2MHz Low speed
GPIO_Speed_25MHz Medium speed
GPIO_Speed_50MHz Fast speed
GPIO_Speed_100MHz High speed on 30 pF (80 MHz Output max speed on 15 pF)
Definition at line 81 of file stm32f4xx_gpio.h.
{
  GPIO_Speed_2MHz = 0x00,
  GPIO_Speed_25MHz = 0x01,
  GPIO_Speed_50MHz = 0x02,
  GPIO_Speed_100MHz = 0x03
}GPIOSpeed_TypeDef;
Function Documentation
GPIO_DeInit()
void GPIO_DeInit (GPIO_TypeDef * GPIOx)
Deinitializes the GPIOx peripheral registers to their default reset values.
Note
By default, The GPIO pins are configured in input floating mode (except JTAG pins).
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
Return values
None
Definition at line 120 of file stm32f4xx_gpio.c.
References DISABLE, ENABLE, and RCC_AHB1PeriphResetCmd().
{
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  if (GPIOx == GPIOA)
  {
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOA, ENABLE);
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOA, DISABLE);
  }
  else if (GPIOx == GPIOB)
  {
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOB, ENABLE);
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOB, DISABLE);
  }
  else if (GPIOx == GPIOC)
  {
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOC, ENABLE);
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOC, DISABLE);
  }
  else if (GPIOx == GPIOD)
  {
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOD, ENABLE);
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOD, DISABLE);
  }
  else if (GPIOx == GPIOE)
  {
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOE, ENABLE);
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOE, DISABLE);
  }
  else if (GPIOx == GPIOF)
  {
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOF, ENABLE);
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOF, DISABLE);
  }
  else if (GPIOx == GPIOG)
  {
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOG, ENABLE);
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOG, DISABLE);
  }
  else if (GPIOx == GPIOH)
  {
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOH, ENABLE);
    RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOH, DISABLE);
  }
  else
  {
    if (GPIOx == GPIOI)
    {
      RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOI, ENABLE);
      RCC_AHB1PeriphResetCmd(RCC_AHB1Periph_GPIOI, DISABLE);
    }
  }
}
GPIO_Init()
void GPIO_Init (GPIO_TypeDef * GPIOx, GPIO_InitTypeDef * GPIO_InitStruct)
Initializes the GPIOx peripheral according to the specified parameters in the GPIO_InitStruct.
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
GPIO_InitStruct pointer to a GPIO_InitTypeDef structure that contains the configuration information for the specified GPIO peripheral.
Return values
None
Definition at line 182 of file stm32f4xx_gpio.c.
References GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AF, GPIO_Mode_OUT, and GPIO_InitTypeDef::GPIO_Pin.
Referenced by GPIO_Config(), I2cMaster_Init(), STM_EVAL_LEDInit(), STM_EVAL_PBInit(), and USART_Config().
{
  uint32_t pinpos = 0x00, pos = 0x00 , currentpin = 0x00;
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  assert_param(IS_GPIO_PIN(GPIO_InitStruct->GPIO_Pin));
  assert_param(IS_GPIO_MODE(GPIO_InitStruct->GPIO_Mode));
  assert_param(IS_GPIO_PUPD(GPIO_InitStruct->GPIO_PuPd));
  /* -------------------------Configure the port pins---------------- */
  /*-- GPIO Mode Configuration --*/
  for (pinpos = 0x00; pinpos < 0x10; pinpos++)
  {
    pos = ((uint32_t)0x01) << pinpos;
    /* Get the port pins position */
    currentpin = (GPIO_InitStruct->GPIO_Pin) & pos;
    if (currentpin == pos)
    {
      GPIOx->MODER &= ~(GPIO_MODER_MODER0 << (pinpos * 2));
      GPIOx->MODER |= (((uint32_t)GPIO_InitStruct->GPIO_Mode) << (pinpos * 2));
      if ((GPIO_InitStruct->GPIO_Mode == GPIO_Mode_OUT) || (GPIO_InitStruct->
      GPIO_Mode == GPIO_Mode_AF))
      {
        /* Check Speed mode parameters */
        assert_param(IS_GPIO_SPEED(GPIO_InitStruct->GPIO_Speed));
        /* Speed mode configuration */
        GPIOx->OSPEEDR &= ~(GPIO_OSPEEDER_OSPEEDR0 << (pinpos * 2));
        GPIOx->OSPEEDR |= ((uint32_t)(GPIO_InitStruct->GPIO_Speed) << (pinpos * 2));
        /* Check Output mode parameters */
        assert_param(IS_GPIO_OTYPE(GPIO_InitStruct->GPIO_OType));
        /* Output mode configuration*/
        GPIOx->OTYPER &= ~((GPIO_OTYPER_OT_0) << ((uint16_t)pinpos)) ;
        GPIOx->OTYPER |= (uint16_t)(((uint16_t)GPIO_InitStruct->GPIO_OType) << ((uint16_t)pinpos));
      }
      /* Pull-up Pull down resistor configuration*/
      GPIOx->PUPDR &= ~(GPIO_PUPDR_PUPDR0 << ((uint16_t)pinpos * 2));
      GPIOx->PUPDR |= (((uint32_t)GPIO_InitStruct->GPIO_PuPd) << (pinpos * 2));
    }
  }
}
GPIO_PinAFConfig()
void GPIO_PinAFConfig (GPIO_TypeDef * GPIOx, uint16_t GPIO_PinSource, uint8_t GPIO_AF)
Changes the mapping of the specified pin.
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
GPIO_PinSource specifies the pin for the Alternate function. This parameter can be GPIO_PinSourcex where x can be (0..15).
GPIO_AFSelection selects the pin to used as Alternate function. This parameter can be one of the following values:
GPIO_AF_RTC_50Hz: Connect RTC_50Hz pin to AF0 (default after reset)
GPIO_AF_MCO: Connect MCO pin (MCO1 and MCO2) to AF0 (default after reset)
GPIO_AF_TAMPER: Connect TAMPER pins (TAMPER_1 and TAMPER_2) to AF0 (default after reset)
GPIO_AF_SWJ: Connect SWJ pins (SWD and JTAG)to AF0 (default after reset)
GPIO_AF_TRACE: Connect TRACE pins to AF0 (default after reset)
GPIO_AF_TIM1: Connect TIM1 pins to AF1
GPIO_AF_TIM2: Connect TIM2 pins to AF1
GPIO_AF_TIM3: Connect TIM3 pins to AF2
GPIO_AF_TIM4: Connect TIM4 pins to AF2
GPIO_AF_TIM5: Connect TIM5 pins to AF2
GPIO_AF_TIM8: Connect TIM8 pins to AF3
GPIO_AF_TIM9: Connect TIM9 pins to AF3
GPIO_AF_TIM10: Connect TIM10 pins to AF3
GPIO_AF_TIM11: Connect TIM11 pins to AF3
GPIO_AF_I2C1: Connect I2C1 pins to AF4
GPIO_AF_I2C2: Connect I2C2 pins to AF4
GPIO_AF_I2C3: Connect I2C3 pins to AF4
GPIO_AF_SPI1: Connect SPI1 pins to AF5
GPIO_AF_SPI2: Connect SPI2/I2S2 pins to AF5
GPIO_AF_SPI3: Connect SPI3/I2S3 pins to AF6
GPIO_AF_I2S3ext: Connect I2S3ext pins to AF7
GPIO_AF_USART1: Connect USART1 pins to AF7
GPIO_AF_USART2: Connect USART2 pins to AF7
GPIO_AF_USART3: Connect USART3 pins to AF7
GPIO_AF_UART4: Connect UART4 pins to AF8
GPIO_AF_UART5: Connect UART5 pins to AF8
GPIO_AF_USART6: Connect USART6 pins to AF8
GPIO_AF_CAN1: Connect CAN1 pins to AF9
GPIO_AF_CAN2: Connect CAN2 pins to AF9
GPIO_AF_TIM12: Connect TIM12 pins to AF9
GPIO_AF_TIM13: Connect TIM13 pins to AF9
GPIO_AF_TIM14: Connect TIM14 pins to AF9
GPIO_AF_OTG_FS: Connect OTG_FS pins to AF10
GPIO_AF_OTG_HS: Connect OTG_HS pins to AF10
GPIO_AF_ETH: Connect ETHERNET pins to AF11
GPIO_AF_FSMC: Connect FSMC pins to AF12
GPIO_AF_OTG_HS_FS: Connect OTG HS (configured in FS) pins to AF12
GPIO_AF_SDIO: Connect SDIO pins to AF12
GPIO_AF_DCMI: Connect DCMI pins to AF13
GPIO_AF_EVENTOUT: Connect EVENTOUT pins to AF15
Return values
None
Definition at line 529 of file stm32f4xx_gpio.c.
Referenced by I2cMaster_Init(), and USART_Config().
{
  uint32_t temp = 0x00;
  uint32_t temp_2 = 0x00;
  
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  assert_param(IS_GPIO_PIN_SOURCE(GPIO_PinSource));
  assert_param(IS_GPIO_AF(GPIO_AF));
  
  temp = ((uint32_t)(GPIO_AF) << ((uint32_t)((uint32_t)GPIO_PinSource & (uint32_t)0x07) * 4)) ;
  GPIOx->AFR[GPIO_PinSource >> 0x03] &= ~((uint32_t)0xF << ((uint32_t)((uint32_t)GPIO_PinSource & (uint32_t
      )0x07) * 4)) ;
  temp_2 = GPIOx->AFR[GPIO_PinSource >> 0x03] | temp;
  GPIOx->AFR[GPIO_PinSource >> 0x03] = temp_2;
}
GPIO_PinLockConfig()
void GPIO_PinLockConfig (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Locks GPIO Pins configuration registers.
Note
The locked registers are GPIOx_MODER, GPIOx_OTYPER, GPIOx_OSPEEDR, GPIOx_PUPDR, GPIOx_AFRL and GPIOx_AFRH.
The configuration of the locked GPIO pins can no longer be modified until the next reset.
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be locked. This parameter can be any combination of GPIO_Pin_x where x can be (0..15).
Return values
None
Definition at line 255 of file stm32f4xx_gpio.c.
{
  __IO uint32_t tmp = 0x00010000;
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  assert_param(IS_GPIO_PIN(GPIO_Pin));
  tmp |= GPIO_Pin;
  /* Set LCKK bit */
  GPIOx->LCKR = tmp;
  /* Reset LCKK bit */
  GPIOx->LCKR = GPIO_Pin;
  /* Set LCKK bit */
  GPIOx->LCKR = tmp;
  /* Read LCKK bit*/
  tmp = GPIOx->LCKR;
  /* Read LCKK bit*/
  tmp = GPIOx->LCKR;
}
GPIO_ReadInputData()
uint16_t GPIO_ReadInputData (GPIO_TypeDef * GPIOx)
Reads the specified GPIO input data port.
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
Return values
GPIO input data port value.
Definition at line 323 of file stm32f4xx_gpio.c.
{
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  return ((uint16_t)GPIOx->IDR);
}
GPIO_ReadInputDataBit()
uint8_t GPIO_ReadInputDataBit (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Reads the specified input port pin.
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to read. This parameter can be GPIO_Pin_x where x can be (0..15).
Return values
The input port pin value.
Definition at line 299 of file stm32f4xx_gpio.c.
Referenced by STM_EVAL_PBGetState().
{
  uint8_t bitstatus = 0x00;
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  assert_param(IS_GET_GPIO_PIN(GPIO_Pin));
  if ((GPIOx->IDR & GPIO_Pin) != (uint32_t)Bit_RESET)
  {
    bitstatus = (uint8_t)Bit_SET;
  }
  else
  {
    bitstatus = (uint8_t)Bit_RESET;
  }
  return bitstatus;
}
GPIO_ReadOutputData()
uint16_t GPIO_ReadOutputData (GPIO_TypeDef * GPIOx)
Reads the specified GPIO output data port.
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
Return values
GPIO output data port value.
Definition at line 362 of file stm32f4xx_gpio.c.
{
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  return ((uint16_t)GPIOx->ODR);
}
GPIO_ReadOutputDataBit()
uint8_t GPIO_ReadOutputDataBit (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Reads the specified output data port bit.
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to read. This parameter can be GPIO_Pin_x where x can be (0..15).
Return values
The output port pin value.
Definition at line 338 of file stm32f4xx_gpio.c.
{
  uint8_t bitstatus = 0x00;
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  assert_param(IS_GET_GPIO_PIN(GPIO_Pin));
  if ((GPIOx->ODR & GPIO_Pin) != (uint32_t)Bit_RESET)
  {
    bitstatus = (uint8_t)Bit_SET;
  }
  else
  {
    bitstatus = (uint8_t)Bit_RESET;
  }
  return bitstatus;
}
GPIO_ResetBits()
void GPIO_ResetBits (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Clears the selected data port bits.
Note
This functions uses GPIOx_BSRR register to allow atomic read/modify accesses. In this way, there is no risk of an IRQ occurring between the read and the modify access.
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
GPIO_Pin specifies the port bits to be written. This parameter can be any combination of GPIO_Pin_x where x can be (0..15).
Return values
None
Definition at line 399 of file stm32f4xx_gpio.c.
{
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  assert_param(IS_GPIO_PIN(GPIO_Pin));
  GPIOx->BSRRH = GPIO_Pin;
}
GPIO_SetBits()
void GPIO_SetBits (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Sets the selected data port bits.
Note
This functions uses GPIOx_BSRR register to allow atomic read/modify accesses. In this way, there is no risk of an IRQ occurring between the read and the modify access.
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
GPIO_Pin specifies the port bits to be written. This parameter can be any combination of GPIO_Pin_x where x can be (0..15).
Return values
None
Definition at line 380 of file stm32f4xx_gpio.c.
{
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  assert_param(IS_GPIO_PIN(GPIO_Pin));
  GPIOx->BSRRL = GPIO_Pin;
}
GPIO_StructInit()
void GPIO_StructInit (GPIO_InitTypeDef * GPIO_InitStruct)
Fills each GPIO_InitStruct member with its default value.
Parameters
GPIO_InitStruct : pointer to a GPIO_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 234 of file stm32f4xx_gpio.c.
References GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_IN, GPIO_InitTypeDef::GPIO_OType, GPIO_OType_PP, GPIO_InitTypeDef::GPIO_Pin, GPIO_InitTypeDef::GPIO_PuPd, GPIO_PuPd_NOPULL, GPIO_InitTypeDef::GPIO_Speed, and GPIO_Speed_2MHz.
{
  /* Reset GPIO init structure parameters values */
  GPIO_InitStruct->GPIO_Pin = GPIO_Pin_All;
  GPIO_InitStruct->GPIO_Mode = GPIO_Mode_IN;
  GPIO_InitStruct->GPIO_Speed = GPIO_Speed_2MHz;
  GPIO_InitStruct->GPIO_OType = GPIO_OType_PP;
  GPIO_InitStruct->GPIO_PuPd = GPIO_PuPd_NOPULL;
}
GPIO_ToggleBits()
void GPIO_ToggleBits (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin)
Toggles the specified GPIO pins..
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
GPIO_Pin Specifies the pins to be toggled.
Return values
None
Definition at line 456 of file stm32f4xx_gpio.c.
{
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  GPIOx->ODR ^= GPIO_Pin;
}
GPIO_Write()
void GPIO_Write (GPIO_TypeDef * GPIOx, uint16_t PortVal)
Writes data to the specified GPIO data port.
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
PortVal specifies the value to be written to the port output data register.
Return values
None
Definition at line 442 of file stm32f4xx_gpio.c.
{
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  GPIOx->ODR = PortVal;
}
GPIO_WriteBit()
void GPIO_WriteBit (GPIO_TypeDef * GPIOx, uint16_t GPIO_Pin, BitAction BitVal)
Sets or clears the selected data port bit.
Parameters
GPIOx where x can be (A..I) to select the GPIO peripheral.
GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_Pin_x where x can be (0..15).
BitVal specifies the value to be written to the selected bit. This parameter can be one of the BitAction enum values:
Bit_RESET: to clear the port pin
Bit_SET: to set the port pin
Return values
None
Definition at line 419 of file stm32f4xx_gpio.c.
References Bit_RESET.
{
  /* Check the parameters */
  assert_param(IS_GPIO_ALL_PERIPH(GPIOx));
  assert_param(IS_GET_GPIO_PIN(GPIO_Pin));
  assert_param(IS_GPIO_BIT_ACTION(BitVal));
  if (BitVal != Bit_RESET)
  {
    GPIOx->BSRRL = GPIO_Pin;
  }
  else
  {
    GPIOx->BSRRH = GPIO_Pin ;
  }
}