USART
USART driver modules.
Modules
 USART_Exported_Constants
 USART_Private_Functions
Classes
struct USART_InitTypeDef
USART Init Structure definition.
struct USART_ClockInitTypeDef
USART Clock Init Structure definition.
Macros
#define CR1_CLEAR_MASK
#define CR2_CLOCK_CLEAR_MASK
#define CR3_CLEAR_MASK ((uint16_t)(USART_CR3_RTSE | USART_CR3_CTSE))
#define IT_MASK ((uint16_t)0x001F)
Functions
void USART_DeInit (USART_TypeDef * USARTx)
Deinitializes the USARTx peripheral registers to their default reset values.
void USART_Init (USART_TypeDef * USARTx, USART_InitTypeDef *USART_InitStruct)
Initializes the USARTx peripheral according to the specified parameters in the USART_InitStruct .
void USART_StructInit (USART_InitTypeDef *USART_InitStruct)
Fills each USART_InitStruct member with its default value.
void USART_ClockInit (USART_TypeDef * USARTx, USART_ClockInitTypeDef *USART_ClockInitStruct)
Initializes the USARTx peripheral Clock according to the specified parameters in the USART_ClockInitStruct .
void USART_ClockStructInit (USART_ClockInitTypeDef *USART_ClockInitStruct)
Fills each USART_ClockInitStruct member with its default value.
void USART_Cmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the specified USART peripheral.
void USART_SetPrescaler (USART_TypeDef * USARTx, uint8_t USART_Prescaler)
Sets the system clock prescaler.
void USART_OverSampling8Cmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's 8x oversampling mode.
void USART_OneBitMethodCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's one bit sampling method.
void USART_SendData (USART_TypeDef * USARTx, uint16_t Data)
Transmits single data through the USARTx peripheral.
uint16_t USART_ReceiveData (USART_TypeDef * USARTx)
Returns the most recent received data by the USARTx peripheral.
void USART_SetAddress (USART_TypeDef * USARTx, uint8_t USART_Address)
Sets the address of the USART node.
void USART_WakeUpConfig (USART_TypeDef * USARTx, uint16_t USART_WakeUp)
Selects the USART WakeUp method.
void USART_ReceiverWakeUpCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Determines if the USART is in mute mode or not.
void USART_LINBreakDetectLengthConfig (USART_TypeDef * USARTx, uint16_t USART_LINBreakDetectLength)
Sets the USART LIN Break detection length.
void USART_LINCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's LIN mode.
void USART_SendBreak (USART_TypeDef * USARTx)
Transmits break characters.
void USART_HalfDuplexCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's Half Duplex communication.
void USART_SmartCardCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's Smart Card mode.
void USART_SmartCardNACKCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables NACK transmission.
void USART_SetGuardTime (USART_TypeDef * USARTx, uint8_t USART_GuardTime)
Sets the specified USART guard time.
void USART_IrDAConfig (USART_TypeDef * USARTx, uint16_t USART_IrDAMode)
Configures the USART's IrDA interface.
void USART_IrDACmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's IrDA interface.
void USART_DMACmd (USART_TypeDef * USARTx, uint16_t USART_DMAReq, FunctionalState NewState)
Enables or disables the USART's DMA interface.
void USART_ITConfig (USART_TypeDef * USARTx, uint16_t USART_IT, FunctionalState NewState)
Enables or disables the specified USART interrupts.
 FlagStatus USART_GetFlagStatus (USART_TypeDef * USARTx, uint16_t USART_FLAG)
Checks whether the specified USART flag is set or not.
void USART_ClearFlag (USART_TypeDef * USARTx, uint16_t USART_FLAG)
Clears the USARTx's pending flags.
 ITStatus USART_GetITStatus (USART_TypeDef * USARTx, uint16_t USART_IT)
Checks whether the specified USART interrupt has occurred or not.
void USART_ClearITPendingBit (USART_TypeDef * USARTx, uint16_t USART_IT)
Clears the USARTx's interrupt pending bits.
Detailed Description
USART driver modules.
Macro Definition Documentation
CR1_CLEAR_MASK
#define CR1_CLEAR_MASK
Value:
((uint16_t)(USART_CR1_M | USART_CR1_PCE | \
                                              USART_CR1_PS | USART_CR1_TE | \
                                              USART_CR1_RE))
< USART CR1 register clear Mask ((~(uint16_t)0xE9F3)) USART CR2 register clock bits clear Mask ((~(uint16_t)0xF0FF))
Definition at line 101 of file stm32f4xx_usart.c.
CR2_CLOCK_CLEAR_MASK
#define CR2_CLOCK_CLEAR_MASK
Value:
((uint16_t)(USART_CR2_CLKEN | USART_CR2_CPOL | \
                                              USART_CR2_CPHA | USART_CR2_LBCL))
USART CR3 register clear Mask ((~(uint16_t)0xFCFF))
Definition at line 106 of file stm32f4xx_usart.c.
CR3_CLEAR_MASK
#define CR3_CLEAR_MASK ((uint16_t)(USART_CR3_RTSE | USART_CR3_CTSE))
USART Interrupts mask
Definition at line 110 of file stm32f4xx_usart.c.
IT_MASK
#define IT_MASK ((uint16_t)0x001F)
Definition at line 113 of file stm32f4xx_usart.c.
Function Documentation
USART_ClearFlag()
void USART_ClearFlag (USART_TypeDef * USARTx, uint16_t USART_FLAG)
Clears the USARTx's pending flags.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_FLAG specifies the flag to clear. This parameter can be any combination of the following values:
USART_FLAG_CTS: CTS Change flag (not available for UART4 and UART5).
USART_FLAG_LBD: LIN Break detection flag.
USART_FLAG_TC: Transmission Complete flag.
USART_FLAG_RXNE: Receive data register not empty flag.
Note
PE (Parity error), FE (Framing error), NE (Noise error), ORE (OverRun error) and IDLE (Idle line detected) flags are cleared by software sequence: a read operation to USART_SR register (USART_GetFlagStatus()) followed by a read operation to USART_DR register (USART_ReceiveData()).
RXNE flag can be also cleared by a read to the USART_DR register (USART_ReceiveData()).
TC flag can be also cleared by software sequence: a read operation to USART_SR register (USART_GetFlagStatus()) followed by a write operation to USART_DR register (USART_SendData()).
TXE flag is cleared only by a write to the USART_DR register (USART_SendData()).
Return values
None
Definition at line 1321 of file stm32f4xx_usart.c.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_CLEAR_FLAG(USART_FLAG));
  /* The CTS flag is not available for UART4 and UART5 */
  if ((USART_FLAG & USART_FLAG_CTS) == USART_FLAG_CTS)
  {
    assert_param(IS_USART_1236_PERIPH(USARTx));
  }
       
  USARTx->SR = (uint16_t)~USART_FLAG;
}
USART_ClearITPendingBit()
void USART_ClearITPendingBit (USART_TypeDef * USARTx, uint16_t USART_IT)
Clears the USARTx's interrupt pending bits.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_IT specifies the interrupt pending bit to clear. This parameter can be one of the following values:
USART_IT_CTS: CTS change interrupt (not available for UART4 and UART5)
USART_IT_LBD: LIN Break detection interrupt
USART_IT_TC: Transmission complete interrupt.
USART_IT_RXNE: Receive Data register not empty interrupt.
Note
PE (Parity error), FE (Framing error), NE (Noise error), ORE (OverRun error) and IDLE (Idle line detected) pending bits are cleared by software sequence: a read operation to USART_SR register (USART_GetITStatus()) followed by a read operation to USART_DR register (USART_ReceiveData()).
RXNE pending bit can be also cleared by a read to the USART_DR register (USART_ReceiveData()).
TC pending bit can be also cleared by software sequence: a read operation to USART_SR register (USART_GetITStatus()) followed by a write operation to USART_DR register (USART_SendData()).
TXE pending bit is cleared only by a write to the USART_DR register (USART_SendData()).
Return values
None
Definition at line 1429 of file stm32f4xx_usart.c.
Referenced by main().
{
  uint16_t bitpos = 0x00, itmask = 0x00;
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_CLEAR_IT(USART_IT));
  /* The CTS interrupt is not available for UART4 and UART5 */
  if (USART_IT == USART_IT_CTS)
  {
    assert_param(IS_USART_1236_PERIPH(USARTx));
  }
    
  bitpos = USART_IT >> 0x08;
  itmask = ((uint16_t)0x01 << (uint16_t)bitpos);
  USARTx->SR = (uint16_t)~itmask;
}
USART_ClockInit()
void USART_ClockInit (USART_TypeDef * USARTx, USART_ClockInitTypeDef * USART_ClockInitStruct)
Initializes the USARTx peripheral Clock according to the specified parameters in the USART_ClockInitStruct .
Parameters
USARTx where x can be 1, 2, 3 or 6 to select the USART peripheral.
USART_ClockInitStruct pointer to a USART_ClockInitTypeDef structure that contains the configuration information for the specified USART peripheral.
Note
The Smart Card and Synchronous modes are not available for UART4 and UART5.
Return values
None
Definition at line 360 of file stm32f4xx_usart.c.
References USART_ClockInitTypeDef::USART_Clock, USART_ClockInitTypeDef::USART_CPHA, USART_ClockInitTypeDef::USART_CPOL, and USART_ClockInitTypeDef::USART_LastBit.
{
  uint32_t tmpreg = 0x00;
  /* Check the parameters */
  assert_param(IS_USART_1236_PERIPH(USARTx));
  assert_param(IS_USART_CLOCK(USART_ClockInitStruct->USART_Clock));
  assert_param(IS_USART_CPOL(USART_ClockInitStruct->USART_CPOL));
  assert_param(IS_USART_CPHA(USART_ClockInitStruct->USART_CPHA));
  assert_param(IS_USART_LASTBIT(USART_ClockInitStruct->USART_LastBit));
  
/*---------------------------- USART CR2 Configuration -----------------------*/
  tmpreg = USARTx->CR2;
  /* Clear CLKEN, CPOL, CPHA and LBCL bits */
  tmpreg &= (uint32_t)~((uint32_t)CR2_CLOCK_CLEAR_MASK);
  /* Configure the USART Clock, CPOL, CPHA and LastBit ------------*/
  /* Set CLKEN bit according to USART_Clock value */
  /* Set CPOL bit according to USART_CPOL value */
  /* Set CPHA bit according to USART_CPHA value */
  /* Set LBCL bit according to USART_LastBit value */
  tmpreg |= (uint32_t)USART_ClockInitStruct->USART_Clock | USART_ClockInitStruct->
      USART_CPOL |
                 USART_ClockInitStruct->USART_CPHA | USART_ClockInitStruct->
      USART_LastBit;
  /* Write to USART CR2 */
  USARTx->CR2 = (uint16_t)tmpreg;
}
USART_ClockStructInit()
void USART_ClockStructInit (USART_ClockInitTypeDef * USART_ClockInitStruct)
Fills each USART_ClockInitStruct member with its default value.
Parameters
USART_ClockInitStruct pointer to a USART_ClockInitTypeDef structure which will be initialized.
Return values
None
Definition at line 391 of file stm32f4xx_usart.c.
References USART_ClockInitTypeDef::USART_Clock, USART_ClockInitTypeDef::USART_CPHA, USART_ClockInitTypeDef::USART_CPOL, and USART_ClockInitTypeDef::USART_LastBit.
{
  /* USART_ClockInitStruct members default value */
  USART_ClockInitStruct->USART_Clock = USART_Clock_Disable;
  USART_ClockInitStruct->USART_CPOL = USART_CPOL_Low;
  USART_ClockInitStruct->USART_CPHA = USART_CPHA_1Edge;
  USART_ClockInitStruct->USART_LastBit = USART_LastBit_Disable;
}
USART_Cmd()
void USART_Cmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the specified USART peripheral.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
NewState new state of the USARTx peripheral. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 408 of file stm32f4xx_usart.c.
References DISABLE.
Referenced by USART_Config().
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the selected USART by setting the UE bit in the CR1 register */
    USARTx->CR1 |= USART_CR1_UE;
  }
  else
  {
    /* Disable the selected USART by clearing the UE bit in the CR1 register */
    USARTx->CR1 &= (uint16_t)~((uint16_t)USART_CR1_UE);
  }
}
USART_DeInit()
void USART_DeInit (USART_TypeDef * USARTx)
Deinitializes the USARTx peripheral registers to their default reset values.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
Return values
None
Definition at line 178 of file stm32f4xx_usart.c.
References DISABLE, ENABLE, RCC_APB1PeriphResetCmd(), and RCC_APB2PeriphResetCmd().
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  if (USARTx == USART1)
  {
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_USART1, ENABLE);
    RCC_APB2PeriphResetCmd(RCC_APB2Periph_USART1, DISABLE);
  }
  else if (USARTx == USART2)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_USART2, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_USART2, DISABLE);
  }
  else if (USARTx == USART3)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_USART3, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_USART3, DISABLE);
  }
  else if (USARTx == UART4)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_UART4, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_UART4, DISABLE);
  }
  else if (USARTx == UART5)
  {
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_UART5, ENABLE);
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_UART5, DISABLE);
  }
  else
  {
    if (USARTx == USART6)
    {
      RCC_APB2PeriphResetCmd(RCC_APB2Periph_USART6, ENABLE);
      RCC_APB2PeriphResetCmd(RCC_APB2Periph_USART6, DISABLE);
    }
  }
}
USART_DMACmd()
void USART_DMACmd (USART_TypeDef * USARTx, uint16_t USART_DMAReq, FunctionalState NewState)
Enables or disables the USART's DMA interface.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_DMAReq specifies the DMA request. This parameter can be any combination of the following values:
USART_DMAReq_Tx: USART DMA transmit request
USART_DMAReq_Rx: USART DMA receive request
NewState new state of the DMA Request sources. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1080 of file stm32f4xx_usart.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_DMAREQ(USART_DMAReq));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the DMA transfer for selected requests by setting the DMAT and/or
       DMAR bits in the USART CR3 register */
    USARTx->CR3 |= USART_DMAReq;
  }
  else
  {
    /* Disable the DMA transfer for selected requests by clearing the DMAT and/or
       DMAR bits in the USART CR3 register */
    USARTx->CR3 &= (uint16_t)~USART_DMAReq;
  }
}
USART_GetFlagStatus()
 FlagStatus USART_GetFlagStatus (USART_TypeDef * USARTx, uint16_t USART_FLAG)
Checks whether the specified USART flag is set or not.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_FLAG specifies the flag to check. This parameter can be one of the following values:
USART_FLAG_CTS: CTS Change flag (not available for UART4 and UART5)
USART_FLAG_LBD: LIN Break detection flag
USART_FLAG_TXE: Transmit data register empty flag
USART_FLAG_TC: Transmission Complete flag
USART_FLAG_RXNE: Receive data register not empty flag
USART_FLAG_IDLE: Idle Line detection flag
USART_FLAG_ORE: OverRun Error flag
USART_FLAG_NE: Noise Error flag
USART_FLAG_FE: Framing Error flag
USART_FLAG_PE: Parity Error flag
Return values
The new state of USART_FLAG (SET or RESET).
Definition at line 1272 of file stm32f4xx_usart.c.
References RESET.
Referenced by _fputc().
{
  FlagStatus bitstatus = RESET;
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_FLAG(USART_FLAG));
  /* The CTS flag is not available for UART4 and UART5 */
  if (USART_FLAG == USART_FLAG_CTS)
  {
    assert_param(IS_USART_1236_PERIPH(USARTx));
  }
    
  if ((USARTx->SR & USART_FLAG) != (uint16_t)RESET)
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  return bitstatus;
}
USART_GetITStatus()
 ITStatus USART_GetITStatus (USART_TypeDef * USARTx, uint16_t USART_IT)
Checks whether the specified USART interrupt has occurred or not.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_IT specifies the USART interrupt source to check. This parameter can be one of the following values:
USART_IT_CTS: CTS change interrupt (not available for UART4 and UART5)
USART_IT_LBD: LIN Break detection interrupt
USART_IT_TXE: Transmit Data Register empty interrupt
USART_IT_TC: Transmission complete interrupt
USART_IT_RXNE: Receive Data register not empty interrupt
USART_IT_IDLE: Idle line detection interrupt
USART_IT_ORE_RX : OverRun Error interrupt if the RXNEIE bit is set
USART_IT_ORE_ER : OverRun Error interrupt if the EIE bit is set
USART_IT_NE: Noise Error interrupt
USART_IT_FE: Framing Error interrupt
USART_IT_PE: Parity Error interrupt
Return values
The new state of USART_IT (SET or RESET).
Definition at line 1355 of file stm32f4xx_usart.c.
References RESET, and SET.
Referenced by main().
{
  uint32_t bitpos = 0x00, itmask = 0x00, usartreg = 0x00;
  ITStatus bitstatus = RESET;
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_GET_IT(USART_IT));
  /* The CTS interrupt is not available for UART4 and UART5 */
  if (USART_IT == USART_IT_CTS)
  {
    assert_param(IS_USART_1236_PERIPH(USARTx));
  }
    
  /* Get the USART register index */
  usartreg = (((uint8_t)USART_IT) >> 0x05);
  /* Get the interrupt position */
  itmask = USART_IT & IT_MASK;
  itmask = (uint32_t)0x01 << itmask;
  
  if (usartreg == 0x01) /* The IT is in CR1 register */
  {
    itmask &= USARTx->CR1;
  }
  else if (usartreg == 0x02) /* The IT is in CR2 register */
  {
    itmask &= USARTx->CR2;
  }
  else /* The IT is in CR3 register */
  {
    itmask &= USARTx->CR3;
  }
  
  bitpos = USART_IT >> 0x08;
  bitpos = (uint32_t)0x01 << bitpos;
  bitpos &= USARTx->SR;
  if ((itmask != (uint16_t)RESET)&&(bitpos != (uint16_t)RESET))
  {
    bitstatus = SET;
  }
  else
  {
    bitstatus = RESET;
  }
  
  return bitstatus;
}
USART_HalfDuplexCmd()
void USART_HalfDuplexCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's Half Duplex communication.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
NewState new state of the USART Communication. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 816 of file stm32f4xx_usart.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the Half-Duplex mode by setting the HDSEL bit in the CR3 register */
    USARTx->CR3 |= USART_CR3_HDSEL;
  }
  else
  {
    /* Disable the Half-Duplex mode by clearing the HDSEL bit in the CR3 register */
    USARTx->CR3 &= (uint16_t)~((uint16_t)USART_CR3_HDSEL);
  }
}
USART_Init()
void USART_Init (USART_TypeDef * USARTx, USART_InitTypeDef * USART_InitStruct)
Initializes the USARTx peripheral according to the specified parameters in the USART_InitStruct .
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_InitStruct pointer to a USART_InitTypeDef structure that contains the configuration information for the specified USART peripheral.
Return values
None
Definition at line 227 of file stm32f4xx_usart.c.
References RCC_ClocksTypeDef::PCLK1_Frequency, RCC_ClocksTypeDef::PCLK2_Frequency, RCC_GetClocksFreq(), USART_InitTypeDef::USART_HardwareFlowControl, USART_InitTypeDef::USART_Mode, USART_InitTypeDef::USART_Parity, USART_InitTypeDef::USART_StopBits, and USART_InitTypeDef::USART_WordLength.
Referenced by USART_Config().
{
  uint32_t tmpreg = 0x00, apbclock = 0x00;
  uint32_t integerdivider = 0x00;
  uint32_t fractionaldivider = 0x00;
  RCC_ClocksTypeDef RCC_ClocksStatus;
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_BAUDRATE(USART_InitStruct->USART_BaudRate));
  assert_param(IS_USART_WORD_LENGTH(USART_InitStruct->USART_WordLength));
  assert_param(IS_USART_STOPBITS(USART_InitStruct->USART_StopBits));
  assert_param(IS_USART_PARITY(USART_InitStruct->USART_Parity));
  assert_param(IS_USART_MODE(USART_InitStruct->USART_Mode));
  assert_param(IS_USART_HARDWARE_FLOW_CONTROL(USART_InitStruct->
      USART_HardwareFlowControl));
  /* The hardware flow control is available only for USART1, USART2, USART3 and USART6 */
  if (USART_InitStruct->USART_HardwareFlowControl !=
      USART_HardwareFlowControl_None)
  {
    assert_param(IS_USART_1236_PERIPH(USARTx));
  }
/*---------------------------- USART CR2 Configuration -----------------------*/
  tmpreg = USARTx->CR2;
  /* Clear STOP[13:12] bits */
  tmpreg &= (uint32_t)~((uint32_t)USART_CR2_STOP);
  /* Configure the USART Stop Bits, Clock, CPOL, CPHA and LastBit :
      Set STOP[13:12] bits according to USART_StopBits value */
  tmpreg |= (uint32_t)USART_InitStruct->USART_StopBits;
  
  /* Write to USART CR2 */
  USARTx->CR2 = (uint16_t)tmpreg;
/*---------------------------- USART CR1 Configuration -----------------------*/
  tmpreg = USARTx->CR1;
  /* Clear M, PCE, PS, TE and RE bits */
  tmpreg &= (uint32_t)~((uint32_t)CR1_CLEAR_MASK);
  /* Configure the USART Word Length, Parity and mode:
     Set the M bits according to USART_WordLength value
     Set PCE and PS bits according to USART_Parity value
     Set TE and RE bits according to USART_Mode value */
  tmpreg |= (uint32_t)USART_InitStruct->USART_WordLength | USART_InitStruct->
      USART_Parity |
            USART_InitStruct->USART_Mode;
  /* Write to USART CR1 */
  USARTx->CR1 = (uint16_t)tmpreg;
/*---------------------------- USART CR3 Configuration -----------------------*/
  tmpreg = USARTx->CR3;
  /* Clear CTSE and RTSE bits */
  tmpreg &= (uint32_t)~((uint32_t)CR3_CLEAR_MASK);
  /* Configure the USART HFC :
      Set CTSE and RTSE bits according to USART_HardwareFlowControl value */
  tmpreg |= USART_InitStruct->USART_HardwareFlowControl;
  /* Write to USART CR3 */
  USARTx->CR3 = (uint16_t)tmpreg;
/*---------------------------- USART BRR Configuration -----------------------*/
  /* Configure the USART Baud Rate */
  RCC_GetClocksFreq(&RCC_ClocksStatus);
  if ((USARTx == USART1) || (USARTx == USART6))
  {
    apbclock = RCC_ClocksStatus.PCLK2_Frequency;
  }
  else
  {
    apbclock = RCC_ClocksStatus.PCLK1_Frequency;
  }
  
  /* Determine the integer part */
  if ((USARTx->CR1 & USART_CR1_OVER8) != 0)
  {
    /* Integer part computing in case Oversampling mode is 8 Samples */
    integerdivider = ((25 * apbclock) / (2 * (USART_InitStruct->USART_BaudRate)));
  }
  else /* if ((USARTx->CR1 & USART_CR1_OVER8) == 0) */
  {
    /* Integer part computing in case Oversampling mode is 16 Samples */
    integerdivider = ((25 * apbclock) / (4 * (USART_InitStruct->USART_BaudRate)));
  }
  tmpreg = (integerdivider / 100) << 4;
  /* Determine the fractional part */
  fractionaldivider = integerdivider - (100 * (tmpreg >> 4));
  /* Implement the fractional part in the register */
  if ((USARTx->CR1 & USART_CR1_OVER8) != 0)
  {
    tmpreg |= ((((fractionaldivider * 8) + 50) / 100)) & ((uint8_t)0x07);
  }
  else /* if ((USARTx->CR1 & USART_CR1_OVER8) == 0) */
  {
    tmpreg |= ((((fractionaldivider * 16) + 50) / 100)) & ((uint8_t)0x0F);
  }
  
  /* Write to USART BRR register */
  USARTx->BRR = (uint16_t)tmpreg;
}
USART_IrDACmd()
void USART_IrDACmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's IrDA interface.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
NewState new state of the IrDA mode. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1034 of file stm32f4xx_usart.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
    
  if (NewState != DISABLE)
  {
    /* Enable the IrDA mode by setting the IREN bit in the CR3 register */
    USARTx->CR3 |= USART_CR3_IREN;
  }
  else
  {
    /* Disable the IrDA mode by clearing the IREN bit in the CR3 register */
    USARTx->CR3 &= (uint16_t)~((uint16_t)USART_CR3_IREN);
  }
}
USART_IrDAConfig()
void USART_IrDAConfig (USART_TypeDef * USARTx, uint16_t USART_IrDAMode)
Configures the USART's IrDA interface.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_IrDAMode specifies the IrDA mode. This parameter can be one of the following values:
USART_IrDAMode_LowPower
USART_IrDAMode_Normal
Return values
None
Definition at line 1016 of file stm32f4xx_usart.c.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_IRDA_MODE(USART_IrDAMode));
    
  USARTx->CR3 &= (uint16_t)~((uint16_t)USART_CR3_IRLP);
  USARTx->CR3 |= USART_IrDAMode;
}
USART_ITConfig()
void USART_ITConfig (USART_TypeDef * USARTx, uint16_t USART_IT, FunctionalState NewState)
Enables or disables the specified USART interrupts.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_IT specifies the USART interrupt sources to be enabled or disabled. This parameter can be one of the following values:
USART_IT_CTS: CTS change interrupt
USART_IT_LBD: LIN Break detection interrupt
USART_IT_TXE: Transmit Data Register empty interrupt
USART_IT_TC: Transmission complete interrupt
USART_IT_RXNE: Receive Data register not empty interrupt
USART_IT_IDLE: Idle line detection interrupt
USART_IT_PE: Parity Error interrupt
USART_IT_ERR: Error interrupt(Frame error, noise error, overrun error)
NewState new state of the specified USARTx interrupts. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1208 of file stm32f4xx_usart.c.
References DISABLE.
Referenced by USART_Config().
{
  uint32_t usartreg = 0x00, itpos = 0x00, itmask = 0x00;
  uint32_t usartxbase = 0x00;
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_CONFIG_IT(USART_IT));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  /* The CTS interrupt is not available for UART4 and UART5 */
  if (USART_IT == USART_IT_CTS)
  {
    assert_param(IS_USART_1236_PERIPH(USARTx));
  }
    
  usartxbase = (uint32_t)USARTx;
  /* Get the USART register index */
  usartreg = (((uint8_t)USART_IT) >> 0x05);
  /* Get the interrupt position */
  itpos = USART_IT & IT_MASK;
  itmask = (((uint32_t)0x01) << itpos);
    
  if (usartreg == 0x01) /* The IT is in CR1 register */
  {
    usartxbase += 0x0C;
  }
  else if (usartreg == 0x02) /* The IT is in CR2 register */
  {
    usartxbase += 0x10;
  }
  else /* The IT is in CR3 register */
  {
    usartxbase += 0x14;
  }
  if (NewState != DISABLE)
  {
    *(__IO uint32_t*)usartxbase |= itmask;
  }
  else
  {
    *(__IO uint32_t*)usartxbase &= ~itmask;
  }
}
USART_LINBreakDetectLengthConfig()
void USART_LINBreakDetectLengthConfig (USART_TypeDef * USARTx, uint16_t USART_LINBreakDetectLength)
Sets the USART LIN Break detection length.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_LINBreakDetectLength specifies the LIN break detection length. This parameter can be one of the following values:
USART_LINBreakDetectLength_10b: 10-bit break detection
USART_LINBreakDetectLength_11b: 11-bit break detection
Return values
None
Definition at line 721 of file stm32f4xx_usart.c.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_LIN_BREAK_DETECT_LENGTH(USART_LINBreakDetectLength));
  
  USARTx->CR2 &= (uint16_t)~((uint16_t)USART_CR2_LBDL);
  USARTx->CR2 |= USART_LINBreakDetectLength;
}
USART_LINCmd()
void USART_LINCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's LIN mode.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
NewState new state of the USART LIN mode. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 739 of file stm32f4xx_usart.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the LIN mode by setting the LINEN bit in the CR2 register */
    USARTx->CR2 |= USART_CR2_LINEN;
  }
  else
  {
    /* Disable the LIN mode by clearing the LINEN bit in the CR2 register */
    USARTx->CR2 &= (uint16_t)~((uint16_t)USART_CR2_LINEN);
  }
}
USART_OneBitMethodCmd()
void USART_OneBitMethodCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's one bit sampling method.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
NewState new state of the USART one bit sampling method. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 481 of file stm32f4xx_usart.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the one bit method by setting the ONEBITE bit in the CR3 register */
    USARTx->CR3 |= USART_CR3_ONEBIT;
  }
  else
  {
    /* Disable the one bit method by clearing the ONEBITE bit in the CR3 register */
    USARTx->CR3 &= (uint16_t)~((uint16_t)USART_CR3_ONEBIT);
  }
}
USART_OverSampling8Cmd()
void USART_OverSampling8Cmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's 8x oversampling mode.
Note
This function has to be called before calling USART_Init() function in order to have correct baudrate Divider value.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
NewState new state of the USART 8x oversampling mode. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 455 of file stm32f4xx_usart.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the 8x Oversampling mode by setting the OVER8 bit in the CR1 register */
    USARTx->CR1 |= USART_CR1_OVER8;
  }
  else
  {
    /* Disable the 8x Oversampling mode by clearing the OVER8 bit in the CR1 register */
    USARTx->CR1 &= (uint16_t)~((uint16_t)USART_CR1_OVER8);
  }
}
USART_ReceiveData()
uint16_t USART_ReceiveData (USART_TypeDef * USARTx)
Returns the most recent received data by the USARTx peripheral.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
Return values
The received data.
Definition at line 554 of file stm32f4xx_usart.c.
Referenced by handle_input().
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  
  /* Receive Data */
  return (uint16_t)(USARTx->DR & (uint16_t)0x01FF);
}
USART_ReceiverWakeUpCmd()
void USART_ReceiverWakeUpCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Determines if the USART is in mute mode or not.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
NewState new state of the USART mute mode. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 625 of file stm32f4xx_usart.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  
  if (NewState != DISABLE)
  {
    /* Enable the USART mute mode by setting the RWU bit in the CR1 register */
    USARTx->CR1 |= USART_CR1_RWU;
  }
  else
  {
    /* Disable the USART mute mode by clearing the RWU bit in the CR1 register */
    USARTx->CR1 &= (uint16_t)~((uint16_t)USART_CR1_RWU);
  }
}
USART_SendBreak()
void USART_SendBreak (USART_TypeDef * USARTx)
Transmits break characters.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
Return values
None
Definition at line 763 of file stm32f4xx_usart.c.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  
  /* Send break characters */
  USARTx->CR1 |= USART_CR1_SBK;
}
USART_SendData()
void USART_SendData (USART_TypeDef * USARTx, uint16_t Data)
Transmits single data through the USARTx peripheral.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
Data the data to transmit.
Return values
None
Definition at line 538 of file stm32f4xx_usart.c.
Referenced by _fputc().
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_DATA(Data));
    
  /* Transmit Data */
  USARTx->DR = (Data & (uint16_t)0x01FF);
}
USART_SetAddress()
void USART_SetAddress (USART_TypeDef * USARTx, uint8_t USART_Address)
Sets the address of the USART node.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_Address Indicates the address of the USART node.
Return values
None
Definition at line 605 of file stm32f4xx_usart.c.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_ADDRESS(USART_Address));
    
  /* Clear the USART address */
  USARTx->CR2 &= (uint16_t)~((uint16_t)USART_CR2_ADD);
  /* Set the USART address node */
  USARTx->CR2 |= USART_Address;
}
USART_SetGuardTime()
void USART_SetGuardTime (USART_TypeDef * USARTx, uint8_t USART_GuardTime)
Sets the specified USART guard time.
Parameters
USARTx where x can be 1, 2, 3 or 6 to select the USART or UART peripheral.
USART_GuardTime specifies the guard time.
Return values
None
Definition at line 901 of file stm32f4xx_usart.c.
{
  /* Check the parameters */
  assert_param(IS_USART_1236_PERIPH(USARTx));
  
  /* Clear the USART Guard time */
  USARTx->GTPR &= USART_GTPR_PSC;
  /* Set the USART guard time */
  USARTx->GTPR |= (uint16_t)((uint16_t)USART_GuardTime << 0x08);
}
USART_SetPrescaler()
void USART_SetPrescaler (USART_TypeDef * USARTx, uint8_t USART_Prescaler)
Sets the system clock prescaler.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_Prescaler specifies the prescaler clock.
Note
The function is used for IrDA mode with UART4 and UART5.
Return values
None
Definition at line 434 of file stm32f4xx_usart.c.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  
  /* Clear the USART prescaler */
  USARTx->GTPR &= USART_GTPR_GT;
  /* Set the USART prescaler */
  USARTx->GTPR |= USART_Prescaler;
}
USART_SmartCardCmd()
void USART_SmartCardCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables the USART's Smart Card mode.
Parameters
USARTx where x can be 1, 2, 3 or 6 to select the USART or UART peripheral.
NewState new state of the Smart Card mode. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 920 of file stm32f4xx_usart.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_USART_1236_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the SC mode by setting the SCEN bit in the CR3 register */
    USARTx->CR3 |= USART_CR3_SCEN;
  }
  else
  {
    /* Disable the SC mode by clearing the SCEN bit in the CR3 register */
    USARTx->CR3 &= (uint16_t)~((uint16_t)USART_CR3_SCEN);
  }
}
USART_SmartCardNACKCmd()
void USART_SmartCardNACKCmd (USART_TypeDef * USARTx, FunctionalState NewState)
Enables or disables NACK transmission.
Parameters
USARTx where x can be 1, 2, 3 or 6 to select the USART or UART peripheral.
NewState new state of the NACK transmission. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 945 of file stm32f4xx_usart.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_USART_1236_PERIPH(USARTx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the NACK transmission by setting the NACK bit in the CR3 register */
    USARTx->CR3 |= USART_CR3_NACK;
  }
  else
  {
    /* Disable the NACK transmission by clearing the NACK bit in the CR3 register */
    USARTx->CR3 &= (uint16_t)~((uint16_t)USART_CR3_NACK);
  }
}
USART_StructInit()
void USART_StructInit (USART_InitTypeDef * USART_InitStruct)
Fills each USART_InitStruct member with its default value.
Parameters
USART_InitStruct pointer to a USART_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 340 of file stm32f4xx_usart.c.
References USART_InitTypeDef::USART_BaudRate, USART_InitTypeDef::USART_HardwareFlowControl, USART_InitTypeDef::USART_Mode, USART_InitTypeDef::USART_Parity, USART_InitTypeDef::USART_StopBits, and USART_InitTypeDef::USART_WordLength.
{
  /* USART_InitStruct members default value */
  USART_InitStruct->USART_BaudRate = 9600;
  USART_InitStruct->USART_WordLength = USART_WordLength_8b;
  USART_InitStruct->USART_StopBits = USART_StopBits_1;
  USART_InitStruct->USART_Parity = USART_Parity_No ;
  USART_InitStruct->USART_Mode = USART_Mode_Rx | USART_Mode_Tx;
  USART_InitStruct->USART_HardwareFlowControl = USART_HardwareFlowControl_None;
}
USART_WakeUpConfig()
void USART_WakeUpConfig (USART_TypeDef * USARTx, uint16_t USART_WakeUp)
Selects the USART WakeUp method.
Parameters
USARTx where x can be 1, 2, 3, 4, 5 or 6 to select the USART or UART peripheral.
USART_WakeUp specifies the USART wakeup method. This parameter can be one of the following values:
USART_WakeUp_IdleLine: WakeUp by an idle line detection
USART_WakeUp_AddressMark: WakeUp by an address mark
Return values
None
Definition at line 652 of file stm32f4xx_usart.c.
{
  /* Check the parameters */
  assert_param(IS_USART_ALL_PERIPH(USARTx));
  assert_param(IS_USART_WAKEUP(USART_WakeUp));
  
  USARTx->CR1 &= (uint16_t)~((uint16_t)USART_CR1_WAKE);
  USARTx->CR1 |= USART_WakeUp;
}