HASH
HASH driver modules.
Modules
 HASH_Exported_Constants
 HASH_Private_Functions
Classes
struct HASH_InitTypeDef
HASH Init structure definition.
struct HASH_MsgDigest
HASH message digest result structure definition.
struct HASH_Context
HASH context swapping structure definition.
Macros
#define MD5BUSY_TIMEOUT ((uint32_t) 0x00010000)
#define SHA1BUSY_TIMEOUT ((uint32_t) 0x00010000)
Functions
void HASH_DeInit (void)
Deinitializes the HASH peripheral registers to their default reset values.
void HASH_Init (HASH_InitTypeDef *HASH_InitStruct)
Initializes the HASH peripheral according to the specified parameters in the HASH_InitStruct structure.
void HASH_StructInit (HASH_InitTypeDef *HASH_InitStruct)
Fills each HASH_InitStruct member with its default value.
void HASH_Reset (void)
Resets the HASH processor core, so that the HASH will be ready to compute the message digest of a new message.
void HASH_DataIn (uint32_t Data)
Writes data in the Data Input FIFO.
uint8_t HASH_GetInFIFOWordsNbr (void)
Returns the number of words already pushed into the IN FIFO.
void HASH_SetLastWordValidBitsNbr (uint16_t ValidNumber)
Configure the Number of valid bits in last word of the message.
void HASH_StartDigest (void)
Starts the message padding and calculation of the final message.
void HASH_GetDigest (HASH_MsgDigest *HASH_MessageDigest)
Provides the message digest result.
void HASH_SaveContext (HASH_Context *HASH_ContextSave)
Save the Hash peripheral Context.
void HASH_RestoreContext (HASH_Context *HASH_ContextRestore)
Restore the Hash peripheral Context.
void HASH_DMACmd (FunctionalState NewState)
Enables or disables the HASH DMA interface.
void HASH_ITConfig (uint8_t HASH_IT, FunctionalState NewState)
Enables or disables the specified HASH interrupts.
 FlagStatus HASH_GetFlagStatus (uint16_t HASH_FLAG)
Checks whether the specified HASH flag is set or not.
void HASH_ClearFlag (uint16_t HASH_FLAG)
Clears the HASH flags.
 ITStatus HASH_GetITStatus (uint8_t HASH_IT)
Checks whether the specified HASH interrupt has occurred or not.
void HASH_ClearITPendingBit (uint8_t HASH_IT)
Clears the HASH interrupt pending bit(s).
 ErrorStatus HASH_SHA1 (uint8_t *Input, uint32_t Ilen, uint8_t Output[20])
Compute the HASH SHA1 digest.
 ErrorStatus HMAC_SHA1 (uint8_t *Key, uint32_t Keylen, uint8_t *Input, uint32_t Ilen, uint8_t Output[20])
Compute the HMAC SHA1 digest.
 ErrorStatus HASH_MD5 (uint8_t *Input, uint32_t Ilen, uint8_t Output[16])
Compute the HASH MD5 digest.
 ErrorStatus HMAC_MD5 (uint8_t *Key, uint32_t Keylen, uint8_t *Input, uint32_t Ilen, uint8_t Output[16])
Compute the HMAC MD5 digest.
Detailed Description
HASH driver modules.
Macro Definition Documentation
MD5BUSY_TIMEOUT
#define MD5BUSY_TIMEOUT ((uint32_t) 0x00010000)
Definition at line 54 of file stm32f4xx_hash_md5.c.
SHA1BUSY_TIMEOUT
#define SHA1BUSY_TIMEOUT ((uint32_t) 0x00010000)
Definition at line 54 of file stm32f4xx_hash_sha1.c.
Function Documentation
HASH_ClearFlag()
void HASH_ClearFlag (uint16_t HASH_FLAG)
Clears the HASH flags.
Parameters
HASH_FLAG specifies the flag to clear. This parameter can be any combination of the following values:
HASH_FLAG_DINIS: Data Input Flag
HASH_FLAG_DCIS: Digest Calculation Completion Flag
Return values
None
Definition at line 625 of file stm32f4xx_hash.c.
{
  /* Check the parameters */
  assert_param(IS_HASH_CLEAR_FLAG(HASH_FLAG));
  
  /* Clear the selected HASH flags */
  HASH->SR = ~(uint32_t)HASH_FLAG;
}
HASH_ClearITPendingBit()
void HASH_ClearITPendingBit (uint8_t HASH_IT)
Clears the HASH interrupt pending bit(s).
Parameters
HASH_IT specifies the HASH interrupt pending bit(s) to clear. This parameter can be any combination of the following values:
HASH_IT_DINI: Data Input interrupt
HASH_IT_DCI: Digest Calculation Completion Interrupt
Return values
None
Definition at line 675 of file stm32f4xx_hash.c.
{
  /* Check the parameters */
  assert_param(IS_HASH_IT(HASH_IT));
  /* Clear the selected HASH interrupt pending bit */
  HASH->SR = (uint8_t)~HASH_IT;
}
HASH_DataIn()
void HASH_DataIn (uint32_t Data)
Writes data in the Data Input FIFO.
Parameters
Data new data of the message to be processed.
Return values
None
Definition at line 306 of file stm32f4xx_hash.c.
{
  /* Write in the DIN register a new data */
  HASH->DIN = Data;
}
HASH_DeInit()
void HASH_DeInit (void)
Deinitializes the HASH peripheral registers to their default reset values.
Parameters
None
Return values
None
Definition at line 171 of file stm32f4xx_hash.c.
References DISABLE, ENABLE, and RCC_AHB2PeriphResetCmd().
Referenced by HASH_MD5(), HASH_SHA1(), HMAC_MD5(), and HMAC_SHA1().
{
  /* Enable HASH reset state */
  RCC_AHB2PeriphResetCmd(RCC_AHB2Periph_HASH, ENABLE);
  /* Release HASH from reset state */
  RCC_AHB2PeriphResetCmd(RCC_AHB2Periph_HASH, DISABLE);
}
HASH_DMACmd()
void HASH_DMACmd (FunctionalState NewState)
Enables or disables the HASH DMA interface.
Note
The DMA is disabled by hardware after the end of transfer.
Parameters
NewState new state of the selected HASH DMA transfer request. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 460 of file stm32f4xx_hash.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the HASH DMA request */
    HASH->CR |= HASH_CR_DMAE;
  }
  else
  {
    /* Disable the HASH DMA request */
    HASH->CR &= ~HASH_CR_DMAE;
  }
}
HASH_GetDigest()
void HASH_GetDigest (HASH_MsgDigest * HASH_MessageDigest)
Provides the message digest result.
Note
In MD5 mode, Data[4] filed of HASH_MsgDigest structure is not used and is read as zero.
Parameters
HASH_MessageDigest pointer to a HASH_MsgDigest structure which will hold the message digest result
Return values
None
Definition at line 331 of file stm32f4xx_hash.c.
{
  /* Get the data field */
  HASH_MessageDigest->Data[0] = HASH->HR[0];
  HASH_MessageDigest->Data[1] = HASH->HR[1];
  HASH_MessageDigest->Data[2] = HASH->HR[2];
  HASH_MessageDigest->Data[3] = HASH->HR[3];
  HASH_MessageDigest->Data[4] = HASH->HR[4];
}
HASH_GetFlagStatus()
 FlagStatus HASH_GetFlagStatus (uint16_t HASH_FLAG)
Checks whether the specified HASH flag is set or not.
Parameters
HASH_FLAG specifies the HASH flag to check. This parameter can be one of the following values:
HASH_FLAG_DINIS: Data input interrupt status flag
HASH_FLAG_DCIS: Digest calculation completion interrupt status flag
HASH_FLAG_BUSY: Busy flag
HASH_FLAG_DMAS: DMAS Status flag
HASH_FLAG_DINNE: Data Input register (DIN) not empty status flag
Return values
The new state of HASH_FLAG (SET or RESET)
Definition at line 584 of file stm32f4xx_hash.c.
References RESET, and SET.
{
  FlagStatus bitstatus = RESET;
  uint32_t tempreg = 0;
  /* Check the parameters */
  assert_param(IS_HASH_GET_FLAG(HASH_FLAG));
  /* check if the FLAG is in CR register */
  if ((HASH_FLAG & HASH_FLAG_DINNE) != (uint16_t)RESET)
  {
    tempreg = HASH->CR;
  }
  else /* The FLAG is in SR register */
  {
    tempreg = HASH->SR;
  }
  /* Check the status of the specified HASH flag */
  if ((tempreg & HASH_FLAG) != (uint16_t)RESET)
  {
    /* HASH is set */
    bitstatus = SET;
  }
  else
  {
    /* HASH_FLAG is reset */
    bitstatus = RESET;
  }
  /* Return the HASH_FLAG status */
  return bitstatus;
}
HASH_GetInFIFOWordsNbr()
uint8_t HASH_GetInFIFOWordsNbr (void)
Returns the number of words already pushed into the IN FIFO.
Parameters
None
Return values
The value of words already pushed into the IN FIFO.
Definition at line 317 of file stm32f4xx_hash.c.
{
  /* Return the value of NBW bits */
  return ((HASH->CR & HASH_CR_NBW) >> 8);
}
HASH_GetITStatus()
 ITStatus HASH_GetITStatus (uint8_t HASH_IT)
Checks whether the specified HASH interrupt has occurred or not.
Parameters
HASH_IT specifies the HASH interrupt source to check. This parameter can be one of the following values:
HASH_IT_DINI: Data Input interrupt
HASH_IT_DCI: Digest Calculation Completion Interrupt
Return values
The new state of HASH_IT (SET or RESET).
Definition at line 641 of file stm32f4xx_hash.c.
References RESET.
{
  ITStatus bitstatus = RESET;
  uint32_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_HASH_GET_IT(HASH_IT));
  /* Check the status of the specified HASH interrupt */
  tmpreg = HASH->SR;
  if (((HASH->IMR & tmpreg) & HASH_IT) != RESET)
  {
    /* HASH_IT is set */
    bitstatus = SET;
  }
  else
  {
    /* HASH_IT is reset */
    bitstatus = RESET;
  }
  /* Return the HASH_IT status */
  return bitstatus;
}
HASH_Init()
void HASH_Init (HASH_InitTypeDef * HASH_InitStruct)
Initializes the HASH peripheral according to the specified parameters in the HASH_InitStruct structure.
Note
the hash processor is reset when calling this function so that the HASH will be ready to compute the message digest of a new message. There is no need to call HASH_Reset() function.
Parameters
HASH_InitStruct pointer to a HASH_InitTypeDef structure that contains the configuration information for the HASH peripheral.
Note
The field HASH_HMACKeyType in HASH_InitTypeDef must be filled only if the algorithm mode is HMAC.
Return values
None
Definition at line 191 of file stm32f4xx_hash.c.
References HASH_InitTypeDef::HASH_AlgoMode.
Referenced by HASH_MD5(), HASH_SHA1(), HMAC_MD5(), and HMAC_SHA1().
{
  /* Check the parameters */
  assert_param(IS_HASH_ALGOSELECTION(HASH_InitStruct->HASH_AlgoSelection));
  assert_param(IS_HASH_DATATYPE(HASH_InitStruct->HASH_DataType));
  assert_param(IS_HASH_ALGOMODE(HASH_InitStruct->HASH_AlgoMode));
  
  /* Configure the Algorithm used, algorithm mode and the datatype */
  HASH->CR &= ~ (HASH_CR_ALGO | HASH_CR_DATATYPE | HASH_CR_MODE);
  HASH->CR |= (HASH_InitStruct->HASH_AlgoSelection | \
               HASH_InitStruct->HASH_DataType | \
               HASH_InitStruct->HASH_AlgoMode);
  
  /* if algorithm mode is HMAC, set the Key */
  if(HASH_InitStruct->HASH_AlgoMode == HASH_AlgoMode_HMAC)
  {
    assert_param(IS_HASH_HMAC_KEYTYPE(HASH_InitStruct->HASH_HMACKeyType));
    HASH->CR &= ~HASH_CR_LKEY;
    HASH->CR |= HASH_InitStruct->HASH_HMACKeyType;
  }
  /* Reset the HASH processor core, so that the HASH will be ready to compute
     the message digest of a new message */
  HASH->CR |= HASH_CR_INIT;
}
HASH_ITConfig()
void HASH_ITConfig (uint8_t HASH_IT, FunctionalState NewState)
Enables or disables the specified HASH interrupts.
Parameters
HASH_IT specifies the HASH interrupt source to be enabled or disabled. This parameter can be any combination of the following values:
HASH_IT_DINI: Data Input interrupt
HASH_IT_DCI: Digest Calculation Completion Interrupt
NewState new state of the specified HASH interrupt. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 555 of file stm32f4xx_hash.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_HASH_IT(HASH_IT));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the selected HASH interrupt */
    HASH->IMR |= HASH_IT;
  }
  else
  {
    /* Disable the selected HASH interrupt */
    HASH->IMR &= (uint8_t) ~HASH_IT;
  }
}
HASH_MD5()
 ErrorStatus HASH_MD5 (uint8_t * Input, uint32_t Ilen, uint8_t Output[16])
Compute the HASH MD5 digest.
Parameters
Input pointer to the Input buffer to be treated.
Ilen length of the Input buffer.
Output the returned digest
Return values
An ErrorStatus enumeration value:
SUCCESS: digest computation done
ERROR: digest computation failed
Definition at line 87 of file stm32f4xx_hash_md5.c.
References HASH_DeInit(), HASH_Init(), HASH_StartDigest(), and SUCCESS.
{
  HASH_InitTypeDef MD5_HASH_InitStructure;
  HASH_MsgDigest MD5_MessageDigest;
  __IO uint16_t nbvalidbitsdata = 0;
  uint32_t i = 0;
  __IO uint32_t counter = 0;
  uint32_t busystatus = 0;
  ErrorStatus status = SUCCESS;
  uint32_t inputaddr = (uint32_t)Input;
  uint32_t outputaddr = (uint32_t)Output;
  /* Number of valid bits in last word of the Input data */
  nbvalidbitsdata = 8 * (Ilen % 4);
  /* HASH peripheral initialization */
  HASH_DeInit();
  /* HASH Configuration */
  MD5_HASH_InitStructure.HASH_AlgoSelection = HASH_AlgoSelection_MD5;
  MD5_HASH_InitStructure.HASH_AlgoMode = HASH_AlgoMode_HASH;
  MD5_HASH_InitStructure.HASH_DataType = HASH_DataType_8b;
  HASH_Init(&MD5_HASH_InitStructure);
  /* Configure the number of valid bits in last word of the data */
  HASH_SetLastWordValidBitsNbr(nbvalidbitsdata);
  /* Write the Input block in the IN FIFO */
  for(i=0; i<Ilen; i+=4)
  {
    HASH_DataIn(*(uint32_t*)inputaddr);
    inputaddr+=4;
  }
  /* Start the HASH processor */
  HASH_StartDigest();
  /* wait until the Busy flag is RESET */
  do
  {
    busystatus = HASH_GetFlagStatus(HASH_FLAG_BUSY);
    counter++;
  }while ((counter != MD5BUSY_TIMEOUT) && (busystatus != RESET));
  if (busystatus != RESET)
  {
     status = ERROR;
  }
  else
  {
    /* Read the message digest */
    HASH_GetDigest(&MD5_MessageDigest);
    *(uint32_t*)(outputaddr) = __REV(MD5_MessageDigest.Data[0]);
    outputaddr+=4;
    *(uint32_t*)(outputaddr) = __REV(MD5_MessageDigest.Data[1]);
    outputaddr+=4;
    *(uint32_t*)(outputaddr) = __REV(MD5_MessageDigest.Data[2]);
    outputaddr+=4;
    *(uint32_t*)(outputaddr) = __REV(MD5_MessageDigest.Data[3]);
  }
  return status;
}
HASH_Reset()
void HASH_Reset (void)
Resets the HASH processor core, so that the HASH will be ready to compute the message digest of a new message.
Note
Calling this function will clear the HASH_SR_DCIS (Digest calculation completion interrupt status) bit corresponding to HASH_IT_DCI interrupt and HASH_FLAG_DCIS flag.
Parameters
None
Return values
None
Definition at line 249 of file stm32f4xx_hash.c.
{
  /* Reset the HASH processor core */
  HASH->CR |= HASH_CR_INIT;
}
HASH_RestoreContext()
void HASH_RestoreContext (HASH_Context * HASH_ContextRestore)
Restore the Hash peripheral Context.
Note
After calling this function, user can restart the processing from the point where it has been interrupted.
Parameters
HASH_ContextRestore pointer to a HASH_Context structure that contains the repository for saved context.
Return values
None
Definition at line 411 of file stm32f4xx_hash.c.
{
  uint8_t i = 0;
  
  /* restore context registers */
  HASH->IMR = HASH_ContextRestore->HASH_IMR;
  HASH->STR = HASH_ContextRestore->HASH_STR;
  HASH->CR = HASH_ContextRestore->HASH_CR;
  
  /* Initialize the hash processor */
  HASH->CR |= HASH_CR_INIT;
  
   /* continue restoring context registers */
  for(i=0; i<=50;i++)
  {
     HASH->CSR[i] = HASH_ContextRestore->HASH_CSR[i];
  }
}
HASH_SaveContext()
void HASH_SaveContext (HASH_Context * HASH_ContextSave)
Save the Hash peripheral Context.
Note
The context can be saved only when no block is currently being processed. So user must wait for DINIS = 1 (the last block has been processed and the input FIFO is empty) or NBW != 0 (the FIFO is not full and no processing is ongoing).
Parameters
HASH_ContextSave pointer to a HASH_Context structure that contains the repository for current context.
Return values
None
Definition at line 389 of file stm32f4xx_hash.c.
{
  uint8_t i = 0;
  
  /* save context registers */
  HASH_ContextSave->HASH_IMR = HASH->IMR;
  HASH_ContextSave->HASH_STR = HASH->STR;
  HASH_ContextSave->HASH_CR = HASH->CR;
  for(i=0; i<=50;i++)
  {
     HASH_ContextSave->HASH_CSR[i] = HASH->CSR[i];
  }
}
HASH_SetLastWordValidBitsNbr()
void HASH_SetLastWordValidBitsNbr (uint16_t ValidNumber)
Configure the Number of valid bits in last word of the message.
Parameters
ValidNumber Number of valid bits in last word of the message. This parameter must be a number between 0 and 0x1F.
0x00: All 32 bits of the last data written are valid
0x01: Only bit [0] of the last data written is valid
0x02: Only bits[1:0] of the last data written are valid
0x03: Only bits[2:0] of the last data written are valid
...
0x1F: Only bits[30:0] of the last data written are valid
Note
The Number of valid bits must be set before to start the message digest competition (in Hash and HMAC) and key treatment(in HMAC).
Return values
None
Definition at line 291 of file stm32f4xx_hash.c.
{
  /* Check the parameters */
  assert_param(IS_HASH_VALIDBITSNUMBER(ValidNumber));
  
  /* Configure the Number of valid bits in last word of the message */
  HASH->STR &= ~(HASH_STR_NBW);
  HASH->STR |= ValidNumber;
}
HASH_SHA1()
 ErrorStatus HASH_SHA1 (uint8_t * Input, uint32_t Ilen, uint8_t Output[20])
Compute the HASH SHA1 digest.
Parameters
Input pointer to the Input buffer to be treated.
Ilen length of the Input buffer.
Output the returned digest
Return values
An ErrorStatus enumeration value:
SUCCESS: digest computation done
ERROR: digest computation failed
Definition at line 87 of file stm32f4xx_hash_sha1.c.
References HASH_DeInit(), HASH_Init(), HASH_StartDigest(), and SUCCESS.
{
  HASH_InitTypeDef SHA1_HASH_InitStructure;
  HASH_MsgDigest SHA1_MessageDigest;
  __IO uint16_t nbvalidbitsdata = 0;
  uint32_t i = 0;
  __IO uint32_t counter = 0;
  uint32_t busystatus = 0;
  ErrorStatus status = SUCCESS;
  uint32_t inputaddr = (uint32_t)Input;
  uint32_t outputaddr = (uint32_t)Output;
  /* Number of valid bits in last word of the Input data */
  nbvalidbitsdata = 8 * (Ilen % 4);
  /* HASH peripheral initialization */
  HASH_DeInit();
  /* HASH Configuration */
  SHA1_HASH_InitStructure.HASH_AlgoSelection = HASH_AlgoSelection_SHA1;
  SHA1_HASH_InitStructure.HASH_AlgoMode = HASH_AlgoMode_HASH;
  SHA1_HASH_InitStructure.HASH_DataType = HASH_DataType_8b;
  HASH_Init(&SHA1_HASH_InitStructure);
  /* Configure the number of valid bits in last word of the data */
  HASH_SetLastWordValidBitsNbr(nbvalidbitsdata);
  /* Write the Input block in the IN FIFO */
  for(i=0; i<Ilen; i+=4)
  {
    HASH_DataIn(*(uint32_t*)inputaddr);
    inputaddr+=4;
  }
  /* Start the HASH processor */
  HASH_StartDigest();
  /* wait until the Busy flag is RESET */
  do
  {
    busystatus = HASH_GetFlagStatus(HASH_FLAG_BUSY);
    counter++;
  }while ((counter != SHA1BUSY_TIMEOUT) && (busystatus != RESET));
  if (busystatus != RESET)
  {
     status = ERROR;
  }
  else
  {
    /* Read the message digest */
    HASH_GetDigest(&SHA1_MessageDigest);
    *(uint32_t*)(outputaddr) = __REV(SHA1_MessageDigest.Data[0]);
    outputaddr+=4;
    *(uint32_t*)(outputaddr) = __REV(SHA1_MessageDigest.Data[1]);
    outputaddr+=4;
    *(uint32_t*)(outputaddr) = __REV(SHA1_MessageDigest.Data[2]);
    outputaddr+=4;
    *(uint32_t*)(outputaddr) = __REV(SHA1_MessageDigest.Data[3]);
    outputaddr+=4;
    *(uint32_t*)(outputaddr) = __REV(SHA1_MessageDigest.Data[4]);
  }
  return status;
}
HASH_StartDigest()
void HASH_StartDigest (void)
Starts the message padding and calculation of the final message.
Parameters
None
Return values
None
Definition at line 346 of file stm32f4xx_hash.c.
Referenced by HASH_MD5(), HASH_SHA1(), HMAC_MD5(), and HMAC_SHA1().
{
  /* Start the Digest calculation */
  HASH->STR |= HASH_STR_DCAL;
}
HASH_StructInit()
void HASH_StructInit (HASH_InitTypeDef * HASH_InitStruct)
Fills each HASH_InitStruct member with its default value.
Parameters
HASH_InitStruct : pointer to a HASH_InitTypeDef structure which will be initialized.
Note
The default values set are : Processor mode is HASH, Algorithm selected is SHA1, Data type selected is 32b and HMAC Key Type is short key.
Return values
None
Definition at line 225 of file stm32f4xx_hash.c.
References HASH_InitTypeDef::HASH_AlgoMode, HASH_InitTypeDef::HASH_AlgoSelection, HASH_InitTypeDef::HASH_DataType, and HASH_InitTypeDef::HASH_HMACKeyType.
{
  /* Initialize the HASH_AlgoSelection member */
  HASH_InitStruct->HASH_AlgoSelection = HASH_AlgoSelection_SHA1;
  /* Initialize the HASH_AlgoMode member */
  HASH_InitStruct->HASH_AlgoMode = HASH_AlgoMode_HASH;
  /* Initialize the HASH_DataType member */
  HASH_InitStruct->HASH_DataType = HASH_DataType_32b;
  /* Initialize the HASH_HMACKeyType member */
  HASH_InitStruct->HASH_HMACKeyType = HASH_HMACKeyType_ShortKey;
}
HMAC_MD5()
 ErrorStatus HMAC_MD5 (uint8_t * Key, uint32_t Keylen, uint8_t * Input, uint32_t Ilen, uint8_t Output[16])
Compute the HMAC MD5 digest.
Parameters
Key pointer to the Key used for HMAC.
Keylen length of the Key used for HMAC.
Input pointer to the Input buffer to be treated.
Ilen length of the Input buffer.
Output the returned digest
Return values
An ErrorStatus enumeration value:
SUCCESS: digest computation done
ERROR: digest computation failed
Definition at line 162 of file stm32f4xx_hash_md5.c.
References HASH_DeInit(), HASH_Init(), HASH_StartDigest(), and SUCCESS.
{
  HASH_InitTypeDef MD5_HASH_InitStructure;
  HASH_MsgDigest MD5_MessageDigest;
  __IO uint16_t nbvalidbitsdata = 0;
  __IO uint16_t nbvalidbitskey = 0;
  uint32_t i = 0;
  __IO uint32_t counter = 0;
  uint32_t busystatus = 0;
  ErrorStatus status = SUCCESS;
  uint32_t keyaddr = (uint32_t)Key;
  uint32_t inputaddr = (uint32_t)Input;
  uint32_t outputaddr = (uint32_t)Output;
  /* Number of valid bits in last word of the Input data */
  nbvalidbitsdata = 8 * (Ilen % 4);
  /* Number of valid bits in last word of the Key */
  nbvalidbitskey = 8 * (Keylen % 4);
   
  /* HASH peripheral initialization */
  HASH_DeInit();
  /* HASH Configuration */
  MD5_HASH_InitStructure.HASH_AlgoSelection = HASH_AlgoSelection_MD5;
  MD5_HASH_InitStructure.HASH_AlgoMode = HASH_AlgoMode_HMAC;
  MD5_HASH_InitStructure.HASH_DataType = HASH_DataType_8b;
  if(Keylen > 64)
  {
    /* HMAC long Key */
    MD5_HASH_InitStructure.HASH_HMACKeyType = HASH_HMACKeyType_LongKey;
  }
  else
  {
    /* HMAC short Key */
    MD5_HASH_InitStructure.HASH_HMACKeyType = HASH_HMACKeyType_ShortKey;
  }
  HASH_Init(&MD5_HASH_InitStructure);
  /* Configure the number of valid bits in last word of the Key */
  HASH_SetLastWordValidBitsNbr(nbvalidbitskey);
  /* Write the Key */
  for(i=0; i<Keylen; i+=4)
  {
    HASH_DataIn(*(uint32_t*)keyaddr);
    keyaddr+=4;
  }
  
  /* Start the HASH processor */
  HASH_StartDigest();
  /* wait until the Busy flag is RESET */
  do
  {
    busystatus = HASH_GetFlagStatus(HASH_FLAG_BUSY);
    counter++;
  }while ((counter != MD5BUSY_TIMEOUT) && (busystatus != RESET));
  if (busystatus != RESET)
  {
     status = ERROR;
  }
  else
  {
    /* Configure the number of valid bits in last word of the Input data */
    HASH_SetLastWordValidBitsNbr(nbvalidbitsdata);
    /* Write the Input block in the IN FIFO */
    for(i=0; i<Ilen; i+=4)
    {
      HASH_DataIn(*(uint32_t*)inputaddr);
      inputaddr+=4;
    }
    /* Start the HASH processor */
    HASH_StartDigest();
    /* wait until the Busy flag is RESET */
    counter =0;
    do
    {
       busystatus = HASH_GetFlagStatus(HASH_FLAG_BUSY);
       counter++;
    }while ((counter != MD5BUSY_TIMEOUT) && (busystatus != RESET));
    if (busystatus != RESET)
    {
      status = ERROR;
    }
    else
    {
      /* Configure the number of valid bits in last word of the Key */
      HASH_SetLastWordValidBitsNbr(nbvalidbitskey);
      /* Write the Key */
      keyaddr = (uint32_t)Key;
      for(i=0; i<Keylen; i+=4)
      {
        HASH_DataIn(*(uint32_t*)keyaddr);
        keyaddr+=4;
      }
  
       /* Start the HASH processor */
       HASH_StartDigest();
       /* wait until the Busy flag is RESET */
       counter =0;
       do
       {
          busystatus = HASH_GetFlagStatus(HASH_FLAG_BUSY);
          counter++;
      }while ((counter != MD5BUSY_TIMEOUT) && (busystatus != RESET));
      if (busystatus != RESET)
      {
         status = ERROR;
      }
      else
      {
         /* Read the message digest */
         HASH_GetDigest(&MD5_MessageDigest);
         *(uint32_t*)(outputaddr) = __REV(MD5_MessageDigest.Data[0]);
         outputaddr+=4;
         *(uint32_t*)(outputaddr) = __REV(MD5_MessageDigest.Data[1]);
         outputaddr+=4;
         *(uint32_t*)(outputaddr) = __REV(MD5_MessageDigest.Data[2]);
         outputaddr+=4;
         *(uint32_t*)(outputaddr) = __REV(MD5_MessageDigest.Data[3]);
      }
    }
  }
  return status;
}
HMAC_SHA1()
 ErrorStatus HMAC_SHA1 (uint8_t * Key, uint32_t Keylen, uint8_t * Input, uint32_t Ilen, uint8_t Output[20])
Compute the HMAC SHA1 digest.
Parameters
Key pointer to the Key used for HMAC.
Keylen length of the Key used for HMAC.
Input pointer to the Input buffer to be treated.
Ilen length of the Input buffer.
Output the returned digest
Return values
An ErrorStatus enumeration value:
SUCCESS: digest computation done
ERROR: digest computation failed
Definition at line 163 of file stm32f4xx_hash_sha1.c.
References HASH_DeInit(), HASH_Init(), HASH_StartDigest(), and SUCCESS.
{
  HASH_InitTypeDef SHA1_HASH_InitStructure;
  HASH_MsgDigest SHA1_MessageDigest;
  __IO uint16_t nbvalidbitsdata = 0;
  __IO uint16_t nbvalidbitskey = 0;
  uint32_t i = 0;
  __IO uint32_t counter = 0;
  uint32_t busystatus = 0;
  ErrorStatus status = SUCCESS;
  uint32_t keyaddr = (uint32_t)Key;
  uint32_t inputaddr = (uint32_t)Input;
  uint32_t outputaddr = (uint32_t)Output;
  /* Number of valid bits in last word of the Input data */
  nbvalidbitsdata = 8 * (Ilen % 4);
  /* Number of valid bits in last word of the Key */
  nbvalidbitskey = 8 * (Keylen % 4);
  /* HASH peripheral initialization */
  HASH_DeInit();
  /* HASH Configuration */
  SHA1_HASH_InitStructure.HASH_AlgoSelection = HASH_AlgoSelection_SHA1;
  SHA1_HASH_InitStructure.HASH_AlgoMode = HASH_AlgoMode_HMAC;
  SHA1_HASH_InitStructure.HASH_DataType = HASH_DataType_8b;
  if(Keylen > 64)
  {
    /* HMAC long Key */
    SHA1_HASH_InitStructure.HASH_HMACKeyType = HASH_HMACKeyType_LongKey;
  }
  else
  {
    /* HMAC short Key */
    SHA1_HASH_InitStructure.HASH_HMACKeyType = HASH_HMACKeyType_ShortKey;
  }
  HASH_Init(&SHA1_HASH_InitStructure);
  /* Configure the number of valid bits in last word of the Key */
  HASH_SetLastWordValidBitsNbr(nbvalidbitskey);
  /* Write the Key */
  for(i=0; i<Keylen; i+=4)
  {
    HASH_DataIn(*(uint32_t*)keyaddr);
    keyaddr+=4;
  }
  /* Start the HASH processor */
  HASH_StartDigest();
  /* wait until the Busy flag is RESET */
  do
  {
    busystatus = HASH_GetFlagStatus(HASH_FLAG_BUSY);
    counter++;
  }while ((counter != SHA1BUSY_TIMEOUT) && (busystatus != RESET));
  if (busystatus != RESET)
  {
     status = ERROR;
  }
  else
  {
    /* Configure the number of valid bits in last word of the Input data */
    HASH_SetLastWordValidBitsNbr(nbvalidbitsdata);
    /* Write the Input block in the IN FIFO */
    for(i=0; i<Ilen; i+=4)
    {
      HASH_DataIn(*(uint32_t*)inputaddr);
      inputaddr+=4;
    }
    /* Start the HASH processor */
    HASH_StartDigest();
    /* wait until the Busy flag is RESET */
    counter =0;
    do
    {
      busystatus = HASH_GetFlagStatus(HASH_FLAG_BUSY);
      counter++;
    }while ((counter != SHA1BUSY_TIMEOUT) && (busystatus != RESET));
    if (busystatus != RESET)
    {
      status = ERROR;
    }
    else
    {
      /* Configure the number of valid bits in last word of the Key */
      HASH_SetLastWordValidBitsNbr(nbvalidbitskey);
      /* Write the Key */
      keyaddr = (uint32_t)Key;
      for(i=0; i<Keylen; i+=4)
      {
        HASH_DataIn(*(uint32_t*)keyaddr);
        keyaddr+=4;
      }
      /* Start the HASH processor */
      HASH_StartDigest();
      /* wait until the Busy flag is RESET */
      counter =0;
      do
      {
        busystatus = HASH_GetFlagStatus(HASH_FLAG_BUSY);
        counter++;
      }while ((counter != SHA1BUSY_TIMEOUT) && (busystatus != RESET));
      if (busystatus != RESET)
      {
        status = ERROR;
      }
      else
      {
        /* Read the message digest */
        HASH_GetDigest(&SHA1_MessageDigest);
        *(uint32_t*)(outputaddr) = __REV(SHA1_MessageDigest.Data[0]);
        outputaddr+=4;
        *(uint32_t*)(outputaddr) = __REV(SHA1_MessageDigest.Data[1]);
        outputaddr+=4;
        *(uint32_t*)(outputaddr) = __REV(SHA1_MessageDigest.Data[2]);
        outputaddr+=4;
        *(uint32_t*)(outputaddr) = __REV(SHA1_MessageDigest.Data[3]);
        outputaddr+=4;
        *(uint32_t*)(outputaddr) = __REV(SHA1_MessageDigest.Data[4]);
      }
    }
  }
  return status;
}