I2C
I2C driver modules.
Modules
 I2C_Exported_Constants
 I2C_Private_Functions
Classes
struct I2C_InitTypeDef
I2C Init structure definition.
Macros
#define CR1_CLEAR_MASK ((uint16_t)0xFBF5) /*<! I2C registers Masks */
#define FLAG_MASK ((uint32_t)0x00FFFFFF) /*<! I2C FLAG mask */
#define ITEN_MASK ((uint32_t)0x07000000) /*<! I2C Interrupt Enable mask */
Functions
void I2C_DeInit (I2C_TypeDef *I2Cx)
Deinitialize the I2Cx peripheral registers to their default reset values.
void I2C_Init (I2C_TypeDef *I2Cx, I2C_InitTypeDef *I2C_InitStruct)
Initializes the I2Cx peripheral according to the specified parameters in the I2C_InitStruct.
void I2C_StructInit (I2C_InitTypeDef *I2C_InitStruct)
Fills each I2C_InitStruct member with its default value.
void I2C_Cmd (I2C_TypeDef *I2Cx, FunctionalState NewState)
Enables or disables the specified I2C peripheral.
void I2C_GenerateSTART (I2C_TypeDef *I2Cx, FunctionalState NewState)
Generates I2Cx communication START condition.
void I2C_GenerateSTOP (I2C_TypeDef *I2Cx, FunctionalState NewState)
Generates I2Cx communication STOP condition.
void I2C_Send7bitAddress (I2C_TypeDef *I2Cx, uint8_t Address, uint8_t I2C_Direction)
Transmits the address byte to select the slave device.
void I2C_AcknowledgeConfig (I2C_TypeDef *I2Cx, FunctionalState NewState)
Enables or disables the specified I2C acknowledge feature.
void I2C_OwnAddress2Config (I2C_TypeDef *I2Cx, uint8_t Address)
Configures the specified I2C own address2.
void I2C_DualAddressCmd (I2C_TypeDef *I2Cx, FunctionalState NewState)
Enables or disables the specified I2C dual addressing mode.
void I2C_GeneralCallCmd (I2C_TypeDef *I2Cx, FunctionalState NewState)
Enables or disables the specified I2C general call feature.
void I2C_SoftwareResetCmd (I2C_TypeDef *I2Cx, FunctionalState NewState)
Enables or disables the specified I2C software reset.
void I2C_StretchClockCmd (I2C_TypeDef *I2Cx, FunctionalState NewState)
Enables or disables the specified I2C Clock stretching.
void I2C_FastModeDutyCycleConfig (I2C_TypeDef *I2Cx, uint16_t I2C_DutyCycle)
Selects the specified I2C fast mode duty cycle.
void I2C_NACKPositionConfig (I2C_TypeDef *I2Cx, uint16_t I2C_NACKPosition)
Selects the specified I2C NACK position in master receiver mode.
void I2C_SMBusAlertConfig (I2C_TypeDef *I2Cx, uint16_t I2C_SMBusAlert)
Drives the SMBusAlert pin high or low for the specified I2C.
void I2C_ARPCmd (I2C_TypeDef *I2Cx, FunctionalState NewState)
Enables or disables the specified I2C ARP.
void I2C_SendData (I2C_TypeDef *I2Cx, uint8_t Data)
Sends a data byte through the I2Cx peripheral.
uint8_t I2C_ReceiveData (I2C_TypeDef *I2Cx)
Returns the most recent received data by the I2Cx peripheral.
void I2C_TransmitPEC (I2C_TypeDef *I2Cx, FunctionalState NewState)
Enables or disables the specified I2C PEC transfer.
void I2C_PECPositionConfig (I2C_TypeDef *I2Cx, uint16_t I2C_PECPosition)
Selects the specified I2C PEC position.
void I2C_CalculatePEC (I2C_TypeDef *I2Cx, FunctionalState NewState)
Enables or disables the PEC value calculation of the transferred bytes.
uint8_t I2C_GetPEC (I2C_TypeDef *I2Cx)
Returns the PEC value for the specified I2C.
void I2C_DMACmd (I2C_TypeDef *I2Cx, FunctionalState NewState)
Enables or disables the specified I2C DMA requests.
void I2C_DMALastTransferCmd (I2C_TypeDef *I2Cx, FunctionalState NewState)
Specifies that the next DMA transfer is the last one.
uint16_t I2C_ReadRegister (I2C_TypeDef *I2Cx, uint8_t I2C_Register)
Reads the specified I2C register and returns its value.
void I2C_ITConfig (I2C_TypeDef *I2Cx, uint16_t I2C_IT, FunctionalState NewState)
Enables or disables the specified I2C interrupts.
 ErrorStatus I2C_CheckEvent (I2C_TypeDef *I2Cx, uint32_t I2C_EVENT)
Checks whether the last I2Cx Event is equal to the one passed as parameter.
uint32_t I2C_GetLastEvent (I2C_TypeDef *I2Cx)
Returns the last I2Cx Event.
 FlagStatus I2C_GetFlagStatus (I2C_TypeDef *I2Cx, uint32_t I2C_FLAG)
Checks whether the specified I2C flag is set or not.
void I2C_ClearFlag (I2C_TypeDef *I2Cx, uint32_t I2C_FLAG)
Clears the I2Cx's pending flags.
 ITStatus I2C_GetITStatus (I2C_TypeDef *I2Cx, uint32_t I2C_IT)
Checks whether the specified I2C interrupt has occurred or not.
void I2C_ClearITPendingBit (I2C_TypeDef *I2Cx, uint32_t I2C_IT)
Clears the I2Cx's interrupt pending bits.
Detailed Description
I2C driver modules.
Macro Definition Documentation
CR1_CLEAR_MASK
#define CR1_CLEAR_MASK ((uint16_t)0xFBF5) /*<! I2C registers Masks */
Definition at line 102 of file stm32f4xx_i2c.c.
FLAG_MASK
#define FLAG_MASK ((uint32_t)0x00FFFFFF) /*<! I2C FLAG mask */
Definition at line 103 of file stm32f4xx_i2c.c.
ITEN_MASK
#define ITEN_MASK ((uint32_t)0x07000000) /*<! I2C Interrupt Enable mask */
Definition at line 104 of file stm32f4xx_i2c.c.
Function Documentation
I2C_AcknowledgeConfig()
void I2C_AcknowledgeConfig (I2C_TypeDef * I2Cx, FunctionalState NewState)
Enables or disables the specified I2C acknowledge feature.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2C Acknowledgement. This parameter can be: ENABLE or DISABLE.
Return values
None.
Definition at line 411 of file stm32f4xx_i2c.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the acknowledgement */
    I2Cx->CR1 |= I2C_CR1_ACK;
  }
  else
  {
    /* Disable the acknowledgement */
    I2Cx->CR1 &= (uint16_t)~((uint16_t)I2C_CR1_ACK);
  }
}
I2C_ARPCmd()
void I2C_ARPCmd (I2C_TypeDef * I2Cx, FunctionalState NewState)
Enables or disables the specified I2C ARP.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2Cx ARP. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 651 of file stm32f4xx_i2c.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the selected I2C ARP */
    I2Cx->CR1 |= I2C_CR1_ENARP;
  }
  else
  {
    /* Disable the selected I2C ARP */
    I2Cx->CR1 &= (uint16_t)~((uint16_t)I2C_CR1_ENARP);
  }
}
I2C_CalculatePEC()
void I2C_CalculatePEC (I2C_TypeDef * I2Cx, FunctionalState NewState)
Enables or disables the PEC value calculation of the transferred bytes.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2Cx PEC value calculation. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 788 of file stm32f4xx_i2c.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the selected I2C PEC calculation */
    I2Cx->CR1 |= I2C_CR1_ENPEC;
  }
  else
  {
    /* Disable the selected I2C PEC calculation */
    I2Cx->CR1 &= (uint16_t)~((uint16_t)I2C_CR1_ENPEC);
  }
}
I2C_CheckEvent()
 ErrorStatus I2C_CheckEvent (I2C_TypeDef * I2Cx, uint32_t I2C_EVENT)
Checks whether the last I2Cx Event is equal to the one passed as parameter.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
I2C_EVENT specifies the event to be checked. This parameter can be one of the following values:
I2C_EVENT_SLAVE_TRANSMITTER_ADDRESS_MATCHED: EV1
I2C_EVENT_SLAVE_RECEIVER_ADDRESS_MATCHED: EV1
I2C_EVENT_SLAVE_TRANSMITTER_SECONDADDRESS_MATCHED: EV1
I2C_EVENT_SLAVE_RECEIVER_SECONDADDRESS_MATCHED: EV1
I2C_EVENT_SLAVE_GENERALCALLADDRESS_MATCHED: EV1
I2C_EVENT_SLAVE_BYTE_RECEIVED: EV2
(I2C_EVENT_SLAVE_BYTE_RECEIVED | I2C_FLAG_DUALF): EV2
(I2C_EVENT_SLAVE_BYTE_RECEIVED | I2C_FLAG_GENCALL): EV2
I2C_EVENT_SLAVE_BYTE_TRANSMITTED: EV3
(I2C_EVENT_SLAVE_BYTE_TRANSMITTED | I2C_FLAG_DUALF): EV3
(I2C_EVENT_SLAVE_BYTE_TRANSMITTED | I2C_FLAG_GENCALL): EV3
I2C_EVENT_SLAVE_ACK_FAILURE: EV3_2
I2C_EVENT_SLAVE_STOP_DETECTED: EV4
I2C_EVENT_MASTER_MODE_SELECT: EV5
I2C_EVENT_MASTER_TRANSMITTER_MODE_SELECTED: EV6
I2C_EVENT_MASTER_RECEIVER_MODE_SELECTED: EV6
I2C_EVENT_MASTER_BYTE_RECEIVED: EV7
I2C_EVENT_MASTER_BYTE_TRANSMITTING: EV8
I2C_EVENT_MASTER_BYTE_TRANSMITTED: EV8_2
I2C_EVENT_MASTER_MODE_ADDRESS10: EV9
Note
For detailed description of Events, please refer to section I2C_Events in stm32f4xx_i2c.h file.
Return values
An ErrorStatus enumeration value:
SUCCESS: Last event is equal to the I2C_EVENT
ERROR: Last event is different from the I2C_EVENT
Definition at line 1091 of file stm32f4xx_i2c.c.
References ERROR, and SUCCESS.
{
  uint32_t lastevent = 0;
  uint32_t flag1 = 0, flag2 = 0;
  ErrorStatus status = ERROR;
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_EVENT(I2C_EVENT));
  /* Read the I2Cx status register */
  flag1 = I2Cx->SR1;
  flag2 = I2Cx->SR2;
  flag2 = flag2 << 16;
  /* Get the last event value from I2C status register */
  lastevent = (flag1 | flag2) & FLAG_MASK;
  /* Check whether the last event contains the I2C_EVENT */
  if ((lastevent & I2C_EVENT) == I2C_EVENT)
  {
    /* SUCCESS: last event is equal to I2C_EVENT */
    status = SUCCESS;
  }
  else
  {
    /* ERROR: last event is different from I2C_EVENT */
    status = ERROR;
  }
  /* Return status */
  return status;
}
I2C_ClearFlag()
void I2C_ClearFlag (I2C_TypeDef * I2Cx, uint32_t I2C_FLAG)
Clears the I2Cx's pending flags.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
I2C_FLAG specifies the flag to clear. This parameter can be any combination of the following values:
I2C_FLAG_SMBALERT: SMBus Alert flag
I2C_FLAG_TIMEOUT: Timeout or Tlow error flag
I2C_FLAG_PECERR: PEC error in reception flag
I2C_FLAG_OVR: Overrun/Underrun flag (Slave mode)
I2C_FLAG_AF: Acknowledge failure flag
I2C_FLAG_ARLO: Arbitration lost flag (Master mode)
I2C_FLAG_BERR: Bus error flag
Note
STOPF (STOP detection) is cleared by software sequence: a read operation to I2C_SR1 register (I2C_GetFlagStatus()) followed by a write operation to I2C_CR1 register (I2C_Cmd() to re-enable the I2C peripheral).
ADD10 (10-bit header sent) is cleared by software sequence: a read operation to I2C_SR1 (I2C_GetFlagStatus()) followed by writing the second byte of the address in DR register.
BTF (Byte Transfer Finished) is cleared by software sequence: a read operation to I2C_SR1 register (I2C_GetFlagStatus()) followed by a read/write to I2C_DR register (I2C_SendData()).
ADDR (Address sent) is cleared by software sequence: a read operation to I2C_SR1 register (I2C_GetFlagStatus()) followed by a read operation to I2C_SR2 register ((void)(I2Cx->SR2)).
SB (Start Bit) is cleared software sequence: a read operation to I2C_SR1 register (I2C_GetFlagStatus()) followed by a write operation to I2C_DR register (I2C_SendData()).
Return values
None
Definition at line 1271 of file stm32f4xx_i2c.c.
{
  uint32_t flagpos = 0;
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_CLEAR_FLAG(I2C_FLAG));
  /* Get the I2C flag position */
  flagpos = I2C_FLAG & FLAG_MASK;
  /* Clear the selected I2C flag */
  I2Cx->SR1 = (uint16_t)~flagpos;
}
I2C_ClearITPendingBit()
void I2C_ClearITPendingBit (I2C_TypeDef * I2Cx, uint32_t I2C_IT)
Clears the I2Cx's interrupt pending bits.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
I2C_IT specifies the interrupt pending bit to clear. This parameter can be any combination of the following values:
I2C_IT_SMBALERT: SMBus Alert interrupt
I2C_IT_TIMEOUT: Timeout or Tlow error interrupt
I2C_IT_PECERR: PEC error in reception interrupt
I2C_IT_OVR: Overrun/Underrun interrupt (Slave mode)
I2C_IT_AF: Acknowledge failure interrupt
I2C_IT_ARLO: Arbitration lost interrupt (Master mode)
I2C_IT_BERR: Bus error interrupt
Note
STOPF (STOP detection) is cleared by software sequence: a read operation to I2C_SR1 register (I2C_GetITStatus()) followed by a write operation to I2C_CR1 register (I2C_Cmd() to re-enable the I2C peripheral).
ADD10 (10-bit header sent) is cleared by software sequence: a read operation to I2C_SR1 (I2C_GetITStatus()) followed by writing the second byte of the address in I2C_DR register.
BTF (Byte Transfer Finished) is cleared by software sequence: a read operation to I2C_SR1 register (I2C_GetITStatus()) followed by a read/write to I2C_DR register (I2C_SendData()).
ADDR (Address sent) is cleared by software sequence: a read operation to I2C_SR1 register (I2C_GetITStatus()) followed by a read operation to I2C_SR2 register ((void)(I2Cx->SR2)).
SB (Start Bit) is cleared by software sequence: a read operation to I2C_SR1 register (I2C_GetITStatus()) followed by a write operation to I2C_DR register (I2C_SendData()).
Return values
None
Definition at line 1365 of file stm32f4xx_i2c.c.
{
  uint32_t flagpos = 0;
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_CLEAR_IT(I2C_IT));
  /* Get the I2C flag position */
  flagpos = I2C_IT & FLAG_MASK;
  /* Clear the selected I2C flag */
  I2Cx->SR1 = (uint16_t)~flagpos;
}
I2C_Cmd()
void I2C_Cmd (I2C_TypeDef * I2Cx, FunctionalState NewState)
Enables or disables the specified I2C peripheral.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2Cx peripheral. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 308 of file stm32f4xx_i2c.c.
References DISABLE.
Referenced by I2cMaster_Init(), and I2Cx_TIMEOUT_UserCallback().
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the selected I2C peripheral */
    I2Cx->CR1 |= I2C_CR1_PE;
  }
  else
  {
    /* Disable the selected I2C peripheral */
    I2Cx->CR1 &= (uint16_t)~((uint16_t)I2C_CR1_PE);
  }
}
I2C_DeInit()
void I2C_DeInit (I2C_TypeDef * I2Cx)
Deinitialize the I2Cx peripheral registers to their default reset values.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
Return values
None
Definition at line 132 of file stm32f4xx_i2c.c.
References DISABLE, ENABLE, and RCC_APB1PeriphResetCmd().
Referenced by I2cMaster_Init(), and I2Cx_TIMEOUT_UserCallback().
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  if (I2Cx == I2C1)
  {
    /* Enable I2C1 reset state */
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_I2C1, ENABLE);
    /* Release I2C1 from reset state */
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_I2C1, DISABLE);
  }
  else if (I2Cx == I2C2)
  {
    /* Enable I2C2 reset state */
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_I2C2, ENABLE);
    /* Release I2C2 from reset state */
    RCC_APB1PeriphResetCmd(RCC_APB1Periph_I2C2, DISABLE);
  }
  else
  {
    if (I2Cx == I2C3)
    {
      /* Enable I2C3 reset state */
      RCC_APB1PeriphResetCmd(RCC_APB1Periph_I2C3, ENABLE);
      /* Release I2C3 from reset state */
      RCC_APB1PeriphResetCmd(RCC_APB1Periph_I2C3, DISABLE);
    }
  }
}
I2C_DMACmd()
void I2C_DMACmd (I2C_TypeDef * I2Cx, FunctionalState NewState)
Enables or disables the specified I2C DMA requests.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2C DMA transfer. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 843 of file stm32f4xx_i2c.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the selected I2C DMA requests */
    I2Cx->CR2 |= I2C_CR2_DMAEN;
  }
  else
  {
    /* Disable the selected I2C DMA requests */
    I2Cx->CR2 &= (uint16_t)~((uint16_t)I2C_CR2_DMAEN);
  }
}
I2C_DMALastTransferCmd()
void I2C_DMALastTransferCmd (I2C_TypeDef * I2Cx, FunctionalState NewState)
Specifies that the next DMA transfer is the last one.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2C DMA last transfer. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 867 of file stm32f4xx_i2c.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Next DMA transfer is the last transfer */
    I2Cx->CR2 |= I2C_CR2_LAST;
  }
  else
  {
    /* Next DMA transfer is not the last transfer */
    I2Cx->CR2 &= (uint16_t)~((uint16_t)I2C_CR2_LAST);
  }
}
I2C_DualAddressCmd()
void I2C_DualAddressCmd (I2C_TypeDef * I2Cx, FunctionalState NewState)
Enables or disables the specified I2C dual addressing mode.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2C dual addressing mode. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 461 of file stm32f4xx_i2c.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable dual addressing mode */
    I2Cx->OAR2 |= I2C_OAR2_ENDUAL;
  }
  else
  {
    /* Disable dual addressing mode */
    I2Cx->OAR2 &= (uint16_t)~((uint16_t)I2C_OAR2_ENDUAL);
  }
}
I2C_FastModeDutyCycleConfig()
void I2C_FastModeDutyCycleConfig (I2C_TypeDef * I2Cx, uint16_t I2C_DutyCycle)
Selects the specified I2C fast mode duty cycle.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
I2C_DutyCycle specifies the fast mode duty cycle. This parameter can be one of the following values:
I2C_DutyCycle_2: I2C fast mode Tlow/Thigh = 2
I2C_DutyCycle_16_9: I2C fast mode Tlow/Thigh = 16/9
Return values
None
Definition at line 561 of file stm32f4xx_i2c.c.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_DUTY_CYCLE(I2C_DutyCycle));
  if (I2C_DutyCycle != I2C_DutyCycle_16_9)
  {
    /* I2C fast mode Tlow/Thigh=2 */
    I2Cx->CCR &= I2C_DutyCycle_2;
  }
  else
  {
    /* I2C fast mode Tlow/Thigh=16/9 */
    I2Cx->CCR |= I2C_DutyCycle_16_9;
  }
}
I2C_GeneralCallCmd()
void I2C_GeneralCallCmd (I2C_TypeDef * I2Cx, FunctionalState NewState)
Enables or disables the specified I2C general call feature.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2C General call. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 485 of file stm32f4xx_i2c.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable generall call */
    I2Cx->CR1 |= I2C_CR1_ENGC;
  }
  else
  {
    /* Disable generall call */
    I2Cx->CR1 &= (uint16_t)~((uint16_t)I2C_CR1_ENGC);
  }
}
I2C_GenerateSTART()
void I2C_GenerateSTART (I2C_TypeDef * I2Cx, FunctionalState NewState)
Generates I2Cx communication START condition.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2C START condition generation. This parameter can be: ENABLE or DISABLE.
Return values
None.
Definition at line 332 of file stm32f4xx_i2c.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Generate a START condition */
    I2Cx->CR1 |= I2C_CR1_START;
  }
  else
  {
    /* Disable the START condition generation */
    I2Cx->CR1 &= (uint16_t)~((uint16_t)I2C_CR1_START);
  }
}
I2C_GenerateSTOP()
void I2C_GenerateSTOP (I2C_TypeDef * I2Cx, FunctionalState NewState)
Generates I2Cx communication STOP condition.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2C STOP condition generation. This parameter can be: ENABLE or DISABLE.
Return values
None.
Definition at line 356 of file stm32f4xx_i2c.c.
References DISABLE.
Referenced by I2Cx_TIMEOUT_UserCallback().
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Generate a STOP condition */
    I2Cx->CR1 |= I2C_CR1_STOP;
  }
  else
  {
    /* Disable the STOP condition generation */
    I2Cx->CR1 &= (uint16_t)~((uint16_t)I2C_CR1_STOP);
  }
}
I2C_GetFlagStatus()
 FlagStatus I2C_GetFlagStatus (I2C_TypeDef * I2Cx, uint32_t I2C_FLAG)
Checks whether the specified I2C flag is set or not.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
I2C_FLAG specifies the flag to check. This parameter can be one of the following values:
I2C_FLAG_DUALF: Dual flag (Slave mode)
I2C_FLAG_SMBHOST: SMBus host header (Slave mode)
I2C_FLAG_SMBDEFAULT: SMBus default header (Slave mode)
I2C_FLAG_GENCALL: General call header flag (Slave mode)
I2C_FLAG_TRA: Transmitter/Receiver flag
I2C_FLAG_BUSY: Bus busy flag
I2C_FLAG_MSL: Master/Slave flag
I2C_FLAG_SMBALERT: SMBus Alert flag
I2C_FLAG_TIMEOUT: Timeout or Tlow error flag
I2C_FLAG_PECERR: PEC error in reception flag
I2C_FLAG_OVR: Overrun/Underrun flag (Slave mode)
I2C_FLAG_AF: Acknowledge failure flag
I2C_FLAG_ARLO: Arbitration lost flag (Master mode)
I2C_FLAG_BERR: Bus error flag
I2C_FLAG_TXE: Data register empty flag (Transmitter)
I2C_FLAG_RXNE: Data register not empty (Receiver) flag
I2C_FLAG_STOPF: Stop detection flag (Slave mode)
I2C_FLAG_ADD10: 10-bit header sent flag (Master mode)
I2C_FLAG_BTF: Byte transfer finished flag
I2C_FLAG_ADDR: Address sent flag (Master mode) `ADSL` Address matched flag (Slave mode)`ENDAD`
I2C_FLAG_SB: Start bit flag (Master mode)
Return values
The new state of I2C_FLAG (SET or RESET).
Definition at line 1194 of file stm32f4xx_i2c.c.
References RESET.
{
  FlagStatus bitstatus = RESET;
  __IO uint32_t i2creg = 0, i2cxbase = 0;
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_GET_FLAG(I2C_FLAG));
  /* Get the I2Cx peripheral base address */
  i2cxbase = (uint32_t)I2Cx;
  
  /* Read flag register index */
  i2creg = I2C_FLAG >> 28;
  
  /* Get bit[23:0] of the flag */
  I2C_FLAG &= FLAG_MASK;
  
  if(i2creg != 0)
  {
    /* Get the I2Cx SR1 register address */
    i2cxbase += 0x14;
  }
  else
  {
    /* Flag in I2Cx SR2 Register */
    I2C_FLAG = (uint32_t)(I2C_FLAG >> 16);
    /* Get the I2Cx SR2 register address */
    i2cxbase += 0x18;
  }
  
  if(((*(__IO uint32_t *)i2cxbase) & I2C_FLAG) != (uint32_t)RESET)
  {
    /* I2C_FLAG is set */
    bitstatus = SET;
  }
  else
  {
    /* I2C_FLAG is reset */
    bitstatus = RESET;
  }
  
  /* Return the I2C_FLAG status */
  return bitstatus;
}
I2C_GetITStatus()
 ITStatus I2C_GetITStatus (I2C_TypeDef * I2Cx, uint32_t I2C_IT)
Checks whether the specified I2C interrupt has occurred or not.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
I2C_IT specifies the interrupt source to check. This parameter can be one of the following values:
I2C_IT_SMBALERT: SMBus Alert flag
I2C_IT_TIMEOUT: Timeout or Tlow error flag
I2C_IT_PECERR: PEC error in reception flag
I2C_IT_OVR: Overrun/Underrun flag (Slave mode)
I2C_IT_AF: Acknowledge failure flag
I2C_IT_ARLO: Arbitration lost flag (Master mode)
I2C_IT_BERR: Bus error flag
I2C_IT_TXE: Data register empty flag (Transmitter)
I2C_IT_RXNE: Data register not empty (Receiver) flag
I2C_IT_STOPF: Stop detection flag (Slave mode)
I2C_IT_ADD10: 10-bit header sent flag (Master mode)
I2C_IT_BTF: Byte transfer finished flag
I2C_IT_ADDR: Address sent flag (Master mode) `ADSL` Address matched flag (Slave mode)`ENDAD`
I2C_IT_SB: Start bit flag (Master mode)
Return values
The new state of I2C_IT (SET or RESET).
Definition at line 1305 of file stm32f4xx_i2c.c.
References RESET.
{
  ITStatus bitstatus = RESET;
  uint32_t enablestatus = 0;
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_GET_IT(I2C_IT));
  /* Check if the interrupt source is enabled or not */
  enablestatus = (uint32_t)(((I2C_IT & ITEN_MASK) >> 16) & (I2Cx->CR2)) ;
  
  /* Get bit[23:0] of the flag */
  I2C_IT &= FLAG_MASK;
  /* Check the status of the specified I2C flag */
  if (((I2Cx->SR1 & I2C_IT) != (uint32_t)RESET) && enablestatus)
  {
    /* I2C_IT is set */
    bitstatus = SET;
  }
  else
  {
    /* I2C_IT is reset */
    bitstatus = RESET;
  }
  /* Return the I2C_IT status */
  return bitstatus;
}
I2C_GetLastEvent()
uint32_t I2C_GetLastEvent (I2C_TypeDef * I2Cx)
Returns the last I2Cx Event.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
Note
For detailed description of Events, please refer to section I2C_Events in stm32f4xx_i2c.h file.
Return values
The last event
Definition at line 1139 of file stm32f4xx_i2c.c.
{
  uint32_t lastevent = 0;
  uint32_t flag1 = 0, flag2 = 0;
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  /* Read the I2Cx status register */
  flag1 = I2Cx->SR1;
  flag2 = I2Cx->SR2;
  flag2 = flag2 << 16;
  /* Get the last event value from I2C status register */
  lastevent = (flag1 | flag2) & FLAG_MASK;
  /* Return status */
  return lastevent;
}
I2C_GetPEC()
uint8_t I2C_GetPEC (I2C_TypeDef * I2Cx)
Returns the PEC value for the specified I2C.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
Return values
The PEC value.
Definition at line 810 of file stm32f4xx_i2c.c.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  /* Return the selected I2C PEC value */
  return ((I2Cx->SR2) >> 8);
}
I2C_Init()
void I2C_Init (I2C_TypeDef * I2Cx, I2C_InitTypeDef * I2C_InitStruct)
Initializes the I2Cx peripheral according to the specified parameters in the I2C_InitStruct.
Note
To use the I2C at 400 KHz (in fast mode), the PCLK1 frequency (I2C peripheral input clock) must be a multiple of 10 MHz.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
I2C_InitStruct pointer to a I2C_InitTypeDef structure that contains the configuration information for the specified I2C peripheral.
Return values
None
Definition at line 175 of file stm32f4xx_i2c.c.
References I2C_InitTypeDef::I2C_Ack, I2C_InitTypeDef::I2C_ClockSpeed, I2C_InitTypeDef::I2C_DutyCycle, I2C_InitTypeDef::I2C_Mode, RCC_ClocksTypeDef::PCLK1_Frequency, and RCC_GetClocksFreq().
Referenced by I2cMaster_Init(), and I2Cx_TIMEOUT_UserCallback().
{
  uint16_t tmpreg = 0, freqrange = 0;
  uint16_t result = 0x04;
  uint32_t pclk1 = 8000000;
  RCC_ClocksTypeDef rcc_clocks;
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_CLOCK_SPEED(I2C_InitStruct->I2C_ClockSpeed));
  assert_param(IS_I2C_MODE(I2C_InitStruct->I2C_Mode));
  assert_param(IS_I2C_DUTY_CYCLE(I2C_InitStruct->I2C_DutyCycle));
  assert_param(IS_I2C_OWN_ADDRESS1(I2C_InitStruct->I2C_OwnAddress1));
  assert_param(IS_I2C_ACK_STATE(I2C_InitStruct->I2C_Ack));
  assert_param(IS_I2C_ACKNOWLEDGE_ADDRESS(I2C_InitStruct->
      I2C_AcknowledgedAddress));
/*---------------------------- I2Cx CR2 Configuration ------------------------*/
  /* Get the I2Cx CR2 value */
  tmpreg = I2Cx->CR2;
  /* Clear frequency FREQ[5:0] bits */
  tmpreg &= (uint16_t)~((uint16_t)I2C_CR2_FREQ);
  /* Get pclk1 frequency value */
  RCC_GetClocksFreq(&rcc_clocks);
  pclk1 = rcc_clocks.PCLK1_Frequency;
  /* Set frequency bits depending on pclk1 value */
  freqrange = (uint16_t)(pclk1 / 1000000);
  tmpreg |= freqrange;
  /* Write to I2Cx CR2 */
  I2Cx->CR2 = tmpreg;
/*---------------------------- I2Cx CCR Configuration ------------------------*/
  /* Disable the selected I2C peripheral to configure TRISE */
  I2Cx->CR1 &= (uint16_t)~((uint16_t)I2C_CR1_PE);
  /* Reset tmpreg value */
  /* Clear F/S, DUTY and CCR[11:0] bits */
  tmpreg = 0;
  /* Configure speed in standard mode */
  if (I2C_InitStruct->I2C_ClockSpeed <= 100000)
  {
    /* Standard mode speed calculate */
    result = (uint16_t)(pclk1 / (I2C_InitStruct->I2C_ClockSpeed << 1));
    /* Test if CCR value is under 0x4*/
    if (result < 0x04)
    {
      /* Set minimum allowed value */
      result = 0x04;
    }
    /* Set speed value for standard mode */
    tmpreg |= result;
    /* Set Maximum Rise Time for standard mode */
    I2Cx->TRISE = freqrange + 1;
  }
  /* Configure speed in fast mode */
  /* To use the I2C at 400 KHz (in fast mode), the PCLK1 frequency (I2C peripheral
     input clock) must be a multiple of 10 MHz */
  else /*(I2C_InitStruct->I2C_ClockSpeed <= 400000)*/
  {
    if (I2C_InitStruct->I2C_DutyCycle == I2C_DutyCycle_2)
    {
      /* Fast mode speed calculate: Tlow/Thigh = 2 */
      result = (uint16_t)(pclk1 / (I2C_InitStruct->I2C_ClockSpeed * 3));
    }
    else /*I2C_InitStruct->I2C_DutyCycle == I2C_DutyCycle_16_9*/
    {
      /* Fast mode speed calculate: Tlow/Thigh = 16/9 */
      result = (uint16_t)(pclk1 / (I2C_InitStruct->I2C_ClockSpeed * 25));
      /* Set DUTY bit */
      result |= I2C_DutyCycle_16_9;
    }
    /* Test if CCR value is under 0x1*/
    if ((result & I2C_CCR_CCR) == 0)
    {
      /* Set minimum allowed value */
      result |= (uint16_t)0x0001;
    }
    /* Set speed value and set F/S bit for fast mode */
    tmpreg |= (uint16_t)(result | I2C_CCR_FS);
    /* Set Maximum Rise Time for fast mode */
    I2Cx->TRISE = (uint16_t)(((freqrange * (uint16_t)300) / (uint16_t)1000) + (uint16_t)1);
  }
  /* Write to I2Cx CCR */
  I2Cx->CCR = tmpreg;
  /* Enable the selected I2C peripheral */
  I2Cx->CR1 |= I2C_CR1_PE;
/*---------------------------- I2Cx CR1 Configuration ------------------------*/
  /* Get the I2Cx CR1 value */
  tmpreg = I2Cx->CR1;
  /* Clear ACK, SMBTYPE and SMBUS bits */
  tmpreg &= CR1_CLEAR_MASK;
  /* Configure I2Cx: mode and acknowledgement */
  /* Set SMBTYPE and SMBUS bits according to I2C_Mode value */
  /* Set ACK bit according to I2C_Ack value */
  tmpreg |= (uint16_t)((uint32_t)I2C_InitStruct->I2C_Mode | I2C_InitStruct->
      I2C_Ack);
  /* Write to I2Cx CR1 */
  I2Cx->CR1 = tmpreg;
/*---------------------------- I2Cx OAR1 Configuration -----------------------*/
  /* Set I2Cx Own Address1 and acknowledged address */
  I2Cx->OAR1 = (I2C_InitStruct->I2C_AcknowledgedAddress | I2C_InitStruct->
      I2C_OwnAddress1);
}
I2C_ITConfig()
void I2C_ITConfig (I2C_TypeDef * I2Cx, uint16_t I2C_IT, FunctionalState NewState)
Enables or disables the specified I2C interrupts.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
I2C_IT specifies the I2C interrupts sources to be enabled or disabled. This parameter can be any combination of the following values:
I2C_IT_BUF: Buffer interrupt mask
I2C_IT_EVT: Event interrupt mask
I2C_IT_ERR: Error interrupt mask
NewState new state of the specified I2C interrupts. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 1032 of file stm32f4xx_i2c.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  assert_param(IS_I2C_CONFIG_IT(I2C_IT));
  
  if (NewState != DISABLE)
  {
    /* Enable the selected I2C interrupts */
    I2Cx->CR2 |= I2C_IT;
  }
  else
  {
    /* Disable the selected I2C interrupts */
    I2Cx->CR2 &= (uint16_t)~I2C_IT;
  }
}
I2C_NACKPositionConfig()
void I2C_NACKPositionConfig (I2C_TypeDef * I2Cx, uint16_t I2C_NACKPosition)
Selects the specified I2C NACK position in master receiver mode.
Note
This function is useful in I2C Master Receiver mode when the number of data to be received is equal to 2. In this case, this function should be called (with parameter I2C_NACKPosition_Next) before data reception starts,as described in the 2-byte reception procedure recommended in Reference Manual in Section: Master receiver.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
I2C_NACKPosition specifies the NACK position. This parameter can be one of the following values:
I2C_NACKPosition_Next: indicates that the next byte will be the last received byte.
I2C_NACKPosition_Current: indicates that current byte is the last received byte.
Note
This function configures the same bit (POS) as I2C_PECPositionConfig() but is intended to be used in I2C mode while I2C_PECPositionConfig() is intended to used in SMBUS mode.
Return values
None
Definition at line 599 of file stm32f4xx_i2c.c.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_NACK_POSITION(I2C_NACKPosition));
  
  /* Check the input parameter */
  if (I2C_NACKPosition == I2C_NACKPosition_Next)
  {
    /* Next byte in shift register is the last received byte */
    I2Cx->CR1 |= I2C_NACKPosition_Next;
  }
  else
  {
    /* Current byte in shift register is the last received byte */
    I2Cx->CR1 &= I2C_NACKPosition_Current;
  }
}
I2C_OwnAddress2Config()
void I2C_OwnAddress2Config (I2C_TypeDef * I2Cx, uint8_t Address)
Configures the specified I2C own address2.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
Address specifies the 7bit I2C own address2.
Return values
None.
Definition at line 434 of file stm32f4xx_i2c.c.
{
  uint16_t tmpreg = 0;
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  /* Get the old register value */
  tmpreg = I2Cx->OAR2;
  /* Reset I2Cx Own address2 bit [7:1] */
  tmpreg &= (uint16_t)~((uint16_t)I2C_OAR2_ADD2);
  /* Set I2Cx Own address2 */
  tmpreg |= (uint16_t)((uint16_t)Address & (uint16_t)0x00FE);
  /* Store the new register value */
  I2Cx->OAR2 = tmpreg;
}
I2C_PECPositionConfig()
void I2C_PECPositionConfig (I2C_TypeDef * I2Cx, uint16_t I2C_PECPosition)
Selects the specified I2C PEC position.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
I2C_PECPosition specifies the PEC position. This parameter can be one of the following values:
I2C_PECPosition_Next: indicates that the next byte is PEC
I2C_PECPosition_Current: indicates that current byte is PEC
Note
This function configures the same bit (POS) as I2C_NACKPositionConfig() but is intended to be used in SMBUS mode while I2C_NACKPositionConfig() is intended to used in I2C mode.
Return values
None
Definition at line 764 of file stm32f4xx_i2c.c.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_PEC_POSITION(I2C_PECPosition));
  if (I2C_PECPosition == I2C_PECPosition_Next)
  {
    /* Next byte in shift register is PEC */
    I2Cx->CR1 |= I2C_PECPosition_Next;
  }
  else
  {
    /* Current byte in shift register is PEC */
    I2Cx->CR1 &= I2C_PECPosition_Current;
  }
}
I2C_ReadRegister()
uint16_t I2C_ReadRegister (I2C_TypeDef * I2Cx, uint8_t I2C_Register)
Reads the specified I2C register and returns its value.
Parameters
I2C_Register specifies the register to read. This parameter can be one of the following values:
I2C_Register_CR1: CR1 register.
I2C_Register_CR2: CR2 register.
I2C_Register_OAR1: OAR1 register.
I2C_Register_OAR2: OAR2 register.
I2C_Register_DR: DR register.
I2C_Register_SR1: SR1 register.
I2C_Register_SR2: SR2 register.
I2C_Register_CCR: CCR register.
I2C_Register_TRISE: TRISE register.
Return values
The value of the read register.
Definition at line 1005 of file stm32f4xx_i2c.c.
{
  __IO uint32_t tmp = 0;
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_REGISTER(I2C_Register));
  tmp = (uint32_t) I2Cx;
  tmp += I2C_Register;
  /* Return the selected register value */
  return (*(__IO uint16_t *) tmp);
}
I2C_ReceiveData()
uint8_t I2C_ReceiveData (I2C_TypeDef * I2Cx)
Returns the most recent received data by the I2Cx peripheral.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
Return values
The value of the received data.
Definition at line 702 of file stm32f4xx_i2c.c.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  /* Return the data in the DR register */
  return (uint8_t)I2Cx->DR;
}
I2C_Send7bitAddress()
void I2C_Send7bitAddress (I2C_TypeDef * I2Cx, uint8_t Address, uint8_t I2C_Direction)
Transmits the address byte to select the slave device.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
Address specifies the slave address which will be transmitted
I2C_Direction specifies whether the I2C device will be a Transmitter or a Receiver. This parameter can be one of the following values
I2C_Direction_Transmitter: Transmitter mode
I2C_Direction_Receiver: Receiver mode
Return values
None.
Definition at line 384 of file stm32f4xx_i2c.c.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_DIRECTION(I2C_Direction));
  /* Test on the direction to set/reset the read/write bit */
  if (I2C_Direction != I2C_Direction_Transmitter)
  {
    /* Set the address bit0 for read */
    Address |= I2C_OAR1_ADD0;
  }
  else
  {
    /* Reset the address bit0 for write */
    Address &= (uint8_t)~((uint8_t)I2C_OAR1_ADD0);
  }
  /* Send the address */
  I2Cx->DR = Address;
}
I2C_SendData()
void I2C_SendData (I2C_TypeDef * I2Cx, uint8_t Data)
Sends a data byte through the I2Cx peripheral.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
Data Byte to be transmitted..
Return values
None
Definition at line 689 of file stm32f4xx_i2c.c.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  /* Write in the DR register the data to be sent */
  I2Cx->DR = Data;
}
I2C_SMBusAlertConfig()
void I2C_SMBusAlertConfig (I2C_TypeDef * I2Cx, uint16_t I2C_SMBusAlert)
Drives the SMBusAlert pin high or low for the specified I2C.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
I2C_SMBusAlert specifies SMBAlert pin level. This parameter can be one of the following values:
I2C_SMBusAlert_Low: SMBAlert pin driven low
I2C_SMBusAlert_High: SMBAlert pin driven high
Return values
None
Definition at line 627 of file stm32f4xx_i2c.c.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_I2C_SMBUS_ALERT(I2C_SMBusAlert));
  if (I2C_SMBusAlert == I2C_SMBusAlert_Low)
  {
    /* Drive the SMBusAlert pin Low */
    I2Cx->CR1 |= I2C_SMBusAlert_Low;
  }
  else
  {
    /* Drive the SMBusAlert pin High */
    I2Cx->CR1 &= I2C_SMBusAlert_High;
  }
}
I2C_SoftwareResetCmd()
void I2C_SoftwareResetCmd (I2C_TypeDef * I2Cx, FunctionalState NewState)
Enables or disables the specified I2C software reset.
Note
When software reset is enabled, the I2C IOs are released (this can be useful to recover from bus errors).
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2C software reset. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 511 of file stm32f4xx_i2c.c.
References DISABLE.
Referenced by I2Cx_TIMEOUT_UserCallback().
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Peripheral under reset */
    I2Cx->CR1 |= I2C_CR1_SWRST;
  }
  else
  {
    /* Peripheral not under reset */
    I2Cx->CR1 &= (uint16_t)~((uint16_t)I2C_CR1_SWRST);
  }
}
I2C_StretchClockCmd()
void I2C_StretchClockCmd (I2C_TypeDef * I2Cx, FunctionalState NewState)
Enables or disables the specified I2C Clock stretching.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2Cx Clock stretching. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 535 of file stm32f4xx_i2c.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState == DISABLE)
  {
    /* Enable the selected I2C Clock stretching */
    I2Cx->CR1 |= I2C_CR1_NOSTRETCH;
  }
  else
  {
    /* Disable the selected I2C Clock stretching */
    I2Cx->CR1 &= (uint16_t)~((uint16_t)I2C_CR1_NOSTRETCH);
  }
}
I2C_StructInit()
void I2C_StructInit (I2C_InitTypeDef * I2C_InitStruct)
Fills each I2C_InitStruct member with its default value.
Parameters
I2C_InitStruct pointer to an I2C_InitTypeDef structure which will be initialized.
Return values
None
Definition at line 284 of file stm32f4xx_i2c.c.
References I2C_InitTypeDef::I2C_Ack, I2C_InitTypeDef::I2C_AcknowledgedAddress, I2C_InitTypeDef::I2C_ClockSpeed, I2C_InitTypeDef::I2C_DutyCycle, I2C_InitTypeDef::I2C_Mode, and I2C_InitTypeDef::I2C_OwnAddress1.
{
/*---------------- Reset I2C init structure parameters values ----------------*/
  /* initialize the I2C_ClockSpeed member */
  I2C_InitStruct->I2C_ClockSpeed = 5000;
  /* Initialize the I2C_Mode member */
  I2C_InitStruct->I2C_Mode = I2C_Mode_I2C;
  /* Initialize the I2C_DutyCycle member */
  I2C_InitStruct->I2C_DutyCycle = I2C_DutyCycle_2;
  /* Initialize the I2C_OwnAddress1 member */
  I2C_InitStruct->I2C_OwnAddress1 = 0;
  /* Initialize the I2C_Ack member */
  I2C_InitStruct->I2C_Ack = I2C_Ack_Disable;
  /* Initialize the I2C_AcknowledgedAddress member */
  I2C_InitStruct->I2C_AcknowledgedAddress = I2C_AcknowledgedAddress_7bit;
}
I2C_TransmitPEC()
void I2C_TransmitPEC (I2C_TypeDef * I2Cx, FunctionalState NewState)
Enables or disables the specified I2C PEC transfer.
Parameters
I2Cx where x can be 1, 2 or 3 to select the I2C peripheral.
NewState new state of the I2C PEC transmission. This parameter can be: ENABLE or DISABLE.
Return values
None
Definition at line 733 of file stm32f4xx_i2c.c.
References DISABLE.
{
  /* Check the parameters */
  assert_param(IS_I2C_ALL_PERIPH(I2Cx));
  assert_param(IS_FUNCTIONAL_STATE(NewState));
  if (NewState != DISABLE)
  {
    /* Enable the selected I2C PEC transmission */
    I2Cx->CR1 |= I2C_CR1_PEC;
  }
  else
  {
    /* Disable the selected I2C PEC transmission */
    I2Cx->CR1 &= (uint16_t)~((uint16_t)I2C_CR1_PEC);
  }
}