Initialization and Configuration functions
Initialization and Configuration functions.
Functions
void HASH_DeInit (void)
Deinitializes the HASH peripheral registers to their default reset values.
void HASH_Init (HASH_InitTypeDef *HASH_InitStruct)
Initializes the HASH peripheral according to the specified parameters in the HASH_InitStruct structure.
void HASH_StructInit (HASH_InitTypeDef *HASH_InitStruct)
Fills each HASH_InitStruct member with its default value.
void HASH_Reset (void)
Resets the HASH processor core, so that the HASH will be ready to compute the message digest of a new message.
Detailed Description
Initialization and Configuration functions.
 ===============================================================================
                      Initialization and Configuration functions
 ===============================================================================  
  This section provides functions allowing to 
   - Initialize the HASH peripheral
   - Configure the HASH Processor 
      - MD5/SHA1, 
      - HASH/HMAC, 
      - datatype 
      - HMAC Key (if mode = HMAC)
   - Reset the HASH Processor 
Function Documentation
HASH_DeInit()
void HASH_DeInit (void)
Deinitializes the HASH peripheral registers to their default reset values.
Parameters
None
Return values
None
Definition at line 171 of file stm32f4xx_hash.c.
References DISABLE, ENABLE, and RCC_AHB2PeriphResetCmd().
Referenced by HASH_MD5(), HASH_SHA1(), HMAC_MD5(), and HMAC_SHA1().
{
  /* Enable HASH reset state */
  RCC_AHB2PeriphResetCmd(RCC_AHB2Periph_HASH, ENABLE);
  /* Release HASH from reset state */
  RCC_AHB2PeriphResetCmd(RCC_AHB2Periph_HASH, DISABLE);
}
HASH_Init()
void HASH_Init (HASH_InitTypeDef * HASH_InitStruct)
Initializes the HASH peripheral according to the specified parameters in the HASH_InitStruct structure.
Note
the hash processor is reset when calling this function so that the HASH will be ready to compute the message digest of a new message. There is no need to call HASH_Reset() function.
Parameters
HASH_InitStruct pointer to a HASH_InitTypeDef structure that contains the configuration information for the HASH peripheral.
Note
The field HASH_HMACKeyType in HASH_InitTypeDef must be filled only if the algorithm mode is HMAC.
Return values
None
Definition at line 191 of file stm32f4xx_hash.c.
References HASH_InitTypeDef::HASH_AlgoMode.
Referenced by HASH_MD5(), HASH_SHA1(), HMAC_MD5(), and HMAC_SHA1().
{
  /* Check the parameters */
  assert_param(IS_HASH_ALGOSELECTION(HASH_InitStruct->HASH_AlgoSelection));
  assert_param(IS_HASH_DATATYPE(HASH_InitStruct->HASH_DataType));
  assert_param(IS_HASH_ALGOMODE(HASH_InitStruct->HASH_AlgoMode));
  
  /* Configure the Algorithm used, algorithm mode and the datatype */
  HASH->CR &= ~ (HASH_CR_ALGO | HASH_CR_DATATYPE | HASH_CR_MODE);
  HASH->CR |= (HASH_InitStruct->HASH_AlgoSelection | \
               HASH_InitStruct->HASH_DataType | \
               HASH_InitStruct->HASH_AlgoMode);
  
  /* if algorithm mode is HMAC, set the Key */
  if(HASH_InitStruct->HASH_AlgoMode == HASH_AlgoMode_HMAC)
  {
    assert_param(IS_HASH_HMAC_KEYTYPE(HASH_InitStruct->HASH_HMACKeyType));
    HASH->CR &= ~HASH_CR_LKEY;
    HASH->CR |= HASH_InitStruct->HASH_HMACKeyType;
  }
  /* Reset the HASH processor core, so that the HASH will be ready to compute
     the message digest of a new message */
  HASH->CR |= HASH_CR_INIT;
}
HASH_Reset()
void HASH_Reset (void)
Resets the HASH processor core, so that the HASH will be ready to compute the message digest of a new message.
Note
Calling this function will clear the HASH_SR_DCIS (Digest calculation completion interrupt status) bit corresponding to HASH_IT_DCI interrupt and HASH_FLAG_DCIS flag.
Parameters
None
Return values
None
Definition at line 249 of file stm32f4xx_hash.c.
{
  /* Reset the HASH processor core */
  HASH->CR |= HASH_CR_INIT;
}
HASH_StructInit()
void HASH_StructInit (HASH_InitTypeDef * HASH_InitStruct)
Fills each HASH_InitStruct member with its default value.
Parameters
HASH_InitStruct : pointer to a HASH_InitTypeDef structure which will be initialized.
Note
The default values set are : Processor mode is HASH, Algorithm selected is SHA1, Data type selected is 32b and HMAC Key Type is short key.
Return values
None
Definition at line 225 of file stm32f4xx_hash.c.
References HASH_InitTypeDef::HASH_AlgoMode, HASH_InitTypeDef::HASH_AlgoSelection, HASH_InitTypeDef::HASH_DataType, and HASH_InitTypeDef::HASH_HMACKeyType.
{
  /* Initialize the HASH_AlgoSelection member */
  HASH_InitStruct->HASH_AlgoSelection = HASH_AlgoSelection_SHA1;
  /* Initialize the HASH_AlgoMode member */
  HASH_InitStruct->HASH_AlgoMode = HASH_AlgoMode_HASH;
  /* Initialize the HASH_DataType member */
  HASH_InitStruct->HASH_DataType = HASH_DataType_32b;
  /* Initialize the HASH_HMACKeyType member */
  HASH_InitStruct->HASH_HMACKeyType = HASH_HMACKeyType_ShortKey;
}