C:/Users/Md. Istiaq Mahbub/Desktop/IMU/MPU6050_MotionDriver/Peripheral/src/i2c.h File Reference
Macros
#define SENSORS_I2C I2C2
#define I2C_SPEED 400000
#define I2C_OWN_ADDRESS 0x00
#define I2C_Config() I2cMaster_Init();
Functions
void I2cMaster_Init (void)
void Set_I2C_Retry (unsigned short ml_sec)
unsigned short Get_I2C_Retry ()
int Sensors_I2C_ReadRegister (unsigned char Address, unsigned char RegisterAddr, unsigned short RegisterLen, unsigned char *RegisterValue)
int Sensors_I2C_WriteRegister (unsigned char Address, unsigned char RegisterAddr, unsigned short RegisterLen, const unsigned char *RegisterValue)
Macro Definition Documentation
I2C_Config
#define I2C_Config() I2cMaster_Init();
Definition at line 14 of file i2c.h.
I2C_OWN_ADDRESS
#define I2C_OWN_ADDRESS 0x00
Definition at line 12 of file i2c.h.
I2C_SPEED
#define I2C_SPEED 400000
Definition at line 11 of file i2c.h.
SENSORS_I2C
#define SENSORS_I2C I2C2
Definition at line 9 of file i2c.h.
Function Documentation
Get_I2C_Retry()
unsigned short Get_I2C_Retry ()
Definition at line 408 of file i2c.c.
References RETRY_IN_MLSEC.
Referenced by Sensors_I2C_ReadRegister(), and Sensors_I2C_WriteRegister().
{
  return RETRY_IN_MLSEC;
}
I2cMaster_Init()
void I2cMaster_Init (void)
Definition at line 53 of file i2c.c.
References ENABLE, GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AF, GPIO_InitTypeDef::GPIO_OType, GPIO_OType_OD, GPIO_InitTypeDef::GPIO_Pin, GPIO_PinAFConfig(), GPIO_InitTypeDef::GPIO_PuPd, GPIO_PuPd_NOPULL, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_100MHz, I2C_InitTypeDef::I2C_Ack, I2C_InitTypeDef::I2C_AcknowledgedAddress, I2C_InitTypeDef::I2C_ClockSpeed, I2C_Cmd(), I2C_DeInit(), I2C_InitTypeDef::I2C_DutyCycle, I2C_Init(), I2C_InitTypeDef::I2C_Mode, I2C_InitTypeDef::I2C_OwnAddress1, RCC_AHB1PeriphClockCmd(), and RCC_APB1PeriphClockCmd().
Referenced by board_init().
{
  GPIO_InitTypeDef GPIO_InitStructure;
  I2C_InitTypeDef I2C_InitStructure;
    /* Enable I2Cx clock */
  RCC_APB1PeriphClockCmd(SENSORS_I2C_RCC_CLK, ENABLE);
  /* Enable I2C GPIO clock */
  RCC_AHB1PeriphClockCmd(SENSORS_I2C_SCL_GPIO_CLK | SENSORS_I2C_SDA_GPIO_CLK,
      ENABLE);
  /* Configure I2Cx pin: SCL ----------------------------------------*/
  GPIO_InitStructure.GPIO_Pin = SENSORS_I2C_SCL_GPIO_PIN;
  GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF;
  GPIO_InitStructure.GPIO_Speed = GPIO_Speed_100MHz;
  GPIO_InitStructure.GPIO_OType = GPIO_OType_OD;
  GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
  /* Connect pins to Periph */
  GPIO_PinAFConfig(SENSORS_I2C_SCL_GPIO_PORT, SENSORS_I2C_SCL_GPIO_PINSOURCE,
      SENSORS_I2C_AF);
  GPIO_Init(SENSORS_I2C_SCL_GPIO_PORT, &GPIO_InitStructure);
  /* Configure I2Cx pin: SDA ----------------------------------------*/
  GPIO_InitStructure.GPIO_Pin = SENSORS_I2C_SDA_GPIO_PIN;
  /* Connect pins to Periph */
  GPIO_PinAFConfig(SENSORS_I2C_SDA_GPIO_PORT, SENSORS_I2C_SDA_GPIO_PINSOURCE,
      SENSORS_I2C_AF);
  GPIO_Init(SENSORS_I2C_SDA_GPIO_PORT, &GPIO_InitStructure);
  
  I2C_DeInit(SENSORS_I2C);
  I2C_InitStructure.I2C_Mode = I2C_Mode_I2C;
  I2C_InitStructure.I2C_DutyCycle = I2C_DutyCycle_2;
  I2C_InitStructure.I2C_OwnAddress1 = I2C_OWN_ADDRESS;
  I2C_InitStructure.I2C_Ack = I2C_Ack_Enable;
  I2C_InitStructure.I2C_AcknowledgedAddress = I2C_AcknowledgedAddress_7bit;
  I2C_InitStructure.I2C_ClockSpeed = I2C_SPEED;
    
  /* Enable the I2C peripheral */
  I2C_Cmd(SENSORS_I2C, ENABLE);
    
  /* Initialize the I2C peripheral */
  I2C_Init(SENSORS_I2C, &I2C_InitStructure);
  
  return;
}
Sensors_I2C_ReadRegister()
int Sensors_I2C_ReadRegister (unsigned char Address, unsigned char RegisterAddr, unsigned short RegisterLen, unsigned char * RegisterValue)
Definition at line 157 of file i2c.c.
References Get_I2C_Retry(), mdelay(), and ST_Sensors_I2C_ReadRegister().
{
  char retries=0;
  int ret = 0;
  unsigned short retry_in_mlsec = Get_I2C_Retry();
  
tryReadAgain:
  ret = 0;
  ret = ST_Sensors_I2C_ReadRegister(slave_addr, reg_addr, len, data_ptr);
  if(ret && retry_in_mlsec)
  {
    if(retries++ > 4)
        return ret;
    
    mdelay(retry_in_mlsec);
    goto tryReadAgain;
  }
  return ret;
}
Sensors_I2C_WriteRegister()
int Sensors_I2C_WriteRegister (unsigned char Address, unsigned char RegisterAddr, unsigned short RegisterLen, const unsigned char * RegisterValue)
Definition at line 133 of file i2c.c.
References Get_I2C_Retry(), mdelay(), and ST_Sensors_I2C_WriteRegister().
{
  char retries=0;
  int ret = 0;
  unsigned short retry_in_mlsec = Get_I2C_Retry();
                              
tryWriteAgain:
  ret = 0;
  ret = ST_Sensors_I2C_WriteRegister(slave_addr, reg_addr, len, data_ptr);
  if(ret && retry_in_mlsec)
  {
    if(retries++ > 4)
        return ret;
    
    mdelay(retry_in_mlsec);
    goto tryWriteAgain;
  }
  return ret;
}
Set_I2C_Retry()
void Set_I2C_Retry (unsigned short ml_sec)
Definition at line 403 of file i2c.c.
References RETRY_IN_MLSEC.
Referenced by board_init().
{
  RETRY_IN_MLSEC = ml_sec;
}