C:/Users/Md. Istiaq Mahbub/Desktop/IMU/MPU6050_MotionDriver/Peripheral/src/i2c.c File Reference
#include <stdio.h>
#include `stm32f4xx.h`
#include `i2c.h`
#include `stm32f4xx_gpio.h`
#include `stm32f4xx_i2c.h`
#include `stm32f4xx_rcc.h`
#include `board-st_discovery.h`
Macros
#define Delay mdelay
#define I2Cx_FLAG_TIMEOUT ((uint32_t) 900)
#define I2Cx_LONG_TIMEOUT ((uint32_t) (300 * I2Cx_FLAG_TIMEOUT))
#define SENSORS_I2C_SCL_GPIO_PORT GPIOB
#define SENSORS_I2C_SCL_GPIO_CLK RCC_AHB1Periph_GPIOB
#define SENSORS_I2C_SCL_GPIO_PIN GPIO_Pin_10
#define SENSORS_I2C_SCL_GPIO_PINSOURCE GPIO_PinSource10
#define SENSORS_I2C_SDA_GPIO_PORT GPIOB
#define SENSORS_I2C_SDA_GPIO_CLK RCC_AHB1Periph_GPIOB
#define SENSORS_I2C_SDA_GPIO_PIN GPIO_Pin_11
#define SENSORS_I2C_SDA_GPIO_PINSOURCE GPIO_PinSource11
#define SENSORS_I2C_RCC_CLK RCC_APB1Periph_I2C2
#define SENSORS_I2C_AF GPIO_AF_I2C2
#define WAIT_FOR_FLAG(flag, value, timeout, errorcode)
#define CLEAR_ADDR_BIT
Functions
unsigned long ST_Sensors_I2C_WriteRegister (unsigned char Address, unsigned char RegisterAddr, unsigned short RegisterLen, const unsigned char *RegisterValue)
Writes a Byte to a given register to the sensors through the control interface (I2C)
unsigned long ST_Sensors_I2C_ReadRegister (unsigned char Address, unsigned char RegisterAddr, unsigned short RegisterLen, unsigned char *RegisterValue)
void I2cMaster_Init (void)
static uint32_t I2Cx_TIMEOUT_UserCallback (char value)
Basic management of the timeout situation.
int Sensors_I2C_WriteRegister (unsigned char slave_addr, unsigned char reg_addr, unsigned short len, const unsigned char *data_ptr)
int Sensors_I2C_ReadRegister (unsigned char slave_addr, unsigned char reg_addr, unsigned short len, unsigned char *data_ptr)
void Set_I2C_Retry (unsigned short ml_sec)
unsigned short Get_I2C_Retry ()
Variables
static unsigned short RETRY_IN_MLSEC = 55
Macro Definition Documentation
CLEAR_ADDR_BIT
#define CLEAR_ADDR_BIT
Value:
I2C_ReadRegister(SENSORS_I2C, I2C_Register_SR1);\
                            I2C_ReadRegister(SENSORS_I2C, I2C_Register_SR2);\
Definition at line 43 of file i2c.c.
Delay
#define Delay mdelay
Definition at line 17 of file i2c.c.
I2Cx_FLAG_TIMEOUT
#define I2Cx_FLAG_TIMEOUT ((uint32_t) 900)
Definition at line 20 of file i2c.c.
I2Cx_LONG_TIMEOUT
#define I2Cx_LONG_TIMEOUT ((uint32_t) (300 * I2Cx_FLAG_TIMEOUT))
Definition at line 21 of file i2c.c.
SENSORS_I2C_AF
#define SENSORS_I2C_AF GPIO_AF_I2C2
Definition at line 35 of file i2c.c.
SENSORS_I2C_RCC_CLK
#define SENSORS_I2C_RCC_CLK RCC_APB1Periph_I2C2
Definition at line 34 of file i2c.c.
SENSORS_I2C_SCL_GPIO_CLK
#define SENSORS_I2C_SCL_GPIO_CLK RCC_AHB1Periph_GPIOB
Definition at line 25 of file i2c.c.
SENSORS_I2C_SCL_GPIO_PIN
#define SENSORS_I2C_SCL_GPIO_PIN GPIO_Pin_10
Definition at line 26 of file i2c.c.
SENSORS_I2C_SCL_GPIO_PINSOURCE
#define SENSORS_I2C_SCL_GPIO_PINSOURCE GPIO_PinSource10
Definition at line 27 of file i2c.c.
SENSORS_I2C_SCL_GPIO_PORT
#define SENSORS_I2C_SCL_GPIO_PORT GPIOB
Definition at line 24 of file i2c.c.
SENSORS_I2C_SDA_GPIO_CLK
#define SENSORS_I2C_SDA_GPIO_CLK RCC_AHB1Periph_GPIOB
Definition at line 30 of file i2c.c.
SENSORS_I2C_SDA_GPIO_PIN
#define SENSORS_I2C_SDA_GPIO_PIN GPIO_Pin_11
Definition at line 31 of file i2c.c.
SENSORS_I2C_SDA_GPIO_PINSOURCE
#define SENSORS_I2C_SDA_GPIO_PINSOURCE GPIO_PinSource11
Definition at line 32 of file i2c.c.
SENSORS_I2C_SDA_GPIO_PORT
#define SENSORS_I2C_SDA_GPIO_PORT GPIOB
Definition at line 29 of file i2c.c.
WAIT_FOR_FLAG
#define WAIT_FOR_FLAG(flag, value, timeout, errorcode)
Value:
I2CTimeout = timeout;\
          while(I2C_GetFlagStatus(SENSORS_I2C, flag) != value) {\
            if((I2CTimeout--) == 0) return I2Cx_TIMEOUT_UserCallback(errorcode); \
          }\
Definition at line 38 of file i2c.c.
Function Documentation
Get_I2C_Retry()
unsigned short Get_I2C_Retry ()
Definition at line 408 of file i2c.c.
References RETRY_IN_MLSEC.
Referenced by Sensors_I2C_ReadRegister(), and Sensors_I2C_WriteRegister().
{
  return RETRY_IN_MLSEC;
}
I2cMaster_Init()
void I2cMaster_Init (void)
Definition at line 53 of file i2c.c.
References ENABLE, GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AF, GPIO_InitTypeDef::GPIO_OType, GPIO_OType_OD, GPIO_InitTypeDef::GPIO_Pin, GPIO_PinAFConfig(), GPIO_InitTypeDef::GPIO_PuPd, GPIO_PuPd_NOPULL, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_100MHz, I2C_InitTypeDef::I2C_Ack, I2C_InitTypeDef::I2C_AcknowledgedAddress, I2C_InitTypeDef::I2C_ClockSpeed, I2C_Cmd(), I2C_DeInit(), I2C_InitTypeDef::I2C_DutyCycle, I2C_Init(), I2C_InitTypeDef::I2C_Mode, I2C_InitTypeDef::I2C_OwnAddress1, RCC_AHB1PeriphClockCmd(), and RCC_APB1PeriphClockCmd().
Referenced by board_init().
{
  GPIO_InitTypeDef GPIO_InitStructure;
  I2C_InitTypeDef I2C_InitStructure;
    /* Enable I2Cx clock */
  RCC_APB1PeriphClockCmd(SENSORS_I2C_RCC_CLK, ENABLE);
  /* Enable I2C GPIO clock */
  RCC_AHB1PeriphClockCmd(SENSORS_I2C_SCL_GPIO_CLK | SENSORS_I2C_SDA_GPIO_CLK,
      ENABLE);
  /* Configure I2Cx pin: SCL ----------------------------------------*/
  GPIO_InitStructure.GPIO_Pin = SENSORS_I2C_SCL_GPIO_PIN;
  GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF;
  GPIO_InitStructure.GPIO_Speed = GPIO_Speed_100MHz;
  GPIO_InitStructure.GPIO_OType = GPIO_OType_OD;
  GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
  /* Connect pins to Periph */
  GPIO_PinAFConfig(SENSORS_I2C_SCL_GPIO_PORT, SENSORS_I2C_SCL_GPIO_PINSOURCE,
      SENSORS_I2C_AF);
  GPIO_Init(SENSORS_I2C_SCL_GPIO_PORT, &GPIO_InitStructure);
  /* Configure I2Cx pin: SDA ----------------------------------------*/
  GPIO_InitStructure.GPIO_Pin = SENSORS_I2C_SDA_GPIO_PIN;
  /* Connect pins to Periph */
  GPIO_PinAFConfig(SENSORS_I2C_SDA_GPIO_PORT, SENSORS_I2C_SDA_GPIO_PINSOURCE,
      SENSORS_I2C_AF);
  GPIO_Init(SENSORS_I2C_SDA_GPIO_PORT, &GPIO_InitStructure);
  
  I2C_DeInit(SENSORS_I2C);
  I2C_InitStructure.I2C_Mode = I2C_Mode_I2C;
  I2C_InitStructure.I2C_DutyCycle = I2C_DutyCycle_2;
  I2C_InitStructure.I2C_OwnAddress1 = I2C_OWN_ADDRESS;
  I2C_InitStructure.I2C_Ack = I2C_Ack_Enable;
  I2C_InitStructure.I2C_AcknowledgedAddress = I2C_AcknowledgedAddress_7bit;
  I2C_InitStructure.I2C_ClockSpeed = I2C_SPEED;
    
  /* Enable the I2C peripheral */
  I2C_Cmd(SENSORS_I2C, ENABLE);
    
  /* Initialize the I2C peripheral */
  I2C_Init(SENSORS_I2C, &I2C_InitStructure);
  
  return;
}
I2Cx_TIMEOUT_UserCallback()
static uint32_t I2Cx_TIMEOUT_UserCallback (char value) [static]
Basic management of the timeout situation.
Parameters
None.
Return values
None.
Definition at line 104 of file i2c.c.
References DISABLE, ENABLE, I2C_InitTypeDef::I2C_Ack, I2C_InitTypeDef::I2C_AcknowledgedAddress, I2C_InitTypeDef::I2C_ClockSpeed, I2C_Cmd(), I2C_DeInit(), I2C_InitTypeDef::I2C_DutyCycle, I2C_GenerateSTOP(), I2C_Init(), I2C_InitTypeDef::I2C_Mode, I2C_InitTypeDef::I2C_OwnAddress1, and I2C_SoftwareResetCmd().
{
  
  /* The following code allows I2C error recovery and return to normal communication
     if the error source doesn’t still exist (ie. hardware issue..) */
  I2C_InitTypeDef I2C_InitStructure;
  
  I2C_GenerateSTOP(SENSORS_I2C, ENABLE);
  I2C_SoftwareResetCmd(SENSORS_I2C, ENABLE);
  I2C_SoftwareResetCmd(SENSORS_I2C, DISABLE);
  
   I2C_DeInit(SENSORS_I2C);
  I2C_InitStructure.I2C_Mode = I2C_Mode_I2C;
  I2C_InitStructure.I2C_DutyCycle = I2C_DutyCycle_2;
  I2C_InitStructure.I2C_OwnAddress1 = I2C_OWN_ADDRESS;
  I2C_InitStructure.I2C_Ack = I2C_Ack_Enable;
  I2C_InitStructure.I2C_AcknowledgedAddress = I2C_AcknowledgedAddress_7bit;
  I2C_InitStructure.I2C_ClockSpeed = I2C_SPEED;
    
  /* Enable the I2C peripheral */
  I2C_Cmd(SENSORS_I2C, ENABLE);
    
  /* Initialize the I2C peripheral */
  I2C_Init(SENSORS_I2C, &I2C_InitStructure);
  return 1;
}
Sensors_I2C_ReadRegister()
int Sensors_I2C_ReadRegister (unsigned char slave_addr, unsigned char reg_addr, unsigned short len, unsigned char * data_ptr)
Definition at line 157 of file i2c.c.
References Get_I2C_Retry(), mdelay(), and ST_Sensors_I2C_ReadRegister().
{
  char retries=0;
  int ret = 0;
  unsigned short retry_in_mlsec = Get_I2C_Retry();
  
tryReadAgain:
  ret = 0;
  ret = ST_Sensors_I2C_ReadRegister(slave_addr, reg_addr, len, data_ptr);
  if(ret && retry_in_mlsec)
  {
    if(retries++ > 4)
        return ret;
    
    mdelay(retry_in_mlsec);
    goto tryReadAgain;
  }
  return ret;
}
Sensors_I2C_WriteRegister()
int Sensors_I2C_WriteRegister (unsigned char slave_addr, unsigned char reg_addr, unsigned short len, const unsigned char * data_ptr)
Definition at line 133 of file i2c.c.
References Get_I2C_Retry(), mdelay(), and ST_Sensors_I2C_WriteRegister().
{
  char retries=0;
  int ret = 0;
  unsigned short retry_in_mlsec = Get_I2C_Retry();
                              
tryWriteAgain:
  ret = 0;
  ret = ST_Sensors_I2C_WriteRegister(slave_addr, reg_addr, len, data_ptr);
  if(ret && retry_in_mlsec)
  {
    if(retries++ > 4)
        return ret;
    
    mdelay(retry_in_mlsec);
    goto tryWriteAgain;
  }
  return ret;
}
Set_I2C_Retry()
void Set_I2C_Retry (unsigned short ml_sec)
Definition at line 403 of file i2c.c.
References RETRY_IN_MLSEC.
Referenced by board_init().
{
  RETRY_IN_MLSEC = ml_sec;
}
ST_Sensors_I2C_ReadRegister()
unsigned long ST_Sensors_I2C_ReadRegister (unsigned char Address, unsigned char RegisterAddr, unsigned short RegisterLen, unsigned char * RegisterValue)
< Send START condition a second time
< Send address for read
< Disable Acknowledgment
< Send STOP Condition
< Disable Acknowledgment
< Send STOP Condition
< Disable Acknowledgment
< Send STOP Condition
< Disable Acknowledgment
< Send STOP Condition
< Re-Enable Acknowledgment to be ready for another reception
Definition at line 249 of file i2c.c.
Referenced by Sensors_I2C_ReadRegister().
{
  uint32_t i=0, result = 0;
  __IO uint32_t I2CTimeout = I2Cx_LONG_TIMEOUT;
   
  /* Wait for the busy flag to be cleared */
  WAIT_FOR_FLAG (I2C_FLAG_BUSY, RESET, I2Cx_LONG_TIMEOUT, 7);
  
  /* Start the config sequence */
  I2C_GenerateSTART(SENSORS_I2C, ENABLE);
  /* Wait for the start bit to be set */
  WAIT_FOR_FLAG (I2C_FLAG_SB, SET, I2Cx_FLAG_TIMEOUT, 8);
  
  /* Transmit the slave address and enable writing operation */
  I2C_Send7bitAddress(SENSORS_I2C, (Address<<1), I2C_Direction_Transmitter);
  /* Wait for the start bit to be set */
  WAIT_FOR_FLAG (I2C_FLAG_ADDR, SET, I2Cx_FLAG_TIMEOUT, 9);
  /* clear the ADDR interrupt bit - this is done by reading SR1 and SR2*/
  CLEAR_ADDR_BIT;
  
  /* Wait for address bit to be set */
  WAIT_FOR_FLAG (I2C_FLAG_TXE, SET, I2Cx_FLAG_TIMEOUT, 10);
  
  /* Transmit the register address to be read */
  I2C_SendData(SENSORS_I2C, RegisterAddr);
  
  /* Wait for address bit to be set */
  WAIT_FOR_FLAG (I2C_FLAG_TXE, SET, I2Cx_FLAG_TIMEOUT, 11);
  I2C_GenerateSTART(SENSORS_I2C, ENABLE);
  
  /* Wait for the start bit to be set */
  WAIT_FOR_FLAG (I2C_FLAG_SB, SET, I2Cx_FLAG_TIMEOUT, 12);
  
  I2C_Send7bitAddress(SENSORS_I2C, (Address<<1), I2C_Direction_Receiver);
  
  /* Wait for the start bit to be set */
  WAIT_FOR_FLAG (I2C_FLAG_ADDR, SET, I2Cx_FLAG_TIMEOUT, 13);
  
  if (RegisterLen == 1)
  {
    I2C_AcknowledgeConfig(SENSORS_I2C, DISABLE);
    
    /* clear the ADDR interrupt bit - this is done by reading SR1 and SR2*/
    CLEAR_ADDR_BIT;
    
    I2C_GenerateSTOP(SENSORS_I2C, ENABLE);
    
    /* Wait for the RXNE bit to be set */
    WAIT_FOR_FLAG (I2C_FLAG_RXNE, SET, I2Cx_FLAG_TIMEOUT, 14);
    
    RegisterValue[0] = I2C_ReceiveData(SENSORS_I2C);
  }
  else if(RegisterLen == 2)
  {
    I2C_AcknowledgeConfig(SENSORS_I2C, DISABLE);
    
   /* Set POS bit */
   SENSORS_I2C->CR1 |= I2C_CR1_POS;
   
   /* clear the ADDR interrupt bit - this is done by reading SR1 and SR2*/
   CLEAR_ADDR_BIT;
   
   /* Wait for the buffer full bit to be set */
   WAIT_FOR_FLAG (I2C_FLAG_BTF, SET, I2Cx_FLAG_TIMEOUT, 15);
   
   I2C_GenerateSTOP(SENSORS_I2C, ENABLE);
   /* Read 2 bytes */
   RegisterValue[0] = I2C_ReceiveData(SENSORS_I2C);
   RegisterValue[1] = I2C_ReceiveData(SENSORS_I2C);
  }
  else if(RegisterLen == 3)
  {
    CLEAR_ADDR_BIT;
    
    /* Wait for the buffer full bit to be set */
    WAIT_FOR_FLAG (I2C_FLAG_BTF, SET, I2Cx_FLAG_TIMEOUT, 16);
    I2C_AcknowledgeConfig(SENSORS_I2C, DISABLE);
    /* Read 1 bytes */
    RegisterValue[0] = I2C_ReceiveData(SENSORS_I2C);
    I2C_GenerateSTOP(SENSORS_I2C, ENABLE);
    /* Read 1 bytes */
    RegisterValue[1] = I2C_ReceiveData(SENSORS_I2C);
    /* Wait for the buffer full bit to be set */
    WAIT_FOR_FLAG (I2C_FLAG_RXNE, SET, I2Cx_FLAG_TIMEOUT, 17);
    /* Read 1 bytes */
    RegisterValue[2] = I2C_ReceiveData(SENSORS_I2C);
  }
  else /* more than 2 bytes */
  {
    /* clear the ADDR interrupt bit - this is done by reading SR1 and SR2*/
    CLEAR_ADDR_BIT;
    
    for(i=0; i<(RegisterLen); i++)
    {
      if(i==(RegisterLen-3))
      {
        /* Wait for the buffer full bit to be set */
        WAIT_FOR_FLAG (I2C_FLAG_BTF, SET, I2Cx_FLAG_TIMEOUT, 16);
        
        I2C_AcknowledgeConfig(SENSORS_I2C, DISABLE);
        
        /* Read 1 bytes */
        RegisterValue[i++] = I2C_ReceiveData(SENSORS_I2C);
        
        I2C_GenerateSTOP(SENSORS_I2C, ENABLE);
        
        /* Read 1 bytes */
        RegisterValue[i++] = I2C_ReceiveData(SENSORS_I2C);
        
        /* Wait for the buffer full bit to be set */
        WAIT_FOR_FLAG (I2C_FLAG_RXNE, SET, I2Cx_FLAG_TIMEOUT, 17);
        
        /* Read 1 bytes */
        RegisterValue[i++] = I2C_ReceiveData(SENSORS_I2C);
        goto endReadLoop;
      }
            
      /* Wait for the RXNE bit to be set */
      WAIT_FOR_FLAG (I2C_FLAG_RXNE, SET, I2Cx_FLAG_TIMEOUT, 18);
      RegisterValue[i] = I2C_ReceiveData(SENSORS_I2C);
    }
  }
  
endReadLoop:
  /* Clear BTF flag */
  I2C_ClearFlag(SENSORS_I2C, I2C_FLAG_BTF);
  /* Wait for the busy flag to be cleared */
  WAIT_FOR_FLAG (I2C_FLAG_BUSY, RESET, I2Cx_LONG_TIMEOUT, 19);
  I2C_AcknowledgeConfig(SENSORS_I2C, ENABLE);
  //Disable POS -- TODO
  SENSORS_I2C->CR1 &= ~I2C_CR1_POS;
     
  /* Return the byte read from sensor */
  return result;
}
ST_Sensors_I2C_WriteRegister()
unsigned long ST_Sensors_I2C_WriteRegister (unsigned char Address, unsigned char RegisterAddr, unsigned short RegisterLen, const unsigned char * RegisterValue)
Writes a Byte to a given register to the sensors through the control interface (I2C)
Parameters
RegisterAddr The address (location) of the register to be written.
RegisterValue the Byte value to be written into destination register.
Return values
0 if correct communication, else wrong communication
Definition at line 189 of file i2c.c.
Referenced by Sensors_I2C_WriteRegister().
{
  uint32_t result = 0;
  uint32_t i = 0; // i = RegisterLen;
  __IO uint32_t I2CTimeout = I2Cx_LONG_TIMEOUT;
  
// RegisterValue = RegisterValue + (RegisterLen - 1);
  /* Wait for the busy flag to be cleared */
  WAIT_FOR_FLAG (I2C_FLAG_BUSY, RESET, I2Cx_LONG_TIMEOUT, 1);
  
  /* Start the config sequence */
  I2C_GenerateSTART(SENSORS_I2C, ENABLE);
  /* Wait for the start bit to be set */
  WAIT_FOR_FLAG (I2C_FLAG_SB, SET, I2Cx_FLAG_TIMEOUT, 2);
  /* Transmit the slave address and enable writing operation */
  I2C_Send7bitAddress(SENSORS_I2C, (Address<<1), I2C_Direction_Transmitter);
  
  /* Wait for address bit to be set */
  WAIT_FOR_FLAG (I2C_FLAG_ADDR, SET, I2Cx_FLAG_TIMEOUT, 3);
  
  /* clear the ADDR interrupt bit - this is done by reading SR1 and SR2*/
  CLEAR_ADDR_BIT
  
  /* Wait for address bit to be set */
  WAIT_FOR_FLAG (I2C_FLAG_TXE, SET, I2Cx_FLAG_TIMEOUT, 4);
  /* Transmit the first address for write operation */
  I2C_SendData(SENSORS_I2C, RegisterAddr);
// while (i--)
// {
// /* Wait for address bit to be set */
// WAIT_FOR_FLAG (I2C_FLAG_TXE, SET, I2Cx_FLAG_TIMEOUT, 5);
//
// /* Prepare the register value to be sent */
// I2C_SendData(SENSORS_I2C, *RegisterValue--);
// }
  
  for(i=0; i<(RegisterLen); i++)
  {
    /* Wait for address bit to be set */
    WAIT_FOR_FLAG (I2C_FLAG_TXE, SET, I2Cx_FLAG_TIMEOUT, 5);
  
    /* Prepare the register value to be sent */
    I2C_SendData(SENSORS_I2C, RegisterValue[i]);
  }
   
  /* Wait for address bit to be set */
  WAIT_FOR_FLAG (I2C_FLAG_BTF, SET, I2Cx_FLAG_TIMEOUT, 6);
  
  /* End the configuration sequence */
  I2C_GenerateSTOP(SENSORS_I2C, ENABLE);
  
  /* Return the verifying value: 0 (Passed) or 1 (Failed) */
  return result;
}
Variable Documentation
RETRY_IN_MLSEC
unsigned short RETRY_IN_MLSEC = 55 [static]
Definition at line 401 of file i2c.c.
Referenced by Get_I2C_Retry(), and Set_I2C_Retry().