C:/Users/Md. Istiaq Mahbub/Desktop/IMU/MPU6050_MotionDriver/Peripheral/src/uart.c File Reference
#include <stdio.h>
#include `stm32f4xx.h`
#include `uart.h`
#include `stm32f4xx_usart.h`
#include `stm32f4xx_gpio.h`
#include `misc.h`
#include `stm32f4xx_exti.h`
#include `stm32f4xx_rcc.h`
Macros
#define USARTx USART1
#define USARTx_CLK RCC_APB2Periph_USART1
#define USARTx_CLK_INIT RCC_APB2PeriphClockCmd
#define USARTx_IRQn USART1_IRQn
#define USARTx_IRQHandler USART1_IRQHandler
#define USARTx_TX_PIN GPIO_Pin_9
#define USARTx_TX_GPIO_PORT GPIOA
#define USARTx_TX_GPIO_CLK RCC_AHB1Periph_GPIOA
#define USARTx_TX_SOURCE GPIO_PinSource9
#define USARTx_TX_AF GPIO_AF_USART1
#define USARTx_RX_PIN GPIO_Pin_10
#define USARTx_RX_GPIO_PORT GPIOA
#define USARTx_RX_GPIO_CLK RCC_AHB1Periph_GPIOA
#define USARTx_RX_SOURCE GPIO_PinSource10
#define USARTx_RX_AF GPIO_AF_USART1
#define USARTx_DMAx_CLK RCC_AHBPeriph_DMA1
Functions
void USART_Config (void)
int _fputc (int ch)
Macro Definition Documentation
USARTx
#define USARTx USART1
************ Pin Defination of USART1
Definition at line 37 of file uart.c.
USARTx_CLK
#define USARTx_CLK RCC_APB2Periph_USART1
Definition at line 38 of file uart.c.
USARTx_CLK_INIT
#define USARTx_CLK_INIT RCC_APB2PeriphClockCmd
Definition at line 39 of file uart.c.
USARTx_DMAx_CLK
#define USARTx_DMAx_CLK RCC_AHBPeriph_DMA1
Definition at line 55 of file uart.c.
USARTx_IRQHandler
#define USARTx_IRQHandler USART1_IRQHandler
Definition at line 41 of file uart.c.
USARTx_IRQn
#define USARTx_IRQn USART1_IRQn
Definition at line 40 of file uart.c.
USARTx_RX_AF
#define USARTx_RX_AF GPIO_AF_USART1
Definition at line 53 of file uart.c.
USARTx_RX_GPIO_CLK
#define USARTx_RX_GPIO_CLK RCC_AHB1Periph_GPIOA
Definition at line 51 of file uart.c.
USARTx_RX_GPIO_PORT
#define USARTx_RX_GPIO_PORT GPIOA
Definition at line 50 of file uart.c.
USARTx_RX_PIN
#define USARTx_RX_PIN GPIO_Pin_10
Definition at line 49 of file uart.c.
USARTx_RX_SOURCE
#define USARTx_RX_SOURCE GPIO_PinSource10
Definition at line 52 of file uart.c.
USARTx_TX_AF
#define USARTx_TX_AF GPIO_AF_USART1
Definition at line 47 of file uart.c.
USARTx_TX_GPIO_CLK
#define USARTx_TX_GPIO_CLK RCC_AHB1Periph_GPIOA
Definition at line 45 of file uart.c.
USARTx_TX_GPIO_PORT
#define USARTx_TX_GPIO_PORT GPIOA
Definition at line 44 of file uart.c.
USARTx_TX_PIN
#define USARTx_TX_PIN GPIO_Pin_9
Definition at line 43 of file uart.c.
USARTx_TX_SOURCE
#define USARTx_TX_SOURCE GPIO_PinSource9
Definition at line 46 of file uart.c.
Function Documentation
_fputc()
int _fputc (int ch)
Definition at line 106 of file uart.c.
References RESET, USART_GetFlagStatus(), and USART_SendData().
{
  //* Place your implementation of fputc here
  //* e.g. write a character to the USART
  USART_SendData(USARTx, (uint8_t) ch);
  //* Loop until the end of transmission
  while (USART_GetFlagStatus(USARTx, USART_FLAG_TC) == RESET)
  {}
  return ch;
}
USART_Config()
void USART_Config (void)
Definition at line 61 of file uart.c.
References ENABLE, GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AF, GPIO_InitTypeDef::GPIO_OType, GPIO_OType_PP, GPIO_InitTypeDef::GPIO_Pin, GPIO_PinAFConfig(), GPIO_InitTypeDef::GPIO_PuPd, GPIO_PuPd_NOPULL, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_50MHz, RCC_AHB1PeriphClockCmd(), RCC_APB2PeriphClockCmd(), USART_InitTypeDef::USART_BaudRate, USART_Cmd(), USART_InitTypeDef::USART_HardwareFlowControl, USART_Init(), USART_ITConfig(), USART_InitTypeDef::USART_Mode, USART_InitTypeDef::USART_Parity, USART_InitTypeDef::USART_StopBits, and USART_InitTypeDef::USART_WordLength.
Referenced by board_init().
{
  USART_InitTypeDef USART_InitStructure;
  GPIO_InitTypeDef GPIO_InitStructure;
  /* Peripheral Clock Enable -------------------------------------------------*/
  /* Enable GPIO clock */
  RCC_AHB1PeriphClockCmd(USARTx_TX_GPIO_CLK | USARTx_RX_GPIO_CLK, ENABLE);
  
  /* Enable USART clock */
  USARTx_CLK_INIT(USARTx_CLK, ENABLE);
  
  /* USARTx GPIO configuration -----------------------------------------------*/
  /* Connect USART pins to AF7 */
  GPIO_PinAFConfig(USARTx_TX_GPIO_PORT, USARTx_TX_SOURCE, USARTx_TX_AF);
  GPIO_PinAFConfig(USARTx_RX_GPIO_PORT, USARTx_RX_SOURCE, USARTx_RX_AF);
  
  /* Configure USART Tx and Rx as alternate function push-pull */
  GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF;
  GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
  GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
  GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
  
  GPIO_InitStructure.GPIO_Pin = USARTx_TX_PIN | USARTx_RX_PIN;
  GPIO_Init(GPIOA, &GPIO_InitStructure);
  
  //GPIO_InitStructure.GPIO_Pin = USARTx_TX_PIN;
  //GPIO_Init(USARTx_TX_GPIO_PORT, &GPIO_InitStructure);
  //GPIO_InitStructure.GPIO_Pin = USARTx_RX_PIN;
  //GPIO_Init(USARTx_RX_GPIO_PORT, &GPIO_InitStructure);
 
  USART_InitStructure.USART_BaudRate = 115200;//115200;460800;
  USART_InitStructure.USART_WordLength = USART_WordLength_8b;
  USART_InitStructure.USART_StopBits = USART_StopBits_1;
  /* When using Parity the word length must be configured to 9 bits */
  USART_InitStructure.USART_Parity = USART_Parity_No;
  USART_InitStructure.USART_HardwareFlowControl = USART_HardwareFlowControl_None;
  USART_InitStructure.USART_Mode = USART_Mode_Rx | USART_Mode_Tx;
  USART_Init(USARTx, &USART_InitStructure);
  USART_ITConfig(USARTx, USART_IT_RXNE, ENABLE);
  /* Enable USART */
  USART_Cmd(USARTx, ENABLE);
}