C:/Users/Md. Istiaq Mahbub/Desktop/IMU/MPU6050_MotionDriver/Peripheral/src/uart.h File Reference
Functions
void USART_Config (void)
int _fputc (int ch)
Function Documentation
_fputc()
int _fputc (int ch)
Definition at line 106 of file uart.c.
References RESET, USART_GetFlagStatus(), and USART_SendData().
{
  //* Place your implementation of fputc here
  //* e.g. write a character to the USART
  USART_SendData(USARTx, (uint8_t) ch);
  //* Loop until the end of transmission
  while (USART_GetFlagStatus(USARTx, USART_FLAG_TC) == RESET)
  {}
  return ch;
}
USART_Config()
void USART_Config (void)
Definition at line 61 of file uart.c.
References ENABLE, GPIO_Init(), GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_AF, GPIO_InitTypeDef::GPIO_OType, GPIO_OType_PP, GPIO_InitTypeDef::GPIO_Pin, GPIO_PinAFConfig(), GPIO_InitTypeDef::GPIO_PuPd, GPIO_PuPd_NOPULL, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_50MHz, RCC_AHB1PeriphClockCmd(), RCC_APB2PeriphClockCmd(), USART_InitTypeDef::USART_BaudRate, USART_Cmd(), USART_InitTypeDef::USART_HardwareFlowControl, USART_Init(), USART_ITConfig(), USART_InitTypeDef::USART_Mode, USART_InitTypeDef::USART_Parity, USART_InitTypeDef::USART_StopBits, and USART_InitTypeDef::USART_WordLength.
Referenced by board_init().
{
  USART_InitTypeDef USART_InitStructure;
  GPIO_InitTypeDef GPIO_InitStructure;
  /* Peripheral Clock Enable -------------------------------------------------*/
  /* Enable GPIO clock */
  RCC_AHB1PeriphClockCmd(USARTx_TX_GPIO_CLK | USARTx_RX_GPIO_CLK, ENABLE);
  
  /* Enable USART clock */
  USARTx_CLK_INIT(USARTx_CLK, ENABLE);
  
  /* USARTx GPIO configuration -----------------------------------------------*/
  /* Connect USART pins to AF7 */
  GPIO_PinAFConfig(USARTx_TX_GPIO_PORT, USARTx_TX_SOURCE, USARTx_TX_AF);
  GPIO_PinAFConfig(USARTx_RX_GPIO_PORT, USARTx_RX_SOURCE, USARTx_RX_AF);
  
  /* Configure USART Tx and Rx as alternate function push-pull */
  GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF;
  GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
  GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
  GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
  
  GPIO_InitStructure.GPIO_Pin = USARTx_TX_PIN | USARTx_RX_PIN;
  GPIO_Init(GPIOA, &GPIO_InitStructure);
  
  //GPIO_InitStructure.GPIO_Pin = USARTx_TX_PIN;
  //GPIO_Init(USARTx_TX_GPIO_PORT, &GPIO_InitStructure);
  //GPIO_InitStructure.GPIO_Pin = USARTx_RX_PIN;
  //GPIO_Init(USARTx_RX_GPIO_PORT, &GPIO_InitStructure);
 
  USART_InitStructure.USART_BaudRate = 115200;//115200;460800;
  USART_InitStructure.USART_WordLength = USART_WordLength_8b;
  USART_InitStructure.USART_StopBits = USART_StopBits_1;
  /* When using Parity the word length must be configured to 9 bits */
  USART_InitStructure.USART_Parity = USART_Parity_No;
  USART_InitStructure.USART_HardwareFlowControl = USART_HardwareFlowControl_None;
  USART_InitStructure.USART_Mode = USART_Mode_Rx | USART_Mode_Tx;
  USART_Init(USARTx, &USART_InitStructure);
  USART_ITConfig(USARTx, USART_IT_RXNE, ENABLE);
  /* Enable USART */
  USART_Cmd(USARTx, ENABLE);
}